### ISSUE TITLE
GigaScience logo size

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1]
The size of the GigaScience [logo](https://github.com/gigascience/gigadb-website/blob/master/images/gigascience.png) is 2688x992 pixels. The logo should be reduced in size so that the image is, at most, as large as the GigaDB website content width. We could reduce the size of the GigaScience logo even further since the web pages where it is displayed ([datasetpage.php](url) and [main.php](url)) shrink the image to a height of 32 pixels.

@pli888 check the content width for the GigaDB website.

**Comment by ScottBGI** [comment]
If we are playing around with the logos can we also crop the GigaGalaxy logos (vector/transparent and solid versions) to remove the CBIIT part. Plus make transparent white versions of them all (GigaScience, GigaDB and GigaGalaxy) that we can use on coloured backgrounds. And make a vector GigaBlog logo.
