### ISSUE TITLE
deleted sample still showing on dataset page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1002]
**Describe the bug**
I used the admin page to find the sample I want to delete, in this case it was the sample with the name "SRS1815432" from dataset 100317, I clicked the little "delete" button, it took a while but it was deleted from my admin view, I checked in the dataset_sample admin view for dataset 100317 and it was also deleted from there (and correctly still remaining in dataset 100310), but when I goto the dataset page https://beta.gigadb.org/dataset/view/id/100317 it is still showing the sample SRS1815432 in the sample table? even after I have deleted my cache its still showing, where is the information coming from if its not in the database any more?

**To Reproduce**
1. Go to https://beta.gigadb.org/adminSample/admin
2. find the sample you want to delete e.g.  SRS1815425 or SRS1815424 (from dataset 100317 not 100310!)
3. click the delete sample button, confirm you want to delete it
4. wait for table to refresh with no sign that sample anymore
5. goto the dataset page https://beta.gigadb.org/dataset/view/id/100317
6. observe the deleted sample still showing in the sample table

**Expected behavior**
when a sample is deleted from the database it should not show up on the dataset pages!

**Additional context**
The sample was also deleted from the dataset_sample table when I deleted it from the sample table using the admin pages, which is the correct behavior.

**Comment by rija** [comment]
probably the invalidation query for the server side cache is not picking up the change.
ensure a dataset_log entry is created upon deletion of the sample so that invalidation query can be written to monitor that table

**Comment by kencho51** [comment]
When try to delete sample `Zhang gu` from dev dataset `100020` in `/adminSample/admin`, will get this error:
```
CDbCommand::execute() failed: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "sample" violates foreign key constraint "file_sample_sample_id_fkey" on table "file_sample"
DETAIL:  Key (id)=(432) is still referenced from table "file_sample".. The SQL statement executed was: DELETE FROM "sample" WHERE "sample"."id"=432.
in /var/www/protected/controllers/AdminSampleController.php (289)
in /var/www/index.php (24)
CDbException: CDbCommand failed to execute the SQL statement: SQLSTATE[23503]: Foreign key violation: 7 ERROR:  update or delete on table "sample" violates foreign key constraint "file_sample_sample_id_fkey" on table "file_sample"
DETAIL:  Key (id)=(432) is still referenced from table "file_sample".. The SQL statement executed was: DELETE FROM "sample" WHERE "sample"."id"=432 in /var/www/vendor/yiisoft/yii/framework/db/CDbCommand.php:358

Stack trace:
#0 /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1810): CDbCommand->execute()
#1 /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1230): CActiveRecord->deleteByPk(432)
#2 /var/www/protected/controllers/AdminSampleController.php(289): CActiveRecord->delete()
#3 [internal function]: AdminSampleController->actionDelete('432')
#4 /var/www/vendor/yiisoft/yii/framework/web/actions/CAction.php(115): ReflectionMethod->invokeArgs(Object(AdminSampleController), Array)
#5 /var/www/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(AdminSampleController), Object(ReflectionMethod), Array)
#6 /var/www/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#7 /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#8 /var/www/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#9 /var/www/vendor/yiisoft/yii/framework/web/CController.php(1148): CFilter->filter(Object(CFilterChain))
#10 /var/www/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#11 /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#12 /var/www/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()
#13 /var/www/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('delete')
#15 /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('adminSample/del...')
#16 /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 /var/www/index.php(24): CApplication->run()
#18 {main}
REQUEST_URI=/adminSample/delete/id/432?ajax=sample-grid
HTTP_REFERER=http://gigadb.gigasciencejournal.com:9170/adminSample/admin
```

**Comment by only1chunts** [comment]
This appears to be fixed in beta, so closing issue.
