### ISSUE TITLE
Develop, test and document standard operating procedure for restoring database for Upstream group - E566

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1008]
## User story

>As a developer
>I want a standard operating procedure to restore database on AWS infrastructure in the `Upstream` Gitlab group
>So that I can perform database restoration in case of database failure for GigaDB website

This work is part of Epic #566. 

## Acceptance criteria

>Given the database has failed
>When I perform the SOP
>Then the database has been restored

## Additional information

* To use RDS backups:
```
$ ../../../scripts/tf_init.sh --project gigascience/upstream/gigadb-website --env staging --restore-backup
```

**Comment by only1chunts** [comment]
done
