### ISSUE TITLE
Develop, test and document standard operating procedure for rolling back to a previous GigaDB deployment state - E566

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1009]
## User story

>As a developer
>I want a standard operating procedure to roll back to a previous GigaDB deployment state on AWS infrastructure in the `Upstream` Gitlab group
>So that I can restore to a good state

This work is part of Epic #566. 

## Acceptance criteria

>Given there is a problem with the current GigaDB website state
>When I perform the SOP
>Then a previous good GigaDB website state is restored

## Additional information

* Should be a matter of re-running the previous good pipeline in Gitlab in Upstream group

**Comment by only1chunts** [comment]
done
