### ISSUE TITLE
Develop, test and document standard operating procedure for deploying to gigadb.org - E566

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1010]
## User story

>As a developer
>I want a standard operating procedure to deploy GigaDB website on AWS infrastructure in the `Upstream` Gitlab group
>So that I can deploy GigaDB website on beta.gigadb.org

This work is part of Epic #566. 

## Acceptance criteria

>Given I have to deploy a new release of GigaDB website
>When I perform the SOP
>Then the release is deployed to beta.gigadb.org

**Comment by only1chunts** [comment]
this story is done, we can deploy to beta.gigadb.org following the protocols created.
