### ISSUE TITLE
Automated email to manualy created user accounts

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#103]
Currently when we do a spreadsheet upload directly to the DB using Jesse's scripts the userID is created but there is no password added and the user cannot login to see the progress of their submission. We need to adjust this so that users are contacted as soon as an account is created for them, they should be sent a URL to a page that asks them to confirm their personal details, including their ORCID, and to provide a password for their GiigaDB account.
to be done in conjunction with issue #64 .

**Comment by sohini-roy** [comment]
hi
thanks for the description :)
i am new to opensource and was wondering if i could work on this issue 

Have a great day :)

**Comment by only1chunts** [comment]
Hi @sohini-roy , great that you are interested in helping us out with some issues. perhaps less complex and self contained item might be issue #113 ? if you would like to fork the github repo and add your code to do that task, please feel free. When you are done just send a pull request to us and we can look over what you have done. If its does what we need and it works then we would merge it into the production code-base.

**Comment by only1chunts** [comment]
Note: this is the text received from a returned email, its possible this was due to any number of reasons, but the point to note here is that the sender is listed as "nobody@gigadb.org" (MAIL From:<nobody@gigadb.org> ) - this could be the reason many servers reject our automated emails as spam.
@jessesiu Can we change the sender to be database@gigasciencejournal.com?

The original message was received at Wed, 25 Apr 2018 09:43:00 GMT
from localhost [127.0.0.1]

   ----- The following addresses had permanent fatal errors -----
<constantinaki@hotmail.com>
    (reason: 550 5.7.1 Client host [218.189.31.218] blocked using Spamhaus. To request removal from this list see http://www.spamhaus.org/lookup.lasso (S3130). [SN1NAM04FT035.eop-NAM04.prod.protection.outlook.com])

   ----- Transcript of session follows -----
... while talking to hotmail-com.olc.protection.outlook.com.:
>>> MAIL From:<nobody@gigadb.org> SIZE=3073
<<< 550 5.7.1 Client host [218.189.31.218] blocked using Spamhaus. To request removal from this list see http://www.spamhaus.org/lookup.lasso (S3130). [SN1NAM04FT035.eop-NAM04.prod.protection.outlook.com]
554 5.0.0 Service unavailable
