### ISSUE TITLE
spreadsheet tool workflow has saving performed MD5 checksum calculation to database

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1032]
Since tech team took over the dataset spreadsheet uploading tool, the systematic saving of MD5 checksum of files url for the files added from the spreadsheets is not performed. The md5 checksum value needs to be added into the `file_attributes` table for each dataset file in the database.

This, I think, is currently done using the consultant's [tool](https://github.com/jessesiu/compare_and_md5).

## Additional information

Every GigaDB dataset has a directory on the FTP server which contains the dataset files. The dataset directory also contains a file with an `md5` extension, e.g. `100508.md5`. The contents of the `100508.md5` file is:
```
$ more /var/ftp/gigadb/pub/10.5524/100001_101000/100508/100508.md5
d41d8cd98f00b204e9800998ecf8427e  ./100508.md5
641672b5373ba591229166d02a8fff23  ./MetaPGN-master.zip
0a7beeef4c8f682fb2f93811fb224775  ./PGN_assemblies_of_760metagenomes.tar.gz
f32fe701a862ac1dc42dbe522486de1d  ./PGN_genes_of_760metagenomes.tar.gz
8eab242f68e77d91c05e5563467cded6  ./Study/Application_in_5_Escherichia_coli_genomes.tar.gz
dab0bb670a2403ae90bca3524eb86966  ./Study/Application_in_5_mock_metagenomes.tar.gz
81b58851e6ea0b4c539d9917b72c233f  ./Study/Application_in_760_genuine_metagenomes.tar.gz
96836f34f2d84aa85da6845a6d0fd86d  ./Study/References.tar.gz
470bd87945f98cf0ab74b589813d4817  ./Study/Scripts.tar.gz
99afccb94350eb7bbb3ba8509ed643ff  ./Study/Subnetwork_analysis.tar.gz
7851524c7c06569849fba22e019cae1c  ./readme.txt
```

The above file is created by the curators using a simple bash script (see below) as part of the dataset curation process.

To fix this issue, we will create a new function in the `protected/commands/FilesCommand` class which will parse the contents of the dataset `*.md5` file, and update the `file_attributes` table with the MD5 checksum value for each file in the dataset.

**Comment by only1chunts** [comment]
Ideally the MD5 values will be added to the database with the filename, filesize file type etc. i.e. when a row is created in the FILE table there should be an accompanying FILE_ATTRIBUTE for md5sum added as well.
As such they need to be created before the README file as the readme is created from the database.
The use of a single nnnnnn.md5 file is a legacy of how this process has been done previously, if there is a better way e.g. each file has its own accompanying <file_name>.md5 file then that is an option.
The script that is run on the server at the moment to create the nnnnnn.md5 file is very basic:

```
#!/bin/bash
# author Jesse

pwd=$(pwd)
filename=$(basename $pwd)
find ./ -type f -exec md5sum {} \;> "./$filename.md5"

```

For the time until the file upload wizard is deployed, the curators can continue to run the above script on each dataset prior to sending the spreadsheet for upload, OR a different script (to be written) if the alternative of 1md5 file per file is preferred?

**Comment by pli888** [comment]
>For the time until the file upload wizard is deployed, the curators can continue to run the above script on each dataset prior to sending the spreadsheet for upload, OR a different script (to be written) if the alternative of 1md5 file per file is preferred?

To confirm what was discussed on Friday, the curators will continue to run the script on each dataset before the spreadsheet is sent to the developers for upload.
