### ISSUE TITLE
[S804] Verify that peter's login to EM has appropriate privilege to design query and publish report

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1043]
Task for #804

**Comment by pli888** [comment]
I confirm that my EM login has create and publish report permissions. After logging into EM, the steps to create a report are:
* Go to `Administrative Functions` box and click on `Reports` link
* In the `Report Tools` section, click on `Enterprise Analytics Reporting` link to create editorial reports
* To create a report, click `Create Report` - you will see a Windows-like UI
* There are several tabs: `Data Sources` tab allows you to select a table to query. To combine data from 2 or more tables, you need to select multiple tables
* Once you have selected your tables click on the `Continue to Fields` button
* You then need to select the fields that you want to appear in your delimited table output. The tool will automatically join data from multiple tables.
* `Style` tab can configure format of delimited file
* `Filters` tab allows you to limit the number of records returned, e.g. by previous month, or yesterday - this could be used to keep data in the peer review system up to date with data on a daily basis
* There is a `SFTP` icon in the bar underneath the tabs. Clicking on this icon will display a window which you can use to enter the sFTP details of the server that will receive the report. N.B. URL for SFTP server should be entered as with the protocol prefix: `sftp://blah.sftp.com`.

The above instructions will be documented in work for #1042.
