### ISSUE TITLE
Make gigadb-website repo a good open-source citizen

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1048]
## User story

>As a developer  
>I want gigadb website to be seen by other technology/science workers as a good open source project 
>So that it is easier to get contributions, funding, new hires

## Additional Info

Provisional check list of stories to implement that help with this epic:

* Add an inclusive code of conduct [1]
* Review the chosen license (currently GPL-3) and code ownership for our codebase and ensure all our code reference licencing and copyright information is consistent [2]
* Remove out-of-date documentation
* Prefer short but focused documentation files written in Markdown and with either minimal jargon or glossary is added
* Use inline docs a lot (PHPDoc for PHP)
* Maintain multiple communication channels with our community at large (chat rooms, dedicated forums, mailing list, conference presence)
* Ensure our codebase can be deployed on Linux and Windows, not just macOS
* Ensure our codebase can be deployed on x86 an ARM  platform
* Join open source programs to get free licence for the enterprise version of tools we already use [3][4]
* Add a CONTRIBUTING file to the root of the codebase to indicate areas people can help with [5]
* Document and enforce consistent coding style in all the languages we support (PHP [6] and Javascript [7])
* Show in readme badges for the state of continuation integration build and where to join the developers
* Add a CODEOWNERS file to the root of the codebase to make it easy for contributors to assign a reviewer [8]
* Make it easier for GigaScience team to contribute (in code, documentation, funding [9], ...) back to other open source projects we depend on
* Make it easy for others to cite the gigadb-website code repository [10]
* Add a ``security.txt`` at root of the website to get help from security researchers [11]
* Replace ``master`` branch with ``main`` branch [12]

[1] https://opensource.guide/code-of-conduct/
[2] https://opensource.org/licenses
[3] https://about.gitlab.com/handbook/marketing/community-relations/opensource-program/
[4] https://blog.jetbrains.com/phpstorm/2020/01/our-pledge-to-open-source/
[5] https://mozillascience.github.io/working-open-workshop/contributing/
[6] https://www.php-fig.org/psr/psr-12/
[7] https://airbnb.io/javascript/
[8] https://github.blog/2017-07-06-introducing-code-owners/
[9] https://opencollective.com/search?tag=php, https://opencollective.com/codeception, https://opencollective.com/vuejs
[10] https://citation-file-format.github.io/
[11] https://en.wikipedia.org/wiki/Security.txt
[12] https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by only1chunts** [comment]
I think we're pretty "good" open source citizens, so lets close this. We can re-open if required.
