### ISSUE TITLE
bug found when viewing dataset after adding a new dataset-manuscript link via admin pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1056]
## User story

>As a curator
>I want to add a manuscript DOI link via the admin page https://beta.gigadb.org/adminManuscript/admin
>So that when a manuscript is given a DOI we can include that in the GigaDB entry

I suspect the issue is that the manuscript DOI I have entered is not YET published by OUP, they have only pre-assigned it, this means that the DOI is not valid and will not appear in cross-ref yet, effectively its a broken link, but we know that it will (eventually) be published and provide the correct link to the MS within the next X days/weeks depending on how fast/slow OUP production is or if there is any embargo on the manuscript.
The example that brought about this ticket is: https://beta.gigadb.org/dataset/view/id/102215
But if my suspicion is correct then that page will not be broken as soon as the DOI is minted by OUP, so depending on when this ticket gets looked it, it might not be showing an error message. Screen attached below shows what I see at the moment:

![image](https://user-images.githubusercontent.com/6037145/173389680-9310bbea-6ce7-4b85-b282-c83800945463.png)

## Acceptance criteria

>Given I add a manuscript link that is currently not "live"
>When I visit the relevant public dataset page
>Then the web page is still displayed but not displaying the link to the manuscript (until that MS DOI is live)

## Additional Info

Seems like the DOI is being used to retrieve citation information. If DOI link is broken then the dataset page is not displayed. Need to check the code that fetches information catches this particular problem.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Fix:
* Ensure the call to CrossRef and PubMed are wrapped in try catch to avoid bubbling server error.
* Capture response code from those api and if response code is error (e.g: 404) just display the info from the database which is either the manuscript or the PubMed link

**Comment by rija** [comment]
if error, add an entry to the error log

**Comment by rija** [comment]
The root cause lies in the file ``protected/views/dataset/view.php``,
in this line:
```
  $text = file_get_contents('https://data.datacite.org/text/x-bibliography/10.5524/' . $model->identifier);
```

``file_get_contents`` was designed mainly for local files, and it doesn't handle error modes for remote files.

Use Guzzle instead.

**Comment by kencho51** [comment]
By using Guzzle,
```
<?php
$url = 'https://data.datacite.org/text/x-bibliography/10.5524/' . $model->identifier;
$webClient = new GuzzleHttp\Client();
$response = $webClient->request('GET', $url);
```
 If trying to get citation from `non live` DOI `300070`, the internal server error `500` due to `404 Not Found` when trying to get citation of it from datacite is reproduced:
<img width="1628" alt="image" src="https://user-images.githubusercontent.com/64770635/210921670-e24b276e-24d6-4324-9da0-5ea5fa0a82d1.png">

This exception error could handled by implementing `try catch`:
```
 try {
    $response = $webClient->request('GET', $url);
    $text = $response->getBody()->getContents();
} catch (GuzzleHttp\Exception\RequestException $e) {
    Yii::log($e->getMessage(), "error");
} 
```
The above block would capture the exception and the web page be still displayed:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/64770635/210922189-9e31dd06-5c33-4f48-b588-ece62e6ee75f.png">

**Comment by kencho51** [comment]
Regarding the `404 Not Found` error,  after updating the `Identifier` to not working one in `/adminManuscript/update` after deploy `upstream/develop` to staging.

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/64770635/212592041-3635a2b3-11f5-4ecf-b6e5-b2ccad8ce11b.png">

And the manuscript table in staging db  has been updated:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/64770635/212592253-ebbed498-0c09-4b9f-9229-19ae66ccf20e.png">
