### ISSUE TITLE
Integration test in GitLab CI/CD pipeline check for both staging and live certs regardless of the deploy environment

### ISSUE THREAD

**Issue by kencho51** [gigascience/gigadb-website#1057]
**Describe the bug**

Now OpenSSL certs for staging and live will be checked at stage `intergration_tests`, which if either of the cert date expired, the gitlab CI/CD pipeline will be stopped. This is undesirable when only live cert expired, staging deployment cannot be proceeded, or vice versa.  

**Expected behavior**

Staging cert will only be checked at stage `build_staging`, while live cert be checked at stage `build_live`.

**Additional context**

**Comment by pli888** [comment]
Can use Uptime Robot to perform this function.
