### ISSUE TITLE
Parse and save EM Manuscript report using spreadsheet parser

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1062]
- [x] Create docker compose service for worker
- [x] Add configuration for manuscript worker so we know which queue to connect to
- [x] Add PHP spreadsheet dependency to composer
- [x] Parse different elements from report into Manuscript object and call `save()`
- [x] Functional test to check contents of manuscript table corresponds to a spreadsheet job present in the manuscript queue (if possible). 

## Additional information

Which database should connect to for functional tests? Need to use the test database so use yii_test configuration. Acceptance tests are run against the normal regular database with real data from the perspective of a real user.

**Comment by rija** [comment]
yii2-queue docs here: https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/README.md

**Comment by only1chunts** [comment]
the associated tasks are closed and merged, and we're going to be moving away from EM anyway, so I'm closing this ticket
