### ISSUE TITLE
Create acceptance test to check manuscript information in database

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1064]
- [x] Provide test data, i.e. the manuscript EM report
- [x] Acceptance test will check database
- [x] Modify acceptance test to use default connection details for SFTP server, i.e. not require live variables.
- [x] Connect this acceptance test work to specific user story, in contrast to functional test which does not require this.

**Comment by only1chunts** [comment]
all tasks ticked so closing this ticket as complete
