### ISSUE TITLE
GigaDB thumbnail image tags

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#1072]
**Describe the bug**
On GigaDB dataset pages, the text that appears over the thumbnail image is now displayed as a tooltip. This has the knock on effect that italics no longer display and that HTML tags are visible in the tooltip.

**To Reproduce**
1. Go to 'https://beta.gigadb.org/dataset/102229'
2. Mouseover the thumbnail image
3. See error

**Expected behavior**
HTML tags should not be visible in the tooltip, but should instead be used to format the text in the tooltip.

**Screenshots**
A screen capture is attached

**Desktop (please complete the following information):**
 - OS: 10.12.6
 - Browser: Firefox
 - Version: 101.0.1
 
![tooltip](https://user-images.githubusercontent.com/33310581/176399059-ac704369-2a2b-4fbc-b483-a6a005a57524.png)

**Comment by rija** [comment]
I think the near fix should aim to reproduce the behaviour we have on CNGB web site using the existing data (that includes the HTML tags added to the database).

TODO: We also need to create a new story to improve on the functionality so we don't have to store HTML tags in the database, and link to this bug.

**Comment by only1chunts** [comment]
this has been fixed
