### ISSUE TITLE
Dataset 100314 not working

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1073]
**Describe the bug**
GigaDB dataset 100314 is bad on live, but non-existent on beta, see ticket #676 for live bug already reported.

**To Reproduce**
1. Go to http://beta.gigadb.org/dataset/100314

**Expected behavior**
Should look more like other datasets e.g. http://gigadb.org/dataset/102236.

**Desktop (please complete the following information):**
- iOS 10.12.6 n.b. I know I need to update this.
- Chrome 103.0.5060.53
- Safari 12.1.2

**Screenshots**
![image](https://user-images.githubusercontent.com/6037145/176832742-80a8515f-13c0-472b-9ecb-6518d17bbc80.png)

Even on Live website it doesn't work properly, see also ticket #676 
![Screen Shot 2022-06-29 at 13 01 23](https://user-images.githubusercontent.com/1359170/176431562-f1e4c75b-e9e9-47ba-8c31-a00c2d5a94ea.png)

![Screen Shot 2022-06-29 at 13 01 38](https://user-images.githubusercontent.com/1359170/176431549-abdf6595-0a50-4092-8b9c-5e08777b33c9.png)

**Comment by rija** [comment]
The log for the webserver is showing this
```
2022/12/20 07:38:33 [error] 29#29: *13712 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/vendor/yiisoft/yii/framework/base/CBehavior.php on line 111PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /var/www/vendor/composer/ClassLoader.php on line 571" while reading response header from upstream, client: 81.220.58.148, server: beta.gigadb.org, request: "GET /dataset/100314 HTTP/2.0", upstream: "fastcgi://172.16.238.2:9000", host: "beta.gigadb.org"
```

**Comment by pli888** [comment]
Sometimes dataset contains lots of files or lots of samples. Suggestion is to show the first 1000 items. Need to provide a way to show users how to get hold of the rest of the files/samples, e.g. click here to get the remaining items.
