### ISSUE TITLE
restrict allowed file formats to predefined list

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#108]
NB- This may already be covered in the File Upload tool works...

## User story
> As a curator
> I want all files to use a specified list of file formats
> so that we can effectively filter on file format field

## Acceptance criteria
> Given a user uploads a file to us
> When its metadata is saved in the database
> Then the file format is selected from a pre-defined list of possible options (currently held in our File_Format table)

## Additional information
The File_format table should be updated at the same time as time work, see #434 
The file format table does contain a wide range of allowable formats, but we should think about how we want to invite authors to contact us regarding new formats to be added.
OR we look to synchronise the table with something like the EDAM_DATA ontology. http://edamontology.org/page

**Comment by rija** [comment]
Done in File Upload Wizard
