### ISSUE TITLE
bug/bad behaviour with Excel spreadsheet upload form

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1082]
**Describe the bug**
This is something I noticed a while ago and forgot to write up, so I'm struggling to remember the exact details!
Its regarding the format of the author list Cell C13 on the study tab of the [v15 template spreadsheet in version control](https://github.com/gigascience/gigadb-website/blob/develop/gigadb/app/tools/excel-spreadsheet-uploader/template/GigaDBUpload-template_v15.xls)
Occasionally I've seen an author get messed up during the upload process for some reason, **I THINK** maybe its to do with the inclusion of square brackets when there is no ORCID for an author.
e.g. an author list written this way is parsed fine:
`Rubina Sherpa [0000-0002-5361-5311]; Ramgopal Devadas [0000-0002-8407-6277]`
written this way also appears to parse OK:
`Rubina Sherpa []; Ramgopal Devadas [0000-0002-8407-6277]`
BUT written this way does not:
`Rubina Sherpa [ ]; Ramgopal Devadas [0000-0002-8407-6277]`
Note the space inside the square brackets, I believe that causes the lookup that the upload script does to find a match on the ORCID field to the first author in the author table that has a space as their orcid ID value, regardless of the name values.

**Expected behavior**
The lookup behaves correctly in that it first looks at the ORCID, then at the names to check GigaDB for already existing authors, but if my theory above is correct, then we should look to do an additional validation on the content of the square brackets before that lookup is done, something relatively simple would suffice, just a check that the content matches the reg-ex of an orcid value.

**Comment by rija** [comment]
Sounds like a the parsing code for orcid in the java tool is not robust enough and should detect ``[ ]`` the same as ``[]``
(and there could more than one space to remove)

**Comment by only1chunts** [comment]
no longer an issue
