### ISSUE TITLE
check sample attributes during spreadsheet ingestion

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1088]
## User story

>As a curator  
>I want the spreadsheet upload tool to include a check of sample attribute names
>So that I can be sure that the sample attributes being uploaded are already in the database

## Acceptance criteria

>Given I have generated a submission spreadsheet including samples with attributes
>When it is parsed by the upload scripts
>Then the sample attribute names are checked against the database

>Given a submission spreadsheet including samples with attributes is parsed by the upload scripts
>When the sample attribute names are checked against the database
>Then any sample attribute names that do not match cause an error log to be generated describing which sample attribute(s) are not present in the GigaDB database.

## Additional Info

There are already checks in place in the Excel spreadsheet so there shouldn't be many cases where the checks fail, but as has been raised before, Spreadsheets are not infallible due to copy/paste issues that remove validation from cells.
There needs to be an assessment of the amount of time this task could take with consideration that the spreadsheet upload tool is meant to be a temporary feature (being replaced by submission wizard eventually) 
Also **IF** this validation work could be incorporated into the submission wizard CSV upload then it wouldn't become redundant after we stop using the spreadsheet upload tool.

If a `new` sample attribute name is identified by the spreadsheet tool then the error log message would inform the curators that the `new` sample attribute name could be a typo which is then fixed in spreadsheet. Or it might be a real new sample attribute.

This is related to and probably should be worked on the same sprint as issue #1091 

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Basically, the work involved is to log to the ``java.log`` the result of validating, parsing, and updating of sample attributes.

**Comment by only1chunts** [comment]
closing this issue as we're not doing any more work on the excel ingestion tools, instead we will be working on the submission wizard which will include these integrity checks
