### ISSUE TITLE
unusual behavior with attributes on beta site sample update page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1102]
## User story

>As an admin user
>I want to be informed by the website of erroneous attributes being used
>So that I can correct my mistake

## Acceptance criteria

>Given I am editing a sample, e.g. https://beta.gigadb.org/adminSample/update/id/1018
> And I include an attribute name that does not exist in the database
>When I click save
>Then the system informs me which attribute name is not valid and asks me to choose a valid attribute name

## Additional Info
Currently the live system fails with a nasty CDb exception.
Currently the beta site does not fail, instead, it appears to insert a new erroneous attribute into the attribute table without informing the user, this must not happen.

We should check if the same thing happens on the file admin page?

This is related to [#1088](https://github.com/gigascience/gigadb-website/issues/1088).

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
If this problem is real, look into foreign constraints in database schema.
They should prevent this from happening

**Comment by kencho51** [comment]
In `/AdminSampleController.php`:

It seems that non-exist attribute is expected to create and save.

```
 // Get attribute, if not exist we create
$attribute = Attribute::model()->findByAttributes(array('structured_comment_name' => trim($data[0])));
if (!$attribute) {
    $attribute = new Attribute();
    $attribute->structured_comment_name = trim($data[0]);
    $attribute->attribute_name = str_replace('_', ' ', trim($data[0]));
    $attribute->definition = str_replace('_', ' ', trim($data[0]));
    $attribute->save();
}
```

**Comment by rija** [comment]
Reopening this issue as @tuli and @only1chunts found a regression on the beta website probably introduced when implementing the fix for this issue

**Comment by kencho51** [comment]
Hi, 

Here is what I have found in my staging.
1. I go `adminSample/update/id/1018`
2. I see:
![image](https://github.com/gigascience/gigadb-website/assets/64770635/230ca359-5431-464c-8ec9-4ab283a1b437)
3. When I update the attribute list by adding `animal="tiger"`, and save, I see:
![image](https://github.com/gigascience/gigadb-website/assets/64770635/8e9fe38f-e9c9-4a89-9998-3b76f396e02b)
4. The alert message correctly displayed the error, but only one of the original attribute was kept.

**Comment by only1chunts** [comment]
This is a very different issue to the one we see now, I've not checked if
this is happening or not.

**Comment by only1chunts** [comment]
Sorry, ignore my last comment, doing this on a phone!
Ken has spotted the issue, i.e. it's only saving the last thing in the list

**Comment by rija** [comment]
The new introduced problems have been fixed in PR #1516 which has been merged yesterday to `develop`.
So it can be tested by users on https://staging.gigadb.org

**Comment by tuli** [comment]
I am not sure if this means that the attribute problem is fixed, but I just tested it on beta and I see the same error.

https://beta.gigadb.org/adminSample/update/id/183132
I want to update current Attributes List Analyte type="DNA" to
Attributes List Description="DNA extracted from an adult ratsnake, Ptyas mucosa. stLFR.",Analyte type="DNA",alt_acc_BioSample="SAMN34176910",alt_acc_SRA_exp="SRX20304009",alt_acc_BioProject="PRJNA955401",Geographic location (country and/or sea,region)="China:Guangxi Province:Hezhou City",Latitude="24.409",Longitude="111.561",Broad-scale environmental context="montane forest[ENVO:01000435]",Local environmental context="mountain[ENVO:00000081]",Life stage="adult",Collection date="2021",tissue="adult organism[UBERON:0007023]",samp_mat_process="samples were transferred to dry ice and quickly frozen",est_genome_size="1.74 Gb",BUSCOv5_result="C:86.6%[S:84.3%,D:2.3%],F:8.9%,M:4.5%,n:3354",contig_n50="9.58 Mb"

It saves it as  Attributes List contig_n50="9.58 Mb"

**Comment by kencho51** [comment]
Hi @tuli,

The fix is in https://staging.gigadb.org now for testing, not in the beta yet.

**Comment by tuli** [comment]
> Hi @tuli,
> 
> The fix is in https://staging.gigadb.org now for testing, not in the beta yet.

Ah thanks. I can't see staging (staging.gigadb.org took too long to respond) so I can't test this. I'm not even sure if I'm meant to be! This ticket just caught my eye.

**Comment by rija** [comment]
> > Hi @tuli,
> > The fix is in https://staging.gigadb.org now for testing, not in the beta yet.
> 
> Ah thanks. I can't see staging (staging.gigadb.org took too long to respond) so I can't test this. I'm not even sure if I'm meant to be! This ticket just caught my eye.

Hi @tuli,

Yes, you are meant to access that URL. It gives you preview of what's going to be deployed eventually on beta/live.
Deployments to the staging environment are fully automated though, so whenever the tech team merge a PR to `develop`, at some point later, a deployment will happen at the end of which the site is briefly non accessible.

I've just checked, and it loads correctly for me at the moment.

**Comment by tuli** [comment]
I can now access staging.
I have reproduced what I tried to do in beta and confirm that I do not get the error i.e. the Attributes List saves as I would expect. I tested only the Sample ID  Ptyas_stlfr

All good.
