### ISSUE TITLE
Add Yannan to team page 

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1106]
## User story

>As a website user  
>I want to see Yannan's information on the team's page https://beta.gigadb.org/site/team
>So that I see her details on it.

## Acceptance criteria

>Given that on web page  
>We can find that page
>Then outcome

## Additional Info
Yannan Fan
Assistant Data Editor

Background with web application development and plant genome evolutional analysis, and now she joins the team as a data editor.

[161661852279_ pic](https://user-images.githubusercontent.com/112144621/187405773-75d952ba-0cf3-4d33-aa6e-eb20543d18d4.jpg)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by only1chunts** [comment]
this is marked as closed, but I dont see these details on the https://beta.gigadb.org/site/team page, i.e. the acceptance criteria has not been fulfilled yet.

**Comment by only1chunts** [comment]
bet has now been deployed with these updates
