### ISSUE TITLE
[S1123] Create bash script to parse rclone logs and return error status  if transfer failure occurs

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1132]
* [x] Install tool `swatch`
* [x] Use `swatch` to look for the error/success messages in the logs file created by the rclone process
* [x] Run notifier script if error/success found

Additional infos:

* https://rclone.org/docs/#exit-code

**Comment by only1chunts** [comment]
all tasked complete and merged so closing ticket
