### ISSUE TITLE
Button to verify what is held in Datacite MetaData Store (MDS) against a current GigaDB dataset info

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#114]
## User Story
>As a site administrator
>I want to be sure that our DataCite metadata is always upto date
>So that we always leverage Datacite to its full extent

>Given a dataset DOI is registered in DataCite 
>And I navigate to a dataset page
>When I click the "Verify" button
>Then a report "showing" the differences between DataCite data and our generated schema is produced

OR (a new idea added Apr2024)
> Once a quarter (i.e. every 3months)
> An automated script is executed that performs a serial check on all current dataset metadata vs datacite metadata
> and reports any differences to the GigaDB curators to investigate and update as required.

## Additional information

>Note: This assume the "mint button" code is using latest schema

having found an old dataset that at some point got rolled back to an outdated version of author list we need to ensure that all datasets remain correct. One way to do with is to check whats in GigaDB against what we sent to DataCite MDS for minting the DOI.
Also by checking datacite matches GigaDB we can be sure we dont forget to update datacite with any changes we make in GigaDB. @jessesiu is writting this script and adding to the weekly report

This is related to #549

**Comment by rija** [comment]
this is not required, so closing
