### ISSUE TITLE
Clicking the Mint DOI button should update the information in DataCite

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#115]
## User Story
>As a curator
>I want to be able to update the metadata stored in DataCite at the click of a button
>So that the DataCite record is easily maintained

## Acceptance criteria

>Given i have a public dataset
>and I have made a minor update to it
>When I click the mint DOI button on the dataset admin page
>then the relevant DOI metadata at DataCite is updated with the minor update.

## Additional information

This is particularly important for addition of journal links to DataCite metadata. i.e. we publish the dataset before we get the manuscript link, so that manuscript DOI doesn't get included in the datacite metadata. 
This could be the same button as "Mint DOI" but that changes to "Update DOI" after its been minted.
scholix - started from RDA research Data alliance - they maintain a ser of guidelines for interoperability. includes shareholders from datacentres and publishers. representation is in XML and JSON. OPEN model. scholix.org - We dont need to worry about this particularly as they interact with DataCite, we just need to make sure we are keeping the DataCite metadat upto date with journal links

2 - The inclusion of manuscript links needs to be updated to include the resourceTypeGeneral attribute to allow datacite to know what the thing we're linking out to is, e.g. from dataset 100747:

```
<relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="IsCitedBy" resourceTypeGeneral="text/journal article">10.1093/gigascience/giaa067</relatedIdentifier>
    </relatedIdentifiers>
```

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by jessesiu** [comment]
Follow up this issue:

1. the Mint DOI button, if you mint the same DOI, DataCite will change it to update metadata XML file. So if you want to update it, just click the button again.

2. Scholix metadata: Add the relationships link to manuscripts in the current dataset metadata XML file via the "IsCitedBy" and value will be the manuscript DOI. 

# Plan
1. select all dataset.identifier and associated manuscript.doi, loop the dataset.identifier list to get all DataCite XML metadata via DataCite API. 

2. parse the XML metadata and add the associated manuscript.doi in the relatedIdentifier section with relationType "isCitedBy" and manuscript DOI. e.g. 
```
<relatedIdentifier
relatedIdentifierType="DOI"relationType="IsCitedBy">10.4232/10.ASEAS-5.2-1
</relatedIdentifier>
```

**Comment by only1chunts** [comment]
Additional plan for new datasets -
-After first successful Mint of DOI, can we get the button name changed to Update DOI instead of Mint DOI?
-Add curators comment whenever the DOI is first minted AND for every subsequent successful update. 
-If possible it would be great to show whats been updated in that comment too.
(maybe the presences of the DOI minted comment could be used as trigger for button to display as update instead of mint?)

**Comment by only1chunts** [comment]
Additional feature request for button- Can the XML generated also be stored somewhere on the local server so that we have a copy, this will be useful in cases where we get an error returned from DataCite API for trouble shooting.

**Comment by rija** [comment]
this is already happening
