### ISSUE TITLE
Bug: Make the spreadsheet upload run with distinct user

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1150]
At the moment, the root user is used to run the spreadsheet upload tool on AWS deployment, this is security issue, so it needs to use a distinct low-privileged user.

**Comment by rija** [comment]
@pli888 I was about to close this ticket, but I first wanted to ask whether you are doing your current spreadsheet upload trial using your user or the centos user?

**Comment by pli888** [comment]
>I was about to close this ticket, but I first wanted to ask whether you are doing your current spreadsheet upload trial using your user or the centos user?

I've not started testing on beta server yet due to spreadsheet problems, but I was going to use centos user as this user account is already created and I have access to it as a developer.

**Comment by only1chunts** [comment]
each curator can run the tools now, so closing this ticket as completed
