### ISSUE TITLE
Add a small up-down symbol to the sample column title which can be sorted

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1155]
## User story

>As a Website user
>I want to add an up-down symbol to the column of the sample table on a dataset page
>So that I know this column can be sorted by clicking.

## Acceptance criteria

![image](https://user-images.githubusercontent.com/112144621/201062764-b927110a-285a-450a-981c-5a31cbf9beee.png)

>Given I browse the sample tab on a  GigaDB dataset page
>When I see the column (Sample ID/Taxonomic ID/Scientific Name) with up-down symbol
>Then I know it can be sorted by clicking.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by only1chunts** [comment]
this task in this issue has been completed and is working on live, so I'm closing this ticket
