### ISSUE TITLE
the saved search option doesn't work as expected

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1168]
## User story

>As a registered GigaDB user
>I want to re-run a previous search  
>So that I can see if any new datasets match my query

## Acceptance criteria

>Given I am logged in to GigaDB
>When I navigate to the public search page
>And I make a search 
>Then I should not see a "Save current search criteria" button

>Given I am logged in to GigaDB
>When I navigate to my user profile
>I should not see the "Your saved search" tab

## Additional Info
There are some bugs at the moment, probably related to the changes @rija made to the search function when he got it working:
 - the searches I had previously saved in my user profile dont return ANY hits, one of them is simply searching for "genome" which should return >1500 results.
 - when I click save current search criteria it enteres a random search called "penguin" into my list of saved searches!?

As this is a low-value feature; For a temporary fix prior to deployment, we can remove the "save search criteria" button and the saved searches tab from public view. 

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Two steps:
 * remove the feature from the public search functionality and from the user profile
 * make it works as part of separate story

**Comment by pli888** [comment]
Implementation: hide this broken functionality for now.

**Comment by kencho51** [comment]
Background work:
1. In `protected/views/search/_search.php`, the data to save is hardcoded as `penguin`:
```
            'data': { 'criteria': '\x7B\x22keyword\x22\x3A\x22penguin\x22,\x22criteria\x22\x3A\x22\x22,\x22tab\x22\x3A\x22\x22,\x22query_result\x22\x3A\x22\x22,\x22type\x22\x3A\x5B\x5D,\x22dataset_type\x22\x3A\x5B\x5D,\x22publisher\x22\x3A\x5B\x5D,\x22project\x22\x3A\x5B\x5D,\x22pubdate_from\x22\x3A\x22\x22,\x22pubdate_to\x22\x3A\x22\x22,\x22moddate_from\x22\x3A\x22\x22,\x22moddate_to\x22\x3A\x22\x22,\x22author_id\x22\x3A\x22\x22,\x22common_name\x22\x3A\x5B\x5D,\x22external_link_type\x22\x3A\x5B\x5D,\x22exclude\x22\x3A\x22\x22,\x22file_type\x22\x3A\x5B\x5D,\x22file_format\x22\x3A\x5B\x5D,\x22reldate_from\x22\x3A\x22\x22,\x22reldate_to\x22\x3A\x22\x22,\x22size_from\x22\x3A\x22\x22,\x22size_to\x22\x3A\x22\x22,\x22size_from_unit\x22\x3A\x22\x22,\x22size_to_unit\x22\x3A\x22\x22\x7D', 'result': '\x7B\x22files\x22\x3A\x5B\x5D,\x22samples\x22\x3A\x5B\x5D,\x22datasets\x22\x3A\x5B210\x5D\x7D' },

```
