### ISSUE TITLE
curation log error

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1169]
## User story

>As a curator
>I want to be able to use the curation log
>So that I can ensure appropriate logging of actions in un-published dataset(s)

## Acceptance criteria

>Given I am on the dataset admin page e.g. https://beta.gigadb.org/adminDataset/update/id/2571
>When I click create new log  e.g. "https://beta.gigadb.org/curationlog/create/id/2571"
>Then I am presented with the create curation log entry page, e.g. http://beta.gigadb.org/curationlog/create/id/2571

>Given I am on the dataset admin page e.g. https://beta.gigadb.org/adminDataset/update/id/2571
>When I click View curation log entry icon e.g. https://beta.gigadb.org/curationlog/view/id/1870
>Then I presented with a view of the curation log entry

>Given I am on the dataset admin page e.g. https://beta.gigadb.org/adminDataset/update/id/2571
>When I click the Edit curation log entry icon  e.g. https://beta.gigadb.org/curationlog/update/id/1870
>Then I am presented with the edit curation log entry page

>Given I am on the dataset admin page e.g. https://beta.gigadb.org/adminDataset/update/id/2571
>When I click delete curation log entry icon, e.g. https://beta.gigadb.org/curationlog/delete/id/973
> Then I am asked to confirm choice
> And when I confirm choice
> Then that curation log entry is deleted from the database

## Additional Info
This is probably related to #1124 
Note- there may be some confusion over which table these entries go in, as there are two logging tables, one for curation logs called CURATION_LOG for things prior to the dataset being public (i.e. the stuff in this ticket), and one called DATASET_LOG used for post-publication updates (not to be touched by things in this ticket).

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by kencho51** [comment]
Background work:
1. The acceptance criteria are passing in local dev
2. Got `Unable to resolve the request "curationlog/create/id/2571".` error in staging
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/64770635/208841950-69b04bd5-008d-4eba-991c-173f8b9cae64.png">

```
$ docker logs kencho-gigadb-website_web_1
14.199.148.232 - - [21/Dec/2022:06:59:56 +0000][-] "GET /assets/45fcd6cc/pager.css HTTP/1.1" 304 0 "http://ec2-staging.gigadb.link/adminDataset/update/id/2571" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"

$ docker logs kencho-gigadb-website_application_1
172.16.238.10 -  21/Dec/2022:07:00:39 +0000 "GET /index.php" 404
CHttpException: Unable to resolve the request "curationlog/create/id/2571". in /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('curationlog/cre...')
#1 /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/index.php(24): CApplication->run()
#3 {main}
REQUEST_URI=/curationlog/create/id/2571
HTTP_REFERER=http://ec2-staging.gigadb.link/adminDataset/update/id/2571
```
