### ISSUE TITLE
file path / location length in admin pages needs to be extended

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1174]
## User story

>As a curator
>I want to be able to add and update file locations that are longer than currently allowed in the admin pages
>So that the file location can be correctly entered via the admin pages

## Acceptance criteria

>Given I need to add a file to an existing dataset in gigadb
>When  I visit the create new file admin page (https://beta.gigadb.org/adminFile/create)
>Then I am able to enter a location URL that is long enough to allow wasabi storage locations.

>Given I need to update a file in an existing dataset in gigadb
>When I visit the update dataset-file admin page (e.g. https://beta.gigadb.org/adminFile/update/id/93734 )
>Then I am able to enter a location URL that is long enough to allow wasabi storage locations.

## Additional Info
This arose when I tried to test adding a Wasabi location to a file in beta.gigadb.org, 
I went to 
https://beta.gigadb.org/adminFile/update/id/93734
pasted in the url from the wasabi file manager into the "Location" box as:
https://s3.us-east-1.wasabisys.com/gigadb-datasets/live/pub/10.5524/100001_101000/100216/Badhwar_HBM_Brainspell-master.zip
Clicked save, noticed that the location had been truncated, see screenshot below:

![image](https://user-images.githubusercontent.com/6037145/206407437-b794d235-38f1-4bee-b470-d269f9d00086.png)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by kencho51** [comment]
Just some background work:
1. On local dev, `/adminFile/create`

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/64770635/207633634-ca7a1005-61be-4fd5-b3e6-e7bccaf7bdfd.png">
In table `file`, the inputed location has not been truncated too.

2. On local dev, `/adminFile/update/id/446`
Change location `ftp://climb.genomics.cn/pub/10.5524/100001_101000/100039/readme.txt` to `https://s3.us-east-1.wasabisys.com/gigadb-datasets/live/pub/10.5524/100001_101000/100216/Badhwar_HBM_Brainspell-master.zip` 

<img width="976" alt="image" src="https://user-images.githubusercontent.com/64770635/207635643-b77a9ed3-3153-4afe-bc35-f0765d3bdc63.png">

3. On staging, `http://ec2-staging.gigadb.link/adminFile/create` then `http://ec2-staging.gigadb.link/adminFile/view/id/535133`
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/64770635/208042236-24f9f4cb-a6dd-4071-bda0-481db94aa1c6.png">

4. On staging, `http://ec2-staging.gigadb.link/adminFile/update/id/535121`
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/64770635/208043237-e95fcff9-bfed-47a0-a678-f40a39019549.png">

**Comment by kencho51** [comment]
Cannot reproduce the problems in my environments.

**Comment by only1chunts** [comment]
Apologies, I've just tried again on beta.gigadb.org and I can see that this is no longer an issue there, so it must have been fixed.
FYI: The issue I spotted during the demo that made me ask it to be reopened was the file name (not location) still has a limit, but i believe thats long enough to accommodate all possible real filenames!
