### ISSUE TITLE
Create Console Controller class

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1178]
- [x] Use model classes to retrieve readme information
- [x] Place new created readme.txt file in /home/curators directory
- [x] Create unit tests
- [x] Create functional test to ensure script outputs a file

Try using dataset 100314 which is a bugbear dataset.

Also try using dataset 100310 which has >19k files.

Points to note:

* Use model classes in `/gigadb/app/worker/file-worker/models` not the model classes that come with GigaDB repo.

**Comment by rija** [comment]
May need to add a PSR-4 clause to composer json to access model class:
```
 "autoload": {
        "psr-4": {
            "app\\models\\" : "/gigadb-apps/worker/file-worker/models"
        }
     }
```

**Comment by only1chunts** [comment]
everything is ticked and merged so I think we can close this ticket
