### ISSUE TITLE
Hard coded API URLs in help page

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#118]
The URLs for the API in the [help page](http://gigadb.org/site/help) are hard coded in the [HTML file](https://github.com/gigascience/gigadb-website/blob/develop/files/html/help.html). Therefore, when you run a test GigaDB website on a Vagrant VM, the API URLs on the help page do not work.

@jessesiu Think about using a Chef template file to generate the HTML help page so that the API calls use the correct domain name in the URL so that they work on any server deployment.

**Comment by only1chunts** [comment]
fixed in jesse/gigadb-website, checked 23-Mar-2017
