### ISSUE TITLE
Setup Application Performance Monitoring tools for the codebase

### ISSUE THREAD

**Issue by kencho51** [gigascience/gigadb-website#1183]
## User story

>As a developer  
>I want selected APM tools installed on dev or production environments
>So that I can fix bugs, monitor the performance and get alerts.

## Additional Info
Here are the tool list for APM:
1. https://www.blackfire.io/
2. https://scoutapm.com/
3. https://tideways.com/

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
We choose Tideways because: 

* dedicated to PHP and integrate with yii framework
* we've already used tideways before
* Tideways is cheapest
* Tideays plan support two environments

**Comment by rija** [comment]
Installation instruction:

https://support.tideways.com/documentation/setup/installation/docker-with-compose.html

* Will need to create a Tideways account - there is a free trial for us to use initially.

**Comment by rija** [comment]
Closing, we went for Tideways a while ago now.
