### ISSUE TITLE
[S1136] Create tutorial for curators to upload files into Wasabi

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1192]
* Work on creating tutorial with ChrisH
* Curators and dataset submitters to use FilaZilla Pro (transfer files from local machine to Wasabi) and RClone (transfer files from CNGB FTP server to Wasabi) for uploading files. Also need to think about how to get files from CNGB drop box to Wasabi.

**Comment by rija** [comment]
closing, as @only1chunts will do it
