### ISSUE TITLE
404 Not Found when trying to get text citation from datacite

### ISSUE THREAD

**Issue by kencho51** [gigascience/gigadb-website#1203]
**Describe the bug**

If trying to get citation from non live DOI, eg. 300070,  it would open a new page showing internal server error 500 due to 404 Not Found or a blank page.

**To Reproduce**
1. Go to '/dataset/300070'
2. Click on 'Cite Datasets'
3. Click on 'Text'

**Expected behavior**

If the url is not resolvable, just hide the `Cite Dataset` box.

**Screenshots**

![image](https://user-images.githubusercontent.com/64770635/218410651-96985407-c27e-4d24-85ba-c7b5b5f7b25f.png)

**Additional context**

**Comment by only1chunts** [comment]
this bug is no longer and issue on live, so i think its fine to close ticket
