### ISSUE TITLE
Can change funder easily  on the funder admin form E1212

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1217]
## User story

>As a curator when I try to change a funder on a dataset
>I want to search for a particular funder name in the admin form "/datasetFunder/create"
So that I can quickly add the author to the dataset I want to update

## Acceptance criteria

>Given a funder already exists in GigaDB
>When I navigate to "/datasetFunder/create"
>then I can change the "funder" value using a search box

## Additional Info

This story is part of Epic #1212

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by only1chunts** [comment]
this has already been done, so closing this ticket
