### ISSUE TITLE
update DCI logo

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#123]
update the DCI logo on this page:
http://gigadb.org/site/about
with the attached new version of the logo.
![dci_badge](https://user-images.githubusercontent.com/6037145/27798049-c0344d54-6007-11e7-8775-e5c8e4091074.png)

**Comment by only1chunts** [comment]
@jessesiu is this ticket OK to close now? i.e. has the update been integrated into the production github code yet?

**Comment by jessesiu** [comment]
Yes, it can close

发自我的 iPhone
