### ISSUE TITLE
make the dataset folders public in Wasabi

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1232]
## User story

>As a user  
>I want to be able to access the dataset folder for a given dataset in Wasabi
>So that I can see all the files and choose which I want to download from Wasabi

## Acceptance criteria

>Given I am on the GigaDB dataset 102360 webpage 
>When I click the "Directory listing" button
>Then it downloads a CSV file listing all the file names, file type, file format, checksum, and files urls for that dataset

## Additional Info

Currently, the folders are not set to public, are there any security issues with changing them to be public?

* https://wasabi-support.zendesk.com/hc/en-us/articles/115001684511-What-are-the-minimum-and-maximum-object-sizes-that-can-be-stored-in-Wasabi-

* https://wasabi-support.zendesk.com/hc/en-us/articles/115001684511-What-are-the-minimum-and-maximum-object-sizes-that-can-be-stored-in-Wasabi-

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Maybe leverage the Readme file and better signage to find the readme file for each dataset

**Comment by only1chunts** [comment]
This is not actually possible with the wasabi user interface, however it is possible with their API if we build that into the file browser widget thing, ticket #232 
There is also a method to do this with various 3rd party tools such as FileZilla or "[S3 Browser](https://s3browser.com/)"
but those methods require the user to have a Wasabi user account, so only suitable for the GigaDB team (curators and tech).

**Comment by only1chunts** [comment]
I dont think we need this ticket anymore, the dataset pages allow browsing by dataset, anyone that wants command line access will need to use rclone or something similar. 
Closing this ticket
