### ISSUE TITLE
erronious behaviour when editing external links on published datasets (on beta)

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1242]
## User story

>As a curator
>I want to be able to add/edit/remove additional link tabs via the admin pages (on beta.gigadb.org)
>So that the dataset page is maintained correctly

## Acceptance criteria

>Given I add a protocols.io widget to a dataset accidentally
>When I remove that protocols.io link from the dataset
>Then it is no longer displayed on that dataset

>Given I have already added an incorrect protocols.io line (above)
>When I edit that link to be the correct type e.g. 3dmodels
>Then the tab displayed on the dataset is the correct (3d models) type

rpt the above for other iframe-type external links (3d model, code-ocean, jbrowse & ucsc tumour map viewer)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
This looks like a caching issue, like on #1175.
The fix of which is merged to the `develop` branch but not yet deployed to `beta.gigadb.org`.
I suggest waiting a couple days from now and verify that this is no longer an issue

**Comment by only1chunts** [comment]
this appears to have been fixed as it now behaves as expected, so closing this ticket
