### ISSUE TITLE
Investigate if Wasabi web console can create user accounts for authors

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1244]
Can the Wasabi web console be used to:

* Create user accounts for dataset authors?
* Enable authors to upload their dataset files into a bucket for review?

**Comment by only1chunts** [comment]
are we using Wasabi for the private user dropboxes? I thought we were looking at AWS for those

**Comment by pli888** [comment]
@only1chunts We looked at costs which will be 200-300 USD per month on AWS just for 4 TB elastic block storage. Then there will be other costs, e.g. for the EC2 instance itself, transfer of data from AWS to Wasabi, etc. So, we thought we would look to see how Wasabi could provide functionality for private user dropboxes.

**Comment by only1chunts** [comment]
I dont think this is required anymore as the FUW work will handle private dropboxes
