### ISSUE TITLE
[S1250] Create SOP to allow curators to run the console command

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1259]
give guidance to curators on how to run the console command on bastion

**Comment by kencho51** [comment]
As discussed, will use the github [wiki page](https://github.com/gigascience/gigadb-website/wiki) to host the SOP for curators/editors

**Comment by only1chunts** [comment]
> As discussed, will use the github [wiki page](https://github.com/gigascience/gigadb-website/wiki) to host the SOP for curators/editors

Sorry to be a pain, but No, the curators will not use a GitHub wiki for SOPs when we already have the intranet pages for all our other SOPs. By all means write an SOP for tech users in a GitHub wiki, but dont expect the curators to use it.
We have one for [completing the spreadsheet](https://sites.google.com/gigasciencejournal.com/giganet/gigadb/curation/excel-submission-sheet-guidelines?authuser=0) and we have one for [using the command line tools](https://sites.google.com/gigasciencejournal.com/giganet/gigadb/curation/spreadsheet-upload-scripts?authuser=0) 
These can be updated easily by anyone with an @gigascience email address.

**Comment by rija** [comment]
Hi @only1chunts, 

What's the entry point for editing existing sites?
The Google sites dashboard doesn't show existing sites not created by me and the search function doesn't surface existing sites in search results


<img width="1718" alt="Screenshot 2023-11-20 at 9 40 11 AM" src="https://github.com/gigascience/gigadb-website/assets/11455/7bcd7d99-0b73-49ed-b7a2-68f029f4a510">

**Comment by only1chunts** [comment]
Just goto the page you want to edit and click the Pencil icon in the bottom right corner:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/02fc3195-b42b-416e-8f20-9f1f09ed0498)

**Comment by rija** [comment]
@only1chunts 

I don't have the pencil icon showing up for me

<img width="1725" alt="Screenshot 2023-11-20 at 9 58 09 AM" src="https://github.com/gigascience/gigadb-website/assets/11455/b4628787-a1ad-4b97-9803-adea1758770c">

**Comment by rija** [comment]
PR is ready for review
