### ISSUE TITLE
[S1265] update the licence text within the readme script 

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1262]
## User story

>As a curator
>I want the readme for each dataset to mention the license that governs the datasets that are hosted by us
>So that our users know what they can do with the datasets they download

The wording of the license section in the readme files automatically generated by the readme script needs to be adjusted:

## Acceptance criteria

>Given I am a curator creating or updating a dataset
>When I run the "create readme" script
>Then it runs as usual but the section under licenses has this new text:

"All files and data in this dataset are distributed under the Open Data Commons, Public Domain Dedication and License v1.0 whose full text can be found at: [http://opendatacommons.org/licenses/pddl/1.0/](https://opendatacommons.org/licenses/pddl/1.0/), unless specifically stated otherwise, see http://gigadb.org/site/term for more details."

## Additional Info

This is another change in the same way that #1210 was done recently by @pli888 . A new data specific license has recently been discovered that is more appropriate than the creative commons one we currently state. 

A similar update will be required on the GigaDB static web pages to reflect this move, a separate ticket will be created #1263.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
this is trivial, it's a template update and can be a task into story #1265

**Comment by only1chunts** [comment]
After further discussions with Scott & Laurie, we (GigaScience Press) dont want to move to using the pddl license(s) yet due to the lack of uptake in the community meaning people searching for CC0 datasets may miss our datasets if they are pddl instead of CC0, (even though the waiver has the same end-results!)
@pli888 please check this wasn't already updated as part of the #1210

**Comment by only1chunts** [comment]
not changing license info yet, will revisit at a later date
