### ISSUE TITLE
Update text in Terms of use page E564

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1263]
## User story

>As a user  
>I want to see the correct information in the GigaDB help pages
>So that I know what to expect from GigaDB

## Acceptance criteria

>Given I visit the "[Terms of Use](http://gigadb.org/site/term)" page 
>When I read the text
>Then I see these 3 corrections:

- [1]

"Datasets associated with GigaScience journal articles are specifically released under a Creative Commons [CC0](http://creativecommons.org/about/cc0) waiver unless stated otherwise. While CC0 waives any legal requirement for"

should be changed to

"Datasets associated with GigaScience journal articles are specifically released under a [Open Data Commons Public Domain Dedication and License (PDDL)](https://opendatacommons.org/licenses/pddl/) waiver unless stated otherwise. While PDDL waives any legal requirement for"

- [2]

"license agreement that supersedes the default CC0 waiver."
should be changed to 
"license agreement that supersedes the default PDDL waiver."

- [3]

"Publication irrevocably grants anyone the right to use this work under the Creative Commons Zero Waiver which releases all rights, like public domain. We agree to include expression of wishes as to their specific licenses but we will not restrict access to data files based on those licenses. We require that all files hosted on our server are given an OSI or similarly open license, if the authors do not expressly provide one, the file(s) will be assumed to be under the most permissive CC0 copyright waiver."

should be changed to

"Publication irrevocably grants anyone the right to use the work under the license stated in the relevant dataset, or where no license is stated then under the PDDL dedication and license which releases all rights and allows use of the data without restriction. We agree to include expression of wishes as to their specific licenses but we will not restrict access to data files based on those licenses. We require that all files hosted on our server are given an [Open Source initiative (OSI)](https://opensource.org/licenses/) or similarly open license, if the authors do not expressly provide one, the file(s) will be assumed to be under the most permissive license appropriate e.g. [PDDL](https://opendatacommons.org/licenses/pddl/) or [CC0](https://creativecommons.org/publicdomain/zero/1.0/) waiver."

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

This Story is part of Epic #564

**Comment by only1chunts** [comment]
After further discussions with Scott & Laurie, we (GigaScience Press) dont want to move to using the pddl license(s) yet due to the lack of uptake in the community meaning people searching for CC0 datasets may miss our datasets if they are pddl instead of CC0, (even though the waiver has the same end-results!)
@luistoptal - apologies, but can this be undone in #1740 please!

**Comment by luistoptal** [comment]
@only1chunts yes, it would be enough to simply not merge #1740

**Comment by rija** [comment]
@only1chunts so can we close this issue then?
