### ISSUE TITLE
Exception thrown when typing "ElectroEncephaloGraphy(EEG)" in  search box

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1268]
## user story

As a website user
I want to search for composite keywords
So that I can find the most relevanty related dataset

## Acceptance criteria

Given I navigate to the search box of GigaDB website
When I search for "ElectroEncephaloGraphy(EEG)"
Then I should see any relevant datasets if any in the results page

## Addtional info

if works if you put a space before the first bracket.
Need to change the keywords filtering to allow  brackets as a separator

**Describe the bug**

A user search for "ElectroEncephaloGraphy(EEG)" in the search box, and the application threw a server error that was captured
by Tideways APM

Keyword with this pattern `/\w+\(\w+\)/` will trigger the error, but if there is a space before the bracket, eg. ElectroEncephaloGraphy (EEG), there would be then no error.

**To Reproduce**

maybe type the keyword above in the search box

**Expected behavior**
should not throw an exception

**Screenshots**

<img width="1209" alt="Screenshot 2023-05-02 at 6 24 50 PM" src="https://github.com/gigascience/gigadb-website/assets/11455/17f7c8e1-729a-4c57-b0e4-91fbd9907c35">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by only1chunts** [comment]
the search returns results when you use the word "ElectroEncephaloGraphy" so i guess we dont need this ticket anymore
