### ISSUE TITLE
[S1121] Create a new controller action for files-metadata-console to update urls

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1279]
New controller action for the console controller of files-metadata-console project, to allow batch update files urls excluding a given list of DOIs

Provisional API:
```
./yii update/urls --prefix=https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/live --separator=pub --exclude-dois=[1000,234324,43534534]
```

**Comment by only1chunts** [comment]
closing as it appears to be completed
