### ISSUE TITLE
Add awardee name field to funding info Admin pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#128]
We ask submitters for :
Funding body
Grant Award ID
Awardee name
Comments (including Program name)

The admin pages for creating/updating this info doesn't include the awardee name field. It needs to be added.
e.g. 
creating http://gigadb.org/datasetFunder/create
updating http://gigadb.org/datasetFunder/update/id/370

**Comment by jessesiu** [comment]
I already changed it when I fixed the issue #121
