### ISSUE TITLE
Giga Jobs page link from GigaDB should open new window/tab

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1283]
## User story

>As a website user
>I want the jobs link to open in a new tab
>So that I am not directed away from GigaDB.org

## Acceptance criteria

>Given I am on gigadb.org
>When I click the menu item "Jobs" under the "About" tab
>Then I am presented with the target URL page in a separate window (i.e. add element to hyperlink html code target=_blank)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
this will be fixed in PR #1742, so closing
