### ISSUE TITLE
update readme files with correct file location prefix

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1284]
## User story

>As a user  
>I want to see a link to the file manifest in the readme file
>So that I know how to construct each file location correctly 
>and work with the files offline

## Acceptance criteria

>Given dataset 102123 exists
>When a user downloads readme_102123.txt
>Then that files includes a link to an API endpoint allowing the files manifest to be generated

## Additional Info

The detail of files manifest creation is described in #679

We need also remove the following files section of the readme is it won't be needed:

> [File Location] https://ftp.cngb.org/pub/gigadb/pub/10.5524/102001_103000/102391/

To make this useful we need to change the file location to the correct Wasabi location prefix, AND add in the relative file locations if they are in subdirectories within a dataset.

**Implementation note **: 
 * Preserve comments from readme by downloading readme file, search/replace url prefix on content and write back the content to the file (and then rclone up it back to Wasabi)

The proper way of handling comments will be done ulteriorly with  #1265

Perhaps look into BioConductor for readme formats - do they recommend prefixes or full paths.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Rather listing files and their metadata in the readme, we are now thinking of making available to website users a files manifest. And the ticket #679 seems to be that.

**Comment by rija** [comment]
all tech work is done. Migration of readme file on beta is underway.
So closing this.
