### ISSUE TITLE
Bug with updating project links in admin pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1290]
## User story

>As a admin user 
>I want to be able to update a projects details without bugs
>So that I can keep the project details upto date

## Acceptance criteria

>Given a project exists in GigaDB 
>When I attempt to update the image location field e.g. http://gigadb.org/adminProject/update/id/38
>Then it works as expected
Currently it seems to be trying to create a new row in the project table instead of updating the existing one, see screenshot for the current behaviour:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/9f848cb3-a18e-40e8-ac28-95253f71bff8)

## Additional Info
related to #376 

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by pli888** [comment]
Closing this ticket as there is PR #1924 for this issue.
