### ISSUE TITLE
Add keywords to dataset display

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#13]
The dataset view in GigaDB website doesn't show the keywords. The keywords are stored in the database table DATASET_ATTRIBUTES table (NB - it looks like there has been some mistakes with keyword uploads in the production database as they are missing the "attribute_id", this will need to be fixed first @jessesiu )
For example dataset 100194 (dataset_id=252) should have 4 keywords displayed:
http://52.68.216.212/dataset/100194

**Comment by jessesiu** [comment]
Updated in dataset_attributes table

**Comment by pli888** [comment]
@jessesiu have the dataset_attributes tables in the sql files in the [sql folder](https://github.com/gigascience/gigadb-website/tree/develop/sql) been updated with the required changes? If not then we can still ask Yuzebo to do this.

**Comment by only1chunts** [comment]
completed ages ago, now closing ticket.
