### ISSUE TITLE
[S1284] make a backup of the all the 14 files that have comments in them

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1308]
Get a list of readme files with comments (see #1307) and download them into archive of site.

related to #1307 which is for curators to do

**Comment by only1chunts** [comment]
Those 15 Readme_files have been saved to this [Google directory](https://drive.google.com/drive/folders/1J9Uyt_s1--3ScgRGaJuYMNOLZAVYEV7_?usp=sharing)
In addition, I have taken a copy of all readme files that have a filename matching the regex '.*readme\_[0-9]*\.txt', currently they are stored in the user101 folder on the private FTP area in CNGB server.
