### ISSUE TITLE
split geographic location longitude and latitude (geo loc lat lon)

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#131]
## User story

>As a curator 
>I want to store latitude and longitute in separate attribute
>So that we align our input and data storage mechanism to common practices in the industry

## Acceptance criteria

>Given there are samples in GigaDB that has attribute "geographic location (latitude and longitude)" of ID 269 set
>When I run a migration script
>Then the value in that attribute is written to distinct latitude (ID 391) and longitute attributes (ID 392)

## Additional info

This is probably a task within a story about visualising samples on a map #718 .

currently many/most geographic locations are given as lat/lon in one value, we should split these to two individual fields:
geo-loc latitude
geo-loc longitude

Since ~ Jan 2021 curators have routinely been using separate lat and lon value terms, but old datasets have not been updated from a single combined lat/lon value term yet.

This change will likely also adversly effect the current Sample Map Browser #132

**Comment by jessesiu** [comment]
It will be change in the database table content

**Comment by only1chunts** [comment]
Jesse has done this in bulk on the historic samples with metadata provided by @only1chunts shown [here](https://docs.google.com/spreadsheets/d/1XXLAAcj1tLVHIy1J4DVwM67BRjRbs7YiQwrpO3OTqOQ/edit#gid=1205394331).
