### ISSUE TITLE
[S1284] Get list of readme files

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1312]
In files-metadata-console, add command to return list of read me file for dataset that have already readme file.

good candidate for batch mechanism (e.g: give me only 100 results, from this doi)

**Comment by pli888** [comment]
Closing this issue because we do not need to filter for datasets whose readme files need regenerating to contain Wasabi File URLs. We can go ahead and generate new readme files with Wasabi URLs for all datasets.
