### ISSUE TITLE
visualisation of samples on map

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#132]
after #131 has been done, we should have a page linked from the about page that shows all GigaDB samples on a map using the geo-loc attributes.

**Comment by only1chunts** [comment]
NB - this should be done with non-google maps! i.e. something that will work in China as well as rest of world.

**Comment by ScottBGI** [comment]
Use OpenStreetMap? https://www.openstreetmap.org

**Comment by only1chunts** [comment]
the sample browser mad should be a new page in GigaDB with the URL 
http://gigadb.org/site/mapbrowse
there should be a link to that page in the header section of every page (see note in attached image)
In the future we might like to link this view to the search function and have facets, but not essential now unless its already included in whatever tool/app is used.
![map-browse](https://user-images.githubusercontent.com/6037145/32476040-e00d29d4-c36c-11e7-948d-d7190013728e.jpg)

**Comment by only1chunts** [comment]
4 Jan. by email I wrote "The new code appears to work fine, there is 1 little point that would be nice if it could be updated; When a flag has multiple samples at that point the list disappears off the bottom of the page with no scroll bar or method of seeing those sample names."
@rob replied to say he would fix that bug.

**Comment by bobbledavidson** [comment]
Hi Chris - apologies for slow running on this - can you confirm that the scroll bar is the only outstanding bug for this issue (and that there are none for 130 which has been closed)?

**Comment by only1chunts** [comment]
@bobbledavidson yes thats it, thanks.
