### ISSUE TITLE
Fix Wave audited accessibility errors on the Help page E1304

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1330]
## User story

>As a website user
>I want to be able to access the content on the help page
>So that I can find the information I am looking for

## Acceptance criteria

>Given I have visual impairment
>When I navigate to "/site/help"
>Then I can access the content

## Additional Info

This is about fixing the Wave error report on that page.

* https://wave.webaim.org/
* This story is part of Epic #1304

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by luistoptal** [comment]
Hi @rija , what does E1304 refer to?

**Comment by luistoptal** [comment]
I am making small adjustments to this page to optimize for accessibility. To be strict about the accessible aspect of the Excel files lnked from this page, we would have to add tables with the same content directly to the html, @rija @only1chunts do we want to do that? I see the Excel file is really complex and making this accessible would likely grant a dedicated page with an exhaustive description that shows examples of all tables. To make this neatly work perhaps we could have a group of forms in the site that replaces or is an alternative to the excel (is that maybe the submission wizard?)

I have also noticed that some of the links to files present in the page no longer work, for example

http://gigadb.org/files/GigaDBUploadForm-example1.xls
https://gigadb.org/files/GigaDBUploadForm-example2.xls
https://schema.datacite.org/meta/kernel-2.2/doc/DataCite-MetadataKernel_v2.2.pdf

Maybe these files have been deleted from the server

**Comment by only1chunts** [comment]
Those Excel files will be removed when we eventually get the submission
wizard up and running.

**Comment by luistoptal** [comment]
@only1chunts thanks, then I think this issue can be closed
