### ISSUE TITLE
Implement and catalogue consistent styling across admin and public pages

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1334]
Our website at [beta.gigadb.org](https://beta.gigadb.org)  (mostly HTML5, LESS/CSS, Bootstrap, jQuery) has an admin section with legacy styling and a public section with newer updated styling. 
The work to be done consists of:
 * [x] #1356
 * [x] #1357
 * [x] #1358
 * [x] #1359

Useful resources:

 * How we organise our stylesheets: http://smacss.com
 * The template used for our style guide: http://bjankord.github.io/Style-Guide-Boilerplate/demo.html
* The Bootstrap theme that was used on the public site: https://htmlstream.com/unify/documentation/getting-started.html

**Comment by only1chunts** [comment]
The main gigadb.org website was re-designed in 2018/19 using the unify-v1.6 template by [htmlstream](https://htmlstream.com/). The work was done by CNGB staff in Wuhan collaborating with Jesse.
If it helps, I have a copy of the Unify-v1.6 template package used in that redesign, @GigaScience email addresses can access it here:
https://drive.google.com/file/d/1g2tpT0M_4gtFrq-0XJTZfH2cJ5g9Hc22/view?usp=sharing

**Comment by rija** [comment]
This work has been implemented, and the corresponding PRs are under review, so closing
