### ISSUE TITLE
update example database values

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#134]
To allow web-code to not break when certain features are used we need to include the external link types in the test database that is stored in GitHub needs to include those types. 
Additional Information
Genome Browser
protocols.io
JBrowse
3D Model

**Comment by only1chunts** [comment]
@rija can we close this ticket? I think the CD/CI pipeline already handles the test data requirements doesn't it?

**Comment by pli888** [comment]
@only1chunts I think you can close this issue. The `prod_like` data directory contains those [external link types](https://github.com/gigascience/gigadb-website/blob/develop/data/prod_like/external_link_type.csv).
