### ISSUE TITLE
iFrame 3D Model Thumbnail

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#135]
We would like to add a thumbnail image by which a user can access 3D models.

**Comment by only1chunts** [comment]
e.g. http://dx.doi.org/10.5524/100364 (when its published) has 6 individual 3D models, currently the only means to show them is with 1x [+] button. we would like 6 custom thumbnails, 1 for each, that the user could click to expand each individually.

**Comment by only1chunts** [comment]
this is complete in production server so I am closing this ticket.
