### ISSUE TITLE
Update existing  UI patterns library

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1359]
We have a style guide available at `/style-guide/` of the GigaDB website local deployment.
In the repository it is located at `style-guide/`

 * [x] Check all the admin patterns are present in the consistent style of the web site
 * [x] Fix cosmetic bug

**Comment by luistoptal** [comment]
@rija I've seen this in the style guide. I did not see this layout anywhere in the live site. Although the layouts (e.g. new_main) seem to contain something that looks similar to this, code-wise, it is also never visible in the page

![image](https://github.com/gigascience/gigadb-website/assets/143437854/e8889de5-a7b9-4547-94e9-b754408ba6eb)

I'm wondering if there's any consideration regarding this. Obviously it doesn't look ok in the sg but if it's never displayed perhaps it makes sense to remove it from the sg to avoid any potential confusion (?)

**Comment by rija** [comment]
Hi @luistoptal,

Sorry for late reply. 
Yes, it can be removed from style guide. 
As affiliate login as we call it is has been removed as a feature.
We will bring it back in the future, but the tech is going to be complete different (use of dedicated auth server with delegation for affiliate login)  and so will the user journey (more aligned with today's practice for SSO and delegated authentication)

**Comment by rija** [comment]
work done
