### ISSUE TITLE
Sample updating page species ID

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#136]
In the admin pages the sample update form automatically prefills with species box with relevant species Row ID rather than the taxonomy ID, but when you come to submit the form the check expects the value to be the taxonID not the row ID, so it throws an error message.
Please update the page to prefill with correct value.
example page:
http://gigadb.org/adminSample/update/id/604
gets pre-filled with Species ID = "38", but it should be "13146:Melopsittacus undulatus,Melopsittacus undulatus"

**Comment by jessesiu** [comment]
@only1chunts This issue already fixed, Please check it on the production server.

**Comment by only1chunts** [comment]
thanks, it appears to work on the production site so I assume the code you have put into github is also fine!
