### ISSUE TITLE
A11y - Skip to content link

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1362]
## User story

Tab navigating any page, first focusable element should be a "skip to main" link

Reasoning behind is that tabbing through header elements in each page is time consuming

## Additional Info

The page layout is probably the right place to implement this

https://webaim.org/techniques/skipnav/

## Requirements

- [x] https://github.com/gigascience/gigadb-website/issues/1361

**Comment by luistoptal** [comment]
Waiting to merge #1403

**Comment by only1chunts** [comment]
@luistoptal can this issue be closed?
