### ISSUE TITLE
a11y - Article detail page - essential fixes

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1371]
## User story

- Missing h1 and h2
- Table headers low contrast
- Table settings > Items per page: label is not associated to select input
- Table settings: checkboxes don't have associated label

https://beta.gigadb.org/dataset/100016

## Acceptance criteria

- [x] The page respects the heading hyerarchy and it has at least one h1 heading
- [x] Table headers have enough contrast between text and background
- [x] Associate label to select input
- [x] Associate label to checkbox inputs and wrap them within a fieldset

## Resources

https://www.w3.org/WAI/tutorials/forms/grouping/#checkboxes

**Comment by luistoptal** [comment]
Working branch: https://github.com/luistoptal/gigadb-website/tree/new-feature/1371/article-detail-page-essential-a11y-fixes

**Comment by only1chunts** [comment]
@luistoptal can this ticket be closed? (all tasks are ticked already)
