### ISSUE TITLE
A11y - Guide page

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1379]
## User story

- Heading hierarchy: lack of heading hyearchy (only h4)
- contrast issues: links, breadcrumbs, muted tab labels
- dataset checklist tab has invisible focus state
- Complex image diagram should have accessible text description, e.g. https://www.w3.org/WAI/tutorials/images/complex/
- Table abbreviations (y/n) and legend (Recommended, optional, mandatory...) these do not help screen readers, for screen readers it's better to not use these at all and add aria-labels explicitly to each table cell
- Crosscheck that table pattern is followed in tables https://www.w3.org/WAI/ARIA/apg/patterns/table/
- Link at the bottom could be a html list
- Undue `<section>` use, e.g. page title is its own section, tabs are its own section

https://beta.gigadb.org/site/guide

## Acceptance criteria

- [x] Fix heading hierarchy
- [x] Fix contrast issues
- [x] Visible focus state for checklist tab
- [x] Complex image has description
- [x] Accessible tables
- [x] List of links
- [x] Fix `<section>` usage

**Comment by only1chunts** [comment]
@luistoptal , all items are ticked, so can this issue be closed?

**Comment by luistoptal** [comment]
@only1chunts any issues or any other pending task or PR created by me from 2023 can be closed as all the necessary work was merged already
