### ISSUE TITLE
create privacy policy page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#139]
we require a statement of our policy on what we do/do not use users personal details for.
this should be a separate page with URL
http://gigadb.org/site/privacy
the page can be linked within the terms and conditions page ( http://gigadb.org/site/term ) perhap as a tab like we do for the about/faq/board (http://gigadb.org/site/about)
I will add some text for the page here when I've worked out what it should say!

**Comment by only1chunts** [comment]
the text for the pages can be found in [this G-doc](https://docs.google.com/document/d/1qa-S5g2e1quSbMZ4mnIpTVTN8sw0vrO8S7sjc3gMdrc/edit?ts=5a4c80a7#)
The section called "Terms of use" can replace the current  http://gigadb.org/site/term page, and the section called "Privacy" can be used to create the page http://gigadb.org/site/privacy

**Comment by pli888** [comment]
Done by @jessesiu in https://github.com/gigascience/gigadb-website/pull/148/commits/e4c64e52fefb9c1889fb4593c916b7328fb0da76.

**Comment by jessesiu** [comment]
@only1chunts Its in the develop branch

**Comment by only1chunts** [comment]
http://gigadb.org/site/privacy
http://gigadb.org/site/collection
http://gigadb.org/site/personal
