### ISSUE TITLE
Replace Google Analytics with something more suitable

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1406]
## User story

>As a curator 
>I want to capture and store the usage metrics of gigadb-website
>So that I can analyse how our users use the web site

## Acceptance criteria

>Given a user is visiting gigadb.org  
>When they navigate the website  
>Then their journey is captured and recorded by an analytics tool

>Given user journeys on gigadb.org have been captured and stored  
>When I log in to the analytics tool  
>Then I can see the usage data of user journeys

>Given usage metrics for gigadb.org is currently stored in Google Analytics
>When the new analytics tool has been installed and setup
>Then the historical usage metrics is stored in the new tool

## Additional Info
related to #942 and Epic #137

Google analytics is not capturing metrics since July 2023.
The data currently stored in Google Analytics will be raised by July 2024.

### Implementation details:

Use Matamo.

* [ ] Create Ansible playbook `analytics_playbook.yml` to install Docker and rclone on the monitoring server
* [ ] Use official Docker compose from Matomo: https://github.com/matomo-org/docker/blob/master/.examples/nginx/docker-compose.yml
* [ ] Add DNS A record  so `analytics.gigadb.host` points to this deployment's EIPs
* [ ] Create a system user for Matomo
* [ ] Ensure AWS credentials for an appropriate role exists on the server
* [ ] Setup automation of backup to S3: https://matomo.org/faq/how-to/how-do-i-backup-and-restore-the-matomo-data/
* [ ] Setup TLS termination for the web server: https://doc.traefik.io/traefik/

* [ ] Replace the analytics Javascript code in gigadb-website: https://developer.matomo.org/guides/tracking-javascript-guide
* [ ] Perform import of Google Analytics data: https://matomo.org/faq/general/set-up-google-analytics-import/

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
closing as we have Matomo cloud account setup that's recording web traffic. If more work needed we will create more specific issues
