### ISSUE TITLE
http://gigadb.org/site/about

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#142]
Please can you remove the following line from the GigaDB About page: http://gigadb.org/site/about

"To submit data to GigaDB, visit GigaDB.org or contact us at: database@gigasciencejournal.com."

**Comment by jessesiu** [comment]
Done

**Comment by pli888** [comment]
Fixed in https://github.com/gigascience/gigadb-website/pull/148/commits/c9d461ac102270cbf92a1ac6fb7910987cd84a6c by @jessesiu
