### ISSUE TITLE
rename file tye to data type

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#143]
The term file-type has been used inconsistently in the past, to try to make more explicit what it is we will rename the column in the submission spreadsheet as  data-type. This will also need to be reflected in the Dataset pages file table, where the column for "File Type" needs to be renamed "Data Type"
Ideally the backend database schema should also be renamed to data_type, but if that will break more things then it can remain as file_type?!

**Comment by only1chunts** [comment]
ensure all locations on website have the "File Type" changed to "Data type":
- main admin page (/site/admin)
- the data type / file type page (/adminFileType/admin)
- Manage Files page (/adminFile/admin )
- the "Display settings" pop-up for file table settings on any dataset page

**Comment by jessesiu** [comment]
@only1chunts  this issue is fixed in the GitHub and production server.

**Comment by only1chunts** [comment]
thanks
