### ISSUE TITLE
4d. tideways deployment on staging should be automated

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1444]
Why?
* In normal circumstances:
Staging deployment is automated. If tideways is not automated we forget to do it and it breaks the flow to have to remember it since stage deployment is supposed to fully automated.
* When there are environment issues occurring with staging after initial successful build:
If tideways hasn't been deployed to staging, and we need to rebuild the live environment, we cannot enable Tideways on live as the job has a dependency on Tideways having been successfully deployed on staging

**Comment by kencho51** [comment]
Closed as implemented in PR #1514
