### ISSUE TITLE
mockup token generation issue

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1446]
**Describe the bug**
Creation of a mockup page (in beta) now requires a reviewer's email address, which it should not.

**To Reproduce**
1. Upload a new dataset using the upload scripts
2. goto beta.gigadb.org admin pages and view the newly uploaded dataset
3. Scroll down to and click 'Generate mockup for reviewers' button
4. See the popup box requesting reviewer email, and length of time for mockup to be valid

**Expected behavior**
When the button is clicked the mockup page is presented with the token URL that has been created.
Also, given that we currently dont have any expiry date on mockup tokens we can probably live with just a standard 6 month expiry, so no need to ask for the length

So the popup is not required at all.

Question - what happens when the token expires? 

**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/6037145/6aada9af-a5c8-4ff3-b07d-802e53940382)
![image](https://github.com/gigascience/gigadb-website/assets/6037145/8a2d72e1-7d28-4d69-928e-44e7e05b15e6)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I think its probably related to [#1026](https://github.com/gigascience/gigadb-website/pull/1026) (in sprint 9)

It is the generation of the time limited mockup tokens for pre-publication datasets, for some reason it requires the inclusion of a reviewers email address in order to create the mockup token URL, this may have been discussed as an optional extra but I dont recall the discussions, but while we will send the mockup URL to peer-reviewers that will be done outside of the GigaDB system (the editorial team do that via email) so we dont need to include reviewers emails here.

**Comment by rija** [comment]
Not issue as the experience happened when I was busy rebuilding the beta environment. Reopen if it's really an issue
