### ISSUE TITLE
Link to GigaBlog is dead

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#145]
The link to GigaBlog (http://blogs.biomedcentral.com/blogs/gigablog/) from the GigaDB homepage (http://gigadb.org/) is dead. I think it should go to http://gigasciencejournal.com/blog/

**Comment by only1chunts** [comment]
@jessesiu the gigablog link is in the bottom right-hand corner of the footer on every GigaDB page! it still points to the BMC blog url which is no-longer active.

**Comment by pli888** [comment]
Fixed in https://github.com/gigascience/gigadb-website/pull/148/commits/2b59660a0366381122ced2b02f32ccdda5ce2352 by @jessesiu.
