### ISSUE TITLE
check whats indexed for search

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#149]
@jessesiu it appears that neither the dataset type nor keywords are being retrieved when you do a search on the GigaDB webpages.
The perfect example of this is @ChrisArmit 's dataset 100365, which is of type "imaging" and has the keyword "imaging" but doesn't get picked up when you search for the word "imaging" because that word isn't in the description. If you search for "image" it does get found.
Please check which fields are indexed for search, and ensure both dataset type and keywords are included.

**Comment by only1chunts** [comment]
@jessesiu wrote "I add the dataset_type value into the search function, It should be OK now. When search genomic it will return 291 datasets, search for "genomic" then filtered on dataset type = genomic will return 228 datasets. "

**Comment by only1chunts** [comment]
Did you also check if the keywords were indexed?

**Comment by ChrisArmit** [comment]
Hi Chris,

Good point. No, the keywords are not indexed.

To test this I run a query for [section atlas].



This does not return any GigaDB entries.



It should work as the GigaDB entry I am looking for has the following
keywords ascribed to it.



[Embryo; Mouse; Section; Atlas; Anatomy; Imaging]



Cheers

Chris A

**Comment by jessesiu** [comment]
@only1chunts @ChrisArmit  It can search the keyword and dataset_type on the production site.

**Comment by only1chunts** [comment]
the search has been updated and this is no longer and issue, so closing ticket.
