### ISSUE TITLE
improve the "dataset you might like" algorithm

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#15]
Currently the "datasets you might like" that are shown to users is based solely on the "dataset type" e.g. genomic, transcriptomic etc...
This could be improved in a number of ways, the simplest could be to show datasets that match keywords and/or authors and/or dataset-type. rank them in some way so as to show most relevant first.

More complex could include browser history, and/or user specified preferences, but these would require more thought.

**Comment by ScottBGI** [comment]
ANDS have done something similar to this, see Andrew Treolar's talk at the DataCite meeting in 2012: https://www.slideshare.net/atreloar/seeking-serendipity

**Comment by ScottBGI** [comment]
Think the code is going to be here somewhere: https://github.com/au-research/ANDS-ResearchData-Registry

**Comment by only1chunts** [comment]
Thanks Scott, the info on Slide 11 (copied below) is very useful for thinking of the sorts of things that need to be included in this:
- Same or Similar spatials coverage
- Same or similar teporal coverage
- If related info contains publications and informatio on the authors of the publications:collections linked to co-authors
- Shared keywords and descriptions

**Comment by only1chunts** [comment]
we no longer have the "datasets you might like" section on the dataset pages so this ticket is no longer required.
