### ISSUE TITLE
dataset admin page save button bug

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1529]
**Describe the bug**
Clicking save on the dataset admin page directs you to the wrong page

**To Reproduce**
1. create a dataset e.g. https://beta.gigadb.org/adminDataset/update/id/2713
2. ensure the dataset already has a private URL token (if not click the create private url button then go back to dataset page)
3. Click on 'Save'
4. See error:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/a6473d65-eae3-4a5c-8a68-f688c2688e85)

**Expected behavior**
The save button should just save the changes and reload the same data-admin page 

**Additional context**

**Comment by kencho51** [comment]
Close as fix in PR #1578
