### ISSUE TITLE
thumbnail image tag length

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#153]
in the dataset admin pages e.g. http://gigadb.org/dataset/update/id/392 the field for "Image Tag" has a validation on it, which throws an error message when the tag length is over 50 char. This is too short, please increase this to 120char.

**Comment by jessesiu** [comment]
@only1chunts  changed in the production server

**Comment by ChrisArmit** [comment]
![Screen Shot 2019-11-04 at 17 12 45](https://user-images.githubusercontent.com/33310581/68141104-d3460e00-ff24-11e9-8b10-92801065734d.png)
