### ISSUE TITLE
dataset admin page Cancel/Save button behaviour update

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1532]
This ticket maybe redundant as its the same as part of ticket #1533

## User story

>As a curator
>I want the dataset-admin form saving and canceling workflows to behave efficiently
>So that I can use it appropriately for my workflow

## Acceptance criteria

> Given I am on a dataset-admin form for a dataset that is not public
>When I click the "Save Changes" button
>Then any changes I have made in the page are saved to the database 
>AND I am returned to the form
>AND the message "Changes have saved." is shown to the user

> Given I am on a dataset-admin form for a dataset that is public
>When I click the "Save Changes" button
>Then any changes I have made in the page are saved to the database 
>AND I am redirected to the public dataset page

> Given I am on a dataset-admin form for a dataset that is not public
>When I click the "Cancel Changes" button
>Then any changes I have made in the page are not saved to the database 
>AND I am redirected to the admin page listing all datasets

> Given I am on a dataset-admin form for a dataset that is public
>When I click the "Cancel Changes" button
>Then any changes I have made in the page are not saved to the database 
>AND I am redirected to the admin page listing all datasets

## Additional Info

 e.g. https://beta.gigadb.org/adminDataset/update/id/2716
spin-off ticket from #1529

This is slightly different to the current (CNGB) live version of the website, at present the save action redirects to the token URL view of the dataset, that action should only happen if I click the "open private URL" or "Create/Reset private URL" buttons

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by kencho51** [comment]
Hi @only1chunts,

For the first acceptance criteria:
```
AND the message "Changes have saved." is shown to the user
```

How do you want to implement the `Changes have saved` ? A pop up box?
My idea is when you made the changes and saved, the same data-admin page would be reloaded, any updates could be seen by the user already.

**Comment by only1chunts** [comment]
a pop-up would be great, especially if its something that doesn't take focus away from the page and just disappears by itself after a few seconds, i.e. no need to click anything to get rid of the popped up window.
The page reload is OK, but only if its required from a technical aspect, i.e. from a curators point of view it doesn't matter if the page reloads or not as long as the changes that have been made are saved to the database when we click the save button(s).

**Comment by kencho51** [comment]
Close as the acceptance criteria have been tested and are passing in PR #1578.
No addtional implementation, as the existing `AdminDatasetForm` behaves as described except the redirect url for the private dataset, a functional test `AdminDatasetFormCest.php` was created to further confirm it.
