### ISSUE TITLE
Fix outstanding issues in map browse page

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1544]
## User story

Fix issues in page http://gigadb.gigasciencejournal.com:9170/site/mapbrowse

* Tabbing shows some broken unstyled controls
* there is an img with missing alt
* there is no h1
* the dots in the map are not focusable
* Consider increasing map height

**Comment by only1chunts** [comment]
NB ticket #831 needs to be done before the map browser is of much use
