### ISSUE TITLE
Fix FAQ page tabpanel misuse

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1556]
## User story

the FAQ page http://gigadb.gigasciencejournal.com:9170/site/faq uses a tablist with tabpanels as children. This does not follow spec (https://www.w3.org/WAI/ARIA/apg/patterns/tabs/), but also, an accordion pattern is more suitable for this page (https://www.w3.org/WAI/ARIA/apg/patterns/accordion/). Update the page to use accordion pattern

**Comment by only1chunts** [comment]
I believe there are potential fixes for this issue coming with the CMS work (completion date unknown)
