### ISSUE TITLE
Focus loss on sorting in edit dataset log form

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1572]
## User story

Page http://gigadb.gigasciencejournal.com:9170/adminDataset/update/id/8/CurationLog_sort/created_by#maincontent has a table, when head is clicked to sort data there is a page refresh. This leads to some problems:
* Focus is lost
* Scroll position goes to top

Maintain focus on clicked element, and prevent scrolling or return to same scroll level

![image](https://github.com/gigascience/gigadb-website/assets/143437854/4bb26923-f9de-4a5d-971e-5d37cbb394a1)

**Comment by luistoptal** [comment]
After a few hours I didn't make much progress solving this

All I found out is that commenting the function `afterAjaxUpdate` in `protected/js/custom-grid-view.js` restores default sorting behavior (i.e. routing), but as soon as it is added, even if it's empty:

- A request to the server is still taking place
- No routing (the url pathname no longer changes)
- Table data does not sort

Based on this, the `afterAjaxUpdate` function, which I would expect runs after the routing has taken place (i.e. after Ajax response), seems to interfere with the update itself

Despite all this, sorting works in other tables that use this script (even if routing does not take place), but not on the table in the http://gigadb.gigasciencejournal.com:9170/adminDataset/update/id/8 page

**Comment by luistoptal** [comment]
@rija @only1chunts How useful is the sorting in this table, for the users? I noticed it doesn't work, not even in staging, (only for this specific table) and I'm wondering just how many attributes we can expect to have here and whether it is useful to be able to sort them, or would it be easier to simply remove the sorting from this one?

http://gigadb.gigasciencejournal.com:9170/adminDataset/update/id/5/CurationLog

![image](https://github.com/gigascience/gigadb-website/assets/143437854/51efbb7b-13fb-48e7-8e94-285236df73cc)

**Comment by only1chunts** [comment]
The curation log need only ever be presented in date order, no need for any
alternative sorting, thanks.
