### ISSUE TITLE
Date dropdowns are not keyboard focusable

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1574]
## User story

the site uses date dropdowns for inputs which cannot be used with keyboard, e.g. in page http://gigadb.gigasciencejournal.com:9170/adminDataset/create

![image](https://github.com/gigascience/gigadb-website/assets/143437854/f5b758fb-16de-432b-b487-d12383f73bd8)

A straightfoward solution would be to add a description to such inputs indicating the format (YYYY-MM-DD)

A more complex solution would be to make the date dropdwon keyboard interactive

**Comment by rija** [comment]
Guess this is done
