### ISSUE TITLE
dataset admin page layout issues

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1584]
## User story

>As a curator  
>I want to reduce the volume of dead/white space on the dataset admin page
>So that I dont have to scroll so much to see everything

## Acceptance criteria

>Given I am looking at a dataset admin page e.g. https://beta.gigadb.org/adminDataset/update/id/2731
>When I look at the items on it
>Then I do not see acres of white space between every item

>Given I am looking at a dataset admin page e.g. https://beta.gigadb.org/adminDataset/update/id/2731
>When I look at the items on it
>Then I see the item name clearly aligned and near the relevant value entry field

For preference:
>Given I am looking at a dataset admin page e.g. https://beta.gigadb.org/adminDataset/update/id/2731
>When I look at the dataset types
>Then I see the tickbox followed directly by the type name (see example in second screenshot below)

## Additional Info
The screenshot below highlights some of the dead space that should be removed:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/ad386e69-01fe-4b1b-b561-8122f23c0fd5)

it should look more like this:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/b433ce40-7fb2-4ab5-ab3e-ec3ccd56962a)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Hi @luistoptal 

I wonder if this might already be fixed in one of your PRs.
could you confirm for us?

**Comment by luistoptal** [comment]
@rija not really, this is how it looks like ~~now~~ in my integration branch, with *all* the drafted PRs applied:

![image](https://github.com/gigascience/gigadb-website/assets/143437854/77034939-34f8-409e-bb67-2e598759196b)

**Comment by only1chunts** [comment]
thanks @luistoptal that looks much better than the current beta server.
my personal preference would be for less dead space between the lines, but maybe thats just me.
I'm hoping its just the screenshot, but the text looks quite pale grey instead of black, so as long as it is infact black when its live it will be OK.

**Comment by luistoptal** [comment]
@only1chunts these are the actual text / bg colors: https://colourcontrast.cc/f8f8f8/656565
they have enough contrast but it can be made black / darker gray, so it can be added to the ticket. When I see the two screen shots side it side it also seems to be that darker and bold labels are better for this form

![image](https://github.com/gigascience/gigadb-website/assets/143437854/f330f22e-b7d4-4c59-b843-d92d0c5ff09a)

As for the empty space here I reduced all spacings by about half

![image](https://github.com/gigascience/gigadb-website/assets/143437854/bb6a3c5a-b17b-4458-9e85-48162e47d430)

Do these look better?

**Comment by luistoptal** [comment]
Also I don't like that the labels wrap to the next line, so I could change that too, however if the label is longer than the existing ones there's eventually no way around wrapping it

**Comment by only1chunts** [comment]
Cool, thanks for the quick response! I like those changes. I'm not worried about the label wrap, its only one field that seems to be affected, and actually for those image fields we could remove the word "image" from the label names as they are all under a subsection called Image metafields anyway!
under the image metafields, the next section could have the heading "dataset metafields" if you wanted to give it a header.
now I can see the lower part of the screenshot, can those title and description value fields be made wider to utilise the screen realestate better? maybe align the field names with those on the left and use the rest of the full screen width for the values? (see the current live screenshot above)

**Comment by tuli** [comment]
It's a great improvement. I agree with @only1chunts' comments.

**Comment by luistoptal** [comment]
@only1chunts does the "Mint DOI" button make sense in the update page? Can it be conditionally displayed only in the create page? Or should it be always present?

**Comment by only1chunts** [comment]
It definitely needs to be available in the update page as thats when it is used most often, but I think its best to always be present.

**Comment by rija** [comment]
this is done and visible on https://staging.gigadb.org
