### ISSUE TITLE
Beta: Files table, Size unit

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1593]
**Describe the bug**
Units of file sizes are now shown as MiB and GiB in beta. Should be MB and GB.

**To Reproduce**
1. Go to https://beta.gigadb.org/dataset/102491/token/I4_bw3Gm4o0ipjlN
2. Scroll to bottom of page to see Files tab
3. Column 4 is Size.

**Expected behavior**
Units should be MB and GB 

**Screenshots**
![Screenshot 2023-12-19 at 11 09 13](https://github.com/gigascience/gigadb-website/assets/1359170/8d179074-8559-4742-a166-d35730e96633)

**Desktop (please complete the following information):**
 - OS: Ventura 13.4
 - Browser Chrome 
 - Version 118.0.5993.117 (

**Comment by rija** [comment]
Hi @tuli 

According to clause 4 of IEC 80000, it's correct to use for binary prefix in information storage the ones currently being used on the file table.

From https://en.wikipedia.org/wiki/ISO/IEC_80000 :
>The standard includes all [SI prefixes](https://en.wikipedia.org/wiki/SI_prefix) as well as the [binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) kibi-, mebi-, gibi-, etc., originally introduced by the [International Electrotechnical Commission](https://en.wikipedia.org/wiki/IEC_60027-2) to standardise binary multiples of byte such as [mebibyte](https://en.wikipedia.org/wiki/Mebibyte) (MiB), for 10242 bytes, to distinguish them from their decimal counterparts such as [megabyte](https://en.wikipedia.org/wiki/Megabyte) (MB), for precisely one million (10002) bytes. In the standard, the application of the binary prefixes is not limited to units of information storage. For example, a frequency ten [octaves](https://en.wikipedia.org/wiki/Octave_(electronics)) above one hertz, i.e., 210 Hz (1024 Hz), is one kibihertz (1 KiHz).[[40]](https://en.wikipedia.org/wiki/IEC_80000-13#cite_note-40) These [binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) were standardized first in a 1999 addendum to [IEC 60027-2](https://en.wikipedia.org/wiki/IEC_60027). The harmonized IEC 80000-13:2008 standard cancels and replaces subclauses 3.8 and 3.9 of IEC 60027-2:2005, which had defined the prefixes for binary multiples. The only significant change in IEC 80000-13 is the addition of explicit definitions for some quantitie

**Comment by only1chunts** [comment]
@rija I have no idea what any of that iec 80000 actually means?! The norm
for megabytes and gigabytes are MB and GB so let's use them since no one
knows what MiB means.

**Comment by rija** [comment]
@tuli @only1chunts fair enough

@pli888 @kencho51 ,

The code change is [one line change](https://github.com/gigascience/gigadb-website/blob/a0a544c4735a8a0b8d5ab9239a9bbdc92054fbe8/protected/models/File.php#L255), plus rewriting the unit tests. 
See https://packagist.org/packages/gabrielelana/byte-units

**Comment by rija** [comment]
@tuli @only1chunts fair enough

@pli888 @kencho51 

the change is [one line change](https://github.com/gigascience/gigadb-website/blob/a0a544c4735a8a0b8d5ab9239a9bbdc92054fbe8/protected/models/File.php#L255), plus rewriting the unit tests

See https://packagist.org/packages/gabrielelana/byte-units

**Comment by kencho51** [comment]
Close as fix in PR #1650
