### ISSUE TITLE
dataset 100894 doesnt load

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1594]
dataset 100894 has ~2900 samples, the dataset page does not load in the Beta.gigadb.org version.

**Comment by pli888** [comment]
I just checked https://beta.gigadb.org/dataset/100894 from a random location in HK and it loads fine in my browser. I'm wondering if you accessed the page first which is the reason for the long load time but now it's cached so there is no long load time now.

**Comment by only1chunts** [comment]
it does indeed load within 5 seconds for me too now, both on my phone while on the train and now that I'm home in UK. So either it was something to do with the airport lounge internet and my VPN (although other pages on beta were loading fine), or it was to do with the caching as you suggested. Either way, its a non-issue now, so I'll close the ticket.
