### ISSUE TITLE
Remove affiliate login buttons from style guide login panel

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1599]
## User story

In reference to https://github.com/gigascience/gigadb-website/issues/1359#issuecomment-1865765202

Get rid of affiliate login buttons in style guide

## Acceptance criteria

Login panels in style guide do not have affiliate buttons and look like login panel in GigaDB site (http://gigadb.gigasciencejournal.com:9170/site/login)

![image](https://github.com/gigascience/gigadb-website/assets/143437854/79202031-15e9-47db-a05c-8c5ba885fa4b)

**Comment by rija** [comment]
Guess this is done
