### ISSUE TITLE
URL link broken

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#160]
@jessesiu 
on the page http://gigadb.org/site/advisory the link from the text "GitHub page) " is broken it points to http://gigadb.org/site/https//github.com/gigascience, it should point to https//github.com/gigascience . Please fix it in GitHub version and production version.

**Comment by pli888** [comment]
@only1chunts The [advisory board page](http://gigadb.org/site/advisory) has a `GitHub page` link that points to https://github.com/gigascience/gigadb-website. Can you confirm that you want it to point to https://github.com/gigascience instead please?

**Comment by kencho51** [comment]
@only1chunts The link for Editorial Board in the [advisory board page](http://gigadb.org/site/advisory) points to [here](http://www.gigasciencejournal.com/about/edboard) which is `Not Found`. It is suggested to create a new issue for that.

**Comment by only1chunts** [comment]
@kencho51, thanks for spotting that, it appears OUP have updated their website, the ed-board link should now point to https://academic.oup.com/gigascience/pages/Editorial_Board
@pli888 , looking at the context of the github link on the advisory board page it seems rather odd! So I have reworded that entire section below, please check carefully my html encoding as I had to add something to indicate where the italics and links go!

In order to aid GigaDB in following best practices, advancing community needs, and taking advantage of novel ideas/tools that can promote innovation as the database evolves, we not only take advantage of the excellent <a href="https://academic.oup.com/gigascience/pages/Editorial_Board" target=blank>Editorial Board</a> that advises <a href="http://www.gigasciencejournal.com/" target=blank><i>GigaScience</i></a> journal ,we also have the following more focused GigaDB Advisory panel. 

We strongly encourage community feedback and involvement, so please feel free to contact any of our Editorial or Advisory board members, or any of the <a href="http://gigadb.org/site/team"><i>GigaScience</i> team</a>, or use the <a href="http://gigadb.org/site/contact">contact us</a> form. 

To further enable transparency the GigaDB website is under continuous open developed in <a href="https://github.com/gigascience/gigadb-website/" target=blank>GitHub</a>, and users may comment and contribute any questions, problems or ideas for GigaDB through the website <a href="https://github.com/gigascience/gigadb-website/" target=blank>issue ticketing</a> system.

**Comment by pli888** [comment]
> In order to aid GigaDB in following best practices, advancing community needs, and taking advantage of novel ideas/tools that can promote innovation as the database evolves, we not only take advantage of the excellent Editorial Board that advises GigaScience journal ,we also have the following more focused GigaDB Advisory panel.

Maybe it would be better to rephrase the last sentence where you say that we take advantage of the Editorial Board. Sounds a bit like we are unfairly imposing ourselves on them.

> We strongly encourage community feedback and involvement, so please feel free to contact any of our Editorial or Advisory board members, or any of the GigaScience team, or use the contact us form.

I'm not sure we should tell the community to contact the Editorial or Advisory board if someone has feedback or an issue for us. Someone like Carole who is on the Editorial Board is super busy and she would just forward the email to us anyway. I think people on these boards are really for us to ask for feedback about a particular aspect.

**Comment by only1chunts** [comment]
point(s) taken!
change "take advantage" -> "leverage"
remove "of our Editorial or Advisory board members, or any"

text now looks like:

In order to aid GigaDB in following best practices, advancing community needs, and taking advantage of novel ideas/tools that can promote innovation as the database evolves, we not only leverage the excellent <a href="https://academic.oup.com/gigascience/pages/Editorial_Board" target=blank>Editorial Board</a> that advises <a href="http://www.gigasciencejournal.com/" target=blank><i>GigaScience</i></a> journal ,we also have the following more focused GigaDB Advisory panel that we can ask for advice and guidance on specific topics. 

We strongly encourage community feedback and involvement, so please feel free to contact any of the <a href="http://gigadb.org/site/team"><i>GigaScience</i> team</a>, or use the <a href="http://gigadb.org/site/contact">contact us</a> form. 

To further enable transparency the GigaDB website is under continuous open developed in <a href="https://github.com/gigascience/gigadb-website/" target=blank>GitHub</a>, and users may comment and contribute any questions, problems or ideas for GigaDB through the website <a href="https://github.com/gigascience/gigadb-website/" target=blank>issue ticketing</a> system.

**Comment by pli888** [comment]
> We strongly encourage community feedback and involvement, so please feel free to contact any of the GigaScience team, or use the contact us form.

@only1chunts The [GigaScience team](http://gigadb.org/site/team) link doesn't display any email addresses. Someone wanting to contact anyone of us directly would have to hunt around for the email address.
