### ISSUE TITLE
MUST Update the tips section to include relevant links to guides

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1607]
## User story

>As an author
>I want to have guidance on how to user File Upload Wizard
>So that I can the follow the prescribed procedure

## Acceptance criteria

>Given I am uploading dataset files with File Upload Wizard
>When I am on the file uploader screen
>then I should see
```
the guideline pages for the relevant dataset types are:
Genomic & Transcriptomic datasets: http://gigadb.org/site/guidegenomic
Epigenomic datasets: http://gigadb.org/site/guideepigenomic
Metagenomic datasets: http://gigadb.org/site/guidemetagenomic
Imaging datasets: http://gigadb.org/site/guideimaging
Metabolomic & Proteomic datasets: http://gigadb.org/site/guidemetabolomic
Software datasets: http://gigadb.org/site/guidesoftware
```

>Given I am uploading dataset files with File Upload Wizard
>When I am on the file uploader screen
>then I should see "If you upload a file of the same name of a previously upload files, the existing file will be overwritten by the new uploaded files"

>Given I am uploading dataset files with File Upload Wizard
>When I am on the file uploader screen
>then I should see the text "For more information about expected files and their formats for given types of datasets"
>and I should a link to the allowed files types and file formats:
```
http://gigadb.gigasciencejournal.com/site/help
```

MUST. 7min. Update the Tips section to include relevant links to guides with Do's and Dont's of files to upload.

**Comment by only1chunts** [comment]
the guideline pages for the relevant dataset types are:
Genomic & Transcriptomic datasets: http://gigadb.org/site/guidegenomic
Epigenomic datasets: http://gigadb.org/site/guideepigenomic
Metagenomic datasets: http://gigadb.org/site/guidemetagenomic
Imaging datasets: http://gigadb.org/site/guideimaging
Metabolomic & Proteomic datasets: http://gigadb.org/site/guidemetabolomic
Software datasets: http://gigadb.org/site/guidesoftware

**Comment by luistoptal** [comment]
@only1chunts Is this what we're looking for, content-wise? (I will improve the styles in another ticket)

![image](https://github.com/gigascience/gigadb-website/assets/143437854/c08375ad-105d-4cd9-a790-e709e61b58f6)

the links will open in different tabs to avoid losing the file uploads

**Comment by only1chunts** [comment]
That looks like the sort of thing yes. Maybe adjust text from "For more information about the allowed file types," to "For more information about expected files and their formats for given types of datasets,"
