### ISSUE TITLE
MUST Disable Samples panel in File Upload Wizard

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1610]
MUST. 9min. Hide the Sample-link button until we have the full submission wizard working as there is currently no way for the user to add sample information to link to!

**Comment by luistoptal** [comment]
@rija  @only1chunts 

The sample excel file and the instructions contain refrences to the sample id field, should these be removed / hidden too?

![image](https://github.com/gigascience/gigadb-website/assets/143437854/ff9095fa-d1d5-413b-bd6a-8b8766ea0b65)

![image](https://github.com/gigascience/gigadb-website/assets/143437854/509cc2b7-f363-459e-9a73-e8721de2735a)

**Comment by only1chunts** [comment]
by "Excel" file are you referring to the CSV/TSV template file? 
if so, then I guess the answer should be yes that column doesn't need to be there. 
My only concern is the future consequences, removing that column will mean the parser that reads that input file will also need to be adjusted, which means when we eventually do reinstate it, the parser needs to be adjusted again. So we just need to ensure that the way its done is easily reversible in the future.

**Comment by luistoptal** [comment]
Yes

- the column "sample IDs" from the CSV template file
- remove the mention to Sample ID from the "tips"

The simplest option if the same feature is going to be added there in the future is to comment out the code and add some kind of reference (like a uid) so when the feature needs to be reenabled, it's possible to search for that uid in the code and restore the code

I'll take a look and I'll ask for help if there's significant backend work

**Comment by rija** [comment]
@luistoptal, @only1chunts 

That's good spot as I miss it in the ticket description.
Yes we want to disable that too

It should be as easy as removing line 182 in `protected/components/DatasetUpload.php`
and updating appropriately the example file in `fuw/input-examples/metadata/files-metadata.csv`

Automated tests may need adjusting to remove the tests associated with that functionality if any.

No need to worry about when we will bring back the functionality, as the code is under version control so we can always resurrect  it if needed, but more likely we might come up with a better way to do it in the future anyways.
