### ISSUE TITLE
SHOULD Update Attributes panel with info about attributes

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1611]
SHOULD. 9Min. Update Attributes button to include description and info about what attributes could be added. 

Depends on: 
*  #1633

**Comment by luistoptal** [comment]
@only1chunts the ticket refers to this screenshot, is this about adding an informational paragraph describing the attributes that can be added, a tootip to the "attributes" button, ...?

![image](https://github.com/gigascience/gigadb-website/assets/143437854/6ef066bf-8439-43f8-93bf-82a5fe9801d8)

**Comment by only1chunts** [comment]
This is dependent on another ticket being completed to allow the system to
know which attributes from the attribute table are suitable/viable to be
added here. This ticket is about offering a drop down menu or something
similar to allow the users to select from the viable list of attributes.
I believe there is another ticket somewhere about adding info pop ups to
assist, but if not there should be 😉 as the tooltip button will be
required eventually (I.e. it's another "should" ticket, not must have to go
live).

**Comment by rija** [comment]
Hi @luistoptal 

until we have a proper API endpoints, you can assume a file will exists at /var/www/files/data/attributes.json with following schema:
```
[
 {
    "attribute_name": "age",
    "definition": "age of host at the time of sampling; relevant scale depends on species and study, e.g. could be seconds for amoebae or centuries for trees",
    "allowed_units": "UO:0000031,UO:0000032,UO:0000033,UO:0000034,UO:0000035,UO:0000036",
    "attachable_to_files": true,
    "attachable_to_samples": true,
    "attachable_to_datasets": false
  },
  {
    "attribute_name": "sex",
    "definition": "physical sex of the host",
    "allowed_units": "[male|female|neuter|hermaphrodite|not determined]",
    "attachable_to_files": true,
    "attachable_to_samples": true,
    "attachable_to_datasets": false
  }
```

**Comment by luistoptal** [comment]
I think it might make sense to include this issue in #1632
