### ISSUE TITLE
MUST Email sent to author upon "DataPending" status needs to be customisable

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1618]
##  User Story

>As a curator
>I want to be able to customise the email to send the submitting author when I change the status to "DataPreparation"(previously DataPending)
>So that I am confident they understand what they need to do

## Additional info

MUST. 21:40min. Email sending to author needs to be editable before being sent to ensure it can contain the instructions for the author of what needs to be done in file upload tool.

**Comment by luistoptal** [comment]
@only1chunts not sure I understand, what form field is this ticket referring to in 21:40? (screenshot attached)

![image](https://github.com/gigascience/gigadb-website/assets/143437854/9f20c4ed-1b47-4676-8d60-780eaa8e9464)

**Comment by only1chunts** [comment]
When the curator sets the status to DataPending and clicks save, the system
sends an email to the author, we need to be able to edit that email before
it's sent.
Thanks.

**Comment by luistoptal** [comment]
will work on it after integration PR is merged as this form as some changes
