### ISSUE TITLE
MUST Audit acceptance tests checking that dataset pages are only visible when set to "published"

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1620]
MUST. Check that the DOI page is only publically visible when the dataset status is "published", certain places in the video seem to show that its openly visible when the status is other things.

**Comment by rija** [comment]
@pli888 @kencho51 I think we've done this in a recent PR right?

**Comment by kencho51** [comment]
> @pli888 @kencho51 I think we've done this in a recent PR right?

Yes, fixed in here https://github.com/gigascience/gigadb-website/pull/1663

**Comment by rija** [comment]
closing as done in #1663
