### ISSUE TITLE
SHOULD Replace attribute text field  with a drop-down menu

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1632]
Could we make the file attributes list a drop down of only those terms that we allow? (There is a ticket (#274) for updating the attribute table to inlclude an additional collumn with a flag for which table the term is allowed to be used is, e.g. is a particular attribute allowed on Files, Datasets or Samples?, when that is in place it will be easy to determine the dropdown list of only the attributes that are allowed on a file)

Depends on:
* #1633

**Comment by rija** [comment]
Hi @luistoptal 

until we have a proper API endpoints, you can assume a file will exists at /var/www/files/data/attributes.json with following schema:
```
[
 {
    "attribute_name": "age",
    "definition": "age of host at the time of sampling; relevant scale depends on species and study, e.g. could be seconds for amoebae or centuries for trees",
    "allowed_units": "UO:0000031,UO:0000032,UO:0000033,UO:0000034,UO:0000035,UO:0000036",
    "attachable_to_files": true,
    "attachable_to_samples": true,
    "attachable_to_datasets": false
  },
  {
    "attribute_name": "sex",
    "definition": "physical sex of the host",
    "allowed_units": "[male|female|neuter|hermaphrodite|not determined]",
    "attachable_to_files": true,
    "attachable_to_samples": true,
    "attachable_to_datasets": false
  }
]
```

**Comment by luistoptal** [comment]
@only1chunts @rija how many attributes can we expect to be there in production to be displayed in the dropdown? 10s? 100s?

**Comment by only1chunts** [comment]
For files it's 10's
for samples it's 100's
