### ISSUE TITLE
Copy dataset images into S3

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1635]
The thumbnail images of a lot of (recent) datasets show the generic logo on AWS deployment even though the same dataset has a proper thumbnail on the CNGB deployment

**Comment by only1chunts** [comment]
please treat this as lower priority as its a task that could be done by curators over time and there are many more things that your time would be better spent doing.

**Comment by rija** [comment]
If to be done manually using the dataset admin form, it's better to wait for PR #1602 to be merged before anyone action this.

**Comment by only1chunts** [comment]
FYI - the curators will manually update the images of the most recent 50ish datasets, as well as the top viewed 100 datasets, as per #1297.  The rest of the thumbnail images will need to be migrated eventually, and we should have a plan to do that somewhere.
