### ISSUE TITLE
odd page redirect when click save on dataset with status "AuthorReview"

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1643]
## User story

>As a curator
>I want to remain on the dataset admin page when I click save
>So that I can see the success notification and continue to make further changes if required

## Acceptance criteria

>Given I am on a dataset admin page  
> and the status of that dataset is "AuthorReview"
>When I make a change to any field and click Save
>Then the changes are saved and the page reloaded with the success (or failure) notification

## Additional Info

Related to issue #1529, specifically the commit: https://github.com/gigascience/gigadb-website/commit/20fc699879b0d17b492b2eb73b8b7949dfbf5aec
Slightly odd behaviour when the dataset status is "AuthorReview"

Note- the expected action of reloading the page and presenting the success/failure notice does happen in when dataset status is anything else, its just for the "AuthorReview" status?!

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by kencho51** [comment]
According to #1529, `The save button should just save the changes and reload the same data-admin page` for the private datasets is implemented, those private datasets has pageType set to `hidden`. For the current implementation, all pageType `hidden` datasets will reload the same admin dataset page after clicking save button for update action.

While for the dataset with upload status falls into any of these: `UserUploading` , `DataAvailableForReview`, `DataPending`, `Curation`, `AuthorReview`, the pageType will be set to `draft`, and in current implementation, all pageType `draft` datasets will redirect to `/adminDataset/admin/` for update action.

**Comment by only1chunts** [comment]
I'm slightly confused by the terminology here, you appear to using statuses (pageType?) of `hidden` and `draft` which are not statuses that we use in curation so I'm not sure what `draft `or `hidden` mean in your terminology? they sounds like the same thing to me.
For any dataset that has a status of ANYTHING other than "Publish" the save action should be the same (i.e. reload the dataset admin page that i'm currently on*. At present that is not the case for when the status is set to `AuthorReview`

\* for clarity the dataset admin page means the page actually showing that individual dataset editing page not the list of all datasets (e.g. https://beta.gigadb.org/adminDataset/update/id/2750)

**Comment by kencho51** [comment]
Fixed in PR #1663
