### ISSUE TITLE
Update documentation on live for API usage

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1652]
## User story

>As a website user  
>I want to have the correct information on how to use the API
>So that I can use it accurately

## Acceptance criteria

>Given I am on http://gigadb.org/site/help#interface
>When I see the section on 

<i>Examples
1. retrieve known datasets by doi
http://gigadb.org/api/dataset?doi=100051</i>

>Then I am warned that this query only returns a maximum of 50 items for each of the sections Sample and File
To retrieve all dataset information please combine the output of the three commands below:
http://gigadb.org/api/dataset?doi=100051&result=dataset
http://gigadb.org/api/dataset?doi=100051&result=sample
http://gigadb.org/api/dataset?doi=100051&result=file

## Additional Info
related to #1651 

IF there are other API queries that also return a limited number of things then we should make sure those are also indicated in the documentation!

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Implemented in PR #1738 that was just merged, so closing
