### ISSUE TITLE
Broken acceptance tests in AdminDatasetForm.feature

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1654]
There are two broken acceptance tests in AdminDatasetForm.feature following the merging of PR [Provide horizontal scroll bar in files table #1649](https://github.com/gigascience/gigadb-website/pull/1649). The broken tests are:

*   Scenario: AuthorReview dataset with private URL buttons
*   Scenario: Open Private URL from AuthorReview dataset

To check the tests are broken, run:
```
$ ./up.sh
$ docker-compose run --rm codecept run --no-redirect acceptance AdminDatasetForm.feature
```

This was caused by the addition of a new dataset 102484 for `dev` data. Fixing lines containing `I am on "/adminDataset/update/id/2343"` with the correct `$id` in AdminDatasetForm.feature should resolve this problem.

**Comment by rija** [comment]
The work was implemented in PR #1655 so closing the issue
