### ISSUE TITLE
Spreadsheet upload tool checks

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1661]
Can we investigate how much time and effort it will cost to put some additional Error log reports on the spreadsheet upload tool?

The curators find it very time consuming to try to identify WHAT the cause of the error message "fillTable output: false" means? There are a number of things it could be listed below, and thats probably not exhaustive, but if there could be a log message to suggest which field fails that would be extreme useful.

- Mis-formatted author list
- Mis-formatted funding list
- Any row(s) inserted/deleted in study tab
- Sample tab has additional or missing header row(s) or incorrect mandatory first 4 columns
- File tab has additional or missing header row(s)
- Sample table has a missing value in the Species Taxon column

Other issues that should be tested that may or may not results in a "fillTable output:false" error messge:
- Missing a mandatory value : identifier (DOI)
- Missing a mandatory value : submitter_first_name
- Missing a mandatory value : submitter_last_name
- Missing a mandatory value : submitter_email
- Missing a mandatory value : submitter_affiliation
- Missing a mandatory value : author_list
- Missing a mandatory value : dataset_type
- Missing a mandatory value : title
- Missing a mandatory value : description

## User story

>As a curator
>I want to know whats wrong with my spreadsheet when it fails to upload
>So that I can fix it efficiently

## Acceptance criteria

>Given my spreadsheet fails to upload with error "fillTable output: false"
>When I look at the java.log file
>Then I get a helpful hint to tell me why it failed

>Given I attempt to upload a spreadsheet with an improperly formatted Author list value (cell C13 of the Study tab), i.e. it contains commas instead of semi-colon delimiters or it has multiple semi-colons side by side or some other delimiter issue.
>When I look at the java.log file
>Then the java.log file contains the prompt "Author list is incorrectly formatted"

>Given I attempt to upload a spreadsheet with an improperly formatted Funder list value (cell C20 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "Funder list is incorrectly formatted"

>Given I attempt to upload a spreadsheet with a Sample tab containing invalid rows (e.g. the template rows 1&3 should be deleted prior to upload)
>When I look at the java.log file
>Then the java.log file contains the prompt "Sample tab includes invalid rows or columns"

>Given I attempt to upload a spreadsheet with a Sample tab containing the incorrect first 4 mandatory columns .
>When I look at the java.log file
>Then the java.log file contains the prompt "Sample tab includes invalid rows or columns"

>Given I attempt to upload a spreadsheet with a File tab containing extra OR fewer header rows than expected.
>When I look at the java.log file
>Then the java.log file contains the prompt "File tab has additional or missing header row(s)"

### Additional potential test

The tests below are perhaps already covered in some cases and are not likely to result in a "fillTable output: false" error message, but should still cause errors:

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "identifier" field (cell C4 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing DOI identifer value"

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "submitter_first_name" field (cell C8 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing submitter_first_name value"

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "submitter_last_name" field (cell C9 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing submitter_last_name value"

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "submitter_email" field (cell C10 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing submitter_email value"

**NB - Currently a Missing email address doesn't fail! Which is a bug and must be fixed, we cannot have users registered in GigaDB without an email address!**

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "submitter_affiliation" field (cell C11 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing submitter_affiliation value"

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "author_list" field (cell C13 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing author_list value"

>Given I attempt to upload a spreadsheet with a missing value in the "Manuscript identifier" field (cell C3 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "Missing manuscript identifier value"

NB the manuscript Identifier is not currently a mandatory field, but it is very useful and there is no reason why we shouldn't be adding it in every case, so I propose we should make it mandatory for the upload process (not in the DB schema)

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "dataset_type" field (cell C14 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing dataset_type value"

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "title" field (cell C15 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing title value"

>Given I attempt to upload a spreadsheet with a missing mandatory value in the "description" field (cell C16 of the Study tab)
>When I look at the java.log file
>Then the java.log file contains the prompt "missing description value"

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
From now on, and until the FUW is ready, the tech team will manually  ingest in the AWS deployment the same dataset spreadsheet that Jesse ingest on CNGB deployment on a regular basis.

**Comment by only1chunts** [comment]
closing this ticket as we're not going to make any changes to the current spreadsheet ingestion tools. We may want to reference this ticket when we start ingesting individual sheet/tables via the submission wizard.
