### ISSUE TITLE
Beta: some actions take too long to 'save'

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1662]
## User story

>As a curator   
>I want to **promptly** save the file update information 
>So that I can get on with my day!

## Acceptance criteria

>Given I am on a File Admin page (e.g. https://beta.gigadb.org/adminFile/update/id/539287)
>When I make a change and click Save 
>Then the updated information is saved to the database quickly and I am directed to the relevant acknowledgement page

NB - The issue is the SPEED (or lack of) with which the action happens, when CIH tested it, it took 95+ seconds to complete the action.

## Additional Info
I (MAT) have only seen the problem with file size changes but it might be a wider issue. 
This only seems to have happened when I have tried to save a file where I've added the file size (because this is not yet added by the upload script).
It takes a very long time, and sometimes has timed out. n.b. after the timed out ones I see that the file has saved with the changes.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by kencho51** [comment]
### Click update first time
![image](https://github.com/gigascience/gigadb-website/assets/64770635/00f28f18-e16f-4df1-97e2-4fa8cca870d0)


![image](https://github.com/gigascience/gigadb-website/assets/64770635/ebc68147-b339-4c9a-8817-4a83637d9a26)


### Click update second time
![image](https://github.com/gigascience/gigadb-website/assets/64770635/94cf360a-6ab5-4edc-8996-c5bac81946e5)


![image](https://github.com/gigascience/gigadb-website/assets/64770635/37205bc5-25e8-46b9-a651-73a198153eb3)

**Comment by kencho51** [comment]
![image](https://github.com/gigascience/gigadb-website/assets/64770635/af534dde-95c0-4725-b96e-6519ec4c1247)

![image](https://github.com/gigascience/gigadb-website/assets/64770635/b287dcb7-24c0-4d13-890c-933cca4c3870)

![image](https://github.com/gigascience/gigadb-website/assets/64770635/a72a8ab4-5ae9-49dc-a747-429e66a7227b)

**Comment by kencho51** [comment]
Close as fix in PR https://github.com/gigascience/gigadb-website/pull/1866
