### ISSUE TITLE
ensure the upload script parses file attributes correctly

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1668]
## User story

>As a curator (someone using spreadsheet upload script)  
>I want it to handle the BUSCO summary results appropriately
>So that the BUSCO summary results can be added as file (and sample) attributes

## Acceptance criteria

>Given I have a dataset that includes a genome assembly file that I have provided the "BUSCOv5_result" attribute for
>When I run the spreadsheet upload script 
>Then the BUSCOv5_result value is uploaded correctly without truncation at any of the colons.

The BUSCOv5_result attribute is valid in both Files and Samples, but to the best of my knowledge (CIH), when used in the Samples tab of the spreadsheet it doesn't cause any issues because the delimiter being looked for on the sample sheet is not a ":" .

## Additional Info
A foibal of how the file attributes are added is that the attribute name and value are separated by ":" which works for most things, but the value for any "BUSCOv5_result" attribute added to a file has this format "C:95.2%[S:20.3%,D:74.9%],F:1.7%,M:3.1%,n:1614"
Which causes issues when the spreadsheet is parsed by the upload scripts.
The file attribute column will contain this`BUSCOv5_result:C:95.2%[S:20.3%,D:74.9%],F:1.7%,M:3.1%,n:1614`

When I asked Jesse how he does it, this was his reply
> Using ':' to truncate the string first, the first value is the file attribute name (if found in the attribute table), and then the rest will be the value. 

Which sounds like it will only ever find 1 attribute, which could also be problematic when multiple attributes are added.

This maybe a challenge too far, and it might just be easier to handle these cases manually, but at least this ticket will raise awareness of the problem.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
@only1chunts please add exampled of multiple attributes

**Comment by only1chunts** [comment]
see file `VNS-main.zip` on dataset [102498](https://beta.gigadb.org/dataset/102498), it has 3 file attributes, 2 of which would be added via the spreadsheet upload script, the MD5sum value gets added separately by the post-upload script.
**license**: MIT
**SWH**: swh:1:dir:9571533272431c9af8cde813cafc5591c94eb58c
**MD5 checksum**: 55326990dfbe66952f300d0533b5012e
(attribute name in bold)
Note the SWH values will have a similar issue to the BUSCO attributes, ie. they contain multiple `:` within the values!

**Comment by rija** [comment]
Instead of modifying the Java tool. Build missing or broken around it on separate script (that may  be based on tools like DuckDB).

**Comment by only1chunts** [comment]
this spreadsheet has an example in the file attributes of a BUSCO value:
https://docs.google.com/spreadsheets/d/1hOKekE2DDWTzTkLKuQLnJv2D0wj5zAwC/edit#gid=152601041

**Comment by only1chunts** [comment]
we're not making any changes to the ingestion scripts so this ticket can be closed. We may want to reference it when we're checking the file upload wizard handles file attributes as expected.
