### ISSUE TITLE
Show full author names

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#167]
@only1chunts says when updating an author on the GigaDB Administration web pages, e.g. [here](http://localhost:9170/adminAuthor/update/id/3789), enable these pages to show the full author name including any middle name in the Display Name text field box.

[https://drive.google.com/open?id=16pBf-O1UsP78NRRRO6BiT1CtN0Ij5hOZ](https://drive.google.com/open?id=16pBf-O1UsP78NRRRO6BiT1CtN0Ij5hOZ)

**Comment by only1chunts** [comment]
The display name field box should show the "display name" as previously defined by Rija's work, and it should be editable to overwrite that display name.
