### ISSUE TITLE
general comments about the File Upload Wizard following Sprint23 demo

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1673]
I made some notes during the sprint23 demo of the FUW. Some of which will already have tickets, some are just questions, and there aer a couple of new issues that will require tickets to be created.

1 - COULD the server address was gigadb.gigasciencejournal.com, will that be simple to change to gigadb.gigsciencePRESS.com as soon as we have access to that domain? Its not a blocker, but it would be nice to not confuse any GigaByte submitters by pointing them to a GigaScience journal server.

2 - SHOULD Can the "Create new box" button that is currently added to the main Datasets Admin list also be added to the relevant individual dataset admin page? i.e. in the demo peter had to click save with the new status "Assign FTPbox" in the individual dataset admin page then navigate back to the main dataset admin list to actually action the new drop box. This is a new feature and as such has lower priority than existing requests.

3 - QUERY (I need a refresher on what the requested behaviour was!) Regarding the "create new box" button, what happens if it is clicked twice/multiple times? Is that even possible? Is a box assigned to the Dataset, or is it assigned to the user (datset owner)? Either could work, and I feel like we have discussed it before, I just cant remember what we decided.

4 - QUERY In the wizard itself, when adding in attributes via the table uploader, why is the delimiter double colons "::" instead of a single char ":" ? Its slightly odd, but if there is a legitimate reason for it, we'll be able to live with it.

5 - OBSERVATION: The file Format is not editable via the GUI, but it is required as a column in the table uploader file. Not sure if any action is required, maybe just needs some thought on consistency.

6 - QUERY (I know I've asked before, sorry for repetition) Does a curator have access to the "user-view" of the upload tool? this will come down to documentation and training, i.e. curators learning how to assist users with things like we do at the moment (e.g. the curator will often add files to the drop boxes directly from what the authors have provided via the journal submission system, if thats not possible we will just need to ask the authors to do it themselves, so its retraining).

7 - SHOULD/MUST? The mishap at the end when Peter set the dataset to Published before clicking the move data to public area needs to be prevented from happening in the live environment. Open to suggestions on how to do that, but maybe not allowing a user to select "publish" until certain checks box have been ticked? e.g. the data needs to have been moved to public server, the DOI needs to have been minted with DataCite, the publication date needs to be set. Some future plans include the addition of a 2nd eyes checklist #705 which maybe relevant here.
An alternative would be to enable a method of revoking "publish" status, but I'm not keen on that idea as it is open to misuse.
Another alternative is to have a documented method to manually do the transfer of files to the live server (after accidentally setting to publish!).

**Comment by rija** [comment]
Closing this as the comments from this ticket have led to updates to #588
