### ISSUE TITLE
MUST Only make the "Published" status selectable when a number of check boxes have been ticked

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1684]
# User story

>As a curator
>I want to not be able to select "Published" status until checks have been ticked
>So that I don't forget steps before setting a dataset as "Published"

## Acceptance criteria

>Given I am on a dataset form
>When all the following check boxes are ticked: 
* Files have been transferred to the public repository
* DOI has been minted
* 2nd eyes check have been performed 
>Then I can select the "Published" status

>Given I am on a dataset form
>When some or none of the following check boxes are ticked: 
* Files have been transferred to the public repository
* DOI has been minted
* 2nd eyes check have been performed 
>Then I cannot select the "Published" status

**Comment by luistoptal** [comment]
@rija not entirely sure how to handle this

I think I can get the DOI from the dataset. The "2nd eyes check" would be defined by the upload status? (but if it's something that the curator can change, not sure if that makes sense). As for the files, I guess also the presence of files would be enough, in combination with the approval of the reviewer (2nd eyes?)

Also, looking at the controller, it looks like that is the responsible of sending to the frontend a list of available statuses, so I'm also wondering whether this task is more indicated for the backend to handle

Will take a closer look on Monday

**Comment by only1chunts** [comment]
You may be overthinking this one a little for now. 
Ideally, in the future, yes we would like those checks to be automated, and its possible the mint DOI one could be automated now as that button is already functional, not essential, but if its an "easy win" we'll take it.
There are tickets in the system to incorporate the 2nd eye checklist into the admin pages, and there are also tickets for a button to move files to the public server, so when those are worked on, then it might be possible to automate the "ticks". 
But for now, literally just 3 tick boxes on the page that an admin user (curator) has to manually tick before the status "publish" is selectable from the drop-down menu of statuses.
Location: probably between the upload status box and the dataset types heading:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/901bc646-cbbc-4093-944f-406fd3493eed)
They could have the heading "Checklist items" if you wanted to make them into a section with a heading.

**Comment by luistoptal** [comment]
@only1chunts 

![image](https://github.com/gigascience/gigadb-website/assets/143437854/961bc232-93e3-4dc0-847e-fbc29d9bbc31)

It's not 100% clear what is the condition for minted DOI. Is it enough that the DOI exists when the page loads?

**Comment by only1chunts** [comment]
If the doi loads , e.g. Https://doi.org/10.5524/100001 then yes that's
enough to say the DOI has been minted.

**Comment by luistoptal** [comment]
@only1chunts is it possible that the DOI is defined in the database (i.e. that the form loads with a defined value for the DOI) but that the DOI is not real? That does not resolve to an existing document?

I will bring it up tomorrow in the VOH to get clarification

**Comment by only1chunts** [comment]
The doi resolver (Https://doi.org) will only work if the doi has been
minted.

**Comment by rija** [comment]
@luistoptal  with respect to this user story, all the checkboxes are manually ticked by curators, there is nothing clever about them. The smart is to be in not allowing the "Publish" option to be effective when not all checkboxes are ticked.

But trying to answer your question, the resolving of a DOI to a document only happen after the curators have "minted" the DOI (i.e: registered the DOI in the Datacite API by clicking the "Mint DOI" button), so yes, there will be a period where the DOI will be in the database (and thus loaded into the form) but not yet registered (and thus not matching any documents)
