### ISSUE TITLE
SHOULD curation log table on dataset form is still using the old legacy styling

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1703]
On a dataset update form, at the bottom, there is a curation log table. At the end of each row there are call to actions icons (view/edit/delete) that are using the old legacy style, they should be using the new font-awesome style instead.

Same goes for the table's headers.

<img width="1144" alt="Screenshot 2024-02-22 at 4 29 58 PM" src="https://github.com/gigascience/gigadb-website/assets/11455/6b62fe3a-f8d1-417e-9037-3d488b3c9c7c">

**Comment by luistoptal** [comment]
@rija this screenshot is showing the old style, below screenshot shows how it should look with the new style in the last version of develop

![image](https://github.com/gigascience/gigadb-website/assets/143437854/6764f4a7-144d-4f98-818b-0ff9cad1fc56)

the most common reason why this might happen is if switching branch and the css file was not rebuilt from the less files. This screenshot looks like it's using the old layout though

**Comment by rija** [comment]
Hi @luistoptal 
yes, you are right, I didn't even noticed the whole page was old style.
I fixed the issue on my side, so will close this ticket
