### ISSUE TITLE
odd behaviour on home page in staging v4.2.0

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1709]
**Describe the bug**
More button is behaving oddly.

**To Reproduce**
1. Go to https://staging.gigadb.org/
2. Click on `+More`
3. See error. The list of dataset types becomes less? and the list of recent datasets becomes more!

**Expected behavior**
The recent dataset list should not be affected by the button.
The list of dataset types should by default be the smaller list, and when you click the `+More` button, it expands to show the rest.

**Comment by only1chunts** [comment]
cache issue, cleared cache its now fine.

**Comment by rija** [comment]
@only1chunts I think you need to hard-refresh the page first as your browser may still cache conflicting CSS files.

I had the same issue and hard-fleshing the page in my web browser solved this
