### ISSUE TITLE
improve visibility of manuscript link

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#171]
Change "Related manuscripts:" text to "READ THE PEER-REVIEWED PUBLICATION(S):" 
this should be done in conjunction with #74 to allow users to see the manuscript title and authors as well as the DOI of the paper.

**Comment by only1chunts** [comment]
I have seen this working correctly in @jessesiu version, and I asked him to change the head to sentence case instead of all CAPS.

**Comment by only1chunts** [comment]
@jessesiu has this work been committed/pulled to the github repo code yet? i.e. can I close this ticket yet?

**Comment by jessesiu** [comment]
Yes, it's in the https://github.com/gigascience/gigadb-website/pull/168
