### ISSUE TITLE
messed up formatting of admin page in staging

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1710]
**Describe the bug**

**To Reproduce**
1. Go to https://staging.gigadb.org/site/admin
2. See error, the buttons are listed in a long list instead of laid out as expected

**Screenshots**
Beta showing as expected:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/057f6d4d-1083-4fb2-9275-0ed956a6f168)

Staging showing messed up format:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/1bc29187-701a-46ae-9833-f5300e78c70a)

**Comment by kencho51** [comment]
Hi @only1chunts 

I believe it is the browser caching problem,it will look as expected when you hard reset your browser.

**Comment by only1chunts** [comment]
It looks like you may be correct!
