### ISSUE TITLE
meaningless text at top of dataset admin page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1711]
**Describe the bug**
odd text at top of manage dataset page, its on live as well so its been there a while, I've just not noticed it before!!! it has no adverse effects on usage so is a very low priority, but its just meaningless text at the top of the page for no reason.

**To Reproduce**
1. Go to http://gigadb.org/dataset/admin
2. See error, the top of the page has text "You may optionally enter a comparison operator (<, <=, >, >=, <> or =) at the beginning of each of your search values to specify how the comparison should be done. Date should be exactly in this format: yyyy-mm-dd"

**Screenshots**
The text highlighted in red below has no reason to be there.
![image](https://github.com/gigascience/gigadb-website/assets/6037145/58f37544-c7e9-45d4-baf5-38863e445cc7)

**Comment by rija** [comment]
Hi @only1chunts,

Why do you say it's meaningless ? it explains how to filter the table below. 
e.g: if you type `<101239` or `>101239` in the DOI column, it will filter the table to only show all datasets with DOI before 101239 and after 101239 respectively

**Comment by rija** [comment]
The text needs rewording and presented as a help section for the table below

**Comment by luistoptal** [comment]
To note that I see similar text in a handful of places
![image](https://github.com/gigascience/gigadb-website/assets/143437854/fa210846-780b-4e0e-b0e2-41f7dcefc02d)

**Comment by luistoptal** [comment]
@only1chunts @rija perhaps something similar to this?
![image](https://github.com/gigascience/gigadb-website/assets/143437854/19565583-581e-4e21-83bb-70386efaf7c8)

this is a commonly used help box, to note that the styles are improved in PR https://github.com/gigascience/gigadb-website/pull/1701

**Comment by only1chunts** [comment]
That looks great. Can that box expand/contract on request so that it only shows when someone clicks the heading "Filtering instructions"?
Thanks
