### ISSUE TITLE
erroneous originator for curation log entry

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1713]
**Describe the bug**

**To Reproduce**
1. Go to https://staging.gigadb.org/adminDataset/update/id/2747
2. change something, Click save
3. Scroll down to the curation log
4. See error: the log has a new entry saying created by "system" 

**Expected behavior**
If I am logged in as a curator/admin and I make a change to the dataset I expect the curation log to state that it was me that made an update not "system".

**Additional context**
related to #1615

**Comment by kencho51** [comment]
Close as fixed in PR #1753
