### ISSUE TITLE
additional text visible on guidelines page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1714]
**Describe the bug**
I'm guessing someone wrote (a very nice) description of the workflow to be used by screen-readers, but that description is appearing on the website instead of just being hidden.

**To Reproduce**
1. Go to https://staging.gigadb.org/site/guide
2. Scroll down to just below the workflow image
4. See the textual description of the image

**Expected behavior**
I would not expect to see the written description of the workflow diagram (unless that diagram is not displayed for some reason!?)

**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/6037145/af7728a4-81fb-4177-bc9c-47c58025282c)

**Comment by rija** [comment]
@luistoptal any advice or comment on this?

**Comment by luistoptal** [comment]
I understand @only1chunts concern about bloating the page

it would be fine to make the textual description available only to screen readers, it's a quick fix

**Comment by rija** [comment]
done with PR #1721
