### ISSUE TITLE
twitter becomes X

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1715]
## User story

>As a user  
>I want to see the X logo instead of the old twitter logo
>So that ... well its just the right thing to do

## Acceptance criteria

>Given I am on gigadb.org
>When I look for a link to X (formerly called twitter) in the page header
>Then I see the X logo instead of the Twitter logo.

>Given I am on gigadb.org
>When I look for a link to X (formerly called twitter) in the page footer
>Then I see the X logo instead of the Twitter logo.

## Additional Info
maybe done in combination with #1716

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
@only1chunts is it worth having similar ticket to add our Mastodon social id alongside the others?

**Comment by only1chunts** [comment]
good idea! - Done #1717
not that I know how to access it or use it, but thats the same for weibo :-D
