### ISSUE TITLE
plus[+] button on Dataset:Sample admin page not working

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1722]
## User story
For the Admin page, when I click the "Dataset:Samples" function, and search DOI 102330 as an example, I cannot use the [+-] button in the "Sample attributes" column to expand the sample information.

>As a admin-user
>I want to be able to inspect the sample attributes of samples in the dataset:sample list page e.g. https://beta.gigadb.org/adminDatasetSample/admin?DatasetSample%5Bdoi_search%5D=102330&DatasetSample%5Bsample_id%5D=&DatasetSample%5Bsample_name%5D=&DatasetSample_page=1
>So that I can benefit

## Acceptance criteria

>Given conditions  
>When event  
>Then outcome

>Given conditions  
>When event  
>Then outcome

## Additional Info
![image](https://github.com/gigascience/gigadb-website/assets/6037145/b7b56e23-64e4-4871-8378-713a8510d35b)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Fixed in PR #1736, and part of release 4.2.1, so closing
