### ISSUE TITLE
Replace all usages of curl with GuzzleHTTP in our GigaDB codebase

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1750]
## User story

>As a developer  
>I want to remove usage of PHP curl  in the codebase
>So that all our code that make HTTP connection works the same way
>And that the amount of code needed to make HTTP connection is drasctically reduced
>And that we can access features (like client side caching) offered by HTTP libraries that support PSR standards

## Acceptance criteria

>Given our GigaDB codebase need to talk to a web service  
>When it is making the HTTP connection  
>Then the connection is made using the same modern client library (GuzzleHTTP)

## Additional Info

This is just for the code we write/maintain.
There are some dependencies that currently may need their own specific  HTTP client installed (e.g: Unleashed)

This is created out of reviewing PR #1728

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by kencho51** [comment]
We need to evaluate the usage of [DataCite REST API](https://support.datacite.org/docs/api).

```
% curl https://api.test.datacite.org/dois/10.80027/100006 | jq '.[].attributes.url' 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9221    0  9221    0     0   8204      0 --:--:--  0:00:01 --:--:--  8233
"http://gigadb.org/dataset/100006"
```

**Comment by rija** [comment]
Hi @kencho51,

That was already suggested in #456

but this issue is independent of what API is used and is not specific to DataCite interactions
We just need to get rid of the use of curl in the codebase. I think we have started doing that already, but there is still the code in AdminDatasetController.php. I believe that's the last instance, but we would need to confirm that.

**Comment by alli83** [comment]
the issue in the current code, is that the errors other than 422 are not being handled. Also why do you need to show the response message received  (frontend)?

**Comment by rija** [comment]
this is fixed already
