### ISSUE TITLE
There are UI buttons that have inconsistent looks on the dataset admin form

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1766]
**Describe the bug**

There are two places where displayed buttons have a visual aspect not one line with the new GigaDB layout (default Bootstrap colours, no space between them)
I have hard-refreshed the page so it doesn't seem cache related 

**To Reproduce**
Steps to reproduce behavior 1:
1. spin up local instance of GigaDB
2. login as and admin and start the FUW workflow by setting upload status to "AssigningFTPbox" and submitter to "user@gigadb.org" on dataset form for DOI 200070 and save
3. Go back to the list of datasets
4. Click the drop box creation icon
5. You should see a message with two buttons. The buttons look off (see screenshots)

Steps to reproduce behaviour 2:

1. Make sure you reproduced behaviour 1 first
2. go back to the admin form for DOI 200070 and change upload status to "Submitted" and save
3. Return to the same form and click the button at the bottom "Generate mockup for reviewers"
4. the popup show tab buttons that looks off and the "Generate mockup" button sports the old style

**Screenshots**

<img width="1287" alt="Screenshot 2024-03-21 at 8 15 27 PM" src="https://github.com/gigascience/gigadb-website/assets/11455/99945efa-5303-42fd-b249-2032681ad43a">

<img width="732" alt="Screenshot 2024-03-21 at 7 09 59 PM" src="https://github.com/gigascience/gigadb-website/assets/11455/459ccb74-d1b1-4845-8004-c75fb37f0c69">

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: Safari 17 and Firefox 123.01

**Comment by luistoptal** [comment]
@rija Case 1 is fixed in PR #1699

I don't think the other use case was updated, I will take a look
