### ISSUE TITLE
Unable to find a dataset-author from dropdown list

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1768]
## User story

>As a curator  
>I want to be able to find the relevant author from the author table in the Dataset_author admin page
>So that I can add the correct author to a dataset

## Acceptance criteria

>Given I am manually adding a author to a dataset
>When I navigate to the create dataset_author page (https://staging.gigadb.org/adminDatasetAuthor/create)
> And I start typing the relevant author name in the box
>Then the list of possible names is provided in a sensible order 
> And I am able to select the correct person from that list

## Additional Info
Currently the list order is not alphabetical, which makes it hard to navigate, and there is no filtering just jumping to a close match to what is typed, that doesn't work when there are multiple names starting the same. e.g. Its impossible to find Christopher Hunter in the list!

Given that we normally add authors to datasets via the spreadsheet upload this feature is not a high priority.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
It should be implemented the same way as for #937

**Comment by rija** [comment]
Hi @luistoptal,

maybe something for you to look into?
