### ISSUE TITLE
Transfer existing user dropboxes from CNGB server to EFS

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1782]
## User story

>As a curator
>I want  files uploaded already by authors to their assigned Dropboxes to be copied over the new infrastructure (AWS EFS)
>So that I can continue my curation work when the old infrastructure is unplugged

## Acceptance criteria 

>Given I have list of all user dropboxes existing on CNGB Server
>When they are marked as "COPY TO NEW SERVER"
>Then the dropboxes are transferred to AWS EFS

>Given I have list of all user dropboxes existing on CNGB Server
>When they have been transferred to the AWS EFS
>Then user can login with FTP using the credentials from the spreadsheet

## Tasks

* [x] #1819
* [x] #1820
* [x] #1821
* [x] #1822
* [x] #1823
* [x] #1824

## Additional infos

list of dropboxes: https://docs.google.com/spreadsheets/d/1qvfqRhfkoMCyubfL7z42hQmFLOozVbD2BYBSPBPPbwU/edit?usp=sharing

AWS Transfer family: https://aws.amazon.com/aws-transfer-family/
## Dependency

Can only be acted upon when following is done:

* [x] #1763

**Comment by only1chunts** [comment]
As we're actively working there are a number of userboxes that have been assigned but are still undergoing changes, either by curators or the authors, these are marked as "will need to be COPied TO NEW SERVER", i will change that status to "COPY TO NEW SERVER" as soon as each have reached a more stable point (usually when its ready for peer-review).

**Comment by rija** [comment]
Cannot use AWS transfer family as the managed service's user management part is not available if we use FTP endpoint and we would need to install our own user management service either using AWS directory service or something bespoke.
Both are either overkill or over-complex of the short term need here.
The easier approach is to implement part of #1634, which can be reused later to complete #588

**Comment by only1chunts** [comment]
We are not completely wedded to FTP, so if there are other protocols that are easier/quicker to implement then we're open to those. no reply required, just making sure you're aware those options are open.

**Comment by rija** [comment]
The last task of this story is implemented in PR #1826 currently awaiting review, so closing.

**Comment by rija** [comment]
as 4.2.7 version of GigaDB as been release, this epic is now completed
