### ISSUE TITLE
issues moving between sample and file view after clicking through some pages of files

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1783]
**Describe the bug**
Looking at a dataset with lots of files and lots of samples, e.g. https://staging.gigadb.org/dataset/100894
When I navigate through the sample table, e.g. click page 9 of samples
Then try to navigate around the files table, e.g. click page4 of files
Then try to return to the samples table view and navigate around that, it takes me back to the files table.
There seems to be new parts appended to the URL each time I click a page within a table, e.g.
start on: https://staging.gigadb.org/dataset/100894
click page 9 of samples: https://staging.gigadb.org/dataset/view/id/100894/Samples_page/9
navigate to files table, click page 4 of files: https://staging.gigadb.org/dataset/view/id/100894/Samples_page/9/Files_page/4

It looks like its retaining the previous `Samples_page/9` part of the URL when you navigate around the files table.

**Expected behavior**
I expect to be shown the page/view that I click on

**Additional context**

**Comment by rija** [comment]
Thanks for reporting. 
Two comments on this one:

1. It already behaves that way on CNGB's deployment at http://gigadb.org (see screenshot)
2. It is causing search bots (Google, Bing, ...)  to follow all those urls combinations


<img width="1388" alt="Screenshot 2024-04-10 at 4 08 30 PM" src="https://github.com/gigascience/gigadb-website/assets/11455/121323b4-44bf-474c-90b0-4fe3834fa74d">

**Comment by rija** [comment]
Note: Reported as part of testing GigaDB release [4.2.3](https://github.com/gigascience/gigadb-website/releases/tag/v4.2.3)

**Comment by only1chunts** [comment]
> It already behaves that way on CNGB's deployment at http://gigadb.org/ 

Wow- I never noticed that before! I think the reason is that most datasets dont have both a lot of samples AND a lot of files, so no need to look at multiple pages of each. Also I have my default settings on the tables set to display 100 rows at a time, so very few datasets have multi-page tables for me.

Would adjusting the default number of rows to be 100 make things easier?

**Comment by luistoptal** [comment]
Regarding the issue with the URLs, I have created a PR to fix it: https://github.com/gigascience/gigadb-website/pull/1790

this should also fix the issue reported above, ie 

> causing search bots (Google, Bing, ...) to follow all those urls combinations

So I believe it should be ok to allow indexing by crawlers

In terms of SEO, I would also encourage to use a canonical url tag in each page to avoid diluting "google juice", which for the case of many URLs related to pagination it would be the "base" url, e.g. http://gigadb.gigasciencejournal.com/dataset/view/id/100035

Page load speed is also important for SEO, but from waht I've heard that should be handled / solved by caching

**Comment by rija** [comment]
> Regarding the issue with the URLs, I have created a PR to fix it: #1790
> 
> this should also fix the issue reported above, ie
> 
> > causing search bots (Google, Bing, ...) to follow all those urls combinations
> 
> So I believe it should be ok to allow indexing by crawlers
> 
> In terms of SEO, I would also encourage to use a canonical url tag in each page to avoid diluting "google juice", which for the case of many URLs related to pagination it would be the "base" url, e.g. http://gigadb.gigasciencejournal.com/dataset/view/id/100035
> 
> Page load speed is also important for SEO, but from waht I've heard that should be handled / solved by caching

Hi @luistoptal,

I agree, and I can see in the source code that we don't do that. 
I feel like it's small piece of work, and there is a ticket that should cover that work already (#514)

**Comment by rija** [comment]
This is done and released
