### ISSUE TITLE
footer still showing old twitter logo

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1793]
**Describe the bug**
Whilst the footer is now showing the new X logo, it is also still showing old twitter logo

**To Reproduce**
1. Go to https://staging.gigadb.org/
2. Scroll down to footer
4. See error (see screenshot below)

**Expected behavior**
I should not see the old Twitter logo

**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/6037145/6fbe7c8a-aadb-4c1b-86c8-5f2709573821)

**Comment by rija** [comment]
This will be fixed in PR #1742, so closing
