### ISSUE TITLE
editorial manager integration into GigaDB

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#180]
we want the information from EM plumbed directly into GigaDB.
The only way to do this would be to set up automated email from EM on a daily basis to send the report I currently get weekly, or perhaps some tweeked version of it, to chris@gigasciencejournal.com
Each MS could automatically have a DOI pre-assigned with a status of "incomplete", The title, authors, ORCIDs, and abstract can all be automatically uploaded from the excel spreadsheet on a daily basis. 
We would need a new status in GigaDB for "rejected" for when the MS get rejected.
It may be possible to add a flag of some sort to editorial manager that the Eds could use to trigger GigaDB to update status to "requested", at which point GigaDB will email database@ and/or generate a ticket in Request Tracker (RT  #179 ) to say a new dataset has been requested.
From that point onwards we would need the job tracker (e.g. RT) to allow us to "claim" datasets to work on.

**Comment by only1chunts** [comment]
[report.xlsx](https://github.com/gigascience/gigadb-website/files/1927147/report.xlsx)
Attached is the report that currently gets sent to chris@giga by email as an attachment each week. We can change the fields that are included in it, rearrange the order of columns but I dont think there is any way to change the format (i.e. the only option if excel). It can be set to send every day.
the columns at present are :

Manuscript   Number |  this number is the tracking ID for the manuscript it is unique within the manuscript tracking system, we currently do not maintain this number in GigaDB anywhere because we use a google-doc to track the links between this manuscrip number and the GigaDB dataset DOI, we need to start keeping a record of this number in GigaDB somewhere - it should be added as an un-editable field on the admin/dataset page!
Initial Date Submitted |  self explanatory, not required in GigaDB
Editorial Status |  This field holds the current status of the manuscript, it is updated within the Editorial Manager system by the editors and will be the trigger for gigaDB to change the status of a dataset to "rejected" if this field has the status "Final Decision Reject".
Article Title |  This is the title for the manuscript, but in GigaDB we like the dataset title to be Supporting data for "<title>". i.e. this field prefixed by the words supporting data for.
Corresponding Author Last Name |  this will be the "users last name"
Corresponding Author First Name |  this will be the "user first name"
E-mail Address |  this will be the "user email"
First Author Last Name |  not specificlly required as the full author list if included (later)
First Author First Name | not specificlly required as the full author list if included (later)
Manuscript Notes |  these are notes added by editors during the review process, we currently have no place to hold these and I dont think we need them in GigaDB
Final Disposition Term |  Ignore this
Publication Date |  Ignore this
All Authors |  This is the full list of authors that will need to be converted to individual authors and added to GigaDB author table
Corresponding Author ORCID | this is the ORCID of the "user" 
Funder Name | this is supposed to be the funding body name - often its not complete or incorrect so I'm not sure how to validate this field
Grant Number | this is supposed to be the funding body name - often its not complete or incorrect so I'm not sure how to validate this field
Grant Recipient | this is supposed to be the funding body name - often its not complete or incorrect so I'm not sure how to validate this field
Abstract | This is what we use as the dataset Description

**Comment by only1chunts** [comment]
Other fields that are "required" for a new dataset that are currently not included in the above report.xlsx are
dataset type(s) | this can be left blank initially, it may require a change to the database rules if its set there are required? but on the webpage we still want it as mandatory so that whenever someone goes to it they are required to complete that field before it will save.
dataset size | default to 0
image information | default to the (G) URL http://gigadb.org/images/data/cropped/no_image.png with the attributes Image Source - GigaDB, Image Tag - GigaDB, Image License - CC0, Image Photographer - GigaDB
DOI | this will need to be set to the next available number (the website currently does this anyway when a new dataset is started online by a user)
FTP site | can be set by adding the DOI number to the FTP site prefix
Publisher | will always be "GigaScience Database"
Fair Use policy | can be left blank/null
Publication date | default to 6months from date of submission ie. 6months from the day the dataset is created with status "incomplete"
modification date | blank/null
keywords | blank
URL redirect | blank

**Comment by only1chunts** [comment]
all datasets are listed in GigaDB and can be seen within the admin pages:
http://gigadb.org/dataset/admin
those new ones that are added via the above automated method will have "status" of incomplete. Admin could view those via the normal dataset update page, e.g. http://gigadb.org/dataset/update/id/223 (screenshot of this one attached)
![incomplete-dataset-view](https://user-images.githubusercontent.com/6037145/38982178-141fd5ba-43b9-11e8-9d1e-1e52303fabed.jpg)

**Comment by only1chunts** [comment]
The report comes to my email address (chris@gigasciencejournal.com) at present, but this can be changed if we generate a new account in editorial manager. let me know if this needs to be a unique email address that create just for this purpose, or if it should be database@giga (which we currently use as the generic contact us email for gigadb. 
![scheduled_report_email](https://user-images.githubusercontent.com/6037145/39032933-3d9c267a-44a2-11e8-984d-6c7753591948.png)

**Comment by only1chunts** [comment]
see #250 for the UploadStatus changes required to handle the EM integration

**Comment by only1chunts** [comment]
The EM report also now contains the column "Editor Last Name" please can we add this to GigaDB as a Dataset attribute "Handling Editor" and display that in the dataset Admin pages both in the table of datasets and in each dataset page (under the curator box).

**Comment by jessesiu** [comment]
@only1chunts the script is running on the http://gigadb-staging-jesse.gigatools.net/. It will run on the production server after we implement the new GigaDB version.

**Comment by only1chunts** [comment]
for #91 we will need to workout how to get the CRediT details out of EM as well.

**Comment by only1chunts** [comment]
the ticket #816 covers this topic, so closing this ticket.
