### ISSUE TITLE
Investigate and fix portainer.gigadb.org

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1802]

**Comment by pli888** [comment]
Looks like https://portainer.gigadb.org is available again after updating Gitlab variables and re-deploying.

**Comment by rija** [comment]
Hi @pli888,
 
> Looks like https://portainer.gigadb.org is available again after updating Gitlab variables and re-deploying.

Ah, that's probably because of line 118 of `ops/configuration/nginx-conf/sites/nginx.target_deployment.https.conf.dist`

Closing this issue now
