### ISSUE TITLE
table setting preferences dont persist when changing page view

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1809]
## User story

>As a user  
>I want to be able to select my table preferences once (per session?)
>So that I tables are always displayed in my preferred way

## Acceptance criteria

>Given I select my SAMPLE table preferences
>When I visit a dataset with a SAMPLEs table
>Then I see the SAMPLE table displayed as per my preferences

>Given I select my SAMPLE table preferences
>When I change the page on a SAMPLEs table within a dataset
>Then the new page of the SAMPLE table is still displayed as per my preferences

>Given I select my FILE table preferences
>When I visit a dataset with a FILEs table
>Then I see the FILEs table displayed as per my preferences

>Given I select my FILE table preferences
>When I change the page on a FILEs table within a dataset
>Then the new page of the FILEs table is still displayed as per my preferences

## Additional Info
In v4.2.4 the Sample table preference change gets reverted to default as soon as you change the current table you're viewing. To replicate the issue:
1 - goto https://gigadb.org/dataset/view/id/100029/
2 - set sample table preferences to "View 20 samples per page"
3 - the page reloads to prefered view
4 - click view page 2 of samples
5 - see error: i.e. the page reloads to display the full sample list instead of just 20 rows.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Very likely related to #1757, and to #1800
