### ISSUE TITLE
The Sample and File tab show error when try to click on other pages in the mockup page.

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1812]
**Describe the bug**

**To Reproduce**
1. Go to mock up page https://gigadb.org/dataset/102519/token/YnBGarHHU3eHQ9J9
2. Click on page "2" in the Sample tab
3. See error 400, 
Error 400
Your request is invalid.
Go to the home page

**Expected behavior**

**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/112144621/75257eb7-d250-4c76-93a3-685e82d20eb3)
![image](https://github.com/gigascience/gigadb-website/assets/112144621/c143b84e-ae18-4fe8-865f-c1976cb68f64)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 114.0.5735.134

**Additional context**

**Comment by rija** [comment]
the fix is implemented in PR #1907
