### ISSUE TITLE
The file size are 0KB in the mock-up page

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1813]
**Describe the bug**

**To Reproduce**
1. Go to mock-up page https://gigadb.org/dataset/102519/token/YnBGarHHU3eHQ9J9
2. Scroll down and click "Files" tab
3. See all file sizes are 0KB

**Expected behavior**

**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/112144621/5dee5cac-e197-488d-a216-2a64aeb0626c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 114.0.5735.134

**Additional context**

**Comment by rija** [comment]
It will be fixed soon , there just a backlog in processing datasets

**Comment by rija** [comment]
Closing as the file sizes have been processed
