### ISSUE TITLE
generate mockup link button fails with error 404

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1817]
**Describe the bug**
When I had to (re)generate the mockup link for dataset 102522 (see #1816 for reasons why I needed to do that) I got an error message instead of geting a mockup page (see screenshot)

**To Reproduce**
1. Go to a dataset admin page e.g. https://gigadb.org/adminDataset/update/id/2785
2. Click on "Generate Mockup for reviewers" button
3. See error (screenshot below)
4. AND I would expect and email notification to the address entered into the reviewers email box, that didn't arrive either.

**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/6037145/964d31e3-f7c5-4531-a938-9c7d7b559928)

**Expected behavior**
When the generate mockup for reviewers button is clicked then a URL for the private view of the dataset page should be generated and displayed.

**Comment by rija** [comment]
Hi @only1chunts,

I think that's the wrong button. You clicked on the one used for File Upload Wizard  (which should not appear) instead of the regular link/button to create private url or open private urls.
I wonder what was the upload status of the dataset when you performed those actions?

**Comment by only1chunts** [comment]
I think it was set as "submitted" at that point, and infact its still set as that, and it shows the button I clicked at the bottom called "Generate Mockup for reviewer", I just tried again and got the same error:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/644d0c1b-fc36-499f-b576-6991cf389d32)

**Comment by rija** [comment]
Hi @only1chunts,

OK, thanks, but it's still the wrong button. That button is a FUW functionality. You cannot use it.

I've just tested on staging.gigadb.org and it matches the behaviour you are seeing.

Until this issue is fixed, the correct button,  called "Create/Reset Private URL" can be made visible if you briefly change the upload status to "ImportFromEM".

If that's not desirable, the URL that button goes to can also be guessed as it follows this pattern: `https://gigadb.org/adminDataset/private/identifier/<DOI goes here>`

**Comment by only1chunts** [comment]
OK, I get what you're saying now, thanks. The name of the button does imply it should create a mockup page though :-D I guess you will hide that button while the FUW is under construction.
I changes the dataset status to "curation", and nothing changed :-( (i.e. the same wrong button is still present)
so I changed it again to "author review" and that time it did present the create/update mockup link button, and it works.
In addition, it also allowed me to update the thumbnail image with the status "author review", so that confirms the tickets 1815-1817 are all related to issues around the dataset status.

**Comment by only1chunts** [comment]
In summary, the create/update mockup link button should only disappear when the status is "Published", we may want to create or update the link token at any other time so it should always be an option.

**Comment by rija** [comment]
Fixed in PR #1847

**Comment by only1chunts** [comment]
I was unable to exactly test the bug reported here as the need to click the button that gave the bug was removed by fixing bug #1816, but instead I discovered a different bug! 

>Go to a dataset admin page e.g. https://staging.gigadb.org/adminDataset/update/id/2782
> because #1816 was fixed there was no need to click the "Generate mockup" button, so instead I clicked the "Create/Reset Private URL" button
>See error (screenshot below) i.e. it redirects to a strange URL https://staging.gigadb.org/adminDataset/private/identifier/102520 and shows a white/blank screen

![image](https://github.com/gigascience/gigadb-website/assets/6037145/00e1e757-ac2c-4aef-bcf5-a7cd7cc79ce1)

I'm Fine if you would rather close this ticket as complete and open a new bug ticket for the scenario above.
