### ISSUE TITLE
Create shell script that generate sizes and checksum for dataset files in dropboxes

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1832]
## User story

>As a curator
>I want to be able to generate the sizes and the checksums of the dataset being reviewed
>So that we have all the files metadata available to be saved in GigaDB

## Acceptance criteria

>Given there files in dropboxes for a given dataset
>When I run a script available to me on the bastion server
>Then the file sizes for all the files of the dataset are saved in file "DOI.filesizes"
>And the MD5 checksums for all the files of the dataset are saved in file "DOI.md5"

### Usage

The script is to be run from the directory containing the files that need their checksum and size to be calculated and listed.

```
$ cd /share/dropbox/user116
$ /usr/local/bin/calculate_checksum_sizes 200007
```

### bastion scripts path

* /usr/local/bin/post_upload, 
* /usr/local/bin/dataset_upload, 
* /usr/local/bin/dataset_reset, 
* /usr/local/bin/calculate_checksum_sizes 

### sudoers list

Update in `users_playbook.yml`, the task " Add curator to sudoers" to allow sudo access to those scripts:

* /usr/local/bin/post_upload, 
* /usr/local/bin/dataset_upload, 
* /usr/local/bin/calculate_checksum_sizes

**Comment by kencho51** [comment]
Close as completed in https://github.com/gigascience/gigadb-website/pull/1842
