### ISSUE TITLE
Files metadata console containers built using gitlab-config-live-build.yml are tagged with "staging"

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1833]
**Describe the bug**
Files metadata console containers built using `gitlab-config-live-build.yml` have `staging` tag - see line 3 in [gitlab-config-live-build.yml](https://github.com/gigascience/gigadb-website/blob/develop/gigadb/app/tools/files-metadata-console/gitlab-config-live-build.yml). This means that the `gitlab-config-live-deploy.yml` script can only deploy old `live` Files metadata console containers or it will fail if there are no files metadata console images with `live` tag.

**Expected behavior**
I need to be able to download a `live` Files metadata console image with the latest code from the bastion server in order to update file sizes in database using information in $doi.filesizes files in S3 bucket.

**Comment by rija** [comment]
fix is in PR #1781
