### ISSUE TITLE
Date format on Manage Datasets Admin pages

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1837]
## User story

>As a curator
>I want the date format to be unambiguous and reflects how dates are saved in the page.
>So that it is not confusing 

## Acceptance criteria

>Given I am on any GigaDB Dataset Admin form
>When I look at "Fair Use Policy", "Publication Date" & "Modification Date" or any other date field
>Then I want to see and enter it in the format yyyy-mm-dd

>Given I am on any GigaDB Dataset Admin form
>When I update the field either manually typed, 
>Or I click on the day in the pop up calendar. 
>Then the date is entered in the box as we would like it, in the format  yyyy-mm-dd (e.g: 2017-05-21)

>Given I am on any GigaDB Dataset Admin form
>When I look at "Fair Use Policy", "Publication Date" & "Modification Date" or any other date field
>Then I should be able to scroll back to earlier months within the calendar date picker.

This is particularly useful at the beginning of the month when I might want to choose e.g. 30-Apr 

>Given I am on any GigaDB Dataset Admin form
>When I look at "Fair Use Policy", "Publication Date" & "Modification Date" or any other date field
>Then I can see example below each fields saying "Format: yyyy-mm-dd"

## Additional Info
![Screenshot 2024-05-01 at 11 38 17](https://github.com/gigascience/gigadb-website/assets/1359170/40d154c0-b171-41c4-836d-5c304b38b2fb)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by tuli** [comment]
![Screenshot 2024-05-01 at 11 39 46](https://github.com/gigascience/gigadb-website/assets/1359170/2429c40b-76c3-48a1-aab2-f517ca643f4b)


This screen shot is better, I can't see how to remove the one I added above.

**Comment by tuli** [comment]
I am not sure whether this needs a new ticket. 
I am trying to select a date 2 weeks from today for the Publication Date but I cannot see any month other than the current one (May). I can work around by manually changing it in the box, but I think I should be able to see other months. 
![Screenshot 2024-05-30 at 11 08 50](https://github.com/gigascience/gigadb-website/assets/1359170/8fdfe991-c810-425f-85cc-fee2f3cda203)

**Comment by only1chunts** [comment]
@luistoptal please can you take a look at this?

**Comment by luistoptal** [comment]
@only1chunts @tuli 
The datepicker formatting should be updated in #1939

As for the otther issue (I assume in Safar), it looks like arrow buttons are missing, I will review how to fix this
![image](https://github.com/gigascience/gigadb-website/assets/143437854/eeb27c30-9ece-40e9-aafb-5f23113c14f7)

Update: added year and month dropdowns
![image](https://github.com/gigascience/gigadb-website/assets/143437854/633e73da-69e9-4bc1-90a7-c0845068e95d)

**Comment by only1chunts** [comment]
its not just safari, I use chrome and the arrows are missing for me too:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/0d87c66a-5b33-4301-bb01-d270700c560d)

Although if you hover over the area where they are meant to be they are actually present, you just cant see them!

**Comment by luistoptal** [comment]
@only1chunts Im having issues reproducing it, can you let me know what OS are you using and what browser version?

**Comment by only1chunts** [comment]
OS = Windows 10Pro Version 22H2
Browsers:
Google Chrome Version 126.0.6478.127 (Official Build) (64-bit)
Microsoft Edge Version 126.0.2592.61 (Official build) (64-bit)
The issue exists in both live and staging, it was also reported first by @tuli who uses a Mac of some sort, so its not OS or browser dependant.

**Comment by tuli** [comment]
My MacOS is Ventura 13.4

**Comment by luistoptal** [comment]
@only1chunts I noticed your screenshot seems to be from an unupgraded version which does not have the last changes. Will need to wait for this update to be deployed (unless you are able to deploy the work branch locally)

**Comment by only1chunts** [comment]
ah, I see. the PR for this fix is still in draft, hence its not on the deployed versions yet. OK we'll wait and see what it looks like in the next (future) release when the PR gets added. Thanks, Chris.
