### ISSUE TITLE
Dataset files table - number of files and navigation options messed on the mockup page on smaller screen

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1843]
**Describe the bug**
Unless the browser window is a certain width, the dataset does not show the number of files and the navigation options (1,2, Next, Last etc) are not user friendly.

**To Reproduce**
1. Go to https://gigadb.org/dataset/102523/token/xmiGZI-YcUdE0GXb
2. Click on Files tab
3. Scroll down to the bottom
4. Number of files is not displayed and the navigation options are hidden under the scroll bar

**Expected behavior**
The number of files should be displayed and the navigation options should be clearly visible.
NOTE: if I refresh the browser everything is fine. If I make the window wider it is also fine, but this would not be clear to users.

**Screenshots**

Showing issue when browser window is too narrow:

![Screenshot 2024-05-03 at 10 13 57](https://github.com/gigascience/gigadb-website/assets/1359170/4cfe8996-28bb-4b0f-b427-62122b3e9cd1)
-------
Showing No issue when browser window is wide enough:
![Screenshot 2024-05-03 at 10 14 09](https://github.com/gigascience/gigadb-website/assets/1359170/dfa2dd08-8c09-4633-9fa6-b9337e970b5b)

what it should and shouldn't look like

**Desktop (please complete the following information):**
 - OS: Mac ventura 13.4
 - Browser: safari
 - Version 16.5

**Additional context**

**Comment by luistoptal** [comment]
@tuli, I'm adding some top spacing to address the issue. Please note that the website currently lacks responsiveness; the layout breaks on mobile. As far as I know, optimizing for mobile hasn't been prioritized yet.
