### ISSUE TITLE
Post upload script not updating all files in datasets with file sizes and md5 values 

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1845]
@only1chunts reported that the post upload script was not updating all files with their file sizes in dataset 102522. And no md5 values at all were added dataset 102522 files.

After cross-referencing file names in dataset 102522 with the information stored for this dataset in the database, discrepancies were found with these two pieces of data. This means that if a dataset has a file on the file server and its corresponding entry has a different file name in the database then it will not be updated with a file size or md5 value.

There is also a suspicion that the md5 update functionality might break off from its loop when it encounters a file within a dataset that is not listed in the database.

**Comment by only1chunts** [comment]
Discrepancies between filenames in server vs spreadsheet is an issue, and if there is a way to test and report those back to curators that would be great!
Regarding the issue with the non-addition of MD5 values to all files, please take a look at 102526. You ran the post-upload script and it only added ~30% of the MD5 values to the database despite there being no file name discrepancies (according to [your report](https://docs.google.com/spreadsheets/d/1PAxCJHzgFD-ixX19wxlp6J3NKJQiYDROmlmWq8mxVHY/edit#gid=0)).

**Comment by pli888** [comment]
> Regarding the issue with the non-addition of MD5 values to all files, please take a look at 102526. You ran the post-upload script and it only added ~30% of the MD5 values to the database despite there being no file name discrepancies (according to [your report](https://docs.google.com/spreadsheets/d/1PAxCJHzgFD-ixX19wxlp6J3NKJQiYDROmlmWq8mxVHY/edit#gid=0)).

The reason why only a subset of md5 values were added into dataset 102526 is because there is a file named `102526.md` listed 90 lines down in the `102526.md5` file. The post upload tool could not find `102526.md` in the database so it stopped adding the md5 values for the remaining files in dataset 102526.

If you look in the 102526 directory on CNGB file server, there is a file called `102526.md` which got copied over into Wasabi.

Presuming `102526.md` should not be there, I have removed its entry from `102526.md5` and re-ran the post upload script. All files for dataset 102526 should now have md5 values.

I have also updated the md5 functionality in the post upload script so that it will ignore files listed in $doi.md5 that it cannot find in the database. There is also a feature in the post upload tool to generate a processing report. These fixes will be in the next release.

**Comment by only1chunts** [comment]
Thats a useful addition. Does the processing report include a list of file names that are present in the wasabi server that are not in the spreadsheet/database, and vice versa?

**Comment by pli888** [comment]
This bug was observed with dataset 102532 and its `102532.filesizes`. It looks like this problem only occurs with files whose filenames is a substring of another file.

This dataset 102532 also has problems updating md5 checksum values using `102532.md5`. This problem occurs with files whose filenames are identical to other files in the dataset but reside in a different directory. The reason for this is that the `FilesCommand` class only uses the filename, but not the whole file path, to search for a file object to update. It can update the wrong file object if a dataset has more than one file with the same filename.

**Comment by kencho51** [comment]
Close as done in #1934
