### ISSUE TITLE
Datasets Admin page - image metafields - changes not saved

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1848]
**Describe the bug**
Tried to update Source, License and Photographer but changes were not saved.

**To Reproduce**
1. Go to https://gigadb.org/adminDataset/update/id/2789
2. Update Source, License and Photographer fields
3. Scroll down to Save
4. See that changes have not been saved. 

**Expected behavior**
That changes are saved.

**Screenshots**

**Desktop (please complete the following information):**
OS: Mac ventura 13.4
Browser: safari
Version 16.5

**Additional context**
If I upload an image as well as updating the image metafields then I find all the changes are saved.

**Comment by tuli** [comment]
https://gigadb.org/adminDataset/update/id/2821

This morning I updated the image (Image status - choose file) and the Tag. Both changes were saved. Good.
Later I needed to update just the Tag. This change was not saved. Not good.
I uploaded the image again as well as the Tag and then the Tag was saved. Good.

I have been able to do the updates I wanted, but it's a bit clunky.

**Comment by alli83** [comment]
> https://gigadb.org/adminDataset/update/id/2821
> 
> This morning I updated the image (Image status - choose file) and the Tag. Both changes were saved. Good. Later I needed to update just the Tag. This change was not saved. Not good. I uploaded the image again as well as the Tag and then the Tag was saved. Good.
> 
> I have been able to do the updates I wanted, but it's a bit clunky.

While working on it, I noticed some inconsistencies which I am currently addressing. Thank you for the update and for highlighting these issues!

**Comment by pli888** [comment]
Closing as fixed in PR #1916
