### ISSUE TITLE
add column description to sample table

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#185]
A request from a user:

> "Regarding the [sample] table contained in the [dataset] page we would like to have further detailed information about each column since we cannot interpret the correct meaning of some columns (common name, scientific name, ect.), can you provide us a description for such columns?"

This seems fair, we should add a (i) information icon in the headers that users can hover over to get a popup of the column descriptions.

**Comment by kencho51** [comment]
Hi @pli888 whats the `information icon` look like? Any example that I can look for it?

**Comment by only1chunts** [comment]
Good point @kencho51 ! just looking around our website the only place we actually use the (i) icon is in the wizard pages, elsewhere we've just added hover over pop-ups to explain some things. So perhaps for consistency on the website we should just use the hover-over pop-up text. Then at some point update the submission wizard to match, what do you think? The alternative is to add (i) icons to various other places!
Do you have the descriptions of the columns yet, they are not in this ticket, so I'll add them: 
```
File Name - The name of the file. Click header to sort by A-Z/Z-A. 
Description - Short description of file contents. Click header to sort by A-Z/Z-A. 
Sample ID - Name or ID of sample used to generate this file.
Data Type - The type of data in the file, see [help](http://gigadb.org/site/help#vocabulary) page for definitions of individual data types.  Click header to sort by A-Z/Z-A. 
File Format - The format of the file, see [help](http://gigadb.org/site/help#vocabulary) page for definitions of individual file formats. Click header to sort by A-Z/Z-A. 
Size - The size on disk of the file. Click header to sort by A-Z/Z-A. 
Release Date - Date of release of the file, see the history log for details of any changes made after initial release date. Click header to sort by A-Z/Z-A. 
File Attributes - Additional information about the file presented as Key:Value pairs. 
Download link - The direct link to the files server location.
```
Note- the link to the data-type and file-format vocaularies page may need to be changed when we update the help pages since the current public list of terms is out of date and incomplete!

**Comment by kencho51** [comment]
Hi @only1chunts Which table do you want to put the hover over pop-up text? The description you gave fits the `Files table`, not the `Sample table`. If you want pop-up text for both tables, please provide the description for `Sample table` as well.

**Comment by only1chunts** [comment]
Sorry! yes please on both tables, and the funding table:
**Sample Table:**
```
Sample ID - User-specified name or identifier of the sample object. Note: a DNA sample and an RNA sample from the same donor are classed as two separate samples.
Taxonomic ID - Species taxonomy ID of the sampled species, we currently use the NCBI taxonomy as the source of this identifier. 
Common Name - A well recognized commonly used name of the species,  usually this is in synonym held in the NCBI taxonomy for the tax ID provided
Genbank Name- The preferred display name used by NCBI taxonomy for the tax ID provided
**Scienfic** Name - The scientific binomial name of the species, usually this is in direct accordance with the NCBI taxonomy ID provided.
Sample Attributes - This is a list of Key:Value pairs, where the Keys are from our Attributes list, and the Value is the specific value for the sample. See our metadata guide for the Attributes list with definitions of all available attributes.
```
Please can we also update the typo in **Scienfic** -> Scientific

**Funding Table:**
```
Funding body - The name of the funding agency providing funding. Where possible this should be from the FundRef list of funding bodies (https://www.e-sciencecentral.org/funder/).
Awardee - The name of the person responsible for getting the award.
Award ID - The grant or contract number of the project that sponsored the effort.
Comments - Some agencies have multiple award programs through which they distribute funding, if appropriate that information can be added here.
```

**Comment by pli888** [comment]
@only1chunts You can take a look at this functionality at https://gigadb-staging.gigatools.net/dataset/100253.

**Comment by only1chunts** [comment]
Hi,
That appears to work as expected, thanks. There is a typo I spotted (that I made above, sorry!) Common name description should be:
Common Name - A well recognized commonly used name of the species, usually this is a synonym held in the NCBI taxonomy for the tax ID provided.
