### ISSUE TITLE
File attribute (BUSCO v5 result) truncated

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1850]
**Describe the bug**
The value of the file attribute BUSCO v5 result is truncated 

**To Reproduce**
1. Go to https://gigadb.org/dataset/102529/token/WAoU5pLiHitSMX8-
2. Click on the Files tab
3. Locate the file name 'cobia.male_HIFI_assembly.fasta.gz and then go to the File Attributes column
4. Value is 'BUSCO v5 result: C97.4%[S' 
The value in the spreadsheet is 'BUSCO v5 result: C:97.4%[S:96.7%,D:0.7%],F:1.1%,M:1.5%,n:3640'

**Expected behavior**
It should be 'BUSCO v5 result: C:97.4%[S:96.7%,D:0.7%],F:1.1%,M:1.5%,n:3640'

**Screenshots**
One of the spreadsheet, one of GigaDB landing page and one of the file in Admin 
![Screenshot 2024-05-10 at 15 31 36](https://github.com/gigascience/gigadb-website/assets/1359170/922b7b92-e0e2-46c5-a434-4daced80e923)
![Screenshot 2024-05-10 at 15 31 51](https://github.com/gigascience/gigadb-website/assets/1359170/607f361f-1759-4ff6-b4b3-5a29f8ec19f7)
![Screenshot 2024-05-10 at 15 34 41](https://github.com/gigascience/gigadb-website/assets/1359170/f02ab8f2-8060-4d4c-ad38-fa378da62dff)

**Desktop (please complete the following information):**
OS: Mac ventura 13.4
Browser: safari
Version 16.5

**Additional context**
This was also an intermittent problem when Jesse did the upload.
I can fix this myself via Admin, but won't do so until you've seen the bug.

**Comment by rija** [comment]
We have a workaround in place, using the "Edit" button in the Admin form, so closing this for now.
