### ISSUE TITLE
Sometimes, saving the form redirect to the admin list of datasets

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1854]
**Describe the bug**

For a couple of upload status, saving the form redirects to the admin list of datasets unstead of staying on the form

**To Reproduce**
1. Go to ' /adminDataset/update/id/1835'
2. Change the upload status to "Private" or "Author review" or "Submitted"
3. Save the form
4. you are redirected to the dataset list

**Expected behavior**

You stay on the form

**Additional context**
spotted while fixing bug #1816

**Comment by alli83** [comment]
which upload statuses should remain on the form page?

**Comment by rija** [comment]
When the user in on the form and click save, it should stay on the form irrespective o the page type or the upload status.

**Comment by tuli** [comment]
This issue seems to exist any time the page is saved, not just changing the upload status.

**Comment by pli888** [comment]
Closing this ticket because there is PR #1925 to fix this problem.
