### ISSUE TITLE
Selecting "Published" and saving the form doesn't immediately remove the links, needs to fully reload the page

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1855]
**Describe the bug**

**To Reproduce**
1. Go to '/adminDataset/update/id/1835'
2. Select "Published" and save the form
3. The mockup link don't disappear immediately, need to the reload the form for that to happen

**Expected behavior**
Upon saving the form, the mockup link should disappear.

**Additional context**

Spotted while fixing bug #1816

**Comment by only1chunts** [comment]
not entirely what this issue is about, but I've never seen anything wrong with the mockup link being present in a published dataset, so closing this as a non-issue
