### ISSUE TITLE
Change layout of File Attribute updates

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1858]
## User story

>As a curator
>I want to see a clean intuitive design when I make File Attribute updates
>So that its simple to use without confusion

## Acceptance criteria

>Given I am on a File admin page (e.g. https://gigadb.org/adminFile/update/id/96250)
>When I click the "Edit" button on an existing file attribute
>Then the display of the Save options is not confusing.

## Additional Info
Currently when you try to Edit an existing File Attribute there are TWO "Save" buttons with different actions, one will save ONLY the Attribute changes, the other will save ONLY the non-attribute information.

Possible solutions would be:
1 - to rename the button that only saves the attribute update
2 - make the full page Save button perform both Save actions
3 - Hide/remove the full page save button as soon as the "edit" attribute button is clicked.

I think my preference would be 2.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by luistoptal** [comment]
> 1 - to rename the button that only saves the attribute update

I've done this

> 2 - make the full page Save button perform both Save actions

this is more of a backend change @rija

**Comment by luistoptal** [comment]
@only1chunts @rija I updated the UI for this button as indicated in this PR https://github.com/gigascience/gigadb-website/pull/1931, however if the save button needs to also update the attributes, then I believe it requires changes in the controller itself

**Comment by luistoptal** [comment]
@rija @only1chunts this is fixed once https://github.com/gigascience/gigadb-website/pull/2082 is merged as it presents the edit attr form as a modal
