### ISSUE TITLE
ORCID - a better way to look up

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#186]
Would it be possible to have a better way to search for orcid IDs? I currently search, one by one on the website. 
It would be good to be able to enter a list of names and to be given a list of possible IDs in return.

Orcid do provide publicly available files: https://figshare.com/articles/_/5479792

**Comment by only1chunts** [comment]
closing this as we shouldn't be looking peoples ORCIDs up, they should be providing them themselves and we have tickets to facilitate that with the gigadb user account and submission wizard
