### ISSUE TITLE
Remove user suffix from wasabi profile and improve curators docs

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1861]
The Users Ansible playbook creates an rclone configuration in user home directory with the profile of pattern "[wasabi_WasabiUserName]".
The part after the underscore is unnecessary, complicates the user of rlcone that requires typing the profile name, and make documentation more complex to comprehend.
We  only need "[wasasbi]" as profile name.

The documentation will need to be updated to reflect the change

**Comment by kencho51** [comment]
After the PR #1771 has been merged, the suffix of the wasabi endpoint will be removed, and the rclone can be executed as below:

```
[lily@ip-10-99-0-212 ~]$ rclone lsd wasabi:gigadb-datasets/
           0 2024-08-06 02:13:45        -1 CI
           0 2024-08-06 02:13:45        -1 dev
           0 2024-08-06 02:13:45        -1 live
           0 2024-08-06 02:13:45        -1 staging
[lily@ip-10-99-0-212 ~]$ rclone lsd wasabi:gigadb-datasets/dev/pub/10.5524
           0 2024-08-06 02:13:40        -1 100001_101000
           0 2024-08-06 02:13:40        -1 102001_103000
           0 2024-08-06 02:13:40        -1 200001_201000
[lily@ip-10-99-0-212 ~]$ rclone lsd wasabi:gigadb-datasets/dev/pub/10.5524/102001_103000
           0 2024-08-06 02:14:44        -1 102484
           0 2024-08-06 02:14:44        -1 102499
           0 2024-08-06 02:14:44        -1 102523
```

And the doc at here: https://sites.google.com/gigasciencejournal.com/giganet/gigadb/curation/gs-curation-step-by-step will be changed from:
```
$ rclone copy . wasabi_ChrisH:gigadb-datasets/live/pub/10.5524/102001_103000/102524
```
to: 
```
$ rclone copy . wasabi:gigadb-datasets/live/pub/10.5524/102001_103000/102524
```
