### ISSUE TITLE
Change configuration location of the FTP server

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1865]
The FTP server on files.gigadb.org has its configuration (password files and password vault) in the incorrect location for our infrastructure.
They should be in `/share/config/pure-ftpd`, but currently they are in `/home/centos/app_data/pure-ftpd`

the impact of the issue is:
* we cannot make available to curators the make_dropbox bulk dropbox creation script on bastion server
* It impedes these tickets of the File Upload Wizard work: 
  * #604 
  * #1680

**Comment by kencho51** [comment]
Close as fix in PR #1943
