### ISSUE TITLE
phpcs-security-audit-sast job is failing on Gitlab pipeline

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1867]
The `phpcs-security-audit-sast` job is failing on Gitlab pipeline in the security and conformance stage. The error message is that this functionality was deprecated in GitLab 16.8 and [removed in GitLab 17.0](https://docs.gitlab.com/ee/user/application_security/sast/).

Information on how to migrate phpcs-security-audit coverage to Semgrep-based analyzer in Gitlab is provided [here](https://gitlab.com/gitlab-org/gitlab/-/issues/364060).

**Comment by rija** [comment]
I think the key comment to try out is this one:
https://gitlab.com/gitlab-org/gitlab/-/issues/364060#note_1271000018

**Comment by kencho51** [comment]
Close as implementation in PR #2063
