### ISSUE TITLE
Extract stages of Postupload script into separate scripts

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1872]
## User story

>As a curators  
>I want the flexibility to run the part of post upload script separately
>So that I can rerun any single part in any order based to the current state of a particular dataset workflow

## Acceptance criteria

>Given I need to generate the readme file for a dataset  
>When I run "readme_generator" script
>Then a readme file for the dataset is created in the userbox
>And the readme file is upload to Wasabi

>Given I need to update the MD5 checksum and file size in the database 
>When I run "files_meta_to_db"
>Then the MD5 checksum and file size for all the files in the dataset are update in the database

## Additional Info

* [x] #1882
* [x] #1883
* [x] #1884

Depends on the following issue to be done:
* [x]  #1840

consoles all file metadata operations into the files-metadata-console (as there are still operations done in Yii1 files command)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by only1chunts** [comment]
closing as i think this is now done
