### ISSUE TITLE
enable bastion to record individual file creator

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1873]
## User story
>As a curator
>I want to be able to see who created a particular file on the bastion server
>So that I have some aide-memoires as to who did what in the history of the dataset preparation

## Acceptance criteria
>Given I am on the bastion server (via SSH)
>When I ls -la the userbox directory (or anywhere else)
>Then the list of files includes the correct user ID of the user that created the file is shown

currently it looks like:

```
[chrish@ip-10-99-0-199 user1]$ ls -la
total 44
drwxr-xr-x.  7 centos centos 6144 May 20 17:50 .
drwxrwxr-x. 77 centos centos 6144 May 21 13:30 ..
drwxr-xr-x.  3 centos centos 6144 May 20 17:50 BAM
drwxr-xr-x.  2 centos centos 6144 May 17 03:12 FASTQ
drwxr-xr-x.  5 centos centos 6144 May 20 14:59 GitHub
-rw-r--r--.  1 centos centos 1071 May 17 03:45 LICENSE
drwxr-xr-x.  2 centos centos 6144 May 16 22:22 NanoCount
drwxr-xr-x.  8 centos centos 6144 Apr 27 06:44 NanoPlot
-rw-r--r--.  1 centos centos 9135 May 17 03:45 README.md
```

It always shows the user and group as "`centos`"
Even when I create a file whilst logged in as `chrish`

ideally it will show the files uploaded by the authors as the username of that person, in the example above that would be `user1` so if for example I had created the `README.md` file above that list would look more like this:
```
[chrish@ip-10-99-0-199 user1]$ ls -la
total 44
drwxr-xr-x.  7 centos centos 6144 May 20 17:50 .
drwxrwxr-x. 77 centos centos 6144 May 21 13:30 ..
drwxr-xr-x.  3 user1 centos 6144 May 20 17:50 BAM
drwxr-xr-x.  2 user1 centos 6144 May 17 03:12 FASTQ
drwxr-xr-x.  5 user1 centos 6144 May 20 14:59 GitHub
-rw-r--r--.  1 user1 centos 1071 May 17 03:45 LICENSE
drwxr-xr-x.  2 user1 centos 6144 May 16 22:22 NanoCount
drwxr-xr-x.  8 user1 centos 6144 Apr 27 06:44 NanoPlot
-rw-r--r--.  1 chrish centos 9135 May 17 03:45 README.md
```

## Additional Info

This is a "nice to have" item so should not be placed as high priority, and eventually it will become irrelevant when we have the File Upload Wizard fully functional.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
At the moment, the ownership is specified in the infrastructure definition (the terraform config for EFS) and it's flexible.
We need to research if there ways to work around that

**Comment by only1chunts** [comment]
lets close this as not required. It would still be a nice to have, but since its such low priority and the file upload wizard will negate the need anyway, lets just forget about it.
