### ISSUE TITLE
Fix: Please extend the log-in time for bastion server

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1896]
**Is your feature request related to a problem? Please describe.**
Currently, the log-in time is a few minutes, and it will log out automatically.

**Describe the solution you'd like**
Please extend the log-in time, I think 30 minutes will be good for us to work with.

**Describe alternatives you've considered**

**Additional context**

**Comment by rija** [comment]
Yannan is using iTerm to connect to the bastion and from China.

**Comment by rija** [comment]
We probably should tweak the sshd daemon to help with the issue:
* https://serverfault.com/a/19641/397195
*https://www.man7.org/linux/man-pages/man5/sshd_config.5.html

The `ClientAliveInterval` setting needs to be set to non-zero value (default is 0, and that's how our config is set currently) so the server sends a message to keep the connection alive.
Given it is Chinese network, the `ClientAliveCountMax` setting might need to be increase to be greater than 3 (the default).


Also we should install screen or tmux which are tools that allow users  session to persist even if they are disconnected, but that's should be done as part of #1904

**Comment by rija** [comment]
you can use tmux as a workound. It will available, once PR #1996 is merged
