### ISSUE TITLE
Datasets in carousel on GigaDB home web page

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#19]
When you open the [GigaDB](http://gigadb.org/site/index) website, the datasets that are displayed in the carousel are old having been published in 2012 and 2011, for example the parrot and penguin datasets.

@only1chunts: It would be better if the most recent datasets are shown in the carousel?

**Comment by only1chunts** [comment]
This was something that was brought up with the development company when it was made, but they wanted to charge extra for it as it was "out of scope" of the original agreement. This is probably a fairly easy fix so we can assign this ticket to the new dev when he starts.
The datasets to show should be the most recently released ones first, scrolling around to older ones (I believe its only a max of 9 datasets shown in the carousel anyway.

**Comment by pli888** [comment]
@jessesiu Since you are the most experienced with the GigaDB code, can you think about how to fix this problem with the carousel and reply with a short list of the programming steps for the new developer to do please?

**Comment by jessesiu** [comment]
I find it's the sql language problem, add the order by part , and solve it.

**Comment by only1chunts** [comment]
Confirmed - fixed in jessesiu/gigadb-website/tree/fix/bugs branch
