### ISSUE TITLE
Install commonly use software to bastion server

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1904]
## User Story

>As a curator
>I want command lines tool useful to my job to be installed on the bastion server
>So that I can perform my job efficiently

## Acceptance criteria

>Given I need to work on the bastion server
>When I login 
>Then the tool git is available to me

>Given I need to work on the bastion server
>When I login 
>Then the tool wget is available to me

**Comment by rija** [comment]
we should add to that list:
* emacs
* screen
* tmux

**Comment by rija** [comment]
this is done in PR #1996

**Comment by only1chunts** [comment]
Has this been deployed yet? I just tried to use emacs in the live bastion and it didn't work.
