### ISSUE TITLE
Improve and fix onboarding for new developers joining the team

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1908]
* [ ] Undocumented variables needs to be added to Gitlab variables
* [ ] env-sample and secrets-sample should be more prominent and better documented
* [ ] Tips for picking up tickets needs added in CONTRIBUTING
* [ ] Review accuracy of developers docs, especially `variables.md`,  `SETUP_CI_CD_PIPELINE.md`, and `SETUP_AWS_ENVIRONMENTS.MD`
* [ ] Delete outdated docs and sections of docs

**Comment by kencho51** [comment]
Close as done in PR #1961
