### ISSUE TITLE
102531 Dataset mockup page - Files - Error trying to go to Next, Last or e.g page 2

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1909]
**Describe the bug**
The dataset has 11 files. Default is to display 10. When I try and view the 11th file by pressing either Next, or Last or entering page 2 in the 'go to page' box I get a 400 error (invalid request). The only way to view the 11th file is by changing the number of files in Table settings. 

**To Reproduce**
1. Go to https://gigadb.org/dataset/102536/token/SR-zdMUKS366HFg4
2. Scroll down to the bottom.
3. Click Next or Click Last or enter select in the Go to page box 
4. See error: 400 - invalid request, or for the Go to Page error is that it takes you to the life site and shows that error (can't display DOI etc) 

**Expected behaviour**
I expect to go to the next page of files, which in this case will be 11th file of 11 total.

I can see this file if I select 20 under Table Settings

**Screenshots**
![Screenshot 2024-06-03 at 15 39 07](https://github.com/gigascience/gigadb-website/assets/1359170/dbea0a43-36a1-4801-a2ba-aa2a5f12afd8)
![Screenshot 2024-06-03 at 15 39 19](https://github.com/gigascience/gigadb-website/assets/1359170/f36fdc01-ee65-4c8c-9369-fb167a53662d)

**Desktop (please complete the following information):**
 - OS: Ventura 13.4
 - Browser Safari
 - Version 16.5

**Comment by rija** [comment]
Hi @tuli 
I believe this is the same issue as #1812
I've implemented a fix for it yesterday but it's not released yet

**Comment by rija** [comment]
This is fixed in PR #1907
