### ISSUE TITLE
reset password page broken

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#191]
the reset password page presents an error when you try to reset your password:
http://gigadb.org/user/reset/username
![screenshot_13](https://user-images.githubusercontent.com/6037145/40120051-2e601d8c-5916-11e8-891e-c32be142a72c.png)

**Comment by jessesiu** [comment]
It's the captcha error, we change the captcha method but this page didn't

![2018-05-17 11 23 26](https://user-images.githubusercontent.com/1147873/40155220-092f3b7e-59c5-11e8-9738-69ab168bd187.png)

**Comment by jessesiu** [comment]
Update it on the production server

**Comment by only1chunts** [comment]
all works on production server now thanks.
in pull request #203
