### ISSUE TITLE
Dataset Admin page - Publication date pop up only shows current month 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1910]
## User story

>As a curator
>I want to be able to easily select a date other than one in the current month
>So that I don't need to enter it manually

## Acceptance criteria

>Given conditions  : Adding the Publication Date to a Dataset via the Dataset Admin page
>When event  : I click in the date field 
>Then I would like a pop up that allows to scroll to all the months.

## Additional Info
I am sure I raised this as an issue last week, but I cannot find it. I apologise if this gives you deja vu. 

nb. I am able to enter whatever date I want manually so this issue does not block work. It was more of an issue last week as we were at the end of May and I wanted to enter dates in June.

![Screenshot 2024-06-03 at 16 53 07](https://github.com/gigascience/gigadb-website/assets/1359170/05b83fba-d689-4d78-84b2-3b267118902d)

the arrows to navigate to previous and next month are there but they are invisible.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by luistoptal** [comment]
@tuli is this still an issue?
