### ISSUE TITLE
Errors when trying to save multiple changes at the same time - File update 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1912]
**Describe the bug**
I need to make the same update to a number of files in a dataset. It is most efficient to open a browser tab for each file, perform the update and Save. This leads to a number of files being updated at the same time, which has caused errors. It's taken me an hour (so far) to update 12 files. 

**To Reproduce**
1. Go to https://gigadb.org/adminFile/admin
2. Query for DOI 102531, filter for File Name "bed.gz" = 12 files.
3. Open a new tab for each file by right mouse clicking on then pen under Actions.
4. Go to each tab e.g. https://gigadb.org/adminFile/update/id/544851 make the change and Save. This means multiples files are being saved at the same time. 
5. See either "503 service temporarily unavailable" or "Safari can't open page" error.

**Expected behavior**
I would like the changes to be saved.

**Screenshots**
![Screenshot 2024-06-04 at 09 51 03](https://github.com/gigascience/gigadb-website/assets/1359170/67f0df30-aa26-46b1-b720-5f1aa751ebc3)
![Screenshot 2024-06-04 at 09 44 08](https://github.com/gigascience/gigadb-website/assets/1359170/2c262b77-54fc-4373-9301-bb6caf942231)
![Screenshot 2024-06-04 at 09 41 55](https://github.com/gigascience/gigadb-website/assets/1359170/bcfcb1a8-d357-4dc6-8cc5-b36070651ce2)

**Desktop (please complete the following information):**
 - OS: venture 13.4
 - Browser safari 
 - Version 16.5

**Additional context**
This is a very common way for curators to perform updates.  Usually to Files or Samples.

**Comment by rija** [comment]
There is PR #1929 ready for the fix, so closing
