### ISSUE TITLE
fix missing $is_no_image property missing

### ISSUE THREAD

**Issue by alli83** [gigascience/gigadb-website#1917]
**Describe the bug**
see https://github.com/gigascience/gigadb-website/issues/588#issuecomment-1980004821
$is_no_image property is missing 

**To Reproduce**
1. Go to '/adminDataset/admin'
2. Click on 'create Dataset'
3. Fill in the required fields
4. Click on 'create'
5. Switch to the user for whom it was created
6. Click on 'your uploaded Datasets
7. Click on 'update'
9. See error

**Expected behavior**
view the form

**Screenshots**
 https://github.com/gigascience/gigadb-website/issues/588#issuecomment-1980004821

**Desktop (please complete the following information):**
 - Browser safari / firefox

**Comment by pli888** [comment]
Closing this ticket because there is PR #1918 fixing this issue.
