### ISSUE TITLE
The “Dataset Size” is 0 KB on the admin page after the uploading has processed

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1920]
**Describe the bug**
The “Dataset Size” is 0 KB on the admin page after the uploading has processed.

**To Reproduce**
1. Go to https://gigadb.org/adminDataset/update/id/2801
2. Scroll down to "Dataset Size"
3. See the data is "0".

**Expected behavior**
The Dataset size has been calculated and has the value in the form.

**Screenshots**
![image](https://github.com/gigascience/gigadb-website/assets/112144621/d458406b-a968-4c24-b99a-1c2b7615e25d)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 125.0.6422.142

**Additional context**

**Comment by only1chunts** [comment]
This is covered by ticket #1093 which is part of the next Milestone to be worked on.
