### ISSUE TITLE
Wasabi accounts for curators

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1921]
## User story

>As a curator
>I want to be able to see what is in Wasabi via a GUI interface
>So that I can easily check whats been uploaded

## Acceptance criteria

>Given I am curator
>When I connect to Wasabi using FileZilla (or some other GUI tool for cloud storage management)
>Then I am able to see the files hosted in the various datasets in Wasabi storage

## Additional Info
Currently I think its only me (ChrisH) that has a Wasabi account, I can use that to access the files using "S3Browser", but the same credentials do not allow me to view the files using FileZila?

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by pli888** [comment]
I followed these [instructions](https://knowledgebase.wasabi.com/hc/en-us/articles/115001754172-How-do-I-use-FileZilla-with-Wasabi) and was able to access the bucket using FileZilla Pro. When configuring a Wasabi Provider, you should add the `ap-northeast-1` region with `s3.ap-northeast-1.wasabisys.com` endpoint. The Host is `s3.ap-northeast-1.wasabisys.com` when adding a new site using the Site Manager window.

**Comment by only1chunts** [comment]
yes those instructions enable me to log onto Wasabi using FileZilla:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/afa50599-5245-44ba-ac8e-e3173c440728)
However, they do not allow me to actually see inside any of the directories, so I cannot even see in "gigadb-dataset" directory:
![image](https://github.com/gigascience/gigadb-website/assets/6037145/5c0f34e2-e7ca-4dcb-a42f-27c9413d5ba6)

It would appear that is because it only works for Root users :-(

> FTP feature can be used only by the root user

Hey ho, thats not going to work then. I've been over the use of rclone with the other curators again and we're OK to use the ls command in there to check files have been transfered, so I'll close this ticket as not required.
Thanks for your reply.
