### ISSUE TITLE
Enable upload tool to ingest version 19 excel spreadsheets

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1923]
## User story

>As a developer  
>I want the upload tool to be able to ingest version 19 excel spreadsheets into my dev GigaDB environment
>So that I can manually check upload of new excel spreadsheets in my local GigaDB installation

## Acceptance criteria

>Given I have an example version 19 excel spreadsheet containing metadata specific to version 19
>When I apply the upload tool on the example version 19 excel spreadsheet  
>Then the example version 19 excel spreadsheet is ingested into my dev GigaDB database
>And I can see the admin dataset page associated with the example version 19 excel spreadsheet

## Additional Info

This work is related to PR #1890 updated upload spreadsheet version. It will involve updating `data/dev/*.csv` files so that they contain new sample attributes and file types that are now found in the version 19 excel template file.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by only1chunts** [comment]
@pli888 can this ticket be closed?

**Comment by only1chunts** [comment]
since v19 is being ingested by the tools, I'm closing this ticket
