### ISSUE TITLE
Unable to update License, Photographer and Source - Dataset Admin page

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#1928]
**Describe the bug**
When I 'save' changes to License, Photographer and Source they are not saved.

**To Reproduce**
1. Go to https://gigadb.org/adminDataset/update/id/2804
2. Within Image metafields, update Source to Arıkan & Muth, 2024, update License to CC-BY and update Photographer to Arıkan & Muth, 2024
3. Scroll down and hit Save 
4. See the change has not been saved. 
5. Try just chaning License, still not saved. Asked another curator. 

**Expected behavior**
I expect the changes to be saved, or an error to be given if there is something preventing the save.

**Screenshots**
![Screenshot 2024-06-14 at 17 30 16](https://github.com/gigascience/gigadb-website/assets/1359170/8babb514-1c78-43dd-b784-0b489a69bafb)

**Desktop (please complete the following information):**
 - OS: ventura 13.4 
 - Browser safari 
 - Version 16.5

**Additional context**
It's not a blocker for public release, but does need fixing.

**Comment by pli888** [comment]
This issue is fixed in PR #1916 so closing this ticket.
