### ISSUE TITLE
Some external links are not opened in new tab

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1948]
issue: I just noticed (I should have spotted that in previous PR) , that some external links don't open in a new tab.
e.g: http://gigadb.gigasciencejournal.com/dataset/100020

On that page, the link "http://foxtailmillet.genomics.org.cn/" under the "Genome browser" section open in the same tab
all the external links in the footer open in the same tab

**Comment by only1chunts** [comment]
the related manuscript link also opens in the same tab, e.g. on the same dataset as Rija mentioned above the bold link below opens in the same window:
Read the peer-reviewed publication(s):
Zhang, G., Liu, X., Quan, Z., Cheng, S., Xu, X., Pan, S., Xie, M., Zeng, P., Yue, Z., Wang, W., Tao, Y., Bian, C., Han, C., Xia, Q., Peng, X., Cao, R., Yang, X., Zhan, D., Hu, J., … Wang, J. (2012). Genome sequence of foxtail millet (Setaria italica) provides insights into grass evolution and biofuel potential. Nature Biotechnology, 30(6), 549–554. https://doi.org/10.1038/nbt.2195 **(PubMed:[22580950]([](http://www.ncbi.nlm.nih.gov/pubmed/22580950)))**

**Comment by luistoptal** [comment]
I think the last refactor of the layouts broke this, it would probably be a good idea to merge this PR first as it is the second chunk of refactoring for the layouts: https://github.com/gigascience/gigadb-website/pull/1913

**Comment by rija** [comment]
> I think the last refactor of the layouts broke this, it would probably be a good idea to merge this PR first as it is the second chunk of refactoring for the layouts: #1913

Hi @luistoptal,
Ok, I get what you are saying, I'll review PR #1913 first because it's the required follow-up to already merged PR #1911 and it is a dependency for this ticket we are currently commenting on.

**Comment by luistoptal** [comment]
@rija this seems to have been fixed by now by some of the recently merged PRs

**Comment by rija** [comment]
> @rija this seems to have been fixed by now by some of the recently merged PRs

I can see that on live website for e.g: https://gigadb.org/dataset/102541
so I think it was PR #1911 that was the final enabler. 
Thanks for spotting this, we can close this ticket.
