### ISSUE TITLE
Help tab

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#195]
I got a bit lost looking around here ie didn't really know what to expect to find.

I think some of this can be moved to the FAQ.

Then the Help tab could have a drop-down menu leading to Submission Guidelines and Application Programming Interface

I think the Controlled Vocabulary section could be renamed so it's more meaningful to users. Most of the info here comes under Submission Guidelines so maybe Submission Guidelines should have two sub-sections: Step-by-step guide and File format help (or something).

The info from Upload Status down seems too in-depth for online guidelines (at least such high level ones), but that might be because I've not used those terms as a curator. 

I think Help should have a link to our email address and to the FAQ

**Comment by only1chunts** [comment]
comments noted, thanks.
We need to get UX testing done on these pages.
Will add this to list for future release.

**Comment by only1chunts** [comment]
@tuli given this is about 7 years old now I'm going to close it, please reopen it if you think we still need to address any of the points in it
