### ISSUE TITLE
table settings not kept on mockup pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1956]
## User story

>As a user
>I want to have my prefered table settings maintained when I refresh a mockup page
>So that I can see the expected things in the table(s)

## Acceptance criteria

>Given I am on a mockup page (e.g. https://staging.gigadb.org/dataset/view/id/102544/token/vEKNF93Qi945PzNo )
>And I'm looking at the Files table
>When I set the "table settings" to view just 10 rows per page
> and I click view "next" 10 items in the table
>Then the page doesn't revert back to showing me >10 rows (in my case it reverted back to all 21 rows, but that maybe dependant on the previous table settings)

## Additional Info

It happens when change the table settings to also add additional columns (Format, release date) in addition to the nb of items per page 

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by luistoptal** [comment]
@rija I see this error also in the dataset view (no mockup), I traced it back to the cookies not being updated, despite the correct arguments passed to the controller in the function protected/components/DatasetPageSettings.php

This is the function that takes care of this

```php
    public function setFileSettings(array $columns, int $pageSize, CMap $cookies): array
    {
        if (isset($cookies['file_setting'])) {
            $cookies['file_setting']->value = json_encode([ "setting" => $columns, "page" => $pageSize]);
        } else {
                $cookie = new CHttpCookie('file_setting', json_encode(array('setting' => $columns, 'page' => $pageSize)));
                $cookie->expire = time() + (60 * 60 * 24 * 30);
                $cookies['file_setting'] = $cookie;
        }
        return [ "columns" => $columns, "pageSize" => $pageSize ];
    }
```

If I get rid of the conditional and the true branch, the cookie is updated, i.e.:

```php
    public function setFileSettings(array $columns, int $pageSize, CMap $cookies): array
    {
        $cookie = new CHttpCookie('file_setting', json_encode(array('setting' => $columns, 'page' => $pageSize)));
        $cookie->expire = time() + (60 * 60 * 24 * 30);
        $cookies['file_setting'] = $cookie;
        return [ "columns" => $columns, "pageSize" => $pageSize ];
    }
```

Does this looks like an correct fix? I don't find in the Yii docs a method to update cookies like the one in the true branch

NOTE: I will assume the above is correct and create a PR

**Comment by luistoptal** [comment]
@only1chunts @rija I see another issue which in principle seems unrelated to this one (happens in develop branch):

Upon refreshing the dataset page, e.g. http://gigadb.gigasciencejournal.com/dataset/view/id/100245 I always see an alert popup "Confirm Form Resubmission":

![image](https://github.com/user-attachments/assets/d92534a5-aeb1-458f-a5cc-3f8a2dbdfb5f)

**Comment by luistoptal** [comment]
Closing this as I think it is fixed by PR https://github.com/gigascience/gigadb-website/pull/1984
