### ISSUE TITLE
file table display issues with long file names

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1960]
## User story

>As a user  
>I want the file table to display in a usable way even when file names are long
>So that I can use the file table

## Acceptance criteria

>Given there is dataset with file with a name of more than 30 characters  
>When I navigate to the file tables view of that dataset
>Then I should see a truncated to 30 characters file name
>And the full file name upon hovering
>And the link should link to the full file name

>Given there is dataset with file with a name of up to 30 characters  
>When I navigate to the file tables view of that dataset
>Then I should see  file name
>And the full file name upon hovering
>And the link should link to the full file name

## Additional Info
The width of the filename column is variable based on the filename length being displayed, which is OK most of the time, but in cases where the filename is very long it makes the entire table wider than the browser window.
for example see https://staging.gigadb.org/dataset/view/id/102427
There are probably some worse examples, and the one that made me create this ticket was 102539 with some file names >150 char!!!, but thats so bad I'm going to go back to the authors and make them reduce the filename lengths!

Should we also consider a restriction on the filename length? If so, what should we set that to?

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by tuli** [comment]
**Should we also consider a restriction on the filename length? If so, what should we set that to?**

Yes we should. 
Best practice websites suggest 25-30 chars.

**Comment by only1chunts** [comment]
we could recomend as short as 25-30 chars, but I think most filenames we see are over 30char, so a more realistic recomendation would be under 50char.  Even then, I dont think we forcably restrict it to that short. 
I wonder if there is a way we can put a "warning" in the fileupload wizard when filenames have length over 50char?
The display table will need to be addressed so that we can still use the table when there are long filenames. 
Figshare handles it by truncating the filename on view, and showing the full length name when you hover over it
 e.g. 
![image](https://github.com/gigascience/gigadb-website/assets/6037145/67ceaeae-1b2f-476a-8f04-76b962edd667)

Maybe thats an option we could do?

**Comment by luistoptal** [comment]
@only1chunts truncating the filename is the way to go here, it is definitely possible

**Comment by only1chunts** [comment]
As long as there is a way for a user to be able to see the full file name
(eg hover over). And the column filter still filters on the full length
file names.

**Comment by tuli** [comment]
I don't know if this is the right ticket to add this to.
https://gigadb.org/dataset/view/id/102558/token/7t-PrpxU_D-mkdYw

It's useful to see the whole list of files (in this case I have selected '50 items per page'. 
It is then very hard to navigate around the page.

e.g. I want to look at the file attributes. I have to go to the bottom, scroll right to be able to see File Attributes. If I then want to see the file name associated with a particular File Attribute, I have to go to the bottom again and scroll left. If it's a long list of files I then lose track of which file I want to see. 
<img width="1320" alt="Screenshot 2024-07-11 at 08 18 48" src="https://github.com/gigascience/gigadb-website/assets/1359170/2396ea79-88a8-4d46-96bf-1306d1405152">

This might be better demonstrated via screen share!

**Comment by luistoptal** [comment]
@tuli yes that is a problem, I see what you mean. One option that comes to mind is to limit the table height and make it scrollable

![image](https://github.com/user-attachments/assets/eb0b16df-fa35-477d-9630-dbfb35c4ac27)

**Comment by luistoptal** [comment]
@only1chunts When the user hovers over the filename, they see a description
![image](https://github.com/user-attachments/assets/578021ef-f1e1-4a12-ae0e-abc0835f6e71)
Is this preferred to see the full file name or should it be replaced by the file name?

An alternative to truncating the name is to force it to break into lines:

![image](https://github.com/user-attachments/assets/6fa14efc-e4cc-46a5-8779-b9845d90cc38)

I think this second option is reasonable and allows us to keep the description popup

**Comment by only1chunts** [comment]
The use of wrapping for the filename seems to be a good choice, thanks.
