### ISSUE TITLE
4) Create and deploy (using `bastion_playbook.yml`) a wrapper script that handles the transfer (`rclone copy`) and logging of selected dataset files to both destinations

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#1967]
have a flag '--wasabi' to indicate the upload is to wasabi.
have a flag '--backup' to indicate the upload is to S3 glacier
show error and usage if no flag passed

**Comment by kencho51** [comment]
Close as completed in https://github.com/gigascience/gigadb-website/pull/1977
