### ISSUE TITLE
help API tab. small change in wording 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#198]
http://gigadb.org/site/help#0.1_API

The current API version is available on our main production database. This version will be periodically updated with new additional functionality, we will whenever possible maintain backwards compatability, but occassionally this may not be possible, for this reason we recomend regularly checking and updating you usage of our API.

Suggest to change to:
The current API version is available on our main production database. This version will be periodically updated with new additional functionality and we will whenever possible maintain backwards compatibility. Occasionally this may not be possible and for this reason we recommend regularly checking and updating your usage of our API.

**Comment by kencho51** [comment]
@pli888 The committed changes to help.html cannot be viewed from my local gigadb website,  may be the changes changes should be made in /site/help.php and yii-config/help.html.dist?

**Comment by pli888** [comment]
@kencho51 From your [pull request](https://github.com/gigascience/gigadb-website/pull/415) for this issue, I can see you have made the correct changes to text in `yii-config/help.html.dist` and `/site/help.php`.

I confirm that the changes in `/site/help.php` are visible on my http://gigadb.gigasciencejournal.com:9170/site/help. 

The changes in `yii-config/help.html.dist` are passed into `files/html/help.html` by `generate_config.sh` after executing `docker-compose run --rm config`.
