### ISSUE TITLE
Cannot update the Sample ID in the Admin page.

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#1991]
**Describe the bug**

**To Reproduce**
1. Go to https://gigadb.org/adminSample/view/id/187284
2. Update the Sample ID from [HiC_lib of NAS] to [HiC_lib_of_NAS]
3. Click 'Save'
4. The Sample ID still be [HiC_lib of NAS]

**Expected behavior**
The Sample ID can be updated as I wanted.

**Screenshots**
<img width="626" alt="截屏2024-07-29 10 57 03" src="https://github.com/user-attachments/assets/8df0f5b8-c507-4201-8509-a0a625a75267">
<img width="504" alt="截屏2024-07-29 10 57 25" src="https://github.com/user-attachments/assets/9269d509-cf4c-460a-94ea-c6d4ce3f198f">

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1 
 - Browser Chrome
 - Version 126.0.6478.185

**Comment by YFan0019** [comment]
Hello @rija, 

Could you please help with the sample ID update from the backend, so that the dataset can be released ASAP？

1. Sample #187284, `HiC_lib of NAS` -> `HiC_lib_of_NAS`
2. Sample #187285, `WGS_HiFi_ONT_utra_long_lib of NAS` -> `WGS_HiFi_ONT_utra_long_lib_of_NAS`
3. Sample #187286, `HiFi_HiC_ONT_utra_long_lib of NAA` -> `HiFi_HiC_ONT_utra_long_lib_of_NAA`

Many thanks.

**Comment by rija** [comment]
> Hello @rija,
> 
> Could you please help with the sample ID update from the backend, so that the dataset can be released ASAP？
> 
> 1. Sample #187284, `HiC_lib of NAS` -> `HiC_lib_of_NAS`
> 2. Sample #187285, `WGS_HiFi_ONT_utra_long_lib of NAS` -> `WGS_HiFi_ONT_utra_long_lib_of_NAS`
> 3. Sample #187286, `HiFi_HiC_ONT_utra_long_lib of NAA` -> `HiFi_HiC_ONT_utra_long_lib_of_NAA`
> 
> Many thanks.

Hi @YFan0019,
the database change was made on the live production environment,
and @alli83 is now looking into fixing the bug.

**Comment by alli83** [comment]
it's possible to update each field right? so the first one with the id - the common name and scientific name should be split right? 

I mean, should we be able to update specie common name and specific name too?

**Comment by only1chunts** [comment]
On the page we're talking about in this thread (i.e. the sample admin page) the "species" field at the top must be chosen from one of the items in the Species table, its parts are not editable here. If you need to make changes to the species details you have to edit them in the species admin page, not in the sample admin page.

**Comment by alli83** [comment]
> On the page we're talking about in this thread (i.e. the sample admin page) the "species" field at the top must be chosen from one of the items in the Species table, its parts are not editable here. If you need to make changes to the species details you have to edit them in the species admin page, not in the sample admin page.

So I should make this first field non updatable right?

**Comment by only1chunts** [comment]
Depends what you mean by "updatable"? We need to be able to select the relevant species, so in that way it DOES need to be updatable, but its a selection from a controlled vocabulary (in this case the Species table), you cannot just add free text.

**Comment by alli83** [comment]
> Depends what you mean by "updatable"? We need to be able to select the relevant species, so in that way it DOES need to be updatable, but its a selection from a controlled vocabulary (in this case the Species table), you cannot just add free text.

Oh I see. so it's conditionally updatable based on a list :)

**Comment by rija** [comment]
Closing as it will be fixed in PR #1995
