### ISSUE TITLE
update contact us page with new address

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#1993]
## User story

>As a user  
>I want to get the correct address off the contact page
>So that I can write a nice letter to everyone at GigaScience thanking them for their great work :-D

## Acceptance criteria

>Given I want to write a letter to the Gigascience team  
>When I navigate to  /site/contact
>Then I should see:
"708-709, 6W Phase One, Hong Kong Science Park, Pak Shek Kok, Hong Kong"

>Given I want to give a phone call to the Gigascience team  
>When I navigate to  /site/contact
>Then I should see:
+852 3610 3533

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
Hi @only1chunts, @kencho51 
guys do you know what's the new phone number?

**Comment by kencho51** [comment]
>  guys do you know what's the new phone number?

Can use +852 3610 3533

**Comment by rija** [comment]
Hi @luistoptal,
I think this ticket is ready to be picked up, it should be a fairly small one.

**Comment by luistoptal** [comment]
@rija PR created
