### ISSUE TITLE
Switch gigadb DNS from alibaba to cloudflare

### ISSUE THREAD

**Issue by kencho51** [gigascience/gigadb-website#2003]
* Look at DNS records in Alicloud and save them so we have a back of the DNS records.
* Start from cloudflare console, and add new gigadb.org domain to manage and follow cloud flare's instructions.
* Then go to Alicloud registry, replace details of gigadb.org domain in there with whatever is provided by cloud flare
* Cloudflare will scan existing DNS records in Alicloud for gigadb.org. Need to ensure all these records are present in Cloudflare.
* Do not use Cloudflare's proxy!

Documentation on how to do this is available at:
https://developers.cloudflare.com/dns/zone-setups/full-setup/setup/

Will be done on Thu 5 Sep VOH.

**Comment by pli888** [comment]
Closing this issue because it was done at Thu 5 Sep VOH.
