### ISSUE TITLE
Create a shell script wrapping rclone sync

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#2004]
the script will be at `/usr/local/bin/sync_dropbox`
and will write logs at `/var/logs/sync_dropbox/`
and reads its config at `/etc/sync_dropbox/rclone.conf`
and will execute:
```
/usr/local/bin/rclone --config /etc/sync_dropbox/rclone.conf -v  sync current-production:/share/dropbox/ /share/dropbox
```

usage should be:
```
sync_drobox [--dry-run]
```
where `--dry-drun` will cause adding the same option to the `rclone` command
In the context of this ticket there is no need for any other options.

**Comment by kencho51** [comment]
Close as done in PR https://github.com/gigascience/gigadb-website/pull/2025
