### ISSUE TITLE
Generate rclone configuration for source of rclone sync

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#2005]
The configuration needs to be deployed at `/etc/sync_dropbox/rclone.conf` and should looks like:
```
[current-production]
type = sftp
host = bastion.gigadb.host
user = centos
key_file = /home/centos/.ssh/upstream_from_alt-live
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
```

The SSH  key should be generated by the bastion playbook into the local `output-x.x.x.x` directory, with the private part stored as ` /home/centos/.ssh/upstream_from_alt-live`, and the public part stays in the output directory and should be manually to the current prodution's authorized keys.

**Comment by kencho51** [comment]
As discussed, will use the `id_rsa_aws_hk_gigadb_pem` from the [cnhk-infra](https://gitlab.com/gigascience/cnhk-infra/-/settings/ci_cd) as the private key.
Will save the public key of `id_rsa_aws_hk_gigadb_pem` to the cnhk-infra for future use.

Close as done in PR https://github.com/gigascience/gigadb-website/pull/2025
