### ISSUE TITLE
Update bastion playbook to add a new cronjob to execute the shell script and to create the rclone configuration

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#2006]
At the moment the following cronjob was manually added:
```
@daily /usr/local/bin/rclone --config rclone_upstream.conf -v  sync live-bastion:/share/dropbox/ /share/dropbox/
```

the generated cronjob should call the `/usr/local/bin/sync_drobox` command from the task #2004 and specifies the exact time to run daily.

**Comment by kencho51** [comment]
Close as done in PR https://github.com/gigascience/gigadb-website/pull/2025
