### ISSUE TITLE
Readme file cannot be downloaded from GigaDB web page.

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#2013]
**Describe the bug**
Readme file cannot be download for 102554 and 102569.

**To Reproduce**
1. Go to https://gigadb.org/dataset/102569 and https://gigadb.org/dataset/102554
2. Click on download button on the web page
3. See error on the web page
4. But other files can be downloaded except the readme file.

I tried to open the readme files through rclone in Wasabi, and that is fine.
I checked the file path on the admin page, and it is fine.
I re-copied the readme files to Wasabi again, but I still cannot download them from the GigaDB page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 127.0.6533.120

**Comment by pli888** [comment]
You need to update the links to the readme files in the database:
* 102554
  * Current - https://s3.ap-northeast-1.wasabisys.com//102001_103000/102554/readme_102554.txt
  * Correct - https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/live/pub/10.5524/102001_103000/102554/readme_102554.txt 
* 102569
  * Current - https://s3.ap-northeast-1.wasabisys.com//102001_103000/102569/readme_102569.txt
  * Correct - https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/live/pub/10.5524/102001_103000/102569/readme_102569.txt

**Comment by YFan0019** [comment]
Thanks @pli888, the readme files can be downloaded now.
