### ISSUE TITLE
Same issue as #1959 - The "Dataset:Relation" function is not available in the admin page

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#2014]
Same as https://github.com/gigascience/gigadb-website/issues/1959

Please add the relationship to the datasets from the backend server.

102568 HasPart 102567, 102566
https://gigadb.org/dataset/102568/token/ff4q2vuQjxqYTtTM

102567 isPartOf 102568
https://gigadb.org/dataset/102567/token/jga2rAcySLU2-mKl

102566 isPartOf 102568
https://gigadb.org/dataset/102566/token/SAdfNmzF98pBXN1g

**Comment by tuli** [comment]
Please can you prioritise this, so that I can release the GigaDB records.

**Comment by pli888** [comment]
Closing this ticket because PR #1987 which provides the dataset relation functionality was merged and released in v4.3.5.
