### ISSUE TITLE
An error statement shows when try to remove files in admin page

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#2015]
**Describe the bug**
An error shows up when click the delete button in the "Dataset:Files" admin page

**To Reproduce**
1. Go to https://gigadb.org/adminFile/admin
2. Search for the files that I want to remove
3. Click on the delete button
4. See the error window shows up, but the function still works.

**Expected behavior**
Please check the cause and remove the error.

**Screenshots**
<img width="1149" alt="截屏2024-08-22 10 11 18" src="https://github.com/user-attachments/assets/63096ca7-e76e-418f-b794-2a86646f5fd1">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 127.0.6533.120

**Additional context**

**Comment by rija** [comment]
This is likely an error thrown by the Yii framework because of the wrong method being used (GET instead of POST)

**Comment by pli888** [comment]
Work merged in PR #2017 and #2042.
