### ISSUE TITLE
The "Curator Assigned" status adds a new record each time I save the admin page.

### ISSUE THREAD

**Issue by YFan0019** [gigascience/gigadb-website#2016]
**Describe the bug**
The "Curator Assigned" status adds a new record each time I save the admin page.

**To Reproduce**
1. Go to https://gigadb.org/adminDataset/update/id/2830
2. Modify some information in the admin page
3. Click "Save"
4. There are multiple "Curator Assigned" records each time I save the admin page.

**Expected behavior**
Only save the status if the info is changed.

**Screenshots**
<img width="1130" alt="截屏2024-08-26 09 50 25" src="https://github.com/user-attachments/assets/4f6adf5f-ea3c-4852-9b9e-1c8104c3805c">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 128.0.6613.85

**Additional context**

**Comment by pli888** [comment]
PR #2023 has been created for this ticket.
