### ISSUE TITLE
GigaBlog

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2028]
## User story

>As a editor/curator/Giga staff
>I want to be able to create blog posts and have them published online at our usual blog site : https://gigasciencejournal.com/blog/
>So that we can continue to publish blogs more easily

## Acceptance criteria

>Given I want to write a blog
>When I try to write the blog online
>Then I can log onto a publishing site, write my blog and publish it

>Given I am travelling and my IP address is never static
>When I want to log into our blog publishing site
>Then I can, without having to get IT to white list my IP address.

>Given a member of Gigascience wants to write a blog post
>When they navigate to the blog dashboard
>Then can log in
>And they can create a post
>And they can publish their post

>Given we have blogs being publishing publicly at gigasciencejournal.com/blog/
>When I access the analytics for our blog system
>Then I can see web traffic stats and usage data

## Additional Info
The basic criteria are to have a stable and secure blog publishing platform.
Additionally we need to be able to have multiple members of staff to be able to log in to write and edit blogs. They may be travelling, so having security that is not based on a white list of IP addresses will also be required.

Our blog posts are also given DOI's via rougescholar, so that integration would be nice to keep if possible.

Finally, having some sort of metrics of how many times a blog is opened, read or cited would be a nice to have.

NOTE - This has been added to the GigaDB Backlog Project, but its not strictly GigaDB, so maybe there is a better project to add this to?

Consider using wordpress.com managed service
Migrate DNS of gigasccienojournal.com to using Cloudflare too.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by pli888** [comment]
Closing this ticket because it has been re-created at https://github.com/gigascience/gigablog/issues/8.
