### ISSUE TITLE
bug in file admin page updates made for v4.3.6

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2029]
Testing the staging environment for the v4.3.6 release I spotted an issue that requires investigation:

I opened this file admin page :
https://staging.gigadb.org/adminFile/update/id/539458
I clicked the "Show new attributes" button to see the newly labelled "add attributes" button
I then clicked the "Edit" button next to the existing MD5 value attribute to see the "add attribute" button there, both looked fine, 
Then I entered a new attribute and tried to save that and instead of adding the new attribute it made a duplicate of the already existing MD5 value attribute?!

![image](https://github.com/user-attachments/assets/6a50f5c9-1f09-45c3-a5f4-013508b29524)

However, I then went back and tried to add a new attribute without clicking the "edit" button AS WELL. and the function worked as expected. so its an odd scenario that I accidentally created by clicking both the edit and the add buttons! but we should create a criteria to prevent that from happening. If I can do it accidentaly then someone else will!

## User story

As a curator
I want to see a clean intuitive design when I make File Attribute updates
So that its simple to use without confusion

## Acceptance criteria

>Given I am on a File admin page (e.g. https://gigadb.org/adminFile/update/id/96250)
>When I click the "Edit" button on an existing file attribute
>Then I should see a "Save Attribute" button next to edit attributes fields

>Given I am on a File admin page (e.g. https://gigadb.org/adminFile/update/id/96250)
>When I click the "Edit" button on an existing file attribute
>And I click the "Show new attribute field" button on an existing file attribute
>And I fill in the value for the new attribute
>And I click "Add attribute"
>Then thew new file attribute should be added to the database
>And no existing file attributes should be duplicated

>Given I am on a File admin page (e.g. https://gigadb.org/adminFile/update/id/96250)
>And the form area for adding new attribute is shown to the user
>When I click the "Edit" button on an existing file attribute
>Then the form area for adding new attribute becomes hidden
>And the form area for the existing file attribute to be edited is shown to the user

>Given I am on a File admin page (e.g. https://gigadb.org/adminFile/update/id/96250)
>And the form area for an existing file attribute to be edited is shown to the user
>When I click the "Show new attribute field" button
>Then the form area for the existing file attribute to be edited becomes hidden
>And the form area for adding new attribute is shown to the user

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
To be extra precise, the problem happen when both the Edit form and the "Show new attribute fields" are open.
We need to ensure opening one will close the other maybe

**Comment by rija** [comment]
Hi @luistoptal 

can you have a look at this when you get a moment.

**Comment by rija** [comment]
this is an issue that stem from deploying the fix to #1858 on staging
