### ISSUE TITLE
blank screen and failure to create mockup 

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2033]
On the recent dataset uploaded [102585 #49](https://github.com/gigascience/dataset-tracking/issues/49) I made all the updates as required in the dataset admin page (added my username, the MS ID, the thumbnail image, release date, set status to "Submitted" etc..) clicked save. All fine, everything saved as expected.
I then clicked "create /reset private URL" button to generate the mockup link- it did this:

![image](https://github.com/user-attachments/assets/bd7146d9-d57e-4520-8096-138da26830cb)

I then went back and tried several changes, eventually I discovered that the Status of "Submitted" was the issue! As soon as I changed that to "Curation" the create/reset button worked as expected.

## User story

>As a curator
>I want to be able to create or reset the private mockup URL when the dataset status is "Submitted"
>So that I can share the private link with people.

## Acceptance criteria

>Given I am on the dataset Admin page of any dataset with a status of anything EXCEPT "Published" 
>When I look at the bottom of the page
>Then I should see a create/reset private URL button
> And when I click that button it does create or reset the private URL for that dataset.

>Given I am on the dataset Admin page of any dataset with status "Published"
>When I look at the bottom of the page
>Then I should NOT see a create/reset private URL button
NB - This is already the case, I'm just making sure its clear here that it is correct.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by alli83** [comment]
@only1chunts apparently, depending on the page type it will redirect to a different page. So should it yield the same result as if it's curation for the upload status?

**Comment by only1chunts** [comment]
by "page type" do you mean the dataset status? if not what does page type mean in this context?
I think the buttons at the bottom of the screen should always have the same effect (from a users point of view) regardless of the dataset status. The buttons that are present will change depending on the status, but the action of the buttons shouldn't be different (from a users perspective, I only say that because I have no idea what they do behind the scenes :-) )

**Comment by pli888** [comment]
Work done in PR #2093.
