### ISSUE TITLE
increase contrast on admin pages for ease of reading

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2034]
## User story

>As a curator 
>I want to be able to easily read text in admin pages
>So that I dont strain my eyes

## Acceptance criteria
Noticed on the dataset Admin page, but its probably an issue on other admin pages too

>Given I am on the dataset-admin page, e.g.https://gigadb.org/adminDataset/update/id/2838
>When scroll to the Description field
>Then I can see the text easily with high contrast
i.e. the text is black on white OR white on black, instead of the current light grey on white that is tricky to read.

>Given I am on the admin form for a dataset  
>When I read the value in the all the fields (especially the description)  
>Then the content is easy to read

## Additional Info

e.g: the keyword field tooltip text is an example of easy to read text

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by luistoptal** [comment]
@only1chunts are you referring to the text in the inputs? Like the image below?
![image](https://github.com/user-attachments/assets/9f43ce82-48be-42ec-a0a9-c3050f897250)

**Comment by only1chunts** [comment]
yes (it doesn't look as pale on your screenshots as it does on my screen!)
![image](https://github.com/user-attachments/assets/3d26b8bd-5960-48e8-992d-f8da634d9614)

**Comment by luistoptal** [comment]
@only1chunts yes, my bad for not being specific about that, my screenshot is after changing the text color to black. I will update it in all inputs, you're right the gray on white is a bit straining
