### ISSUE TITLE
unable to delete keywords

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2061]
## User story

>As a curator
>I want to be able to edit and delete dataset keywords in the dataset admin pages
>So that I can make corrections to dataset keywords

## Acceptance criteria

>Given I need to delete a keyword from a dataset
>When I visit the relevant dataset admin page [e.g.](https://staging.gigadb.org/adminDataset/update/id/2820) 
> And click the delete keyword X button to remove a keyword
> And click Save dataset
>Then the dataset is saved without the keyword

>Given conditions  
>When event  
>Then outcome

## Additional Info
Noticed while investigating #2027 
**This only seems to be an issue when there are no keywords, e.g. if I only delete one of many keywords then it saves correctly, but if I delete all keywords then it doesn't save correctly**

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by luistoptal** [comment]
I looked at this and created a PR with a fix
