### ISSUE TITLE
Create copy of ami from an existing instance

### ISSUE THREAD

**Issue by kencho51** [gigascience/gigadb-website#2072]
**Describe the bug**

**To Reproduce**
```
# for existing infrastructure
% terraform refresh
...
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.files_host.data.aws_ami.centos,
│   on ../../modules/aws-instance/aws-instance.tf line 74, in data "aws_ami" "centos":
│   74: data "aws_ami" "centos" {
│ 
╵
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.ec2_dockerhost.data.aws_ami.centos,
│   on ../../modules/aws-instance/aws-instance.tf line 74, in data "aws_ami" "centos":
│   74: data "aws_ami" "centos" {
│ 
╵
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.ec2_bastion.data.aws_ami.centos,
│   on ../../modules/bastion-aws-instance/bastion-aws-instance.tf line 42, in data "aws_ami" "centos":
│   42: data "aws_ami" "centos" {
│ 
╵
Releasing state lock. This may take a few moments...
```

It seems this data block in aws-instance.tf line 74 and bastion-aws-instance.tf line 42 returned no results:
```
data "aws_ami" "centos" {
  most_recent = true

  filter {
    name   = "name"
    values = ["CentOS Stream 8 x86_64 *"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["125523088429"]
}
```

**Additional context**

```
module.ec2_dockerhost.aws_eip_association.docker_host_eip_assoc: Creation complete after 2s [id=eipassoc-03266d6e434a0f0a7]
╷
│ Error: updating RDS DB Instance (rds-server-staging-ken): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: afc74e71-b939-471e-b049-db58985e4822, api error InvalidParameterCombination: Cannot upgrade postgres from 14.12 to 14.10
│ 
│   with module.rds.module.db.module.db_instance.aws_db_instance.this[0],
│   on .terraform/modules/rds.db/modules/db_instance/main.tf line 29, in resource "aws_db_instance" "this":
│   29: resource "aws_db_instance" "this" {
│ 
╵
```

**Suggested solution**
1.  Create an CentOS Stream 8 ami from existing instance which has been deprecated
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/83101d35-ff2c-430f-9c43-c563effd6b19">

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/c320671b-ba6e-40fa-a4ef-556404f37de8">

<img width="2003" alt="image" src="https://github.com/user-attachments/assets/13620228-22d9-48d0-9b60-35ba68e26f0c">

3. Refactor the current tf to reference the customized ami, instead of the public one

![image](https://github.com/user-attachments/assets/460d0665-7d99-496f-bffb-93d3786f41a5)

![image](https://github.com/user-attachments/assets/baae12b5-d9d4-4735-a9eb-bb79a0a62e19)

![image](https://github.com/user-attachments/assets/c53c9900-de37-4233-9d52-9957c24e0fd4)

**Comment by kencho51** [comment]
AWS official private Centos 8 ami at https://aws.amazon.com/marketplace/pp/prodview-urkpdamxhet6q

**Comment by pli888** [comment]
Closing this ticket as we are moving to Centos 9 Stream #1897.
