### ISSUE TITLE
fix the calendar moving arrows on date picker in various pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2079]
## User story

>As a curator
>I want to be able to navigate the calendar date picker everywhere that it appears 
>So that I can select the appropriate date from the calendar

## Acceptance criteria

>Given I am on a dataset admin page e.g. https://staging.gigadb.org/adminDataset/update/id/2860
>When I try to set the date for Fair Use Policy
>Then I can see the relevant month in the date picker AND see arrows pointing left and right to change the month back or forwards

>Given I am on a dataset admin page e..g. https://staging.gigadb.org/adminDataset/update/id/2860
>When I try to set the date for Publication Date
>Then I can see the relevant month in the date picker AND see arrows pointing left and right to change the month back or forwards

>Given I am on a dataset admin page e.g. https://staging.gigadb.org/adminDataset/update/id/2860
>When I try to set the date for Modification Date
>Then I can see the relevant month in the date picker AND see arrows pointing left and right to change the month back or forwards

>Given I am on a dataset-file admin page e.g. https://staging.gigadb.org/adminFile/update/id/96248
> OR the create dataset-file page e.g. https://staging.gigadb.org/adminFile/create
>When I try to set the date for the file release date
>Then I can see the relevant month in the date picker AND see arrows pointing left and right to change the month back or forwards

>Given I am on a News admin page e.g. https://staging.gigadb.org/news/update/id/5
> OR the create news item page e.g. https://staging.gigadb.org/news/create
>When I try to set the date for the "Start date"
>Then I can see the relevant month in the date picker AND see arrows pointing left and right to change the month back or forwards

>Given I am on a News admin page e.g. https://staging.gigadb.org/news/update/id/5
> OR the create news item page e.g. https://staging.gigadb.org/news/create
>When I try to set the date for the "End date"
>Then I can see the relevant month in the date picker AND see arrows pointing left and right to change the month back or forwards

and on the RSS message admin page: https://staging.gigadb.org/rssMessage/create - although I dont think we've ever used that page!

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by luistoptal** [comment]
@only1chunts is this still an issue? this is what I see in 3 browsers I tested, I can see arrows to cycle through months

![image](https://github.com/user-attachments/assets/8aaed6e7-4714-436d-89a4-24858f344225)

**Comment by only1chunts** [comment]
yes this is still an issue on both staging.gigadb.org and on live.
this is how it looks for me:
![image](https://github.com/user-attachments/assets/6be98832-a83b-40d2-a32f-d04b0e747618)

I'm on Chrome Version 129.0.6668.101 & I just updated to Version 130.0.6723.117 and its still the same issue.
NB - I also tried in Microsoft Edge Version 130.0.2849.68 and have the same issue.
