### ISSUE TITLE
News items on the home page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#208]
## User Story

>As website user
>I want an efficient way of seeing navigating news items on the home page
>So that I can see what's new with GigaDB

## Acceptance tests

>Given there is one new item in the database
>When I navigate to the home page
>Then I should see tthe title and first line of the news item
>And I should see a "See more" link to the full news article
>And I should not see the pagination arrows to scroll for more news

>Given there are four news item in the database
>When I navigate to the home page
>Then I should see the title and first line of the first three  news items side by side
>And I should see a "See more" link to the full news article for each of them
>And I should see the pagination arrows to scroll for more news

These have been added to the home page, but they currently look like they are an after-thought (which they were!) need to get them looking more in keeping with page, and fix how it handles multiple news items, it has arrows suggesting you can scroll left/right, but the multiple news items are listed one below the other!

add a news item to the list (http://54.169.242.2/news/admin) and nothing shows up on the home page. can we add a section for when news items are current? between the datasets by type and the summary stats.

**Comment by rija** [comment]
Will be managed in CraftCMS

**Comment by rija** [comment]
Hi @luistoptal,

Although long term it will be managed by CMS, in the meantime the UX on the home page for news items could do with the above suggestions from @only1chunts.

And I can confirm that adding new news items works fine from the admin dashboard for new items
(local url: http://gigadb.gigasciencejournal.com/news/admin)

**Comment by luistoptal** [comment]
@only1chunts I cannot see any new items in the home page, can you provide a screenshot of what this ticket refers to?

**Comment by only1chunts** [comment]
the news items admin page can be accessed here:
![image](https://github.com/user-attachments/assets/b20b57f6-b6b6-4bfc-9b44-bd4c9603fc30)

you can add/edit/delete news items here: https://gigadb.org/news/admin
![image](https://github.com/user-attachments/assets/5b85ae1c-4a40-49b4-a7be-a80d1f4759a6)

They show up on the home page like this:
![image](https://github.com/user-attachments/assets/3e87ddb3-0411-42ed-9daa-99b90b636096)

**Comment by only1chunts** [comment]
I'm open to any suggestions of how to make the Latest news section look better

**Comment by rija** [comment]
Hi @luistoptal,

on your local deployment, for your own testing, you can also create any number of news items yourself at  http://gigadb.gigasciencejournal.com/news/admin

**Comment by luistoptal** [comment]
@rija is this priority over the vue widget to upload logos? (#376)

**Comment by only1chunts** [comment]
@luistoptal, no this is not a priority over #376

**Comment by luistoptal** [comment]
@only1chunts still work in progress and I will tweak it a bit more stylewise, but does this layout seem reasonable? I think a carousel of boxes is quite standard for this type of section

![image](https://github.com/user-attachments/assets/470c4217-de6f-43a7-b65c-8ad4e7b7c8dc)

**Comment by only1chunts** [comment]
yes that looks fine, the box outlines make a huge difference, thakns
