### ISSUE TITLE
Fix bug that admin changes made to sample 'species' and 'sample ID' are not saved

### ISSUE THREAD

**Issue by molcretb** [gigascience/gigadb-website#2088]
## User story

>As a curator
>I want to be able to modify the sample 'species' and 'sample ID' fields in the 'Update sample' window
>So that the changes are saved

## Acceptance criteria

>Given I am on a dataset admin page e.g. https://gigadb.org/adminSample/update/id/187935
>When I modify the fields 'Species *'  or 'Sample ID' AND click to the 'Save' button
>Then the modifications are saved AND I can see the new values in the Sample admin browser e.g. https://gigadb.org/adminSample/admin

## To Reproduce
1. Go to 'Admin/Samples' and search sample ID 'test_for_bug_Species_sampleID_tryToRemoveThis'
2. Click on 'update'
3. Remove the '_tryToRemoveThis' part of the Sample ID field and click on 'Save'
4. See error (modification is not saved)

## Expected behavior
I want the modified fields 'Species' and 'Sample ID' to be saved after modification.

## Screenshots
![Image](https://github.com/user-attachments/assets/bb5fdf67-cc24-4704-873f-404e2b3cbd12)
![Image](https://github.com/user-attachments/assets/98747f08-6583-483d-ad34-f7fcbe19e9e8)
![Image](https://github.com/user-attachments/assets/88c68060-9e0f-463a-94a2-041ca41d8c76)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome
 - Version 130.0.6723.92

**Additional context**

**Comment by alli83** [comment]
fix in PR https://github.com/gigascience/gigadb-website/pull/1995

**Comment by tuli** [comment]
@only1chunts can you clarify the status of this fix? I have a Species I need to update in a sample, but am unable to do so.
Do I need to ask Tech to fix it? https://gigadb.org/adminSample/update/id/188956 Current - 291826:Elopichthys bambus, Should be 238031:Elopichthys bambusa 
291826 is Xenocypris davidi which is what is showing in the mockup https://gigadb.org/dataset/102615/token/DsWoUBLw3g6Ouz8V

**Comment by only1chunts** [comment]
this fix has not been deployed yet so you will not be able to change the species until it has been.
The work around is to create a new sample with the correct details and then delete the wrong one (do not change the species name in the species table as that will then be incongruent with the NCBI taxon)

**Comment by alli83** [comment]
https://github.com/gigascience/gigadb-website/pull/1995#pullrequestreview-2483762715

**Comment by pli888** [comment]
Closing this ticket because its PR #1995 has been merged.
