### ISSUE TITLE
prevent emails being blocked

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#209]
How do we stop our automated emails from being blocked/returned or classed as junk/spam?
Every automated email that gets sent by GigaDB is effected by this problem and now that we expect EVERY user to confirm their own account by an automated password reset it is a major problem!

**Comment by pli888** [comment]
@only1chunts What email account are you using to send the GigaDB emails?

**Comment by pli888** [comment]
You could try following best practices for sending automated HTML-based emails by GigaDB, e.g. look at advice by [MailChimp](https://mailchimp.com/resources/guides/avoid-spam-filters/). Then send these new emails to online spam checkers to see whether they will clear people's spam filters.

**Comment by only1chunts** [comment]
it looks like the main issue could be 
1 - sending through verified domains i.e. Some spam filters will flag a campaign if anyone with the same IP has sent spam in the past.  Is there a way to change the IP address of where we send them from?
2 - Spam filters can be triggered by sloppy code, extra tags, or code pulled in from Microsoft Word. 
3 - personalize the To: field of emails
4 - apparently our server IP is black-listed here https://www.abuseat.org/lookup.cgi?ip=218.189.31.218 I believe this is the major problem, it requires us to check for viruses before getting delisted.

**Comment by pli888** [comment]
@only1chunts Could relay GigaDB emails via Gmail. The problem is if Gmail has blacklisted the GigaDB servrer's IP address. In this case, you'll need to contact Google to get off the [blacklist](https://support.google.com/mail/contact/msgdelivery).

**Comment by jessesiu** [comment]
Hi,

I test the https://github.com/PHPMailer/PHPMailer today, it will send the
email via SMTP from Gmail, it seems work. I will do more testing.

Jesse

2018-06-20 14:27 GMT+08:00 Peter Li <notifications@github.com>:

**Comment by only1chunts** [comment]
@pli888 I dont tink its a problem of google blacklisting us because most of the emails we send to are not gmail accounts. Its the CBL listing that is the major Issue I think.
https://www.abuseat.org/lookup.cgi?ip=218.189.31.218
I've asked Jesse to follow the instruction on that page to try to get us unlisted.

**Comment by pli888** [comment]
@only1chunts my suggestion was to use the Gmail server to send the emails instead of them coming directly from the GigaDB server to get around the GigaDB server IP blacklist problem. But sure, fix the CBL first.

**Comment by jessesiu** [comment]
@pli888 I test the PHPMailer and Gmail SMTP in the vagrant, it will send the email from Gmail server with TLS encryption. So will use it in GigaDB send mail function.

e.g.
from: | GigaDB <database@gigasciencejournal.com>
to: | jesse@gigasciencejournal.com
date: | 20 June 2018 at 15:00
subject: | Password reset
Signed by: | gigasciencejournal-com.20150623.gappssmtp.com
security: | Standard encryption (TLS) Learn more
: | Important according to Google magic.

**Comment by only1chunts** [comment]
Does this new method work OK? can we get it deployed on the production server, almost every email sent by the web-server is being blocked.

**Comment by jessesiu** [comment]
Just changed in the password reset function, will do it to all functions.


发自我的 iPhone

**Comment by jessesiu** [comment]
@only1chunts all emails send to users go through the gigasciencejournal.com SMTP server

**Comment by only1chunts** [comment]
it seems to work, but there is one minor issue with the "New user registration" email, the format is odd? it seems to be in HTML format with attached images, but those images are not used/displayed, and the previous version was plain text. Also the line-returns are missing. This is not a problem because that email only comes to us for information, i'm just pointing it out incase its a sign of something that could be wrong?
