### ISSUE TITLE
Some older dataset readme_DOI.txt files have incorrect author lists!

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2116]
## User story

>As a user  
>I want to be given the correct information in a dataset readme file
>So that I can accurately cite the dataset in my work

## Acceptance criteria

>Given a dataset include the file 'readme_DOI.txt'
>When I download and view that file
>Then the author list matches exactly the author list of the dataset as shown in the DOI page

## Additional Info
This appears to be an issue in many of the older datasets, see for example 100925
The author list in the database (and therefore the [DOI](https://doi.org/10.5524/100925)) is given as "Ou M; Huang R; Yang C; Gui B; Luo Q; Zhao J; Li Y; Liao L; Zhu Z; Wang Y; Chen K"
The author list given in [readme_100925.txt](https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/live/pub/10.5524/100001_101000/100925/readme_100925.txt) is "Wang, Y; Ou, M; Huang, R; Luo, Q; Zhao, J; Chen, K; Yang, C; Gui, B; Li, Y; Liao, L; Zhu, Z" 
Same names, different order!

It is not every dataset, and I dont know how to check which or how many are affected.

Its not just older dataset the following datasets show the same issue:
102479 (released Nov2023) 
102529 (released May2024)
102569 (released Aug2024)
102618 (released last week)

NB. I picked dataset numbers at random, and only found 2 that had the correct author list, so I think this issue is quite widespread!
 

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by only1chunts** [comment]
This will need to be fixed before #2113

**Comment by kencho51** [comment]
Close as implemented in PR https://github.com/gigascience/gigadb-website/pull/2123
