### ISSUE TITLE
the tilda symbol "~" does not display well on dataset pages, can that be improved?

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#2124]
## User story

>As a website user  
>I want to be able to distinguish between a tilda "~" and a hyphen "-" on GigaDB pages
>So that I know when a value is an approximation

## Acceptance criteria

>Given a dataset page contains a tilda somewhere in the text
>When I view that page
>Then I can tell its a tilda ~

## Additional Info
for example in the screenshot below (taken from dataset 102616 before the tilda's were removed):
![image](https://github.com/user-attachments/assets/baad55e9-d454-4682-872f-fc527a5cc3d2)
The two values highlighted are actually ~ but they look more like - 
My guess is that its the Font we are using, so can that be changed?

Infact the issue can also be seen on the home page if you try to [type ~ into the search box](https://gigadb.org/search/new?keyword=%7E)

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by tuli** [comment]
![Screenshot 2024-12-10 at 12 24 23](https://github.com/user-attachments/assets/a815ea27-2ab6-42b0-8177-07aecc9d2c25)
For comparison, it looks fine in my browser (Safari 16.5)

**Comment by rija** [comment]
not a problem on Mac with Retina display, but not readable on some other computers/resolutions

**Comment by luistoptal** [comment]
@only1chunts in your image the character umabiguously looks like a "-", which seems strange. I am unable to replicate it as I see "~" in multiple browsers. What browser and OS are your screenshots?

**Comment by only1chunts** [comment]
We discussed this in a call, and it seems to be a retina display thing, I'm guessing you use a Mac with a retina display, which shows it OK, but for those of us that refuse to use Macs and dont have a equivelantly high resoluton screen, its an issue. But its only an issue on GigaDB for me! in your above comment it looks fine, so therefore it must be the choice of font we use in GigaDB that means its a very low curve making it look almost flat.
FYI - I am a Windows 11 PC, using Chrome Version 131.0.6778.140, with a screen resolution of 1920x1080
I know my screen is not the best (its quite old), but I dont think I will be alone in having a screen of that resolution.
