### ISSUE TITLE
Check if all published datasets have a DOI minted

### ISSUE THREAD

**Issue by alli83** [gigascience/gigadb-website#2125]
linked to https://github.com/gigascience/gigadb-website/issues/549: pre step

We need to ensure that all published datasets have a DOI minted

**Comment by only1chunts** [comment]
Thats a test we've never done before. I just did it and discovered 2 datasets that has indeed been published in GigaDB without the DOI being minted at DataCite (100823 & 102585) I have now fixed those, and can confirm that (as of 10 Dec 2024) every published dataset in GigaDB has a corrosponding DataCite entry.
