### ISSUE TITLE
DataCite complains of missing data in the payload GigaDB send

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#2132]
## User story

>As a curator  
>I want to ensure all the data needed by Datacite is sent  
>So that there is no error when updating metadata on DataCite

## Acceptance criteria

>Given I navigate dataset page for 100203 or 100425
>When I click on the funding tab
>Then all entries should have a funding body filled in

## Additional Info

Error when minting those DOI: 100203 and 100425
```
This DOI exists in datacite, but failed to update metadata because of: DOI 10.5524/100425: [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'. at line 57, column 0
```

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not been compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (i.e. the increment has not broken anything)

**Comment by rija** [comment]
curator task

**Comment by only1chunts** [comment]
done in live
