### ISSUE TITLE
table settings

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#216]
In the new version, when you change the table settings it reloads the page and returns the user to the first (left-most) tab, e.g. usually the Samples tab, which when you were adjusting the table settings on the Files tab is a VERY odd behavior.

**Comment by jessesiu** [comment]
Please check it again.

Thanks,
Jesse

2018-06-26 20:25 GMT+08:00 Chris Hunter <notifications@github.com>:

**Comment by only1chunts** [comment]
still does it.

**Comment by jessesiu** [comment]
Hi Chris，

I changed on the website, pls check it again.

Thanks,
Jesse

发自我的 iPhone

**Comment by only1chunts** [comment]
yay thats better, thanks.  please ensure this change gets into the github production branch
