### ISSUE TITLE
missing a space in the citations

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#219]
can we add a space between last author and publication year in the citation of all datasets .
e.g. 
http://gigadb.org/dataset/100470

Jia H; Kristiansen K; Xiao L(2018): Supporting data
should be a space between L and (2018) to become

Jia H; Kristiansen K; Xiao L (2018): Supporting data

**Comment by jessesiu** [comment]
@only1chunts Pls check it

**Comment by only1chunts** [comment]
perfect
