### ISSUE TITLE
jbrowse on penguin

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#220]
the "open jbrowse in a new window" button points to the penguin server, e.g. http://penguin.genomics.cn/jbrowse/index.html?data=100240

that needs to be changed to point to parrot now.

**Comment by only1chunts** [comment]
@jessesiu Can this ticket be closed?
This has been fixed in public server, but has it been committed to code?

**Comment by jessesiu** [comment]
@only1chunts  Yes, It can be closed. The Parrot FTP is not in the GigaDB website repo. All jbrowse links already switched to parrot in the database dump file.
