### ISSUE TITLE
odd arrows on dataset pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#222]
there are a couple of odd arrows appearing at the bottom of dataset pages, see highlighted box in screenshot_5
![screenshot_5](https://user-images.githubusercontent.com/6037145/42174026-e1d48660-7e18-11e8-915c-7c71cb6caac0.png)

**Comment by jessesiu** [comment]
@only1chunts  Pls check it again

**Comment by only1chunts** [comment]
gone :-)
