### ISSUE TITLE
ftp server link button not working

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#223]
The link to the FTP server on the files tab doesn't seem to be working, see screenshot for which link I mean:
![screenshot_16](https://user-images.githubusercontent.com/6037145/42174091-183f24a8-7e19-11e8-9171-0f810aa08e03.png)
If I right click it I can open it in a new tab, but just left clicking it doesn't do anything?

**Comment by jessesiu** [comment]
@only1chunts  Pls check it again

**Comment by only1chunts** [comment]
thats better, thanks
