### ISSUE TITLE
change highlighted button on pop-up

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#224]
When being redirected from an old version to a newer one the default highlighted action should be to "View new version" 
![screenshot_18](https://user-images.githubusercontent.com/6037145/42207735-8b5a224c-7ea2-11e8-9eb2-7f6b3559d157.png)

**Comment by jessesiu** [comment]
@only1chunts  Pls check it e.g. http://gigadb.org/dataset/view/id/100252

**Comment by only1chunts** [comment]
thats better, thanks.
