### ISSUE TITLE
italics in title

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#229]
If we encode italics (e.g. for a species name) in the title it seems to come out very small text compared tot he rest of the title!?

**Comment by jessesiu** [comment]
Pls check it

**Comment by only1chunts** [comment]
cool, thanks. make sure this gets into the main codebase

**Comment by only1chunts** [comment]
@jessesiu this issue is back (or never went away?!)
see dataset http://dx.doi.org/10.5524/100489

**Comment by jessesiu** [comment]
It's not very small text compared with the rest of title?

2018-08-07 20:33 GMT+08:00 Chris Hunter <notifications@github.com>:

**Comment by jessesiu** [comment]
You need to clean all the cache in your browser. Otherwise, it will use the
cached CSS file.



2018-08-08 14:20 GMT+08:00 Chris Hunter <notifications@github.com>:

**Comment by only1chunts** [comment]
thats wierd because I only set that to italics yesterday?!so surely it couldn't have cached something that didn't exist? and yet I just cleared the cache and now its fine. Hey ho, its fixed. Thanks.
