### ISSUE TITLE
Frictionless data plugins

### ISSUE THREAD

**Issue by ScottBGI** [gigascience/gigadb-website#247]
UKDS/OKI have developed a toolkit and plugins for things such as conversion of data and metadata to open formats, a toolchain to assess and report on data quality (e.g. validating tabular data with goodtables). Could be useful to include this in the curation workflow and also allows you to continuously test if data still works
See: https://frictionlessdata.io/articles/ukds/ & https://github.com/frictionlessdata

**Comment by only1chunts** [comment]
this ticket has been replaced by #1099
