### ISSUE TITLE
create account captcha instructions are misleading

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#25]
On the create a new user account page
 http://gigadb.org/user/create
There is a Captcha function to prevent robots from spamming us. the instructions for the captcha say "Enter both words separated by a space: "
However, the actual captcha image doesn't contain any words, it has numbers! either the captcha needs to be changed to having two words, or the instructions need to be changed to "Enter the alpha-numeric characters visible in the image below:"
![image](https://cloud.githubusercontent.com/assets/6037145/15312826/a782fe76-1c39-11e6-8c8f-618c035da19e.png)

**Comment by jessesiu** [comment]
But some time it will shows two words
![image](https://cloud.githubusercontent.com/assets/1147873/15699627/fafdee08-2800-11e6-853a-8477d9c90c1a.png)
Still need change to alpha-numeric characters?

**Comment by only1chunts** [comment]
OK, lets make the instructions say "Enter the alpha-numeric characters visible in the image below, separate individual words by a space:"

**Comment by only1chunts** [comment]
fixed in jesses branch /fix/bugs/
