### ISSUE TITLE
dataset status changes

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#250]
Please update the list of available Upload Status's to match the table below.

| status name | previous name | description |
|--------------|----------------|------------|
| ImportFromEM | None | Dataset metadata imported directly from EM via daily spreadsheet upload
| UserStartedIncomplete | Incomplete | Manual dataset submission was started by user online, but not yet submitted
| Rejected | None | Related manuscript was rejected so no need for dataset to be kept
| Not required | None  | Associated manuscript has no data.
| AssigningFTPbox | None | Editors have asked curators to check what data is required and assign an FTP dropbox to the authors so they can upload their data files
| UserUploadingData | None | Drop box details provided to user to enable data upload
| DataAvailableForReview | None  | Users have uploaded files ready for manuscript review
| Submitted | Request | Dataset has been submitted for curator review, can be either status update from ImportFromEm, OR from UserStartedIncomplete
| DataPending | None | This status should be used while the curator is working on getting the data in the correct place on the FTP server
| Curation | Uploaded | To indicate all data is now present
| AuthorReview | Pending | use to indicate the dataset is pending review by authors
| Private | Private | use to indicate the dataset is approved by user and ready to be released
| Published | Published | the final status, once the DOI is minted the status can be made Published

Does the database have space to hold the descriptions? if so add them, if not, dont worry we will include the table on the new user guide.

Statuses that matter for the import from EM work (#180):

"ImportFromEM" - this will be 1st item in the list and is the lowest status, it will be used for newly imported datasets that come directly from the upload of info from the EM daily report (#180 )

"Rejected" - will be 3rd item in list and used for datasets linked to manuscripts that are rejected, (or manually submitted datasets that we reject.) This will be updated by EM integration when manuscripts are flagged as status "Final Decision Reject"

"AssigningFTPbox" - The status will be updated to AssigningFTPbox when the manuscript has been flagged with "Get Data For Review" by the editors (i.e. from the EM integration)

"Submitted" - The status will be updated to Submitted when the manuscript has been Flagged with "Get DOI Ready for GigaDB"

Please ensure these statuses are also tracked in the curation log so that we have dates of when they change.

**Comment by rija** [comment]
Hi @only1chunts, @pli888 

Can I get a clarification on how to map the statuses above and the steps of the file upload workflow ?

Below is the file upload workflow (ignoring the preceding stages of manuscript and dataset submission, and the last stages from DOI minting):

(1) Create a drop box  for dataset/author --> (2) Drop box is created --> (3) author can use file upload wizard to upload files and metadata --> (4) all files are uploaded to drop box by author  --> (5) a link to a mockup page with link to drop box can be created and sent to reviewers --> (6) Data reviewers audit the files --> (7) Files are being moved from Drop box to public FTP --> (8) Files are available on public FTP

My understanding is that:
* (1) --> (2) is triggered by "AssigningFTPbox"
* (3) --> (4) --> (5) is triggered by "UserUploadingData"
* (7) is triggered by acceptance of the manuscript (which status above is that?)
* How about (8) ? What status shall the system set the dataset with once the files are all on the public ftp?

Also please note that (2) and (7) may not be instant, is there one or more "pending" type of status I could use?

**Comment by only1chunts** [comment]
> (1) --> (2) is triggered by "AssigningFTPbox" 

Correct

> (3) --> (4) --> (5) is triggered by "UserUploadingData"

this merges/skips multiple steps in the process.
We will set the status to "UserUploadingData" at the point we send the dropbox details to the author, initially this step is likely to be manual, unless its easy to have a standard email sent out automatically as soon as the drop-box is created? (if so then the status change can also be automated)
The author will effectively move it to the next status "DataAvailableForReview" when they complete the file upload using the file uploader, (or tell us by email if they have to use another method).
An email notification to editorial@gigasciencejournal.com when the status changes from "UserUploadingData" to "DataAvailableForReview"
The Editors will then be responsible for the next status change to either "Reject" or "Submitted"
Email notification to database@gigasciencejournal.com when status turns to "Submitted".
The curators will manually inspect datasets/files etc of datasets with status "Submitted", if more information/files are required the status will be set to "DataPending" by curators and email authors to get relevant information/files etc.
The authors (or curators) can then move the status forward to "Curation" when the requested data/files/info is/are provided.
When curator is happy with the dataset we move the status to "AuthorReview" and email the authors to make the final checks, they reply by email and curators update status to "Private" if it needs to be held before publication for any reason, or mint the DOI and move it straight to "Published".

Your (7) is not exactly triggered by anything, it is just one of the steps we do manually in the "Curation" status.
(8) As soon as we move the files to the public FTP they are technically available, but we manually set the status in the database to "AuthorReview" when we are happy the mockup of the dataset is ready for them to make a final check.

**Comment by rija** [comment]
Thanks a lot @only1chunts, it helped a lot.

Just to remove any remaining potential ambiguity, regarding:

>Your (7) is not exactly triggered by anything, it is just one of the steps we do manually in the "Curation" status.
>(8) As soon as we move the files to the public FTP they are technically available, but we manually set the status in the database to "AuthorReview" when we are happy the mockup of the dataset is ready for them to make a final check.


are you saying that:


* The mockup of the dataset you are referring to above is the currently existing functionality that create a private link to a dataset mockup pointing to public location of files (and **NOT** the dataset mockup I need to create in (5) for curators that point to the drop box location of files)
* You set the status to "AuthorReview" **AFTER** you've moved the files to the public FTP and you are happy that the dataset mockup pointing to public location of files looks OK.
