### ISSUE TITLE
Incorrect logos for LinkedIn and ORCID on login page

### ISSUE THREAD

**Issue by djcomlab** [gigascience/gigadb-website#252]
Hi guys!

I noticed that the LinkedIn and ORCID logos are the wrong way around on login page http://gigadb.org/site/login:

<img width="1089" alt="screen shot 2018-11-12 at 23 07 24" src="https://user-images.githubusercontent.com/3604134/48380470-c571fa00-e6cf-11e8-900f-748e80bc9962.png">

**Comment by only1chunts** [comment]
Hi David, Thanks for spotting that! We'll get it sorted out.

**Comment by only1chunts** [comment]
@djcomlab ,  @jessesiu has  corrected the linked-in logo, and actually removed the ORCID affiliate login for now (its not been behaving correctly so we need to make some changes to that before we allow people to use it). Thanks .
