### ISSUE TITLE
add new advisory board member

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#28]
add Guojie Zhang to the advisory panel page:
http://gigadb.org/site/advisory

use his photo from here:
http://zhanggj.cngb.org/home/wp-content/uploads/2015/01/zhangguojie.gif

and add two links to his details pages here:
http://www1.bio.ku.dk/english/staff/?pure=en/persons/438634/
and here:
http://zhanggj.cngb.org/home/?page_id=1460

**Comment by pli888** [comment]
This seems straight forward. Let's give this work to Yu zebo to do.

**Comment by pli888** [comment]
This [commit](https://github.com/gigascience/gigadb-website/commit/8178facf69c68a2df17213088df51f12abad0cd5) implements this feature request issue.
