### ISSUE TITLE
Configuring docker-postinstall role with GitLab project name

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#282]
The docker-postinstall Ansible role posts the values for the staging_private_ip, staging_public_ip and staging_tlsauth_* CI/CD environment variables in GitLab.com. The problem is that the name of GitLab project appears to be hard-coded into the [docker-postinstall/tasks/main.yml](https://github.com/gigascience/gigadb-website/blob/develop/ops/infrastructure/roles/docker-postinstall/tasks/main.yml) file, e.g. `rija-gigadb-website` in `https://gitlab.com/api/v4/projects/gigascience%2Fforks%2Frija-gigadb-website/variables`

Developers might want different names for their GitLab gigadb-website project to distinguish them from others.

One solution is to configure the GitLab project name as a variable in the [ops/infrastructure/inventories/hosts](https://github.com/gigascience/gigadb-website/blob/develop/ops/infrastructure/inventories/hosts) file which can then be picked up by the `docker-postinstall/tasks/main.yml` file when executing the Ansible staging playbook.

@rija is this the correct solution to this problem or is there a better alternative?

**Comment by rija** [comment]
Hi @pli888 ,

That approach is correct, and  ``ops/infrastructure/inventories/hosts`` is indeed the appropriate location to set such variable.

Instead of storing just the name, it's probably better to store the base url as a variable, e.g:

```
gitlab_url = "https://gitlab.com/api/v4/projects/gigascience%2Fupstream%2Fgigadb-website"
```
as some developers might run their own instance of Gitlab CI/CD server.

**Comment by rija** [comment]
An improvement to the approach described above is to set up the variable in the ansible vault file (alongside database connection strings), and then reference it in ``ops/infrastructure/inventories/hosts`` as ``vault_gitlab_url``

(As an aside,  the ``ansible_ssh_private_key_file" variable should also go into the vault file.)

That way, the ``ops/infrastructure/inventories/hosts`` can ve versioned and merged safely with no hardcoded reference to a specific fork/install.

sample below shows how the changes would appear in the host file (notice the new [all:vars] section)

```
...
[staging_dockerhost:vars]

ansible_ssh_private_key_file= {{ vault_staging_private_key_file_location }}
ansible_user="centos"
ansible_become="true"
database_bootstrap="../../sql/production_like.pgdmp"
pg_user = {{ vault_staging_pg_user }}
pg_password = {{ vault_staging_pg_password }}
pg_database = {{ vault_staging_pg_database }}
gitlab_private_token = {{ lookup('file','~/.gitlab_private_token') }}
gigadb_environment = staging
...
[production_dockerhost:vars]

ansible_ssh_private_key_file= {{ vault_production_private_key_file_location }}
ansible_user="centos"
ansible_become="true"
database_bootstrap="../../sql/production_like.pgdmp"
pg_user = {{ vault_production_pg_user }}
pg_password = {{ vault_production_pg_password }}
pg_database = {{ vault_production_pg_database }}
gitlab_private_token = {{ lookup('file','~/.gitlab_private_token') }}
gigadb_environment = production

...

[all:vars]
gitlab_url = {{ vault_gitlab_url }}
```

The ansible vault file will look like: 

```
vault_staging_pg_user: somevalue
vault_staging_pg_password: somevalue
vault_staging_pg_database: somevalue
vault_staging_private_key_file_location: somevalue

vault_production_pg_user: somevalue
vault_production_pg_password: somevalue
vault_production_pg_database: somevalue
vault_production_private_key_file_location: somevalue

vault_private_gitlab_token: somevalue
vault_gitlab_url: somevalue

```
