### ISSUE TITLE
length of external link

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#285]
There is a string length limit on the admin page to "create a new external link" (http://gigadb.org/adminExternalLink/create) . This needs to be increased to allow longer URLs.
e.g.
https://view.commonwl.org/workflows/github.com/vetscience/Assemblosis/blob/66660a64824e4c1019680c6c7ea489ea359cd5f6/Run/assembly.cwl

**Comment by rija** [comment]
may not be an issue
