### ISSUE TITLE
add FAQ - What does my dataset status mean?

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#291]
the text and image for this FAQ can be found here:
https://docs.google.com/document/d/1UyKA0_PQs44JIfkFciyKXiLoODpZ8uq7UlgBKwotRik/edit#heading=h.7dv2rrdars77

**Comment by only1chunts** [comment]
@jessesiu when you get the new statuses included in the Dev version, please can you also update the FAQ pages with these details, that way hopefully when it all goes live on the production version the information will also be available to users.

**Comment by kencho51** [comment]
@only1chunts You want the changes like this?

#### Is your feature request related to a problem? Please describe.
add an FAQ to the FAQ page (http://gigadb.org/site/faq)

#### Describe the solution you'd like
Q - What does my dataset status mean?
A - The text and image for this FAQ can be found here:
https://docs.google.com/document/d/1UyKA0_PQs44JIfkFciyKXiLoODpZ8uq7UlgBKwotRik/edit#heading=h.7dv2rrdars77

**Comment by pli888** [comment]
@kencho51 I think @only1chunts wants this `dataset status` FAQ to look like what you actually see in the [Google Doc on page 28](https://docs.google.com/document/d/1UyKA0_PQs44JIfkFciyKXiLoODpZ8uq7UlgBKwotRik/edit#heading=h.7dv2rrdars77).

**Comment by kencho51** [comment]
This [/site/guide](http://gigadb.org/site/guide) codes are chained with multiple files in production server, which have to be updated to make it work in local gigadb server.
@pli888 Peter, please help have a look on this issue.

**Comment by pli888** [comment]
@kencho51 There are a number of things you need to do to get this FAQ online:

1. Add FAQ text into `/site/faq` page
2. Add diagram image into `images` directory
3. Add `guide.php` and the other `guide*.php` files from the production server into the `protected/site` directory
4. Update `protected/controllers/SiteController.php` with new `actionGuide`, `actionGuidegenomic`, `etc` functions. Also update function `accessRules()` to enable users to access `/site/guide`, `/site/guidegenomic`, `etc`
