### ISSUE TITLE
Test data for submission wizard development

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#292]
Development of the submission wizard functionality (#241) requires test data in the GigaDB Postgresql database. Because the submission wizard is being developed by an external contractor, test data cannot contain sensitive data, *e.g.* real user email addresses.

@only1chunts says 
> the data in the [staging version of GigaDB](http://gigadb-staging-jesse.gigatools.net) is plenty for testing purposes, the issue you raised about effectively publishing all the user details in the user table is a worry and goes against the GDPR! so we do need to effectively remove those details from view. Deleting all affiliation info is fine as that data is not used anywhere.

> Keeping all @gigasciencejournal.com emails and details is fine and I would certainly like mine kept as it makes it easier for me to log in as admin on any test/dev versions deployed.

> All other names and email addresses need to be obliterated in some way, just hiding first and last letter is not enough. first names can all be "A", Is it possible to make surnames random strings of the same length as the current names? then create email addresses for each from those as A.surname@madeup.com 

> But... If we can make user 2 `liuxin@genomics.cn` an example user for White Label to use that might also be useful as that user has got 11 datasets to their name! by far the most of any user in the database. So change that username to be "Example User" and give it an email address that WhiteLabel can access (make up a new gmail box or something that we can share the password for).

**Comment by pli888** [comment]
Based on this [docker-compose.yml](https://github.com/gigascience/gigadb-website/blob/develop/ops/deployment/docker-compose.yml) file, it seems [bootstrap.sql](https://github.com/gigascience/gigadb-website/blob/develop/ops/configuration/postgresql-conf/bootstrap.sql) is being used to populate the Postgresql database in a local GigaDB.

I think the above changes described by @only1chunts need to be made to `production_like.pgdmp` and then merge these data into `bootstrap.sql` so that they are available for developing GigaDB.

**Comment by jessesiu** [comment]
![image](https://user-images.githubusercontent.com/1147873/54734457-9c5ff980-4bda-11e9-978c-07ba8b92a824.png)
@only1chunts Does this format meet your requirements.

**Comment by only1chunts** [comment]
that looks OK, but "Liuxin Liu" needs to be replaced with a "Example User" name and a new email address that we can log into and provide the log in details for to WL.

**Comment by pli888** [comment]
Is it be possible to replace the fake email addresses with `test+gigadb1@gigasciencejournal.com`? Increment the 1 digit for the next user email address so that the next email address to use would be `test+gigadb2@gigasciencejournal.com`, *etc*. In the future, if we want test sending emails from GigaDB, they would be sent to the `test@gigasciencejournal.com` email account which exists.

**Comment by only1chunts** [comment]
thats a great idea, could it perhaps make use of the user ID column number instead of just the incremental numbers?
