### ISSUE TITLE
bug fixes to github version

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#293]
there are a number of things that have been fixed in the production version recently that have not made it into the master branch on github for various reasons:

- [x] http://gigadb-staging-jesse.gigatools.net/site/help still has the old submission guidelines

- [x] http://gigadb-staging-jesse.gigatools.net/site/term the "General" heading is missing and the other headings are odd font format

- [x] http://gigadb-staging-jesse.gigatools.net/site/team Our team page has had some updates of pictures and text

- [x] the login page still has the ORCID option to login with, we removed that because we cant get a contact email from them if they use that.

- [x] The map browser of samples is not working http://gigadb-staging-jesse.gigatools.net/site/mapbrowse

- [x] The new feature of a User being able to claim authorship by associating their user account to an author name is working except for the email notification, database@ should receive a notification if an user tries to link an authors name to their account. The website tells me an email has been sent, but I dont see it in the mailbox.

- 6 FAQ's missing:
- [x] Why do you request so many sample attributes?
- [x] Why is the directory structure missing from the file table view on my dataset page?
- [x] What should I do if I accidentally identify an individual from anonymized human (meta)data within a dataset?
- [x] What curation do you carry out?
- [x] What procedures are in place to ensure data integrity?
- [x] What data storage procedures do you follow?

- [x] due to the missing style sheet in the admin pages (#289) its very difficult to tell if there anythings missing there at the moment!

**Comment by pli888** [comment]
@jessesiu how much work has been completed for this issue?

**Comment by Rahul-coder01** [comment]
Why the website is offline..

**Comment by only1chunts** [comment]
Dear @Rahul-coder01 ,  [GigaDB.org](www.gigadb.org) is the live website location and it is online. If you are referring to the temporary url listed in the above ticket this was only a temporary development staging version used for testing this particular update/code change. Please feel free to email me (chris@gigasciencejournal.com) if you require any information about GigaDB.org. Regards Chris.

**Comment by pli888** [comment]
>due to the missing style sheet in the admin pages (#289) its very difficult to tell if there anythings missing there at the moment!

@only1chunts This is fixed now - see [staging server](http://gigadb.gigasciencejournal.com:9170/site/admin).

**Comment by pli888** [comment]
@only1chunts 

>The new feature of a User being able to claim authorship by associating their user account to an author name is working except for the email notification, database@ should receive a notification if an user tries to link an authors name to their account. The website tells me an email has been sent, but I dont see it in the mailbox.

Pull request [504](https://github.com/gigascience/gigadb-website/pull/504) fixes this email sending problem.

**Comment by only1chunts** [comment]
There were lots of emails received to database@ for various author associations, I sent the first one to Rija and said I will delete any others unless he wants me to notify him. He didn't ask for them so I just deleted them all as soon as they came in.
