### ISSUE TITLE
Opening port 5432 on database container via dockerhost for pgAdmin access

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#294]
@only1chunts and his curators sometimes need to manage the GigaDB PostgreSQL database using tools such as [pgAdmin](https://www.pgadmin.org). pgAdmin requires the database container to be accepting connections on port 5432.

Currently, the [docker-compose.yml](https://github.com/gigascience/gigadb-website/blob/develop/ops/deployment/docker-compose.yml) file tells the database container to only allow linked container services on the `db-tier` network access to PostgreSQL using the `expose` instruction.

`expose` will not allow communication via the defined ports to containers outside of the same network or to the host machine. To allow this to happen, we need to use the `ports` instruction to get port 5432 on the `database` container published on the `dockerhost` to another port, e.g. `54321`. pgAdmin can then connect to PostgreSQL on the database container via `dockerhost` and port `54321`.

In the [docker-compose.yml](https://github.com/gigascience/gigadb-website/blob/develop/ops/deployment/docker-compose.yml) file, this will require replacing in the `database` service:
```
expose:
  - "5432"
```

with:
```
ports:
  - "54321:5432"
```

We need to be aware of [security issues](https://serverfault.com/questions/627169/how-to-secure-an-open-postgresql-port) with allowing external access to PostgreSQL via port 5432.

**Comment by pli888** [comment]
> We need to be aware of security issues with allowing external access to PostgreSQL via port 5432.

@only1chunts the curators will need access to the GigaDB PostgreSQL database using the pgAdmin tool in the production GigaDB website?

@jessesiu you will use pgAdmin on a local GigaDB application for development work? I will presume pgAdmin access won't be required in a stage version of GigaDB.

**Comment by jessesiu** [comment]
@pli888 I have some JDBC scripts needs to use the production GigaDB 5432 port in the intranet and also the CNGB team maybe can index us from this port in the intranet. But for the stage version, not need to open this port.

**Comment by only1chunts** [comment]
I'm assuming the postgresql database is the thing that deals with the ftp-userN dropbox passwords? the intention is that Rija's FileUploader work will handle all the creation of dropboxes and the associated passwords etc, so when that is done, curators shouldn't need to use the current methods.

**Comment by pli888** [comment]
> I'm assuming the postgresql database is the thing that deals with the ftp-userN dropbox passwords? 

@only1chunts No, its the database that holds the information about datasets, authors, etc.

**Comment by only1chunts** [comment]
In which case the curators have no need to do anything by direct access to the database, everything is done via the admin pages in website.

**Comment by pli888** [comment]
> I have some JDBC scripts needs to use the production GigaDB 5432 port in the intranet and also the CNGB team maybe can index us from this port in the intranet. But for the stage version, not need to open this port.

@jessesiu I will publish port 5432 from the database container on a port on the dockerhost machine when I come to write the `docker-compose.production.yml` file for deploying a production GigaDB on a CNGB server. I will also publish port 5432 on a local GigaDB installation for your development work.
