### ISSUE TITLE
Problem with building application Docker image

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#296]
When the `application` image is being built, it generates an error message:
```
checking for sodium support... yes, shared
checking for pkg-config... /usr/bin/pkg-config
checking for libsodium... configure: error: Libsodium 1.0.0 is too old, version >= 1.0.9 required
ERROR: `/tmp/pear/temp/libsodium/configure --with-php-config=/usr/local/bin/php-config' failed
```

The cause of this error seems to be a result of the `libsodium13` package being installed and then `pecl` tries to install `libsodium-2.0.21` which is incompatible and therefore generates the error.

Editing the `gigadb-website/ops/packaging/Dockerfile` so that line 153 is:
```
pecl install libsodium-1.0.6 && \
```

appears to fix the error so that the `application` image builds.

This [`pecl` documentation](https://hub.docker.com/_/php) says that it is best to use a version number when installing PHP extensions.

@jessesiu can you check the above works for you please?

@rija can you check if you have this problem please?

**Comment by jessesiu** [comment]
@pli888 after rebuilding the application and test images, the libsodium get installed now

**Comment by pli888** [comment]
Whilst using `libsodium-1.0.6` will allow the `application` image to build, starting the `application` container displays an error message:
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/sodium.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/sodium.so: cannot open shared object file: No such file or directory in Unknown on line 0

```

**Comment by rija** [comment]
Hi @pli888, 

Last time the image container was built successfully on my machine was 11 days ago and I've used the functionality enabled by libsodium every day since wihout any issue (locally, as well as on CI where the image gets built everytime).

I've deleted the image just now on my machine and rebuilt it to check, and the build fails for me but, not because of libsodium but something wrong with the Debian repos (similar to an issue Jesse emailed me couple of weeks ago). I'll sort myself out with that respect and then will look at what may be going on with your libsodium incident.

**Comment by pli888** [comment]
I have a problem with the Debian repos too since `Step 3/41 : RUN apt-get update ...` in `gigadb-website/ops/packaging/Dockerfile` fails.

I added the following lines into the `Dockerfile` before `RUN apt-get update && \` to do some testing:
```
RUN echo "deb http://ftp.hk.debian.org/debian jessie main" | tee /etc/apt/sources.list && \
    echo "deb http://ftp.hk.debian.org/debian-security jessie/updates main" | tee -a /etc/apt/sources.list && \
    echo "deb http://ftp.cvut.cz/debian jessie-updates main" | tee -a /etc/apt/sources.list
```

**Comment by pli888** [comment]
I managed to get things working again including the libsodium problem with this [Dockerfile](https://github.com/pli888/gigadb-website/blob/libsodium-build-error/ops/packaging/Dockerfile).

**Comment by rija** [comment]
Great. 
Interestingly It works for me only if I remove the CZ mirror.

Also, you can combine the first two RUN as below, otherwise it will create an additional, separate layer:
```
RUN echo "deb http://ftp.hk.debian.org/debian jessie main" | tee /etc/apt/sources.list && \
    echo "deb http://ftp.hk.debian.org/debian-security jessie/updates main" | tee -a /etc/apt/sources.list && \
    apt-get update -yq && \
    apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        bc
```

**Comment by rija** [comment]
ok, the following works for me (replaced **jessie-updates** by **jessie**)

```
# Problem with Debian repos - adding repos to use below
RUN echo "deb http://ftp.hk.debian.org/debian jessie main" | tee /etc/apt/sources.list && \
    echo "deb http://ftp.hk.debian.org/debian-security jessie/updates main" | tee -a /etc/apt/sources.list && \
    echo "deb http://ftp.cvut.cz/debian jessie main" | tee -a /etc/apt/sources.list && \
# basic dependencies
    apt-get update -yq && \
    apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        bc
```

**Comment by rija** [comment]
By the way, we are  not the only ones currently seeing this problem:

https://github.com/circleci/circleci-images/issues/269

I think there's more to it, than just changing the source urls.

**Comment by rija** [comment]
I think I've got to the bottom of the issue.

The current problem may be an aftermath of this annoucement:

https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

However, as said in that message as well as on the official LTS page for Debian 8 (Jessie):

https://wiki.debian.org/LTS/Using

Jessie on amd64 platform (which is what we use) should not be impacted by the annoucement as it is supported until end of June 2020.

Furthermore, if we apply the instructions from the official LTS page, it will currently break the way we've been seeing, so it's clearly an issue on Debian side.

This is not the first time, it happened in February 2015 with Debian 7 (squeeze):

https://lists.debian.org/debian-security/2015/02/msg00036.html

and most likely in October 2018 with Debian 8 (Jessie):

https://github.com/circleci/circleci-images/issues/269#issuecomment-432044646


In both case, it was eventually resolved.

Based on the official instructions for LTS and the current issue, I updated the Dockerfile as below and it works for me:

```
# Problem with Debian repos - adding official LTS repos to use below
RUN echo "deb http://deb.debian.org/debian/ jessie main contrib non-free" | tee /etc/apt/sources.list && \
    echo "deb-src http://deb.debian.org/debian/ jessie main contrib non-free" | tee -a /etc/apt/sources.list && \
    echo "deb http://security.debian.org/ jessie/updates main contrib non-free" | tee -a /etc/apt/sources.list && \
    echo "deb-src http://security.debian.org/ jessie/updates main contrib non-free" | tee -a /etc/apt/sources.list && \
# the two repo below are the problematic ones, so commenting them out until debian fix them
#    echo "deb http://deb.debian.org/debian/ jessie-updates main contrib non-free" | tee -a /etc/apt/sources.list && \
#    echo "deb-src http://deb.debian.org/debian/ jessie-updates main contrib non-free" | tee -a /etc/apt/sources.list && \
# basic dependencies
    apt-get update -yq && \
    apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        bc && \
    docker-php-ext-install mcrypt

# Install the PHP pdo_pgsql extention
RUN docker-php-ext-install pdo_pgsql

...

```

**Comment by pli888** [comment]
Thanks @rija. I will merge your code into the `develop` branch along with the fix for the libsodium problem.

**Comment by rija** [comment]
You're welcome @pli888.  
Thanks for providing the fix for the libsodium issues.
At some point in the future (we've got time for that, and it's not trivial, so no rush), we will probably need to rebuild our Dockerfile to use Debian 9 Stretch as base image for the application/test/bastion containers.

**Comment by pli888** [comment]
The `with_new_cert_deploy` job is broken in the [gitlab.com](https://gitlab.com) CI/CD pipeline for GigaDB. This is because the `with_new_cert_deploy` section in [gitlab-ci.yml](https://github.com/gigascience/gigadb-website/blob/develop/.gitlab-ci.yml) references [docker-compose.build.yml](https://github.com/gigascience/gigadb-website/blob/develop/ops/deployment/docker-compose.build.yml) which uses [Production-Dockerfile](https://github.com/gigascience/gigadb-website/blob/develop/ops/packaging/Production-Dockerfile) to build the application container. However, executing [Production-Dockerfile](https://github.com/gigascience/gigadb-website/blob/develop/ops/packaging/Production-Dockerfile) results in an error message:
```
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
```

**Comment by pli888** [comment]
>The with_new_cert_deploy job is broken in the gitlab.com CI/CD pipeline for GigaDB. This is because the with_new_cert_deploy section in gitlab-ci.yml references docker-compose.build.yml which uses Production-Dockerfile to build the application container. However, executing Production-Dockerfile results in an error message:
```
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)
```

This appears to be the same problem as above that results in `sodium` not being able to to be installed. The same fix allowed `sodium` to be installed and the `with_new_cert_deploy` job to successfully finish with GigaDB being deployed on a [staging server](https://gigadb-staging.gigatools.net).
