### ISSUE TITLE
Supporting Different Screens

### ISSUE THREAD

**Issue by jessesiu** [gigascience/gigadb-website#31]
This may not be an issue with the latest dev version so its possible this ticket can just be closed, but the current production version doesn't behave well on certain screen sizes.

>As a website user
>I want to be able to see all dataset pages on any device
>So that I get a consistent user experience on any device

**Comment by only1chunts** [comment]
This is what a dataset on GigaDB.org looks like on my mobile:
![screenshot_2018-11-13-15-43-49-766_com android chrome](https://user-images.githubusercontent.com/6037145/48424906-9ef9a080-e75b-11e8-9cb6-f841d02129a1.png)
it is the same for all datasets, its missing the vital information at the top of the screen. This example was www.doi.org/10.5524/100533
This needs doing in combination with #152 so the mobile view uses the simplified view.

**Comment by pli888** [comment]
As an example of how other databases do this, take a look at how PDB displays web pages for a [protein structure](http://www.rcsb.org/structure/6BKI) on a desktop PC and a handheld device.

**Comment by rija** [comment]
closing as fixed in fuw-cicd branch (at least for tablet size). Will createissue a problem
