### ISSUE TITLE
adminSample/admin page give an error

### ISSUE THREAD

**Issue by jessesiu** [gigascience/gigadb-website#317]
**Describe the bug**
The URL link http://gigadb.gigasciencejournal.com:9170/adminSample/admin
will return 
Error 500 
Property "Sample.fullAttrDesc" is not defined.

**To Reproduce**
1. Go to 'http://gigadb.gigasciencejournal.com:9170/adminSample/admin'
2. See error

**Screenshots**
<img width="543" alt="屏幕快照 2019-05-16 下午5 03 15" src="https://user-images.githubusercontent.com/1147873/57841461-2bfddf00-77fd-11e9-92f9-49771872ed9b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Comment by only1chunts** [comment]
no longer an issue.
