### ISSUE TITLE
Typo in FAQ

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#318]
**Describe the bug**
Typo. "preious public annotations" -> "previous public annotations"

**To Reproduce**
1. Go to http://gigadb.org/site/faq
2. Click on 'What is Hypothes.is?'

**Comment by ChrisArmit** [comment]
![Screen Shot 2019-11-04 at 17 05 50](https://user-images.githubusercontent.com/33310581/68140517-db517e00-ff23-11e9-990e-de97ee661be3.png)

**Comment by jessesiu** [comment]
it updated on the public website.

**Comment by pli888** [comment]
This `preious public annotations` typo is still present in the `develop` branch in [faq.php](https://github.com/gigascience/gigadb-website/blob/develop/protected/views/site/faq.php) so re-opening this issue.
