### ISSUE TITLE
add twitter feed as a tab

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#319]
in the same way BiorXiv have all the tweets relating to each article listed at the bottom of their articles we should have a tab displaying all tweets mentioning the GigaDB dataset by DOI or URL.

**Comment by ScottBGI** [comment]
FYI Altmetric plugin is not the way to do this now they are charging: https://blog.zenodo.org/2020/07/09/2020-07-09-altmetric-badges/

**Comment by only1chunts** [comment]
@ScottBGI I think your comment is more relevant to issue #137 (dataset metrics)

**Comment by only1chunts** [comment]
I dont think we want twitter stuff added to datasets anymore. If we decide we want BlueSky or something else then we can create a new ticket for that

**Comment by ScottBGI** [comment]
Is there a bluesky widget as that seems to be the platform everyone has moved to now? It finally looks like there is an alternative for twitter.
