### ISSUE TITLE
new version notice in GigaDB

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#32]
At some point since release the notice that pops up at users when they visit a dataset that has been superseded by a newer version, eg. http://gigadb.org/dataset/100015 used to have a notice telling users that went to it saying there is a new version available here http://gigadb.org/dataset/100038
It no longer happens. 
@jessesiu please can you work out why? and fix it.

**Comment by jessesiu** [comment]
Done, will commit in the repo.

**Comment by only1chunts** [comment]
Fixed in jesse's branch /fix/bugs/
