### ISSUE TITLE
hypothes.is is missing?

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#320]
We used to have hypothes.is visible on all GigaDB pages regardless of users being logged in, but that seems to have disappeared at some stage. Can we reinstate it?

**Comment by jessesiu** [comment]
@only1chunts Please test it again on the GigaDB pages.

**Comment by tuli** [comment]
It looks fine now; the only thing I suggest is that the log in wording is
"you must be logged into hypothes.is" to avoid confusion in case users
think it means they must be logged into Giga.

M.A.

**Comment by jessesiu** [comment]
Doing the CI/CD now, will send the pull request soon
