### ISSUE TITLE
When to update API docs using PHPDoc?

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#321]
Updating API docs using PHPDoc results can result in changes to hundreds of files in the `docs` directory. For example, see this [commit](https://github.com/gigascience/gigadb-website/pull/316/commits/4f34c00737ce2cfcada1a777cd0ca79875a09f0b) by @jessesiu. If all these changed files are committed into the Github repo, it seems to detract from the code changes directly related to the issue being addressed.

@rija Would a better solution be to commit updates to the API docs only when `official` releases of GigaDB are made?

**Comment by rija** [comment]
@pli888,

yes, updating the phpdocs can be distracting if done as part of regular code change.
You can indeed run phpdocs when making a release. Or maybe it can also be done as a separate dedicated commit  (with only the artefacts generated following running phpdocs) if there's a need to update documentation before a release (which may be desirable if a contributor want to peruse an up-to-date version and a release is not scheduled soon)
