### ISSUE TITLE
Database schema changes for submission wizard

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#324]
Database schema changes are required for developing the submission wizard #241. The following schema changes have been proposed by @lump1k:

1. dataset dataset_size can be NULL because we dont have it at the creating form now
2. image source can be NULL
3. image character can be NULL because some licenses dont need a photographer (Image Credit)
4. contribution table for credits in Author tab
5. author contribution_id to relate author and credit
6. dataset additional_information for adding values which user check in Additional Information TAB
7. external_link fields type and description need it in Additional Information TAB (Other links)
8. prefix regexp for validation in Additional Information TAB (Public data archive links)
9. dataset funding user need fundings or not
10. funding table
11. sample description new field because need it
12. sample_template table for sample tamplates
13. sample_template_attribute for attributes for sample template

**Comment by pli888** [comment]
Responses by @only1chunts to proposed database schema changes:

**DATASET table**
>1. dataset_size can be NULL because we dont have it at the creating form now 

agreed

**IMAGE Table**
>2. image source can be NULL 

Why? as far as I can tell there should always be a source of the image recorded

>3. image character can be NULL because some licenses dont need a photographer (Image Credit) 

What is "Image character"? The image table contains:
* ID
* location
* tag
* URL
* license
* photographer
* source

All images should have an ID, location, source, license, tag and a photographer. NOTE - Even when the generic GigaDB logo is chosen by the user those fields are still filled:
* Image source  = GigaDB
* Image Tag = no image icon
* Image license = public domain
* Image Photographer = GigaDB

**CONTRIBUTION table**
>4. contribution table for credits in Author tab

Agreed, there needs to be a place to hold the CREDIT names, please call the table CREDIT with these columns:
* ID - for the unique database row ID
* Name - name of the role
* Source - the link to the original source of the role
* Description - for the description of the role

>5 - author contribution_id to relate author and credit

The AUTHOR table MUST remain dataset independant, instead please use the DATASET_AUTHOR table for this, add a column for contribution ID.

> 6 - dataset additional_information for adding values which user check in Additional Information TAB

NO! all the additional_information goes in the appropriate tables. Perhaps that was not entirely clear from the powerpoint slides so I can expand on the details here. Please feel free to ask more questions on this, as its fundamental to the project!

The additional information tab by sections:
* add a public archive link - these details are stored in the LINK table (*-see also 8 
* Related GigaDB dataset link - these details are stored in the RELATION table, with the dropdown sections from the RELATIONSHIP table
* Collaboration links - these are stored in the DATASET_PROJECT table with the dropdown list coing from the PROJECT table
* Other links, Published manuscript - these are stored in MANUSCRIPT table
* Other links, protocols - these are stored in EXTERNAL_LINK table with the link type = protocols.io
* Other links, SketchFab - these are stored in EXTERNAL_LINK table with the link type = SketchFab
* Other links, Code Oceans - these are stored in EXTERNAL_LINK table with the link type = Code Ocean
* Other links, Other URLS - these are stored in EXTERNAL_LINK table with the link type = Additional Information

>7 - external_link fields type and description need it in Additional Information TAB (Other links)

See 6 above & the EXTERNAL_LINK table will need an additional column for the "Link Description".

>8 - prefix regexp for validation in Additional Information TAB (Public data archive links)

There is a need for a regex column to be added to the PREFIX table. The type of ID (i.e. which database the ID is from) will determine the regex to be implemented. Currently the PREFIX table has columns for ID, prefix, source and URL, we should add columns for "RegEx" and for "Description". I will curate the content for those columns which we can add to the develop branch version of the database.

>9 - dataset funding user need fundings or not

The addition of funding information is not mandatory.

>10 - funding table

Not sure what this point means in your list? There is already a table for the funding bodies (to be selected by user in slide 22 of power point) called FUNDER_NAME. The other 3 fields on the form in slide 22 are all stored in the database table DATASET_FUNDER.

>11 - sample description new field because need it

Not needed. The descriptions (and all other sample attributes) are stored in the SAMPLE_ATTRIBUTE table.

>12 - sample_template table for sample templates

This is a very good point! We need to proivide the templates information somehow, is a database table the best option for this? we should discuss this via Skype. The fields to be included are already determined, but how to store those in a way that is useful to you/the website is not yet determined.

>13 - sample_template_attribute for attributes for sample template

Not needed. All attributes used in any sample template must be from the ATTRIBUTES table.

**Comment by lump1k** [comment]
I cant remove additional_information from dataset table
because i will not know is it everything no or it's only the start
http://i.imgur.com/DgBZqd6.png

the same with funding tab. i must have some flag

**Comment by only1chunts** [comment]
Hi, 
Sorry i don't understand why you want to remove additional information tab? 
Please explain the problem. 
Thanks 
Chris

**Comment by lump1k** [comment]
Hello
if user click  "NO" for Public data archive links, Public data archive links, etc  I will not know what to show next time on this tab. because he can return on it. and i have to show this: http://i.imgur.com/DgBZqd6.png or everything with "NO" http://i.imgur.com/9oVJt72.png

**Comment by only1chunts** [comment]
just leave it with the No highlighted. if you remove the tab they will not have the option to change their mind and add them later.

**Comment by only1chunts** [comment]
@lump1k , regarding number 12&13 above; we have discussed this and agree that we should have 2 new tables for this;
TEMPLATE_NAME which has the columns;
ID
template name
template description (to allow us to include a short description of the sorts of datasets that this template might be useful for)
notes (this is to allow us to include internal notes like whether the template was generated from an external checklist /recommendation or something)

and
TEMPLATE_ATTRIBUTES
ID
template_name_ID
attribute_ID

please let me know if you have any questions on this.
Note @pli888 I will add another github ticket to request a future development for the inclusion of an admin page to allow us to generate/edit templates.

**Comment by lump1k** [comment]
@only1chunts 
so if user go to this tab first time he should see this
http://i.imgur.com/bcuuEja.png
yes?

**Comment by only1chunts** [comment]
the first time neither yes or no should be highlighted, the user will need
to select. If they go back to that page after having selected yes or no,
they should see whatever they previously selected.

**Comment by only1chunts** [comment]
@lump1k proposed an additional change to the schema that I think is also required. 
DATASET table will require 2 new columns, "additional_information" and "funding information", these are boolean values, (null or not null). The usage is purely for the submission wizard display of the "additional information" and "Funding" tabs. Upon first visit to the additional information tab the default value will be null in the DATASET table, this tells the web-app that fields should all be displayed with neither yes or no highlighted. Upon selection and saving of any yes OR no values in the submission wizard by the user, the database table will be updated with not-null value.
A not-null value tells the web-app that the page has been visited before for that dataset and the values will either be yes or no (i.e. one or other will be highlighted) if nothing is stored in the relevant database table then the answer to the question is NO, if there is something in the relevant database table then it is displayed in the submission wizard.

**Comment by pli888** [comment]
@only1chunts @jessesiu By comparing the database schema for GigaDB with the WL dataset submission wizard with that of the production GigaDB, these are the schema differences:

## New tables in data submission wizard

### Table: contribution

Column Name | type
----------- | ----
id | integer DEFAULT nextval('public.contribution_id_seq'::regclass) NOT NULL
name | character varying(255) NOT NULL
source | character varying(255) NOT NULL
description | character varying(255) NOT NULL

### Table: template_attribute

Column Name | type
----------- | ----
id | integer DEFAULT nextval('public.template_attribute_id_seq'::regclass) NOT NULL
template_name_id | integer
attribute_id | integer

### New table: template_name

Column Name | type
----------- | ----
id | integer DEFAULT nextval('public.template_name_id_seq'::regclass) NOT NULL
template_name | character varying(50) NOT NULL
template_description | character varying(255)
notes | character varying(255)

<hr>

## Tables with different column types in data submission wizard

### WL table: attribute

Column Name | type
----------- | ----
id | `integer DEFAULT nextval('public.attribute_id_seq'::regclass) NOT NULL`
attribute_name | character varying(100)
definition | character varying(1000)
model | character varying(100)
structured_comment_name | character varying(50)
value_syntax | character varying(500)
allowed_units | character varying(100)
occurance | character varying(5)
ontology_link | character varying(1000)
note | character varying(100)

### Production table: attribute

Column Name | type
----------- | ----
id | `integer NOT NULL`
attribute_name | character varying(100)
definition | character varying(1000)
model | character varying(100)
structured_comment_name | character varying(50)
value_syntax | character varying(500)
allowed_units | character varying(100)
occurance | character varying(5)
ontology_link | character varying(1000)
note | character varying(100)

<hr>

## Tables with different number of columns in data submission wizard 

### WL table:dataset

Column Name | type
----------- | ----
id | integer NOT NULL
submitter_id | integer NOT NULL
image_id | integer
identifier | character varying(32) NOT NULL
title | character varying(300) NOT NULL
description | text DEFAULT ''::text NOT NULL
dataset_size | bigint
ftp_site | character varying(100) NOT NULL
upload_status | character varying(45) DEFAULT 'AuthorReview'::character varying NOT NULL
excelfile | character varying(50)
excelfile_md5 | character varying(32)
publication_date | date
modification_date | date
publisher_id | integer
token | character varying(16) DEFAULT NULL::character varying
fairnuse | date
curator_id | integer
manuscript_id | character varying(50)
`additional_information` | `smallint`
`funding` | `smallint`
`is_test` | `smallint`
`creation_date` | `date`
`is_deleted` | `smallint`

### Production table:dataset

Column Name | type
----------- | ----
id | integer NOT NULL
submitter_id | integer NOT NULL
image_id | integer
identifier | character varying(32) NOT NULL
title | character varying(300) NOT NULL
description | text DEFAULT ''::text NOT NULL
dataset_size | bigint NOT NULL
ftp_site | character varying(100) NOT NULL
upload_status | character varying(45) DEFAULT 'Pending'::character varying NOT NULL
excelfile | character varying(50)
excelfile_md5 | character varying(32)
publication_date | date
modification_date | date
publisher_id | integer
token | character varying(16) DEFAULT NULL::character varying
fairnuse | date
curator_id | integer
manuscript_id | integer

<hr>

### WL table:dataset_author

Column Name | type
----------- | ----
id | integer NOT NULL
dataset_id | integer NOT NULL
author_id | integer NOT NULL
rank | integer DEFAULT 0
role | character varying(30)
`contribution_id` | `integer`

### Production table:dataset_author

Column Name | type
----------- | ----
id | integer NOT NULL
dataset_id | integer NOT NULL
author_id | integer NOT NULL
rank | integer DEFAULT 0
role | character varying(30)

<hr>

### WL table: external_link

Column Name | type
----------- | ----
id | integer NOT NULL
dataset_id | integer NOT NULL
url | character varying(128) NOT NULL
external_link_type_id | `integer`
`description` | `character varying(200)`

### Production table: external_link

Column Name | type
----------- | ----
id | integer NOT NULL
dataset_id | integer NOT NULL
url | character varying(128) NOT NULL
external_link_type_id | `integer NOT NULL`

<hr>

### WL table:prefix

Column Name | type
----------- | ----
id | integer DEFAULT nextval('public.link_prefix_id_seq'::regclass) NOT NULL
prefix | character(20) NOT NULL
url | text NOT NULL
source | character varying(128) DEFAULT ''::character varying
icon | character varying(100)
`regexp` | `character varying(128)`

### Production table: prefix

Column Name | type
----------- | ----
id | integer DEFAULT nextval('public.link_prefix_id_seq'::regclass) NOT NULL
prefix | character(20) NOT NULL
url | text NOT NULL
source | character varying(128) DEFAULT ''::character varying
icon | character varying(100)

<hr>

## List of unchanged tables
 * AuthAssignment
 * AuthItem
 * YiiSession
 * alternative_identifiers
 * author
 * author_rel
 * curation_log
 * dataset_attributes
 * dataset_funder
 * dataset_log
 * dataset_project
 * dataset_sample
 * dataset_session
 * dataset_type
 * exp_attributes
 * experiment
 * extdb
 * external_link_type
 * file
 * file_attributes
 * file_experiment
 * file_format
 * file_relationship
 * file_sample
 * file_type
 * funder_name
 * gigadb_user
 * type
 * image
 * link
 * manuscript
 * news
 * project
 * publisher
 * relation
 * relationship
 * rss_message
 * sample
 * sample_attribute
 * sample_experiment
 * sample_rel
 * schemup_tables
 * search
 * species
 * tbl_migration
 * unit
 * user_command
 * yiisession

<hr>

Count | Total
----- | -----
No. of unchanged tables | 48
No. of changed tables | 8
No. of tables in data submission wizard database | 56

**Comment by only1chunts** [comment]
Thanks for the lists @pli888 very useful.
All 3 new tables are required and appear correct.
ATTRIBUTE table - change seems appropriate
EXTERNAL_LINK table - changes are fine
PREFIX table - changes are fine

DATASET table - I would need to see some descriptions of what those additional variables are for (@lump1k ) ?:
  - I dont know what "additional information" would be held there, as far as I know all the additional information is held in a variety of other tables depending on the type of additional information. 
  - The "funding" variable seems NOT required as we already have the dataset_funder table to hold that information.
  - "creation date" I thought was implicit in the database anyway, but if its required as an explicit variable then fine.
  - "is_test" presumably something to do with demarking a dataset as a test submission?!
  - "is_deleted" no idea what this is for ??? surely if something is deleted then its not present, so why is a variable needed for it?

DATASET_AUTHOR table - the variable "role" was meant to be used to hold the contributor role so we dont need both "role" and "contribution_id" just one or the other will be fine.

**Comment by pli888** [comment]
@only1chunts Looking at the submission wizard practice area part of the WL work, I'm confirming they are following changes to the `dataset` table:

The `dataset` table has 2 new columns:
* is_test smallint NULL
* creation_date date NULL

**Comment by pli888** [comment]
> * "is_deleted" no idea what this is for ??? surely if something is deleted then its not present, so why is a variable needed for it?

The `is_deleted` column in the dataset table is for the undo function - see #212.

**Comment by only1chunts** [comment]
all of this is covered in various other tickets or has been completed. I'm happy yo close this ticket.
