### ISSUE TITLE
Dataset Upload page - Download template file error

### ISSUE THREAD

**Issue by jessesiu** [gigascience/gigadb-website#326]
**Describe the bug**
Can't get the template files when clicking the download button on the /datasetSubmission/upload page

**To Reproduce**
1. Go to /datasetSubmission/upload
2. Click on Download Template File or Download Example File
3. See error

**Screenshots**
Error 404
Unable to resolve the request "files/GigaDBUploadForm.xls".

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by only1chunts** [comment]
closing as we will move away from the spreadsheet templates when we have the submission wizard anyway.
