### ISSUE TITLE
Hi-C data vis with Juicebox integration or widgets E613

### ISSUE THREAD

**Issue by ScottBGI** [gigascience/gigadb-website#329]
## User Story

>AS a website user
>I want add to visualise Hi-C heat maps
>So that it is easy to see how contiguous fragments of chromosomes are assigned

## Acceptance Criteria

>Given I have a dataset with one or more `.hic` files
>When I navigate to the dataset page
>Then I should see a tab called "Juicebox"
>And I can see in that tab a visualization of the `.hic` files

# Additional info

The javascript library for implementing the visualizer is on Github: https://github.com/igvteam/juicebox.js

After talking to Erez Aiden at PAG Asia sounds very easy to optimise GigaDB to plug in his Hi-C visualisation tool Juicebox. He said our code base might already be optimised and it sounds like it just plugs in. If GEO can install it he thinks it should be much easier with us. We already have a lot of Hi-C datasets, and numbers are increasing. See:

http://gigadb.org/search/new?keyword=Hi-C

Code and documentation should be here:

https://www.aidenlab.org/juicebox/
https://github.com/aidenlab/Juicebox/wiki/Download

this Story is part of Epic #613

**Comment by ScottBGI** [comment]
Can read more in bioRxiv https://doi.org/10.1101/254797

**Comment by ScottBGI** [comment]
Sanger people recommending we use HiGlass for this task as they say its higher resolution and less buggy. Should take a look at https://higlass.io/

Can read more in the paper here: dx.doi.org/10.1186/s13059-018-1486-1

**Comment by ScottBGI** [comment]
Sanger now publishing first genomes through Wellcome Open Research. They seem to have interactive plugin for the first two examples with Juicebox but don't seem to have it working for HiGlass. You can see the two examples in Fig 4 of these papers:

https://wellcomeopenresearch.org/articles/5-18
https://wellcomeopenresearch.org/articles/5-33

They seem to use the following javascript, so would this work for our examples?

<a target="_blank" href="https://wellcomeopenresearch.s3.amazonaws.com/manuscripts/17235/dbc9dc65-ce5f-4c3e-95b7-897e667c318a_figure4.gif" data-framesrc="https://aidenlab.org/juicebox/?juiceboxURL=http://bit.ly/2SmuPBj"><img alt="dbc9dc65-ce5f-4c3e-95b7-897e667c318a_figure4.gif" src="https://wellcomeopenresearch.s3.amazonaws.com/manuscripts/17235/dbc9dc65-ce5f-4c3e-95b7-897e667c318a_figure4.gif" title="Open the interactive figure in a popup window." style="margin-bottom: 40px;"><span class="research-layout"><span class="f1r-icon-circle-wrapper light-grey-bg article-page-mobile-image-icon" style="margin-top: -15px; margin-right: -2px; margin-left: -30px;"><span class="f1r-icon icon-42_new_window orange"></span></span></span><span class="_mdl-layout f1r-article-desk"><button title="Open the interactive figure in a popup window." class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--icon mini-icon custom-image-icon" data-upgraded=",MaterialButton,MaterialRipple"><i class="material-icons">open_in_new</i><span class="mdl-button__ripple-container"><span class="mdl-ripple"></span></span></button></span></a><div class="f1r-article-desk-inline open-static-interactive-image" style="top: 176px;"><a href="#" class="js-open-static-image">View static version of this image</a></div><div class="caption"><h3>Figure 4. Genome assembly of <i>Lutra lutra</i> mLutLut1: Hi-C contact map.</h3><p id="d3154e893">Hi-C contact map of the L. lutra mLutLut1 assembly, visualized in Juicebox (<a href="#ref-6">Durand <i>et al.</i>, 2016</a>). An interactive version of the map hosted <a target="xrefwindow" href="https://aidenlab.org/juicebox/?juiceboxURL=http://bit.ly/2SmuPBj" id="d3154e901">here</a>, powered by Juicebox.js (<a href="#ref-12">Robinson <i>et al.</i>, 2018</a>).</p></div><div class="f1r-article-desk interactive-content-ribbon js-custom-image-open"><div class="interactive-content-label article-custom-image">Interactive figure</div><div class="interactive-content-button"></div></div><div class="f1r-article-mobile mobile-interactive-note">View on desktop for interactive features<img src="/img/icon/interactive_content.png" class="float-right margin-right-40"></div>

**Comment by only1chunts** [comment]
the interactive version is actually hosted on the Aiden lab server with the article just linking an iframe window to it. The static version is hosted by welcome open research. 
This is very similar to what we do with the sketchfab, code ocean and protocols.io widgets at the moment, so should be pretty easy to add this for the Aiden Lab widget of Juicebox, but it will require the Aiden Lab people to generate and host the actual data, which I'm not sure they would be willing to do for just anyone?!

**Comment by only1chunts** [comment]
To host our own visualisations without relying on external sources being persistent for us to link to we need to assess which tool works best for our needs, here is a selection of possible options available now:
Juicebox & Juicer 
HiGlass & HiPiler http://hipiler.higlass.io/explore 
HiCPlotter https://github.com/kcakdemir/HiCPlotter 

A more comprehensive list of tools is available here 
https://www.4dnucleome.org/software.html

**Comment by ChrisArmit** [comment]
Juicebox is visualization software for Hi-C data.
https://github.com/aidenlab/Juicebox

A test example has been created by Chris H:
http://gigadb.org/dataset/view/id/200070/token/ImP3Bbu7ytRSfYFh

Juicebox is displayed in an iFrame in GigaDB, but the Contact Map for a given dataset is not shown by default.

**Comment by only1chunts** [comment]
related to this, there is a 3D image viewer widget ([ViewSTL](https://www.viewstl.com/)) that we would like to integrate in the same way for .stl files (see #2054), perhaps that can be investigated at the same time? Note. The STL viewer is probably of higher importance than this HiC viewer, as there is a real possibility that SketchFab will remove the function that we utilise at the moment.

**Comment by luistoptal** [comment]
@only1chunts I was looking at this right now. I think it would make sense to split this into two separate issues, one for hic files and another one for stl

**Comment by only1chunts** [comment]
its already two issues (this one, and #2054) , but can you prioritise the STL viewer over the HiC viewer please.

**Comment by luistoptal** [comment]
Suggested library: HiGlass https://higlass.io/app , slighlty more use, seems better maintained and better docs (311 github stars, last update 1 week ago), compared to juicebox (245 github stars, last update 3 months ago)

How it works:

- raw files are preprocessed with a python script (it can easily be run using the docker container as described here: https://github.com/higlass/higlass-docker)
- preprocessed files are stored somewhere
- website user requests visualization, preprocessed files are serverd as input to the HiGlass frontend application (which can be embedded in out website)

Suggested flow:

- curators use a command line script to preprocess the raw data
- curator stores preprocessed data as dataset file
- dataset view receives preprocessed file, and shows a data representation

**Comment by only1chunts** [comment]
Ideally, we're looking for something light-weight that doesn't require additional work. I think with the Juicer tool you simply drop a .hic matrix file in it and it displays. So the idea of having to pre-process, and store additional files for higlass is putting me off a little. 
The .hic files can be quite large (e.g. see one [here](https://doi.org/10.5524/102531) is 684Mb) so we dont really want to be storing duplicates of them if possible.
In the [webap](https://www.aidenlab.org/juicebox/) you can load the [URL](https://s3.ap-northeast-1.wasabisys.com/gigadb-datasets/live/pub/10.5524/102001_103000/102531/contigs.hic) for that large file and it displays in a couple of seconds.
Having said all that, it higlass is technically the best one to go for, and you can make it as simple to use as juicer then thats probably the way to go.

**Comment by rija** [comment]
> The .hic files can be quite large (e.g. see one [here](https://doi.org/10.5524/102531) is 684Mb) so we dont really want to be storing duplicates of them if possible.

There is a performance concern that we would need to investigate.
We don't want regular visitors of the website  to have a bad experience, because one person is visualising a large hi-c file.
And it's unclear at the moment,  how the web version of Juicebox performs

**Comment by luistoptal** [comment]
@only1chunts I will take a closer look to juicebox to see what it's doing

**Comment by luistoptal** [comment]
@only1chunts you are correct that juicebox is lightweight as opposed to higlass, and could fit well our use case. It is definitely much easier to implement

juicebox is for simple .hic visualizations, whereas HiGlass is a more advanced tool

- juicebox: .hic files only, client side only, no extra preprocessing (hic files as input), lightweight and easy to embed, performance dependent on user device
- HiGlass: General genomic data visualization, Client-side with server-side preprocessing, Requires preprocessing to create tiles, More complex; requires server deployment, Scalable and performant even for large datasets

for our purpose of a simple hic visualizer, juicebox might be sufficient
