### ISSUE TITLE
BagIt integration for the uploader

### ISSUE THREAD

**Issue by ScottBGI** [gigascience/gigadb-website#340]
An improvement to the uploader functionality would be to integrate BagIt. This would provide functionality for organisation of data packets, a manifest itemising the files, and automated checksums checking if we don't already have that. Would also increase compatibility with whats ongoing with the Research Object specification

For more see: http://www.dcc.ac.uk/resources/external/bagit-library

**Comment by only1chunts** [comment]
I think for download we should definitely look to providing bagit compliant packages.
I think for upload it will require a lot of implementation to handle the diverse specifications, and to account for all the different optional bits of information users could include. I will add it to the cross-walk table for mapping our terms to BagIt terms.

**Comment by only1chunts** [comment]
i'm closing this as I dont think "BagIt" is still a thing anymore, but instead I will create a ticket to look into providing RO-Crates of GigaDB datasets as I think that maybe a more useful option.
