### ISSUE TITLE
Change password page

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#349]
The `Change Password` page at `/user/changePassword` doesn't look consistent with other pages:

<img width="1600" alt="change_password" src="https://user-images.githubusercontent.com/2101491/66109017-5a3a5a80-e5f6-11e9-88f6-76082343e6eb.png">

It would be better if it is updated so that it has the same look as the `Your profile page` at `/user/view_profile`:

<img width="1600" alt="profile_page" src="https://user-images.githubusercontent.com/2101491/66109146-9e2d5f80-e5f6-11e9-93ef-9a2a6f06e718.png">

**Comment by only1chunts** [comment]
that would be a nice fix, thanks

**Comment by kencho51** [comment]
Hi @pli888, what do you mean `has the same look`? These two pages serve different purpose.

**Comment by pli888** [comment]
I mean the layout of the "/user/changePassword" page is not the same as the rest of the website pages. For example, look at where the `Change Password` title is in relation to the `Your profile page` title in the two screenshots.
