### ISSUE TITLE
Broken link in http://gigadb.org/site/advisory 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#354]
**Describe the bug**
Broken link in http://gigadb.org/site/advisory 

The link to the GigaScience advisors is broken. 
It should be https://academic.oup.com/gigascience/pages/Editorial_Board but instead it is http://www.gigasciencejournal.com/about/edboard

**Comment by pli888** [comment]
This has been fixed in https://github.com/gigascience/gigadb-website/pull/427.
