### ISSUE TITLE
update dataset on admin pages can't show on dataset view page

### ISSUE THREAD

**Issue by jessesiu** [gigascience/gigadb-website#358]
**Describe the bug**
When you update any content on the admin page. e.g.  http://gigadb-staging-jesse.gigatools.net/adminDataset/update/id/1637

I update the title to "Image data of Nanmaohu Park Corydalis sp. plant specimen, RL0947 TEST TEST" then save, the dataset view page title changed. But when I update the title to "Image data of Nanmaohu Park Corydalis sp. plant specimen, RL0947 TEST TEST 1111" and save it again. The dataset page didn't update, still shows the "Image data of Nanmaohu Park Corydalis sp. plant specimen, RL0947 TEST TEST".

It seems yii cache didn't flush when you update on the admin page.

@rija  Do you have any idea to fix this issue?

**To Reproduce**
1. http://gigadb-staging-jesse.gigatools.net/adminDataset/update/id/1637
2. update title
3. click save

<img width="1192" alt="屏幕快照 2019-10-18 下午2 00 38" src="https://user-images.githubusercontent.com/1147873/67069641-5e4aa880-f1b0-11e9-8c55-d02d5662ec5d.png">

<img width="1244" alt="屏幕快照 2019-10-18 下午2 00 47" src="https://user-images.githubusercontent.com/1147873/67069648-61459900-f1b0-11e9-885f-5d20a46a1dc6.png">

**Comment by jessesiu** [comment]
@pli888 Peter also has this error

**Comment by rija** [comment]
Hi @pli888, @jessesiu,

this is a configuration issue.

The invalidation of content is controlled by an SQL query in ``protected/config/main.php`` generated from ``ops/configuration/yii-conf/main.php.dist``

under the **'cacheConfig' => 'DatasetComponents' => 'invalidationQuery'** key of that config file.

The dependency management is performed by Yii's CDbCacheDependency class (instanciated  in DatasetController.php but attached to the CApcCache in DatasetComponents's saveLocaldataInCache method) and its ``sql`` property used for invalidation expects an sql expression that returns a scalar value. However, as you can see in the file,  the sql returns an array result.

Therefore, replacing the last part of the query:
```
select d.latest,c.latest from the_dataset_log d, the_curation_log c
```
 with 

 ```
 select d.latest from the_dataset_log d, the_curation_log c
 ```

will fix the issue (after regenerating the config and restarting the ``application`` container).

However, in that case, the cache invalidation won't invalidate if curation log is updated but only if dataset_log is updated, but that might not be an issue, as dataset_log is always changed whenever a dataset row is changed and curation_log may have editorially focused entries not related to actual change to the dataset table row itself anyways.
Please confirm behaviour and feel free to tweak the invalidation sql query appropriately.

Steps to fix the issue:

1) Change the query in ``main.php.dist``
2) regenerate the config:
```
docker-compose run --rm config
```
3) restart the application container (that will flush the cache and the old invalidation rules):
```
docker-compose restart application
```

**Comment by rija** [comment]
I forgot to mention, this issue is a good candidate for adding a functional test as the issue cuts across layers and configuration, and it seems existing test harness didn't catch it.

**Comment by only1chunts** [comment]
comment says its fixed, so closing ticket.
