### ISSUE TITLE
Improve datacite metadata

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#37]
in conjunction with issue #38  (adding a mint DOI button), we need to update all additional dataset metadata that could be added to datacite XML to allow better discovery there (e.g. keywords, where we have it we should include the ORCID's of authors. 
I have annotated the datacite v3 example XML with all the bits that need to be updated, see [attached](https://drive.google.com/a/gigasciencejournal.com/file/d/0BwZOaUMoLRQAWkFzbWR2cHFwZXc/view?usp=sharing) file.

**Comment by only1chunts** [comment]
The Datacite schema 4.0 is due to be made the current version in Sept 2016. We need to update to it ASAP.
The new version includes funder information fields that we should use. as well as the ability to split names into first names and surnames.

**Comment by only1chunts** [comment]
The new datacite schema has been released. I have made comments within the attached example of all the things that need to be changed from our current v3 datacite files.
@jessesiu please change any scripts you use to generate Datacite XML, and make them available in GitHub ready for use when the button is added ( #38 ) .

**Comment by rija** [comment]
Hi, in the sample  XML attached, where in the database does the content of the element below come from ? I'm having trouble finding it.
`<date dateType="Available">2014-10-17</date>`

**Comment by only1chunts** [comment]
@jessesiu please correct me if I'm wrong, but I think that will be the release date of the dataset, it should be stored in the DATASET table as PUBLICATION_DATE

**Comment by jessesiu** [comment]
Yes, It is the DATASET table as PUBLICATION_DATE.

**Comment by only1chunts** [comment]
version 4.0 of the datacite schema includes the ability to add funding info, see example here https://schema.datacite.org/meta/kernel-4.0/example/datacite-example-fundingReference-v.4.0.xml 
@jessesiu Please can we add that to the script that creates the XML to submit to datacite?

**Comment by only1chunts** [comment]
since this ticket was never closed, I'll append these 2 extra bits here :-)

I was just browsing around the datacite repo looking at our data and noticed we are going to the bother of adding Funders and trying to ensure they are ones that are in FundRef yet the "mint DOI" script is not adding the FundRef ID to the metadata e.g :

<fundingReference>
            <funderName>MOST</funderName>
            <funderIdentifier funderIdentifierType="Crossref Funder ID">unknown</funderIdentifier>
            <awardNumber>2016YFC1200600</awardNumber>
        </fundingReference>


The related Identifiers are not showing the Protocols.io (as was requested in issue #37 when Rija was working on the button). Dataset 100480 has links to protocols.io but these are not included in the datacite metadata "relatedIdentifiers" section:

<relatedIdentifiers>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="IsSupplementedBy">101052</relatedIdentifier>
        <relatedIdentifier relatedIdentifierType="DOI" relationType="IsSupplementedBy">101053</relatedIdentifier>
</relatedIdentifiers>


Please can you look into the script that gets run by the webpage button that mints the DOI and see if those can be added?

**Comment by only1chunts** [comment]
closed this issue and opened a new one with better explaination of the last items appended to this ticket.
