### ISSUE TITLE
Typo replace word Funder with Attribute

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#378]
**Describe the bug**
The update attribute page within the Admin pages has the heading update funder instead of update attribute

**To Reproduce**
1. Login as Admin user
2. goto any edit attribute page (e.g. http://gigadb.org/attribute/view/id/310)
3. See top of page has heading "Update Funder 310", it should read "Update Attribute 310"

**Comment by kencho51** [comment]
This issue is duplicated with Issue [#425](https://github.com/gigascience/gigadb-website/issues/425), and Issue [#425](https://github.com/gigascience/gigadb-website/issues/425) has been closed.
