### ISSUE TITLE
Add a mint DOI button

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#38]
This can be done in conjunction with issue #37 
Aim: To allow admin persons to mint DOI's for datasets that are ready to be published.
Action: We need a button adding to the dataset admin page (i.e. http://127.0.0.1:9170//dataset/update/id/nnn) to allow admin person to mint the DOI of a dataset.
The function should ONLY be possible with datasets of status "pending", "private" or "published", i.e. the button should not function if the dataset status is "incomplete", "request", or "uploaded"
![image](https://cloud.githubusercontent.com/assets/6037145/18745373/ce48423e-80b9-11e6-846e-ac6ca2191b96.png)

**Comment by only1chunts** [comment]
NB - @jessesiu has a script for creating the datacite XML from GigaDB metadata.

**Comment by rija** [comment]
Putting here DataCite's MDS Api Doc for my own reference:

https://mds.datacite.org/static/apidoc

**Comment by rija** [comment]
The doc linked above show the list of response for the POST request to mint a DOI. One of them is: 
412 Precondition failed - metadata must be uploaded first

Does that mean that the "Mint a DOI" button's workflow should first upload the metadata to MDS and then make the request to MDS for a new DOI?

**Comment by jessesiu** [comment]
Yes, For mint a DOI you need upload the metadata first
e.g
                    $url2="https://mds.datacite.org/metadata";
                    $ch=  curl_init($url2);
                    curl_setopt($ch, CURLOPT_POST, 1);
                    curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type:application/xml'));
After received 201 Created then mint the doi
e.g
                    $url1="https://mds.datacite.org/doi";
                    $ch1=  curl_init($url1);
                    curl_setopt($ch1, CURLOPT_POST, 1);
                    curl_setopt($ch1, CURLOPT_HTTPHEADER, array('Content-Type:application/xml'));

You can use the special test prefix 10.5072, to mint the testing doi.
