### ISSUE TITLE
Web-based interface for managing user file uploads by FTP

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#40]
@only1chunts says we need to think of an alternative method for giving submission access to individual areas!? Something that is easy to maintain, and extendable to cope with the ever increasing number of submitters.

**Comment by pli888** [comment]
EBI's file upload system setup involves:

* Standard FTP server + custom PAM module. The FTP daemon used must support the
change of the user name by the PAM module. We are using the vsftpd daemon.

* Aspera. The custom PAM module should be used by the ssh daemon. We are using
the openssh daemon - the PAM module must be enabled during compilation and run
time. The openssh daemon must be patched to allow user name change by the PAM
module. A custom NSS module must be used.

* The following file for the PAM module is created every 10 minutes.
username\tpasswordhash\thomefolder\n
username\tpasswordhash\thomefolder\n
...

* Corresponding /etc/passwd file should contain records for username +
homefolder users and folders for them. This file is also generated by the system.

The account holder can manage their own details online. See:

[https://wwwdev.ebi.ac.uk/ena/submit/sra/#home](https://wwwdev.ebi.ac.uk/ena/submit/sra/#home)

**Comment by only1chunts** [comment]
Can the above be integrated into the GigaDB submission wizard? e.g. so that the GigaDB username and password will also be the username and password for the file-uploader & it can be launched from within the browser.

**Comment by pli888** [comment]
Sounds doable but we'll have to ask the developer to confirm its possible.

**Comment by rija** [comment]
It should be feasible to integrate the upload functionality into a multi-screen submission process. 
However if the file uploads take a long time, should that block the whole submission until upload is finished?

**Comment by only1chunts** [comment]
Can we incorporate a faster UDP protocol with the tool? according to this [website](http://filecatalyst.com/comparison-of-web-based-file-transfer-methodologies/) the best option for doing that would be to use a Java applet.
It looks like [Tsunami](http://tsunami-udp.sourceforge.net/) is free open source so we could install that server side, but would it be possible to have the java app work as the client side (so that no one has to go workout how to download and install separate software).

**Comment by only1chunts** [comment]
Hi @rija , The submission process has a natural break at the point of file upload anyway, i.e. once the files are uploaded by the user I take a look at the submission and do a manual review of the information provided. So blocking any further submission action while the upload is happening is fine. 
However, there are multiple other factors that would need to be addressed before we can really start working on this tool, I am in the process of writing up those as github issues now, I will add relevant issue numbers here when ready.

**Comment by only1chunts** [comment]
OK, so I think its just being able to generate new user area's on the server ( #71 ) thats needs to be done in conjunction with this one.

**Comment by pli888** [comment]
Regarding using a faster file upload protocol, CNGB said they were looking into this. I am also waiting to find out what kind of file transfer system we will be working with once GigaDB's data has been moved over to the CNGB data center. Could be Aliyun's Object Storage Service or FTP.

**Comment by only1chunts** [comment]
FYI - CNGB are now looking at using ExpeDat (http://www.dataexpedition.com/expedat/price.html)

**Comment by only1chunts** [comment]
This may make use of TUS.io resumable file upload tool http://tus.io

**Comment by only1chunts** [comment]
the general layout and design can be seen in the attached powerpoint slides.
[file-upload-wizard-mockup.pptx](https://github.com/gigascience/gigadb-website/files/2537501/file-upload-wizard-mockup.pptx)

**Comment by only1chunts** [comment]
@rija I think this was one of the earliest tickets about the file upload tool, its possible we dont need this ticket any more, or that it shouldn't be in the product backlog as its already in progress, I'll let you workout if its needed or if it can just be closed.

**Comment by rija** [comment]
Implemented already in file upload wizard, so closing.
