### ISSUE TITLE
No hits to GigaDB (according to google analytics)

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#404]
@only1chunts says: Something odd is happening with Google analytics, its not registering any (0) hits to gigadb.org since Jan 19/20th !?

The website has been up for all of that time (even for the few minutes that I broke the database yesterday the website was still up) so why has google stopped recording hits?

The analytics API has flagged this and gives me this warning message:

> Property gigadb is not receiving hits. Either your site is not receiving any sessions or it is not tagged correctly.
> Google Tag Assistant Recordings can help you ensure that your site is tagged correctly.

This is the support page they link to for more information:
https://support.google.com/analytics/answer/1008080?hl=en

As far as I'm aware we haven't changed anything on the website at that time? do you have any idea why this might be happening and how we can fix it?

The website appears to be functioning as expected with no problems other than the lack of analytics being recorded.

**Comment by pli888** [comment]
The source code of the gigadb.org home page looks like it is using the Google Analytics ga.js. Apparently, this tracking library is legacy now and should be upgraded:

https://developers.google.com/analytics/devguides/collection/upgrade

It might be possible to fix this problem by replacing the current Google Analytics tracking code at the beginning of the gigadb.org homepage with the new Global Site Tag tracking code:

https://analytics.google.com/analytics/web/#/a40438882w69626116p71747719/admin/tracking/tracking-code/

**Comment by pli888** [comment]
The current staging server at https://gigadb-staging.gigatools.net/ uses the latest tracking code which seems to enable tracking by Google Analytics.

**Comment by only1chunts** [comment]
this was an issue with a setting in the google analytics pages, I added a filter trying to look at historical data for a subset of datasets, it appears that filter got saved and used for all current collection of data! Once the filter was removed the analytics appears to be working correctly again now.
