### ISSUE TITLE
Problem with creating a new user

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#407]
When a non-logged in user is on the "/site/login" page and clicks the "Create account" link to create a new user account, it goes to the "/user/create" page. The problem is that this page displays:

>Error 500 CDbCommand failed to execute the SQL statement: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "LIMIT" LINE 1: SELECT * FROM "author" "t" WHERE gigadb_user_id = LIMIT 1 ^.

This problem can be reproduced with the `develop` branch code by going to http://gigadb.gigasciencejournal.com:9170/user/create.

Looking more closely at the problem, this is what seems to be going on:

* `protected/views/site/login.php` renders "/site/login" page
* Clicking on the "Create account" link causes `UserController actionCreate()` to execute `protected/views/user/create.php` which then uses renderPartial() to render `protected/views/user/_form.php`
* `_form.php` looks for a `$linked_author` using `findAttachedAuthorByUserId($model->id)` but the problem is no value is not provided for the `UserId`. If there is no user logged in then this would explain why there is no `UserId`?

This problem is related to #56 and #367.

**Comment by only1chunts** [comment]
This is not a problem on the current public site, so i added the whitelabelworks flag.

**Comment by pli888** [comment]
I'm not sure if it's something to do with WL's work. This problem is found with the code in the `develop` branch.

**Comment by only1chunts** [comment]
closing this as I think its covered by other tickets in #1060
