### ISSUE TITLE
Update Mint DOI button to produce better DataCite metadata

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#414]
**Is your feature request related to a problem? Please describe.**
The Mint DOI button on the admin pages allows curators to submit the relevant metadata to DataCite for the assignment of DOI's to datasets. There is currently an issue with author names formatting;
    <creator>
        <creatorName>LastName MiddleInitials FirstName</creatorName>
        <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0001-2345-6789</nameIdentifier>
    </creator>

But this is how DataCite recomend it be structured:
<creator>
	<creatorName nameType="Personal">Miller, Elizabeth</creatorName>
	<givenName>Elizabeth</givenName>
	<familyName>Miller</familyName>
	<nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0001-5000-0007</nameIdentifier>
</creator>

**Describe the solution you'd like**
Update the "Mint DOI" button script to include the correctly formatted datacite metadata for the authors.

**Additional context**
This is important because the current author names are displayed incorrectly in DataCite and this actually effects the citation information in datacite, e.g.
for dataset 100749, the correct citation of the dataset should be:
> Serra A; Fratello M; del Giudice G; Saarimäki LA; Paci M; Federico A; Greco D (2020): Supporting data for "TinderMIX: Time-Dose INtegrated moDelling of toxicogenomics data" GigaScience Database. http://dx.doi.org/10.5524/100749

But according to DataCite they have the citation listed as:
> Angela, S., Michele, F., Giusy, D. G., Saarimäki Aliisa Laura, Paci Michelangelo, Antonio, F., & Dario, G. (2020). Supporting data for "TinderMIX: Time-Dose INtegrated moDelling of toxicogenomics data" [Data set]. GigaScience Database. https://doi.org/10.5524/100749

This could be done in combination with work in ticket #372

**Comment by rija** [comment]
closing as superceded by #456
