### ISSUE TITLE
Update map and postal address on Contact Us page

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#436]
The current [Contact Us](http://gigadb.org/site/contact) page on the GigaDB website requires updating with the new Shek Mun address and location map.

**Comment by kencho51** [comment]
I have looked into this issue. For the map,  here are some possible solutions:
1. Embed an image.png  
2. Embed a google static map, there is a [Yii extension](https://www.yiiframework.com/extension/google-static-maps) for it. 

@pli888 @only1chunts Which one will be more preferred?

**Comment by only1chunts** [comment]
We should avoid using Google as that tends to be blocked in China.
Would open street maps be an option?  https://wiki.openstreetmap.org/wiki/Beginners%27_guide

**Comment by pli888** [comment]
Closing this issue as it has been fixed in pull request #439 with a new png image file
showing a map of the Shek Mun location.
