### ISSUE TITLE
Software Checklist

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#440]
The Software Checklist is currently just a broken link at the bottom of this page.
http://gigadb.org/site/guide

**Comment by tuli** [comment]
Software checklist (when it's available) should also be added to the 'Datasets checklist' tab.

**Comment by ChrisArmit** [comment]
A Google Doc with the content for the Software Checklist is available from the following link:
https://docs.google.com/document/d/1_pHOdO04fJGtPh49sBupV0011Cx-F94ay0rm613A05s/edit?ts=5c56ed5e

**Comment by only1chunts** [comment]
@kencho51 the software checklist is now ready. Let me know if you have any questions about it. 
@pli888 , will you or Ken be able to add this to the current public pages as well, or should I ask Jesse to add it as part of his contract work?

**Comment by pli888** [comment]
>@pli888 , will you or Ken be able to add this to the current public pages as well, or should I ask Jesse to add it as part of his contract work?

Me and Ken will do it. The PHP view classes for all of the checklists need to be obtained from the production server, and then corrected and added into the repo.
