### ISSUE TITLE
Update GigaDB team page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#441]
**Describe the bug**
Our public website "team" page http://gigadb.org/site/team needs updating:
1- it still shows Jesse as our database manager. 
2- it's missing Rija 
3- it's missing Ken

**To Reproduce**
1. Go to 'http://gigadb.org/site/team'
2. See error

**Expected behavior**
To see the current team members only

**Additional context**
We may wish to consider adding an "Alumni" section to the team page, we have 3-5 past members that could be listed (depends who you count; Jesse, Rob, Tam, Alexandria, and Uzebo!)

**Comment by kencho51** [comment]
@only1chunts Hi Chris,
1. What is your preference in ordering the picture?
2. If there is an Alumni section, their photos and permission will be need.

**Comment by only1chunts** [comment]
1. no preference for photo order.
2. good point, lets leave off the alumni section then.
