### ISSUE TITLE
Update terms page on website

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#448]
**Is your feature request related to a problem? Please describe.**
The Core Trust Seal application requires us to have a public statement available about the hosting and preservation of data. 

**Describe the solution you'd like**
I would like to add a statement to our Terms pages on the website. This should be in the form of an additional tab "Hosting Statement" on the page http://gigadb.org/site/term 

![image](https://user-images.githubusercontent.com/6037145/84370783-a5b6f680-abd0-11ea-93b7-ff901d59c49e.png)

The text to go on this tab is here:
https://docs.google.com/document/d/1FliFak4ls0WvcJrXwmW-d4VrE7qDbuh10Xpi3D4sjgs/edit?usp=sharing

This needs to be done on the public production version ASAP so that we can make a final submission of the CTS application.

**Describe alternatives you've considered**
We could save the statement as a PDF and save it to our FTP server, then just add a link in the website to it, but that still requires an update to the website and it doesn't look as nice.

@pli888 @kencho51 , in the interests of speed should I ask Jesse to make the update to the public page first then you guys can add it to the dev version when you get time?

**Comment by pli888** [comment]
> in the interests of speed should I ask Jesse to make the update to the public page first then you guys can add it to the dev version when you get time?

@only1chunts If you want to get it done as soon as possible then ask Jesse to do it for you.

**Comment by only1chunts** [comment]
Jesse has now added this page to the public website (thanks @jessesiu )
