### ISSUE TITLE
change the default table settings in dataset pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#462]
**Is your feature request related to a problem? Please describe.**
Current the default view of the Files table on a dataset page (e.g. http://www.gigadb.org/dataset/100767) doesn't show the best selection of columns. 
The default view is of:
File Name | Sample ID | Data Type | File Format | Size | Release Date | Download
I would like to change the default view to be:
File Name | Description | Data Type | Size |  File Attributes | Download

It is possible for a user to define the columns displayed in the files table, but very few users are aware of that fact, so they don't change them.

**Describe the solution you'd like**
The default setting on the file table view needs to be changed to the above list.

**Describe alternatives you've considered**
making all columns visible by default is also an option, but that makes the table wider than the screen/browser window so users would need to scroll right to see the download button which is not good.

**Additional context**
This issue may need to be taken into consideration for the file browser widget (#63 ) too.

**Comment by pli888** [comment]
>I would like to change the default view to be:
File Name | Description | Data Type | Size | File Attributes | Download

FYI @only1chunts not all all files have descriptions. Based on the output of `select count(*) from file where description = ''`, there are 20,289 files with no descriptions.

**Comment by only1chunts** [comment]
Thanks Peter, descriptions weren't required when we first started so that
vast majority of those without description will be from datasets submitted
in the first year or so.
Cheers
Chris
