### ISSUE TITLE
GigaDB file server setup

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#465]
It is currently unknown how the file server for GigaDB was set up on a CNGB virtual server. Things that we need to know about include:

* Installation and configuration of FTP server
* Management of FTP user accounts
* How the disks containing the actual data files have been mounted

Information on the above issues is required to replicate the setup in case we need to re-deploy the service and for development purposes. Ideally, Terraform and Ansible scripts would have been written to automate the deployment of the GigaDB file server.

**Comment by pli888** [comment]
Jesse says the CNGB team installed the dependencies to deploy the file server. I don't know how they could do this without knowing what the dependences are and how they are related to each other. Maybe they used an old [Chef script](https://github.com/gigascience/gigadb-website/blob/3.1/chef/site-cookbooks/fileserver/recipes/default.rb) I wrote as a basis.

**Comment by pli888** [comment]
An update from Jesse:

* Installation and configuration of FTP server was done manually.
* FTP user account management is done through a Django backend application
* How the disks containing the actual data files have been mounted - use Ali cloud NAS storage mounted to the FTP server, the storage size is 10PB.

**Comment by pli888** [comment]
I have received the source for the Django backend application. I also have the configuration files for the FTP server and for how the storage disks have been mounted.

**Comment by only1chunts** [comment]
closing as we no longer use CNGB servers so this ticket is irrelevant
