### ISSUE TITLE
Replace logos

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#471]
@ScottBGI says we need to replace the GigaScience and BGI logos on the website:

> So BGI have noticed and flagged we are still using the old BGI logo on GigaBlog, and I can see we are also using it on the GigaDB and GigaGalaxy websites. Can we replace the GigaBlog BGI logo with the new GigaScience Press logo, and for GigaDB you might want to think about using one or both new logos. They are really trying to remove the old one so please swap that if you can.

**Comment by ScottBGI** [comment]
Talked this through in the editorial meeting. Can you update the BGI logos on GigaDB and GigaGalaxy and also put the GigaScience Press logo somewhere there if it fits. For GigaBlog can you just put the GigaScience Press logo and don't bother with the BGI one.

**Comment by pli888** [comment]
>Talked this through in the editorial meeting. Can you update the BGI logos on GigaDB and GigaGalaxy and also put the GigaScience Press logo somewhere there if it fits. For GigaBlog can you just put the GigaScience Press logo and don't bother with the BGI one.

@ScottBGI All of the above has been done now.

**Comment by ScottBGI** [comment]
We also need to update the CNGB logo in GigaGalaxy as its been flagged by Xueqin Guo that we have the old one still.

**Comment by pli888** [comment]
> We also need to update the CNGB logo in GigaGalaxy as its been flagged by Xueqin Guo that we have the old one still.

The CNGB logo has been updated now on GigaGalaxy.
