### ISSUE TITLE
What does my dataset status mean?

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#485]
**Is your feature request related to a problem? Please describe.**
Update flowchart in this FAQ.

**Describe the solution you'd like**
The flowchart figure in the answer to this FAQ should match that shown in the submission guidelines:

http://gigadb.org/site/guide

**Comment by only1chunts** [comment]
@ChrisArmit, I dont think this is required as the FAQ is correct as it is. The workflow is linked to, and the image in this FAQ actually shows the statuses, not the workflow so I think its fine without any changes.
