### ISSUE TITLE
New FAQ - What do you get from us?

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#487]
**Is your feature request related to a problem? Please describe.**
New FAQ.

**Describe the solution you'd like**
What do you get from us?
From RDS website:
"Research Data Support makes research data easier to find and understand by editing and enhancing metadata about submitted data and files (such as titles, authors, keywords and descriptions). Professional Research Data Editors also carry out checks on file integrity, for the presence of potentially sensitive information, and for consistency with associated manuscripts where applicable. Publication of data will be coordinated with the publication of the authors’ associated Springer Nature articles, where applicable."

**Comment by only1chunts** [comment]
closing ticket as this is covered by other faqs
