### ISSUE TITLE
New FAQ - Why use GigaDB data support service?

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#488]
**Is your feature request related to a problem? Please describe.**
New FAQ.

**Describe the solution you'd like**
Why use GigaDB data support service?
GigaDB was was created to address the challenge of finding an appropriate repository to host your data. We know researchers dont want to spend their time on administrative tasks like filing their data, so we have trained BioCurators to help, saving the researcher time and ensuring their efforts are made in the right area's to make their research data easy to find, cite and understand.
Saving the researcher time that could be uses to carry out new research.

**Comment by only1chunts** [comment]
this is covered by other FAQs already "why use gigadb"
