### ISSUE TITLE
merge authors in admin table

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#49]
If a user just adds new authors when we already have them in gigadb we need a way to link them together. e.g. Jun Wang = Jun Wang, or ORCID 000100123456789 = 000100123456789 etc...so where we are sure they mean the same thing we can reduce redundancy and make explicit links between authors.
We use the relationship table for this. i.e. create an "Author_rel" table with "ID", "Author_ID", "related_Author_ID" and "relationship" columns.
The association should be reversible incase of mistake.
The author table in the admin pages would be the best place to provide the tool: http://gigadb.org/adminAuthor/admin on each individual edit author screen, the option to add "linked author information" the relationship should be pre-defined as "identical_to".

**Comment by rija** [comment]
HI @only1chunts ,

Please find at the link below, for review, clarification, and amendments, the acceptance tests for this issue. 

I'll start implementation against the scenarios in this file, when the scenarios are agreed.

https://github.com/rija/gigadb-website/blob/merge-authors-49/tests/features/merge-authors-49.feature

Kind regards,
Rija

**Comment by only1chunts** [comment]
line 25, can the dialog box contain full author details that we have (full names and orcids) side by side for easy comparison 
e.g. 
merge  | with  
Zhang  | Pan   
M      |       
Gordon | Steve 
0      | 123   


So when they are merged/linked how does that effect the author-user links? i.e. if 1 of the merged authors is already linked to user, will the datasets associated with the merged author be displayed in that users profile page along with those of the author they are linked to?


----- Original Message -----

**Comment by rija** [comment]
Hi @only1chunts ,

sorry for the delay, thank you for your feedback.

I've updated the scenario to test the dialog box to show the detailed name and orcid id of the two authors to merge.

Regarding the second question, I envisaged the scenarios to be independent from the implementation off the user/author link: If user U1 is linked to author A1, and if author A1 is merged with author A2, then the user profile for user U1 will only show the datasets authored by A1, as only A1 has explicit linking to U1.

If showing A2's datasets on U1's profile page is also desired, I can modify User profile controller to aggregate the datasets from its directly linked author and from the author it has an "identical to" relationship with. It makes the user controller code more complex, but it's doable with the current database schema.

In longer term, it would be beneficial to introduce a graph database (like Neo4J) into the infrastructure 
in order to manage and surface to users and admins, in a scalable way , all the explicit and implicit linking that are potentially useful and helpful.

**Comment by only1chunts** [comment]
The use of graph database sounds like something we should discuss its not something I'm familiar with, but sounds like it could be useful.

As for the addition of A2 to the U1 thing, yes please, if 2 (or more) authors are linked as being the same then having any 1 of those linked to a user should mean they are all linked to that user.

Thanks
Chris


----- Original Message -----

**Comment by rija** [comment]
Hi @only1chunts , I've added the following scenarios to the feature to cater for the multiple possibilities of linking two or more authors  and for unmerging an author

```gherkin
Scenario: If exists (A1 identical_to A4), attempt to merge A1 with A4 again should not be possible
	Given author "3791" is merged with author "3794"
	And I sign in as an admin
	When I go to "/adminAuthor/update/id/3791"
	When I follow "Merge with an author"
	And I wait "2" seconds
	And I click on the row for author id "3794"
	And I wait "1" seconds
	Then A dialog box reads "Confirm merging Zhang Guojie with Pan S ?"
	And I follow "Yes, merge with selected author"
	Then I should see "Authors already merged. Choose another author to merge with"

Scenario: If exists (A1 identical_to A4), attempt to merge A4 with A1 should not be possible
	Given author "3791" is merged with author "3794"
	And I sign in as an admin
	When I go to "/adminAuthor/update/id/3794"
	When I follow "Merge with an author"
	And I wait "2" seconds
	And I click on the row for author id "3791"
	And I wait "1" seconds
	Then A dialog box reads "Confirm merging Pan S with Zhang Guojie ?"
	And I follow "Yes, merge with selected author"
	Then I should see "Authors already merged. Choose another author to merge with"

Scenario: If exists (A1 identical_to A4), A4 view shows link to A1
	Given author "3791" is merged with author "3794"
	And I sign in as an admin
	When I go to "/adminAuthor/view/id/3794"
	Then I should see "this author is merged with author(s):"
	Then I should see "Zhang Guojie (3791)"

Scenario: If exists (A1 identical_to A4), on A4 edit form: shows link to A1 and unmerge button
	Given author "3791" is merged with author "3794"
	And I sign in as an admin
	When I go to "/adminAuthor/update/id/3794"
	Then I should see "this author is merged with author(s):"
	Then I should see "Zhang Guojie (3791)"
	And I should see "Unmerge"


Scenario: If exists (A1 i_t A2), (A1 i_t A3) and (A2 i_t A5), on A1 view: a graph of merged authors is shown properly
	Given author "3791" is merged with author "3792"
	And author "3791" is merged with author "3793"
	And author "3792" is merged with author "3795"
	And I sign in as an admin
	When I go to "/adminAuthor/view/id/3791"
	Then I should see "this author is merged with author(s):"
	Then I should see "3792"
	Then I should see "3793"
	Then I should see "3795"

Scenario: If exists (A1 i_t A2), (A1 i_t A3) and (A2 i_t A5), a graph of merged authors is shown properly on A5
	Given author "3791" is merged with author "3792"
	And author "3791" is merged with author "3793"
	And author "3792" is merged with author "3795"
	And I sign in as an admin
	When I go to "/adminAuthor/view/id/3795"
	Then I should see "this author is merged with author(s):"
	Then I should see "3791"
	Then I should see "3792"
	Then I should see "3793"

Scenario: If exists (A1 i_t A2), (A1 i_t A3) and (A2 i_t A5), on A1 edit form: shows links and an unmerge button
	Given author "3791" is merged with author "3792"
	And author "3791" is merged with author "3793"
	And author "3792" is merged with author "3795"
	And I sign in as an admin
	When I go to "/adminAuthor/update/id/3791"
	Then I should see "this author is merged with author(s):"
	And I should see "3792"
	And I should see "3793"
	And I should see "3795"
	And I should see "Unmerge"


Scenario: If exists (A1 i_t A2), (A1 i_t A3) and (A2 i_t A5), on A5 edit form: shows links and an unmerge button
	Given author "3791" is merged with author "3792"
	And author "3791" is merged with author "3793"
	And author "3792" is merged with author "3795"
	And I sign in as an admin
	When I go to "/adminAuthor/update/id/3795"
	Then I should see "this author is merged with author(s):"
	And I should see "3791"
	And I should see "3792"
	And I should see "3793"
	And I should see "Unmerge"


Scenario: If exists (A1 i_t A2), (A1 i_t A3) and (A2 i_t A5), on A3 edit form, pressing unmerge removes A3 from graph
	Given author "3791" is merged with author "3792"
	And author "3791" is merged with author "3793"
	And author "3792" is merged with author "3795"
	And I sign in as an admin
	When I go to "/adminAuthor/update/id/3793"
	And I follow "Unmerge"
	And I wait "2" seconds
	Then I should be on "/adminAuthor/view/id/3793"
	And I should not see "3791"
	And I should not see "3792"
	And I should not see "3795"
	And I should not see "Unmerge"
```

**Comment by only1chunts** [comment]
I think I follow all of that, but with the last scenario:
Scenario: If exists (A1 i_t A2), (A1 i_t A3) and (A2 i_t A5), on A3 edit form, pressing unmerge removes A3 from graph
Given author "3791" is merged with author "3792"
And author "3791" is merged with author "3793"
And author "3792" is merged with author "3795"
And I sign in as an admin
When I go to "/adminAuthor/update/id/3793"
And I follow "Unmerge"
And I wait "2" seconds
Then I should be on "/adminAuthor/view/id/3793"
And I should not see "3791"
And I should not see "3792"
And I should not see "3795"
And I should not see "Unmerge"

what happens if author "3793" is (also) merged with author "3796"
does the link between 3793 and 3796 remain when unmerged from the rest of the graph? or would 3796 somehow remain linked to the 3791/3792/3795 graph?

or put another way:
with the same "Given" as your scenario above, what happens when A2 is unmerged?



----- Original Message -----

**Comment by rija** [comment]
Hi Chris,

thanks for your feedback, 

if 3796 was merged with 3793 when 3793 was still in the graph (3791,3792,3795), then 3796 would be part of that graph too.

So when 3793 is removed, 3796 would still remain part of the graph (3791,3792,3795) as unmerging only removes one node of the graph.

If 3796 was also a mistake, it would have to be unmerged specifically.

because "identical_to" means any two authors connected are identical, it's correct to infer that the graph of connected nodes are the set of identical authors.

The above preopety is what will allow us to show all the identical authors on any of the graph author's view page and to show all the relevant datasets on the user's profile if a user user is linked to one of the author in the graph.

I will add test scenario very similar to the latest one, focusing on unmerging A2 as you've suggested to make the test suite more comprehensive.

**Comment by only1chunts** [comment]
all clear now thanks. Just as a precaution is it possible to add in some sort of warning when merging two graphs, e.g. if there is a graph of A1,A2,A3 and a separate graph of A4,A5,A6, and I tried to merge A4 to A1 it would mean all 6 are actually identical and therefore unmerging those back to 2 separate graphs would be tricky. so having a warning "This action will merge A1,A2,A3,A4,A5,and A6 into a single author, are you sure you want to do this?" before actually committing it would be nice.

**Comment by rija** [comment]
yes, we should be able to show the existing graph before merging a new author into it.

**Comment by jessesiu** [comment]
@pli888 can we close it?
