### ISSUE TITLE
Update submission spreadsheet

### ISSUE THREAD

**Issue by ChrisArmit** [gigascience/gigadb-website#493]
**Is your feature request related to a problem? Please describe.**
Update the submission spreadsheet.

**Describe the solution you'd like**
"Download template file" on the following page should download the most recent version of the spreadsheet: 
http://gigadb.org/dataset/upload

The submission spreadsheet should be named as follows so that the correct link is manitained:
http://gigadb.org/files/GigaDBUploadForm.xlsx

**Comment by only1chunts** [comment]
I have updated the spreadsheet (not the example versions just the template) using a more upto date version of the spreadsheet, it contains ~500 of the attributes from the database, I updated any missing descriptions and corrected a load of structured comment names in the database before creating this spreadsheet. The version now available from the website is also attached here for future convenience.
[GigaDBUploadForm-forWebsite-v05Aug2020.xlsx](https://github.com/gigascience/gigadb-website/files/5029493/GigaDBUploadForm-forWebsite-v05Aug2020.xlsx)
 
In the future the WL submission wizard will allow for CSV file upload of authors, sample details and file details, the basic dataset level metadata will be imported directly from EM or RV. Those updates, when released will mean we can move away from using this spreadsheet in the future. 
Please do NOT consider this spreadsheet to be the best version for any purposes, always refer to the production database for the most upto date versions of all attributes etc.
