### ISSUE TITLE
Local dev GigaDB has no guidelines option on dataset pages

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#494]
On the [GigaDB homepage](http://gigadb.gigasciencejournal.com:9170) in a local dev installation, the drop down `Help` menu has a `Guidelines` option. However, this `Guidelines` option is not present on dataset pages, for example, [/dataset/100004](http://gigadb.gigasciencejournal.com:9170/dataset/100004).

**Comment by Rahul-coder01** [comment]
java -jar DVUploader-v1.0.0.jar -server=<Dataverse server URL> -did=<Dataset DOI> -key=<User's API Key> <file or directory list>

**Comment by pli888** [comment]
> java -jar DVUploader-v1.0.0.jar -server= -did= -key=<User's API Key>

@Rahul-coder01 I am not sure how running a JAR packaged application will help this issue.
