### ISSUE TITLE
Problems with HTML table in Files tab for datasets

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#505]
In the file pagination PR #437, @only1chunts said:

>there are a couple of issues when i try to do things [when viewing the Files tab for datasets]:
1 - when I try to edit the table settings the selection boxes are tiny dots (instead of tick boxes) that are almost impossible to tell if they are selected or not
![Screenshot_12](https://user-images.githubusercontent.com/6037145/91526996-c3a51500-e8fc-11ea-98d1-9a420bfecd13.png)
2 - The sort by column header doesn't appear to be working properly, e.g. I clicked sort by "Data type" it does appear to sort the files that are currently showing in the table, but when I change page that sorting disappears ...
3 - and I realized that it has only sorted the items showing in that page, not the entire list of files as its meant to.

**Comment by pli888** [comment]
>1 - when I try to edit the table settings the selection boxes are tiny dots (instead of tick boxes) that are almost impossible to tell if they are selected or not

@only1chunts what browser are you using? The selection boxes look fine for me on Safari, Chrome and Firefox.

>2 - The sort by column header doesn't appear to be working properly, e.g. I clicked sort by "Data type" it does appear to sort the files that are currently showing in the table, but when I change page that sorting disappears ...
3 - and I realized that it has only sorted the items showing in that page, not the entire list of files as its meant to.

Looks like this is fine on the production server so must be caused by differences between the code there and in the develop branch.

**Comment by only1chunts** [comment]
That was in Chrome, but having just looked again on the staging server it appears to be fine now.

**Comment by only1chunts** [comment]
just looking at the staging server for something else I noticed that the files table is currently missing the info at the bottom right of the table e.g. "Displaying 1-137 of 137 File(s)." , the screenshot is of dataset 100306, live version on left staging version on right:
![Screenshot_60](https://user-images.githubusercontent.com/6037145/101616701-9d1c6d00-3a07-11eb-8faf-d2c98b6f08ec.png)

**Comment by only1chunts** [comment]
closing this as the file table is behaving as expected now
