### ISSUE TITLE
Upgrade wordpress version  for GigaBlog

### ISSUE THREAD

**Issue by ScottBGI** [gigascience/gigadb-website#509]
Think we need to upgrade the wordpress version used for GigaBlog. Currently we are using WordPress 4.9.15 and WordPress 5.5.1 is out. Some of the plugins are giving messages that they will stop supporting older versions. If there is an issue with the new block editor in v5+, we can install the Classic Editor plugin which supposedly gives us the same editing experience we have now, but also the security of newer versions of WordPress and Yoast SEO. It would be nice if the newer versions of Yoast also had metrics for numbers of views as we've needed that for a long time or if there were other plugins for this functionality.

**Comment by pli888** [comment]
@ScottBGI GigaBlog has been updated to WordPress 5.5.1. I have updated the SEO plugin too.
