### ISSUE TITLE
Link to GigaPress from GigaDB homepage

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#525]
**Describe the bug**
The link from the GigaDB homepage to what should be GigaPress still goes to GigaScience
**To Reproduce**

Steps to reproduce the behaviour:
1. Go to http://gigadb.org/
2. Click on GigaSciencePress logo in bottom banner

**Expected behavior**
Clicking on the GigaSciencePress logo should go to http://gigasciencepress.com/

![Screen Shot 2020-11-05 at 12 21 04](https://user-images.githubusercontent.com/1359170/98240530-75963880-1f61-11eb-9ec6-aea75733578a.png)

**Desktop (please complete the following information):**
 - OS: macOS Sierra 10.12.6
 - Chrome 
 - Version 85.0.4183.121

**Additional context**
Thank you :-)

**Comment by pli888** [comment]
This has been fixed now in the codebase and on the production server.
