### ISSUE TITLE
bug in display of sample attributes after update

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#53]
The sample attributes are not being shown in the admin view after updating the sample details : e.g. http://gigadb.org/adminSample/view/id/17513 only shows 1 of the peoples names in the collected by value field. this should be fixed when dealing with "sample attributes display and updating" #54 .

**Comment by only1chunts** [comment]
When trying to update the sample attributes the KEYs are often missing from the text box?! 
e.g. on dataset http://dx.doi.org/10.5524/100321 the sample attributes all look fine, but if I goto the update sample attributes page the attached image is what I see. 
![screenshot_sample-attributes-issue](https://user-images.githubusercontent.com/6037145/31721059-3927987c-b410-11e7-85ff-4116066488f8.jpg)
notice the attribute names for both sex and age are missing?!
 ...alt_acc_SRA_sample="SRS1579614",="adult",="male",tissue="liver",...

Also, the sample species on the update page is not pre-populated with the correct value. I think it is using the species table row ID instead of the TaxonID. in the screen shot the species taxon ID should be 36187 not the number its showing (18084)

**Comment by jessesiu** [comment]
It already merged in the GitHub repo. You can close it. http://127.0.0.1:9170/adminSample/view/id/17513
