### ISSUE TITLE
specification for the readme.txt file

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#55]
I would like to define the readme.txt file as a specific gigadb readme format so all datasets have the same information in their readme files, think about EMBL flat file format maybe? the file should be both human and computer readable.

**Comment by only1chunts** [comment]
We have 4 possible versions to choose from:
[readme_100397_combined4.txt](https://github.com/gigascience/gigadb-website/files/1642119/readme_100397_combined4.txt)
[readme_100397_combined3.txt](https://github.com/gigascience/gigadb-website/files/1642120/readme_100397_combined3.txt)
[readme_100397_combined2.txt](https://github.com/gigascience/gigadb-website/files/1642122/readme_100397_combined2.txt)
[readme_100397_combined1.txt](https://github.com/gigascience/gigadb-website/files/1642121/readme_100397_combined1.txt)

**Comment by ChrisArmit** [comment]
Thanks Chris.

I think version 1 is the most human-readable version. This uses square
brackets in the titles and avoids the use of the hash symbol, which is
primarily used by software developers.

Version 2, where the square brackets have been removed, would be my second
option.

Cheers
Chris A

**Comment by tuli** [comment]
I like 1. 
I don't like 2.
I can't see the difference between 3 and 4, but agree, hash should be avoided.

**Comment by only1chunts** [comment]
readme_100397_combined1.txt it is then :-D

**Comment by only1chunts** [comment]
decision made, new ticket created for creation of scripts (#154) and assigned to Jesse.
