### ISSUE TITLE
Transition files backup process from CNGB to IT team E572

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#574]
## User Story

>As a curator
>I want files uploaded by authors to be stored in several places
> So that a data-loss on main storage server can be recovered from reliably and promptly

## Additional Info

https://docs.google.com/document/d/1IzM-FkFC5xTQQIsWHWiQmzPFELiWP6Ud1tNuOznc7qo/edit?usp=sharing

This Epic is part of Epic #572

**Comment by only1chunts** [comment]
This is done.

**Comment by only1chunts** [comment]
Actually, its still being done manually, so this ticket remains open until its automated

**Comment by rija** [comment]
The process backing up to Tencent has been handed to the IT Team, so closing this one
