### ISSUE TITLE
Decommission old tools and restrict access to servers E572

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#575]
## User Story

>As a developer
>I want to decommission dataset related tools operated by departed contractor
>So that I don't let redundant tools wasting infrastructural resource
>and that I reduce software vulnerability surface in our infrastructure

## Acceptance Criteria

>Given we have deployed software and process to replace previous outsourced operations
>When someone attempt to use old tools and process
>Then they are unable to proceed

>Given we have deployed software and process to replace previous outsourced operations
>When someone attempt to access the web server of the storage server in non sanctioned way
>Then they are unable to proceed

## Additional Info

https://docs.google.com/document/d/1G44imqgdBtHUhrnfl7vfKq4t3Ez_8lkSGyuEcro7Qic/edit#heading=h.ehbc0r4zoxip

## Product Backlog Item Ready Checklist

* [x] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [x] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

This Story is part of Epic #572

**Comment by only1chunts** [comment]
[Jesse's daily tasks document](https://docs.google.com/document/d/1G44imqgdBtHUhrnfl7vfKq4t3Ez_8lkSGyuEcro7Qic/edit#heading=h.ehbc0r4zoxip) contains a list of the things he was doing before he left, some of which he continues to do as a contractor.
He has a [repository](https://github.com/jessesiu/gigadb-tools-dataupload) of some of the code he was/is using.

**Comment by rija** [comment]
Done as part of #1893
