### ISSUE TITLE
Setup infrastructure monitoring tools E576

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#580]
## User Story

>As a developer
>I want to take measurement from our infrastructure
>So that I can be informed of resources usage and alerted and they are low 

## Acceptance Criteria

>Given a monitoring is setup
>When I disk usage goes low
>Then I am alerted

## Additional Info

What's invovled roughly:

* Write Ansible playbook to install Prometheus on an EC2 instance
* create manually a new ec2 instance ini ap-east-1 and deploy Prometheus playbook
* Create an Ansible playbook to install Prometheus node exporter in EC2  webapp and bastion instances
* update security for web2 ec2 instance to allow the port for prometheus monitoring
* update prometheus configuration to monitor the webapp ec2 instance
* create grafana cloud account for tech AT gigasciencejournal.com 
  * and add the url of our  prometheus instance deployed in step 1 as source
* Only grafana need to access prometheus from the Internet
* node exporter communicate with prometheus using local addresses 

Prometheus and Grafana are part of the Cloud Native Computing Foundation, there are industry standard for enterprise grade cloud operations.

After the assessment, the setup will remain for day-to-day monitoring and alerting of File Upload Wizard operation.

## pli888's messy notes

* https://github.com/prometheus-community/ansible
        * https://prometheus-community.github.io/ansible/branch/main/
        * There is an ansible  node_exporter role
        * To install node_exporter role, we need to install the prometheus ansible collection: ansible-galaxy collection install prometheus.prometheus
        * Installs 'prometheus.prometheus:0.3.1' to '/Users/peterli/.ansible/collections/ansible_collections/prometheus/prometheus'
        * Is it possible to install in the roles directory? In staging folder, execute:
            * ansible-galaxy collection install prometheus.prometheus -p ../../collections
        * How to use in webapp playbook: See https://github.com/prometheus-community/ansible/tree/main/roles/node_exporter
        * Node exporter will expose GigaDB website metrics from the EC2 webapp instance endpoint. However, we do not want everyone to be able to see to see the metrics provided by webapp instance node exporter. Therefore lock down node exporter endpoint to the trusted Prometheus client using TLS client authentication. The Prometheus server will therefore query the node exporter on the EC2 webapp instance over HTTPS. 
        * node_exporter_tls_server_config
            * cert_file: /etc/letsencrypt/live/$DOMAIN/fullchain.pem
            * key_file: /etc/letsencrypt/live/$DOMAIN/privkey.pem
            * REMOTE_HOSTNAME = [gigadb-staging.gigatools.net](http://gigadb-staging.gigatools.net/)
        * Execute `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` to fix `A worker was found in a dead state` Ansible playbook error.
        * https://www.shellhacks.com/ansible-sudo-a-password-is-required/ due to downloading node_exporter tarball gzip file on local host
        * sudo port install py-passlib
        * $ TF_KEY_NAME=private_ip ansible-playbook -vvv -i ../../inventories webapp_playbook.yml --ask-become-pass
            * Last flag required for node exporter tarball gzipped file to be downloaded to local /tmp directory
        * prometheus.yml is located in /etc/prometheus directory
        * reload prometheus.yml -> sudo killall -HUP prometheus
        * Problem: Client sent an HTTP request to an HTTPS server. - need to get prometheus to scrape https endpoint
        * randomuser: *examplepassword*
        * https://gigadb-staging.gigatools.net:9100/metrics
        * systemctl status prometheus
        * sudo systemctl restart prometheus
        * http://52.192.86.16:9090/targets#pool-prometheus-gigadb
        * https://www.stackhero.io/en/services/Prometheus/documentations/Using-Node-Exporter/Add-TLS-encryption-to-Prometheus-Node-Exporter

--

prometheus.yml

global: 
  scrape_interval: 15s 
  external_labels: 
    monitor: 'prometheus' 
scrape_configs: 
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090'] 
  - job_name: 'prometheus-gigadb' 
    static_configs:  
      - targets: [gigadb-staging.gigatools.net:9100] 
    basic_auth: 
      username: "randomuser" 
      password: "examplepassword" 
    scheme: https 
    tls_config: 
      insecure_skip_verify: true

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

This Story is part of Epic #576

**Comment by rija** [comment]
Won't do.

**Comment by rija** [comment]
For the node exporter and prometheus, use 
https://galaxy.ansible.com/prometheus/prometheus

**Comment by kencho51** [comment]
Additional information:

Prometheus’s local storage is not intended to be durable long-term storage, [external solutions offer extended retention and data durability](https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects).

[Thanos](https://github.com/thanos-io/thanos) is an open-source, highly available Prometheus setup with long-term storage capabilities, focusing on long-term storage and thanos [repo](https://github.com/thanos-io/thanos).

It seems thanos can replace prometheus is an easy way.

**Comment by rija** [comment]
This is done with PR #1324 and the monitoring is at http://monitoring.gigadb.host:3000/
