### ISSUE TITLE
Backup public dataset files on new cloud storage to CNGB mirror E582

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#584]
## User Story

> As a developer
> I want CNGB storage to be set up as backup for new storage 
> And that it is enabled as a download mirror for GigaDB users in China
>So that CNGB storage is used for its strength to complement our new storage provider

## Acceptance Criteria

>Given a file has been uploaded to gigadb.org
>And the file has been saved to the main storage's drop box
>And has been promoted to the public datasets area
>When the file is synchronised to the on-premise NAS
>Then the file is synchronised to the CNGB mirror automatically 

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

This Story is part of Epic #582

**Comment by only1chunts** [comment]
The intention is to set up Cloudflare to provide local cache/mirrors around the world so this ticket should not be required.
