### ISSUE TITLE
GigaGalaxy

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#591]
## User Story

>As a website user
>I want to browse GigaGalaxy bioinformatics analysis published in gigascience papers
>So that I can see their results

## Acceptance criteria

>Given there is worflow file in GigaDB  
>When I go to GigaGalaxy 
>Then I can see diagram of the workflow

>Given there is worflow file in GigaDB  
>When I go to GigaGalaxy 
>Then I can execute the workflow and browse through the result

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by only1chunts** [comment]
I dont think we're moving this forwards anymore, so closing this ticket. We can reopen it if we decide to go ahead in the future.
