### ISSUE TITLE
Improved Search

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#599]
CIH - for a collection of use case tickets and bugs in search see project https://github.com/gigascience/gigadb-website/projects/7

**Comment by kencho51** [comment]
Hi, here is some background information about the `elasticsearch` process running in the production server, the  detailed audit doc at (here)[https://docs.google.com/document/d/1IQ7ZtJJD9sVsvLk8gJm9IJ5dFeuISgIrVQUUOM9Kdkw/edit?usp=sharing).

The process is running like this:
```
/usr/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Delasticsearch -Des.pidfile=/var/run/elasticsearch/elasticsearch.pid -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.3.4.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.work=/tmp/elasticsearch -Des.default.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.Elasticsearch
```
It is taking up ~17.4Gb of the total memory, together with other running process, the memory in production server is ~93% full now.

**Comment by only1chunts** [comment]
This is done on beta. It will be deployed to the live public version when the beta website is moved to public live.
