### ISSUE TITLE
YiiSession and yiisession tables in Postgresql database schema

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#6]
There is a YiiSession table and a yiisession table in the Postgresql database schema. Both of these tables contain the same column names (id, expire and data). Are these two tables required or should one of them be removed?

@jessesiu and @only1chunts to decide what to do.

**Comment by jessesiu** [comment]
The yiisession can remove.
http://www.yiiframework.com/doc/api/1.1/CDbHttpSession

I tested in the VM

2016-05-09 9:08 GMT+08:00 pli888 <notifications@github.com>:

**Comment by only1chunts** [comment]
I agree, one of them should be removed, and since Jesse has tested the removal of yiisession then it may as well be that one.

**Comment by pli888** [comment]
Let's give this issue to the new developer since it should be easy to fix.

**Comment by only1chunts** [comment]
@pli888 is this ticket done now? can we close it?
