### ISSUE TITLE
Select a CMS solution E564

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#615]
## User story

>As a developer 
>I want to select a Content Management System(CMS) that fit our criteria
>So that the CMS solution can be integrated and maintained efficiently within our software architecture

## Acceptance criteria

* Headless: exposes an API our web applications can interact with to bring content to website
* Has workflow support: typical publishing workflows (editing/proofreading, scheduling)
* Self hosted: It's a component in our software architecture which deployment we control
* Open Source: ease of auditing, integration and, no lock-in to proprietary vendor, free

>Given we want to publish content ot the web site
>When using a headless CMS  
>Then the content can be published within our existing website

>Given we want to publish content ot the web site
>When workflow for validation (author/proofreader) is available in the CMS  
>Then I can publish error free content to the public

>Given we want to publish content ot the web site 
>When workflow for scheduled publishing is available in the CMS  
>Then I can schedule when specific content appears on the website

>Given we want to publish content ot the web site  
>When the CMS is self hosted
>Then it can be tested and deployed using our CI/CD pipeline

>Given we want to publish content ot the web site 
>When the CMS is open source
>Then the IT team has reduced risks of security vulnerability and integration problems

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

This Story is part of Epic #564

**Comment by rija** [comment]
Done. We are going with CraftCMS

**Comment by only1chunts** [comment]
@rija, I'm happy we have selected something to go with, I just want to check that it will also fulfill this acceptance criterion?

> As a Giga team member
> I want to be able to see internal documentation (our intranet) that is not visible to the general public
> So that I can find specific details only for the Giga team.

> Given we want to publish sensitive information for internal team use only
> When we "publish" intranet page
> Then those pages are ONLY visible to GigaScience team members that are logged in

## Additional information
Currently, this is achieved using Google-sites, which only displays the pages if the user is logged into their @gigasciencejournal.com google-account.

**Comment by rija** [comment]
Hi @only1chunts,
Yes, It's a good base to implement that scenario.

The CMS has an integrated presentation layer, so implementing our intranet system is actually more straightforward than the GigaDB static site (that need an API and a client side work done): the only necessary work would be to define the collection of intranet objects, and then adding/migrating the information manually.

Regarding the authentication, you don't need the Google ID, but we still need the access to be restricted as it is for our organisation internal use only.
Ideally that will be performed by the centralised authentication service we've talked about the other day.
Most likely happening is we add its own authentication to the CMS to start with, until that service is ready if CMS related stories are worked on before the authentication service.

**Comment by only1chunts** [comment]
to make it more inclusive it would be nice if the intranet pages could live on a gigascience press domain rather than a GigaDB-specific one, just raising it now incase its something that needs to be considered in the setup stages?
