### ISSUE TITLE
Use HTTP protocol for downloading FTP link to fix issues with Chrome and Safari

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#617]
## User story

>As a website user
>I want to download from GigaDB website the files associated with a dataset 
>So that I can do my work

## Acceptance criteria

>Given I use Chrome web browser to navigate to GigaDB web site  
>When I navigate to the dataset pages's files tab
>And I click on a download link
>Then the file is downloaded

>Given I use Firefox web browser to navigate to GigaDB web site  
>When I navigate to the dataset pages's files tab
>And I click on a download link
>Then the file is downloaded

>Given I use Safari web browser to navigate to GigaDB web site  
>When I navigate to the dataset pages's files tab
>And I click on a download link
>Then the file is downloaded

## Additional Info

* Make production database backup accessible to the whole IT team
* Load production database backup on a local postgresql server
* Create and run search and replace script on local database
* Create and run acceptance tests
* Iterate on batches of datasets
* Restore replaced batches on production

**Note:**
> Behat tests currently use Chrome as backend for test automation, so no problem for implementing the first acceptance test criterium.
> It has been very hard to automate Firefox as backend to Behat as Firefox WebDriver API had long happening issues.
> Safari has a WebDriver API. I haven't tried it yet and I've haven't seen anyone documenting success automating it with Behat yet

**Useful resources:**

* Safari WebDriver tutorial: https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari

## Product Backlog Item Ready Checklist

* [x] Business value is clearly articulated
* [x] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [x] Dependencies are identified and no external dependencies would block this item from being completed
* [x] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [x] This item is estimated and small enough to comfortably be completed in one sprint
* [x] Acceptance criteria are clear and testable
* [x] Performance criteria, if any, are defined and testable
* [x] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by rija** [comment]
Chris says:

> I just saw the new ticket that I'm sure we'll discuss tomorrow:
> https://github.com/gigascience/gigadb-website/issues/617
> but there is an another "user story" that needs to be considered before this one can be done, i.e. we can easily fix the ability to download from the website simply by updating the URL stored in the database, the only reason we are not doing that yet is because we still dont have the download logs for the http://ftp.cngb mirror to be able to track when users do download from there.
> 
> I'm not sure how you want to word that?
> 
> As a dataset owner (someone that has in the past been a submitter, so could potentially call this user a submitter!)
> I want see how many times my data files have been downloaded
> So that I can track the impact of my dataset
> 
> or 
> 
> As a database manager 
> I want to be able to provide download statistics 
> So that I can justify the utility and value of GigaDB
> 
> Given a user downloads a file from a dataset
> When the download is completed
> Then the recorded number of downloads for that file should increase by 1 download
> 
> 
> 
> the implementation to fix #617 is to run an SQL replace command on the database file table to replace "ftp://parrot.genomics.cn/gigadb/pub/" with "https://ftp.cngb.org/pub/gigadb/pub/"

**Comment by rija** [comment]
Hi @pli888, @kencho51, @only1chunts,

Having looked into #632, although I didn't go all the way (docker, behat/codeception layers), I'm now confident it's possible to pilot Safari from a php program.
However I don't think anymore  it's the right approach for this story:
Ensuring the dataset files on a page have a http link (not an ftp one) after running the update script is enough to prove that the fix to the problem works.
Running such test in different browsers won't bring any additional value as all browsers know how to deal with http links (it's kind of one of their "raison d'être").

We do need to automatically tests on multiple browsers for some features (especially the ones that rely heavily on CSS and Javascript), but this is not such feature.

Furthermore, the original acceptance test scenarios didn't take into account the batch nature of the update process we're envisaging, that some files have external hosting and there's a need for a dry-run mode. Finally, the update script should be idempotent, i.e: if it is run (deliberately or accidentally) several times, it should be safe and no-op for the database state.

Therefore I propose for the acceptance test scenarios to #617 to be:

Given there are files attached to datasets:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | ftp://ftp.genomics.cn/000007/sample1.fa |
| 000007 | ftp://ftp.genomics.cn/000007/sample2.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample3.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample4.fa |
| 000009 | ftp://ftp.genomics.cn/000009/sample5.fa |
When I run the update script on datasets:
| doi |
| 000007 |
| 000008 |
| 000009 |
And I navigate to the dataset pages:
| doi |
| 000007 |
| 000008 |
| 000009 |
Then I see in the respective files tab:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | https://ftp.genomics.cn/000007/sample1.fa |
| 000007 | https://ftp.genomics.cn/000007/sample2.fa |
| 000008 | https://ftp.genomics.cn/000008/sample3.fa |
| 000008 | https://ftp.genomics.cn/000008/sample4.fa |
| 000009 | https://ftp.genomics.cn/000009/sample5.fa |


Given there are files attached to datasets:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | ftp://ftp.genomics.cn/000007/sample1.fa |
| 000007 | ftp://ftp.genomics.cn/000007/sample2.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample3.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample4.fa |
| 000009 | ftp://ftp.genomics.cn/000009/sample5.fa |
When I run the update script in dry-run mode on datasets: 
| doi |
| 000007 |
| 000008 |
| 000009 |
And I navigate to the dataset pages:
| doi |
| 000007 |
| 000008 |
| 000009 |
Then I see in the respective files tab:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | ftp://ftp.genomics.cn/000007/sample1.fa |
| 000007 | ftp://ftp.genomics.cn/000007/sample2.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample3.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample4.fa |
| 000009 | ftp://ftp.genomics.cn/000009/sample5.fa |


Given there are files attached to datasets:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | ftp://ftp.genomics.cn/000007/sample1.fa |
| 000007 | ftp://ftp.genomics.cn/000007/sample2.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample3.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample4.fa |
| 000009 | ftp://ftp.genomics.cn/000009/sample5.fa |
When I run the update script twice on datasets:
| doi |
| 000007 |
| 000008 |
| 000009 |
And I navigate to the dataset pages:
| doi |
| 000007 |
| 000008 |
| 000009 |
Then I see in the respective files tab:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | https://ftp.genomics.cn/000007/sample1.fa |
| 000007 | https://ftp.genomics.cn/000007/sample2.fa |
| 000008 | https://ftp.genomics.cn/000008/sample3.fa |
| 000008 | https://ftp.genomics.cn/000008/sample4.fa |
| 000009 | https://ftp.genomics.cn/000009/sample5.fa |


Given there are files attached to datasets:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | ftp://ftp.genomics.cn/000007/sample1.fa |
| 000007 | ftp://ftp.genomics.cn/000007/sample2.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample3.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample4.fa |
| 000009 | ftp://ftp.genomics.cn/000009/sample5.fa |
When I run the update script on datasets:
| doi |
| 000005 |
| 000006 |
And I navigate to the dataset pages:
| doi |
| 000007 |
| 000008 |
| 000009 |
Then I see in the respective files tab:
| doi | url |
| 000007 | http://external.hosting.com/steps.txt |
| 000007 | ftp://ftp.genomics.cn/000007/sample1.fa |
| 000007 | ftp://ftp.genomics.cn/000007/sample2.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample3.fa |
| 000008 | ftp://ftp.genomics.cn/000008/sample4.fa |
| 000009 | ftp://ftp.genomics.cn/000009/sample5.fa |

**Comment by rija** [comment]
@pli888 suggested adding another scenario for actually downloading from the url:

>Given CNGB has setup a web server in front of the ftp server
>When I download a link "https://ftp.genomics.cn/000009/small_file.txt"
>Then the file is downloaded locally

**Comment by rija** [comment]
@only1chunts  added that the url used for downloading the dataset files follows a specific naming pattern and that pattern is slightly different with the https version:

```
On 26 May 2021, at 12:33 PM, Chris Hunter <...> wrote:

Hi Rija,

I think there is a problem with the URLs you've listed: e.g. 

The From URL should be something like this:

https://ftp.genomics.cn/gigadb/pub/10.5524/<dataset_range_directory>/<datasetDOI>/<file_name or directory>

example: ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100001/example_file1.fa

and the TO URL should be:

https://ftp.cngb.org/pub/gigadb/pub/10.5524/<dataset_range_directory>/datasetDOI/filename or directory

This might mean you need more tests to check that the correct dataset range directory is the correct one, and that the subdirectories within the datasets are correctly accounted for.

The ranges are done in units of 1000, so datasets 100001 through 101000 are stored in the directory called 100001_101000, and 101001 through 102000 are in "101001_102000" etc...
```

**Comment by rija** [comment]
Hi @only1chunts,

Thanks for the observation, that's helpful, as in my mind it was just a ``ftp -> https`` transformation.
I don't think we need to add more scenarios. Instead, the scenarios I've proposed and the additional one suggested by @pli888 will need to use the before/after formats that follow the pattern you've described.
I'll list again the scenarios but approprately updated in a new comment shortly to make it clearer.

**Comment by rija** [comment]
Hi @pli888, @kencho51, @only1chunts,

After having looked at the data in the daily production database backup, I realised there are two urls that need to be transformed, those starting with ``ftp://parrot.genomics.cn`` and those starting with ``ftp://ftp.cngb.org``

Below are the updated acceptance tests that cover that as well as everything we've mentioned before, and using real examples found in the aforementioned backup file.

### Default path

Given there are files attached to datasets:
| doi | url |
| :-- | --: |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

When I run the update script on datasets:
| doi |
| :-- |
| 100373 |
| 100891 |
| 100633 |

And I navigate to the dataset pages:
| doi |
| :-- |
| 100373 |
| 100891 |
| 100633 |

Then I see in the respective files tab:
| doi | url |
| :-- | --: |
| 100373 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

### Dry-run

Given there are files attached to datasets:
| doi | url |
| :-- | --: |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

When I run the update script in dry-run mode on datasets: 
| doi |
| :-- |
| 100373 |
| 100891 |
| 100633 |

And I navigate to the dataset pages:
| doi |
| :-- |
| 100373 |
| 100891 |
| 100633 |

Then I see in the respective files tab:
| doi | url |
| :-- | --: |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

## Idempotence

Given there are files attached to datasets:
| doi | url |
| :-- | --: |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

When I run the update script twice on datasets:
| doi |
| :-- |
| 100373 |
| 100891 |
| 100633 |

And I navigate to the dataset pages:
| doi |
| :-- |
| 100373 |
| 100891 |
| 100633 |

Then I see in the respective files tab:
| doi | url |
| :-- | --: |
| 100373 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

## Target only specified datasets

Given there are files attached to datasets:
| doi | url |
| :-- | --: |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

When I run the update script on datasets:
| doi |
| :-- |
| 100169 |
| 100894 |

And I navigate to the dataset pages:
| doi |
| :-- |
| 100373 |
| 100891 |
| 100633 |

Then I see in the respective files tab:
| doi | url |
| :-- | --: |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/vcf/bb_snp.vcf.gz |
| 100373 | ftp://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100373/readme.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/readme_100891.txt |
| 100891 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100891/MesKit-master.zip |
| 100633 | ftp://ftp.ebi.ac.uk/pub/databases/reference_proteomes/previous_releases/qfo_release-2011_04/2011_04_reference_proteomes.tar.gz |
| 100633 | https://figshare.com/s/19a006d6fea9c2494ab8 |
| 100633 | ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt |

## Make sure the web frontend to the FTP server actually works

Given CNGB has setup a web server in front of the ftp server
When I download a link "https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100633/readme_100633.txt"
Then the file is downloaded locally

**Comment by only1chunts** [comment]
Hi Rija,
There really shouldn't be anything in the database starting with `ftp://ftp.cngb.org` so thats a great spot thanks! Glad they are going to get sorted out too.

**Comment by rija** [comment]
Hi @pli888, @kencho51, @only1chunts,

I've updated the scenarios in my previous comment to include ``ftp_site`` as a table column in which to perform the replacement, in addition to the ``location`` column. Also replaced ``doi`` and ``url`` with ``identifier`` and ``location`` respectively to match the  table's column names.

**Comment by only1chunts** [comment]
do you need to include the relevant table names too? i.e. "location" and "ftp_site" columns are in different tables. "FILE.location" and "DATASET.ftp_site" might be more complete.

**Comment by rija** [comment]
Done using files-url-updater
