### ISSUE TITLE
Alert mechanism for technical incidents and under-performance of GigaDB infrastructure

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#625]
## User story

>As a developer  
>I want to know to be notified automatically and immediately when something in GigaDB infrastructure is misbehaving
>So that I can promptly investigate and remediate the situation

## Additional Info

need to gather metrics and logs together in a visualisation tool that has also an alerting system: Grafana
There is already a PBI that will gather metrics into Prometheus for the File Upload Wizard as part of the storage provider migration.

We need do that for other components of GigaDB, and need to gather logs and we need to integrate the alert system with our communication tools. We need  a IT Team dashboard that show green/red status for all components of infrastructure.
This looks like an Epic. More stories to come and be attached to this.

* metrics capture with Prometheus: https://prometheus.io/
* logs aggregation with Loki: https://grafana.com/oss/loki/
* querying, visualisation, dashboard and alerts with Grafana: https://grafana.com/oss/grafana/

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by only1chunts** [comment]
done
