### ISSUE TITLE
delete dataset 100674 files from backup

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#626]
## User story

>As a Site Administrator
>I need to be able to permanently remove the files in dataset 100674 from the public storage 
>So that we can comply with data retraction requirements

## Acceptance criteria

>Given data released as dataset 100674 was retracted (and deleted from public FTP)
>When we do a retrieval from backup
>Then files are NOT restored to 100674

## Additional Info
This is the first manuscript retraction that has resulted in a dataset needing to be retracted also, but its possible it could happen again in the future so there should be an SOP for doing it.
Its possible that we require a flag within the Admin pages for datasets to allow curators to set a dataset as retracted, but that needs more thought and discussion.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by pli888** [comment]
@only1chunts has deleted the files for this dataset from the GigaDB file server and updated its `readme_100674.txt` README file. This file in the Tencent backup therefore needs to be updated too at `/cngbdb/giga/gigadb/pub/10.5524/100001_101000/100674/`. All other files in this backup directory needs to be deleted.

File deletion in Tencent backup needs to be documented and an SOP produced.

**Comment by rija** [comment]
@pli888,
can you confirm whether those files have been removed from the Tencent backup?

**Comment by pli888** [comment]
>can you confirm whether those files have been removed from the Tencent backup?

All files for dataset 100674 in Tencent backup have been deleted.
