### ISSUE TITLE
Make production database backup accessible to the whole IT team

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#630]
Download database fbackup from ftp directory using 
"user-101" username from public ftp server.

hostname: ftp.genomics.cn

**Comment by rija** [comment]
I confirm I am able to download the database backup using credentials and file name supplied by @only1chunts.

Had to adjust the hostname which is not ftp.genomics.cn, but the parrot one.

@pli888, @kencho51: when you confirm you've managed to download the files, I can move this task to Done column.

**Comment by kencho51** [comment]
@rija I could download the database backup by logging in to parrot ftp.

**Comment by pli888** [comment]
@rija I confirm I can download database backup files from the public ftp server using its parrot hostname.

**Comment by rija** [comment]
Hi @kencho51, @pli888 

I discovered you cannot load the backup file into a database server using the client tools from PostgreSQL 9.4 (develop branch) or PostgreSQL 9.6 (fuw-cicd branch).

The backup format is that of a prehistoric version of Postgresql and the latest version supporting it is 9.3. The code below worked for me:
```
$ docker run -v $(pwd):/tmp/sql --name pgsql93 -d postgres:9.3

$ docker exec -it pgsql93 psql -U postgres
> create user gigadb;
> create database gigadb owner gigadb;

$ docker exec -it pgsql93 pg_restore  --exit-on-error --verbose  -U postgres --dbname gigadb  /tmp/sql/gigadbv3_20210518.pgdmp

```

**Comment by only1chunts** [comment]
closing this ticket as its completed
