### ISSUE TITLE
Install rclone instead of cosmd

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#638]
coscmd is limited to tencent cloud. For upcoming stage 2 and 3, we need to be able to connect to other storage

This task is part of Story #600

**Comment by pli888** [comment]
It should be possible to custom install `rclone` as a [precompiled library](https://rclone.org/install/#linux-installation-from-precompiled-binary) in the user home directory of the `transfer` server which is used to perform backups of GigaDB data from CNGB file server to Tencent COS. Installing the tool in `/usr/bin` as recommended in the `rclone` documentation will require sysadmin approval.

Its probably a good idea to check `rclone` works as expected when installed this way in a test installation that mimics the same environment on the `transfer` server that also has `coscmd` installed too.

**Comment by rija** [comment]
not doing anything with tencent anymore
