### ISSUE TITLE
delete dataset 100193 files from backup E574

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#661]
## User story

>As a Site Administrator
>I need to be able to permanently remove the files in dataset 100193 from the public storage 
>So that we can comply with data retraction requirements

## Acceptance criteria

>Given data released as dataset 100193 was retracted (and deleted from public FTP)
>When we do a retrieval from backup
>Then files are NOT restored to 100193

## Additional Info
The readme.txt file should remain in the public server. It has been updated to include a comment about the removal of the data from public view, so the readme.txt file should be backed up.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

This Story is part of #574

**Comment by rija** [comment]
@pli888,
can you confirm whether those files have been removed from the Tencent backup?

**Comment by pli888** [comment]
All files for dataset 100193 in Tencent backup have been deleted.
