### ISSUE TITLE
GigaDB landing page image - roll over display issue

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#666]
**Describe the bug**
There seems to be some limits imposed on the amount of text that is visible for the roll-over display of the text associated with landing page images of GigaDB records.

**To Reproduce**
1. Go to http://dx.doi.org/10.5524/100901
2. Roll over the image
3. I have fixed this now, but the original text was longer (see screenshot) and wasn't entirely visible.

**Expected behavior**
To see all the text that has been added. 
The text is made up of 4 fields which you can see here: http://gigadb.org/dataset/update/id/2311
The fields are: 
1) Image Source 
2) Image Tag
3) Image License 
4) Image Photographer 
I am not sure if the issue is related just to Image Tag or whether it's all of them together. 

**Screenshots**
![Screen Shot 2021-06-01 at 13 47 36](https://user-images.githubusercontent.com/1359170/120649257-769a3480-c474-11eb-912b-32ecca525227.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser : chrome
 - Version : 90.0.4430.212

**Comment by only1chunts** [comment]
fixed
