### ISSUE TITLE
Sample metadata issue 100464

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#675]
Dataset [100464 ](http://dx.doi.org/10.5524/100464)has some confused sample metadata, samples listed as H.sapiens but with larval stages? or C.elegans sample listed with cell type breast cancer?! e.g.
SAMEA2149758 | Caenorhabditis elegans | Description:RNA-seq transcript sequences of Stratagene Universal Human Reference RNA (catalogue ID#740000)Alternative names:humanAlternative accession-BioSample:SAM20465Alternative accession-BioProject:PRJEB22606Sample source:Stratagene Catalogue ID #740000Cell type:breast adenocarcinoma, plasmacytoma, hepatoblastoma, cervical adenocarcinoma, embryonal testis carcinoma, brain glioblastoma, melanoma, liposarcoma, histiocytic lymphoma cell, lymphoblastic leukemia T lymphoblast

Looks like things got muddled up during upload.

**Comment by ChrisArmit** [comment]
Sample attributes have now been updated.
