### ISSUE TITLE
[S600] Handle file permissions issues

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#684]
* [x] Create a test dataset file that's not globally accessible
* [ ] Run ``rclone check`` from the root directory of all public dataset to our test Tencent bucket  with ``--error /var/log/file_errors.log`` option
* [ ] Verify that the permission problem is shown in ``file_errors.log``
* [ ] Setup a cron job to run rclone check command above every hour

The operator who performs the backup will need to consult the error log above before running the sync.
and maybe do something like (don't garantee that's the exact syntax) ``grep <permission error message> /var/log/file_errors.log -exec chmod 777 \{}``

**Comment by rija** [comment]
@kencho51
updated the description to suggest steps towards completion of this task

**Comment by kencho51** [comment]
@rija We have found out that `rclone check` could not for the file permission issues properly, so we propose to use `find . ! -perm -g+r,u+r,o+r` instead.

**Comment by only1chunts** [comment]
just for my information; does "-g+r" mean group=Read only, or does it mean group=read and/or read/write and/or read/write/execute? (or something else?!)

**Comment by kencho51** [comment]
> just for my information; does "-g+r" mean group=Read only, or does it mean group=read and/or read/write and/or read/write/execute? (or something else?!)

Hi @only1chunts , 
`-g+r` means file with group read permission only. And this cmd `find . ! -perm -g+r,u+r,o+r -exec chmod a+r {} \;` is to find the permission that not readable by `group, user or others`, and then change it to readable by everyone. For example, from `----------` to `-r--r--r--`.

**Comment by only1chunts** [comment]
So we are making the assumption that ALL files that we host will ONLY be read access, is that correct?
The only thing that might be an issue (I dont know, thats why I'm bringing it up) are things like HTML and video files, are they OK as read-only? or do they need to be executable to display in a browser?

**Comment by kencho51** [comment]
Hi @only1chunts ,
We are only looking at the files that are not `globally readable` then change it to, all other previous permissions would remain unchanged. For example, if the permission is `-rw-------`, the permission would become `-rw-r--r--` after the change.

**Comment by only1chunts** [comment]
i think this ticket is redundant since we moved to Wasabi hosting, so I'm closing it, please re-open if i'm wrong!
