### ISSUE TITLE
Add keywords field to dataset admin page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#69]
Aim: Since v3 we have been able to handle keywords for datasets, but only if they are added directly to the database by SQL. We need a means to add/update keywords via the admin pages.
Action: Add a keywords field to the dataset admin page as shown below. The keywords are held in the database in the "dataset_attributes" table with the attribute_ID for "Keyword" (which can be found in the "attributes" table.)
![image](https://cloud.githubusercontent.com/assets/6037145/18745373/ce48423e-80b9-11e6-846e-ac6ca2191b96.png)

**Comment by rija** [comment]
Hi. Am I assuming correctly that the "PX_keywords" attribute  I can see referenced  in DatasetController.php is not related to this ticket, and that I should still create an attribute with "Keyword" as attribute_name for the dataset_attributes ?

**Comment by only1chunts** [comment]
Hi, You are correct that "PX_keywords" is different to "keyword" but there should already be a "keyword" attribute in the database dump that Jesse sent you, unfortunately I'm having connection issues (VPN has stopped working) at the moment so I cant check the production database, but it should be either "keyword" or "keywords".

**Comment by rija** [comment]
Oh I see. I have encoding issues with the dump, so I wasn't able to load it yet. I'll look into that dump tmr as it seem to have all the database related changes in it already.  Thank you.
