### ISSUE TITLE
[S600] Add mechanism to reduce occurence of human error

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#694]
| activities | to be careful for | Suggested actions | 
| --- | --- | --- | 
| Querying list of files in Tencent COS | n/a | nothing |
| Sync local changes with remote Tencent COS deep archive | wrong file permissions, make sure the path is right, network failure |  [ ] wrap rclone sync in thin shell scripts, [ ] put path in variable, [ ] log error, [ ] run as cronjob to avoid human error, [ ] default to dry-run |
| upload local files to remote Tencent COS deep archive | wrong file permissions, make sure the path is right, need confirmation, network failure |  we don't really use that as sync is our use case, we will revisit hardening this when it's something we have a use for  |
| Restoration of local files from server | make sure the file has previously been moved from DEEP_ARCHIVE to STANDARD,  we are not overwriting a valid local change | probably best leave this for later when we do versioning  and gitlab based deployment of the tool |
| other admin | [ ] make sure we cannot delete or purge the bucket by accident | [ ] wrap rclone purge in thin shell scripts, [ ] ask for confirmation, [ ] default to dry-run |
| tests| make sure the tests are not running against production Tencent COS | not happening as bucket name hard coded |

**Comment by rija** [comment]
Implementation in pli888/gigadb-website#29

**Comment by rija** [comment]
Reopening to cover addiitional work around restoring files

**Comment by only1chunts** [comment]
closed as the S600 ticket it relates to is closed
