### ISSUE TITLE
Dataset Admin page re-arrangement

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#70]
Should be done in conjunction with #38 , #41 , & #69 
Aim: easier view of dataset admin page.
Action: to rearrange some of the field on the admin dataset page to look more like this:
![image](https://cloud.githubusercontent.com/assets/6037145/18745373/ce48423e-80b9-11e6-846e-ac6ca2191b96.png)

**Comment by rija** [comment]
Hi, a couple of question:
 
The current admin interface seems to be missing the keyword fields and the Type list of checkboxes doesn't have all the values listed on that screenshot.

I cannot see  a keywords field in the database schema for the dataset table.
And the type tables only contains the 10 types I see in the admin page.

Is it an expectation of this ticket that the keywords fields be created and the new types be added?

**Comment by only1chunts** [comment]
Hi, 
The types are a dynamic list of terms that is stored in the database, I guess the github version of the DB only contains a minimal set of terms as its a minimal database for dev purposes, @jessesiu please send @rija a dump of the entire database so that he see's the same as we see in the production site.
The keywords are stored as DATASET_ATTRIBUTES as "keywords" which should be a value in the ATTRIBUTES table (see issue #69), the term maybe missing from the minimal version in Git.

**Comment by rija** [comment]
Great. make sense. And #69 is on my todo list of task anyway. So the screenshot actually shows all the work that need to be done. Not just the re-arangement work. Thanks.
