### ISSUE TITLE
[S600] Configure backup server to suit our workflow

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#709]
The server `` cngb-gigadb-bak`` needs to be configured so we run the robust backup tool:

* [x] It needs rclone
* [x] It needs yum and sudo
* [x] it needs cron

**Comment by rija** [comment]
Here's the doc on how to interact with a Gitlab container registry using docker

https://docs.gitlab.com/ee/user/packages/container_registry/index.html

The doc above indicates that the external port used is the default HTTPS port (``443``):
>The Container Registry works under HTTPS by default. You can use HTTP but it’s not recommended and is beyond the scope of this document. Read the insecure Registry documentation if you want to implement this. 


The ``.gitlab-ci.yml`` in our project's root directory is a good example for what's described in that doc and the desired workflow.
The difference here, is that the part with the ``docker pull`` will be performed directly from the backup server rather than as deployment stage on the Gitlab pipeline. 


Our gitlab config also shows that the host name we need to access is ``registry.gitlab.com``.

**Comment by kencho51** [comment]
@rija 
Now the `backup server` could access to ` https://registry.gitlab.com/`.
Next will be creating `.gitllab-ci.yml` in backup server with updated steps?

**Comment by rija** [comment]
@kencho51, @pli888

just to summarise,

we will not try to get Gitlab-based deployment as part of this task (we will do that next sprint as part of Gitlab pipeline work).

So I've replaced:

```
* [ ] The tool needs to be deployed from our Gitlab Container repository (see my comment below).
```

with

```
* [ ] rclone is configured to sync incrementally the files from the root directory of all public dataset to our test Tencent bucket configured using DEEP_ARCHIVE storage class
```

**Comment by rija** [comment]
@kencho51 @pli888 

I've realised this task is merely for getting the backing server to have all system dependencies installed rather than deploying the backup workflow (there will be another task for that).
So I've replaced the last item in description with ``cron``

After talking to @kencho51 earlier, we've confirmed that cron is installed, so this ticket can be closed.
