### ISSUE TITLE
[S600] Write rclone smoke tests for the same normal paths coscmd has test for

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#714]
write tests in the same Cest file used for rclone setup for:

* backup
* only updated files are uploaded
* deletion of remote file if local file is deleted

**Comment by pli888** [comment]
The rclone tests have been implemented in the [dataset-backup-tool](https://github.com/pli888/gigadb-website/commits/dataset-backup-tool) branch now.

**Comment by only1chunts** [comment]
closed as the S600 ticket it relates to is closed
