### ISSUE TITLE
[S600] Install cronjobs/scripts to enable the workflow and run a real backup

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#715]
* cronjob for fixing permission
* manually run a real backup with rclone
* then ask ourselves are we comforable running the backup in a cron job too?
* Opportunity for pair working

**Comment by kencho51** [comment]
`cron job` testing documentation at [here](https://github.com/kencho51/gigadb-website/tree/cronjob-for-dataset-backup-tool/gigadb/app/tools/dataset-backup-tool#cron-job-testing-on-smoc-server).
The following processes have been tested:
1. Cron scheduling
2. Find and fix permissions
3. rclone sync --dry-run

**Comment by only1chunts** [comment]
closed as the S600 ticket it relates to is closed
