### ISSUE TITLE
[S781] Setup Gitlab Secret Variables for live production environment

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#725]
* Update the ``env-sample`` and ``secrets-sample`` to have LIVE_ variables (not just STAGING_)
* have distinct groups in gitlab for staging and live
* Make sure the Gitlab Upstream group has the appropriate default for variables used on live production environment (not just for staging)

**Comment by only1chunts** [comment]
looks like this is done and merged so closing the ticket
