### ISSUE TITLE
Audit what's on the old Gigadb.org server

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#729]
Make lists of tools and configuration artefacts on CNGB server hosting the web site and the database server that need to be moved out before we can decomission it.

**Comment by kencho51** [comment]
[Tools installed and configuration](https://docs.google.com/document/d/1IQ7ZtJJD9sVsvLk8gJm9IJ5dFeuISgIrVQUUOM9Kdkw/edit?usp=sharing) of the server hosting the gigaDB website.
[Tools installed and configuration](https://docs.google.com/document/d/1-Jsb9rL8AnBJNFevYO17pUiq2ewwHjF2oxZhySaO4q4/edit?usp=sharing) of the server hosting gigaDB database.

**Comment by only1chunts** [comment]
if it wasn't done already its too late now :-D  so closing this ticket.
