### ISSUE TITLE
schema.org and google dataset ext. BioSchema

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#73]
Make entire website complies with [schema.org](http://schema.org/docs/gs.html) schema, including the new Google [Datasets ](https://developers.google.com/search/docs/data-types/datasets)extension.

**Comment by only1chunts** [comment]
look at doing this with BioSchemas.org instead /aswell

**Comment by only1chunts** [comment]
To enable BioSchema and schema compliance for the GigaDB repository home page we can add in the JSON-LD code below to the home page:
`<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "DataCatalog", 
    "name": "GigaDB.org",
    "description": "GigaDB primarily serves as a repository to host data and tools associated with articles in GigaScience; however, it also includes a subset of datasets that are not associated with GigaScience articles. GigaDB defines a dataset as a group of files (e.g., sequencing data, analyses, imaging files, software programs) that are related to and support an article or study. Through our association with DataCite, each dataset in GigaDB will be assigned a DOI that can be used as a standard citation for future use of these data in other articles by the authors and other researchers. Datasets in GigaDB all require a title that is specific to the dataset, an author list, and an abstract that provides information specific to the data included within the set. We encourage detailed information about the data we host to be submitted by their creators in ISA-Tab, a format used by the BioSharing and ISA Commons communities that we work with to maintain the highest data and metadata standards in our journal. To maximize its utility to the research community, all datasets in GigaDB are placed under a CC0 waiver (for more information on the issues surrounding CC0 and data see Hrynaszkiewicz and Cockerill, 2012).Datasets that are not affiliated with a GigaScience article are approved for inclusion by the Editors of GigaScience. The majority of such datasets are from internal projects at the BGI, given their sponsorship of GigaDB. Many of these datasets may not have another discipline-specific repository suitably able to host them or have been rapidly released prior to any publications for use by the research community, whilst enabling their producers to obtain credit through data citation. The GigaScience Editors may also consider the inclusion of particularly interesting, previously unpublished datasets in GigaDB, especially if they meet our criteria and inclusion as Data Note articles in the journal.",
    "alternateName":"GigaScience Journal Database",
    "license":"Public Domain",
    "citation":"Tam P. Sneddon, Xiao Si Zhe, Scott C. Edmunds, Peter Li, Laurie Goodman, Christopher I. Hunter; GigaDB: promoting data dissemination and reproducibility, Database, Volume 2014, 1 January 2014, bau018, https://doi.org/10.1093/database/bau018",
    "url": "https://GigaDB.org/",
            "keywords": ["registry","life science","GigaScience Journal"],
            "provider": [
         {
                "@type":"Person",
                "name": "GigaDB.org support",
                "email": "database@gigasciencejournal.com"
               }
     ]
}
</script>
`

**Comment by only1chunts** [comment]
@jessesiu please confirm this has only been done on the home-page so far, correct? 
If so, I can close this ticket but open a new one for the same thing to be done for the dataset pages (but they require dynamic code to pull specific details from the database).

**Comment by jessesiu** [comment]
Yes, only done on the home-page right now.

**Comment by ScottBGI** [comment]
If we want better indexing in Baidu we need to apply to/use BaiduOpen on top of schema.org:

https://www.dragonsocial.net/blog/top-chinese-search-engines/

Might want to talk to CNGB about this.
