### ISSUE TITLE
[S781] Enable Database backup from AWS deployed database server

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#732]
* Configure the RDS PostgreSQL server to create daily backup that are stored of the database server
* Test the new backups that they can restore the database

**Comment by rija** [comment]
Use DB snapshots to configure in AWS RDS

**Comment by only1chunts** [comment]
I know we have backups as they are used to sync the staging server on a regular basis, and the merge ticket above suggests this ticket is done, so closing it now
