### ISSUE TITLE
Transfer ownership of gigadb.org domain to our alibaba account

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#737]
* Create a route 53 account
* From there, submit a domain name transfer request

**Comment by pli888** [comment]
The registrant for gigadb.org domain has been changed to GigaScience Press with my work email address. However, management of the domain is via a BGI IT Alibaba Cloud account. I have requested BGI IT to transfer the domain to my Alibaba Cloud account.

**Comment by pli888** [comment]
Document to justify that we directly manage the gigadb.org domain can be found [here](https://docs.google.com/document/d/1bRaWJhT1aOraPaQIc0rdUoTi0YslYMfCOgg3nnEaGoQ/edit?usp=sharing).

**Comment by pli888** [comment]
BGI IT department have agreed to transfer management of gigadb.org to us. I've requested for the domain to be transferred to my Alibaba account so the DNS server can be updated before moving domain to AWS Route 53. If the DNS server is not updated then gigadb.org won't be resolvable during transfer to Route 53 as we won't be able to use Alibaba DNS.

**Comment by pli888** [comment]
Closing this ticket because we have ownership of gigadb.org domain in our alibaba account.
