### ISSUE TITLE
Backup HTTPS to Gitlab Secrets upon creation and renewal

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#738]
* When setting up HTTPS certificates during deployment to staging production environment, make a backup of the certificates files to Gitlab Secrets for the Upstream > Staging group
* When setting up HTTPS certificates during deployment to live production environment, make a backup of the certificates files to Gitlab Secrets for the Upstream > Live group
* When testing if a cert exists: if it doesn't,  check on Gitlab variable and if not there create cert otherwise retrive the Gitlab version
* The variables name should contain environment: e.g: staging_fullchain_pem

**Comment by rija** [comment]
@kencho51 an example of us saving certificate data to gitlab api is in this file:
https://github.com/rija/gigadb-website/blob/fuw-cicd/ops/infrastructure/roles/docker-postinstall/tasks/main.yml

Notice the task with ``uri`` commands and HTTP verbs (POST,PUT)

We need to do the same but using ``curl`` instead. The following forum post may help:
https://forum.gitlab.com/t/example-of-how-to-use-api-to-send-curl-request-from-file/39655/2

once we have the right curl command, it can go into this script:
https://github.com/rija/gigadb-website/blob/fuw-cicd/ops/scripts/setup_cert.sh

**Comment by rija** [comment]
@kencho51  the three files we need to save are the three *.pem file mentioned in the nginx config: 
https://github.com/rija/gigadb-website/blob/fuw-cicd/ops/configuration/nginx-conf/sites/staging/gigadb.staging.https.conf

**Comment by rija** [comment]
Finally, better fork ``fuw-cicd``  branch for this taks so you get most up-to-date deployment process

**Comment by rija** [comment]
Just added a bullet point to the description to indicate that we want to try pull the value from Gitlab if the cert doesn't exist on filesystem (which is the main objective of this ticket)

**Comment by kencho51** [comment]
> Notice the task with `uri` commands and HTTP verbs (POST,PUT)
> 
> We need to do similar but using `curl` instead and use as input the three files (so three variablefs) associated with HTTP cert.
> 
Hi @rija ,
Here is the `curl` command:
```
# Path to the certs
FULLCHAIN_PEM=/etc/letsencrypt/live/$REMOTE_HOSTNAME/fullchain.pem

# Backup the fullchain cert to GITLAB CI environment variable and get the http code
http_code_fullchain=$(curl --show-error --silent --output /dev/null --write-out "%{http_code}" \
    --request POST --url $PROJECT_VARIABLES_URL \
    --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" \
    --header "content-type: application/json" \
    --data '{
        "key":"$GIGADB_ENV_tlsauth_fullchain",
        "value":"$FULLCHAIN_PEM['content'] | b64decode"
      }'
    )

if [[ $http_code_fullchain == 400 ]]; then
  curl --show-error --silent --output /dev/null \
    --request PUT \
    --url "$PROJECT_VARIABLES_URL/$GIGADB_ENV_tlsauth_fullchain" \
    --header "content-type: application/json" \
    --header "PRIVATE-TOKEN: $GITLAB_PRIVATE_TOKEN" \
    --data '{
        "value":"$FULLCHAIN_PEM['content'] | b64decode"
      }'
fi
```
This `curl` command works when I hardcoded the variables `$GIGADB_ENV`, `$FULLCHAIN_PEM['content']`, and can be confirmed by looking at the gitlab variable:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/64770635/128994469-5fe6b2a8-b72b-4cfa-ad2f-7e052a3bf9f2.png">

But this is not our intention,  could you tell that what is the proper way to express those variables in `setup_cert.sh`?
