### ISSUE TITLE
get complete citation from DOI ref

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#74]
In the dataset view we have a associated manuscripts section, currently this only displays the DOI as we enter it in the database, this should be able to look up that DOI and retrieve the text citation (i.e. title, authors etc...).
NB - this functionality will be used in #73 when completing the "citation" part of the dataset extension schema.
For ease it maybe worth considering adding those details to the database, so the lookup is only done once?
Both Crossref and datacite have APIs that could be useful for this?

**Comment by jessesiu** [comment]
@only1chunts  This return citation is suitable?

curl -LH "Accept: text/x-bibliography; style=harvard3" https://doi.org/10.1093/gigascience/giy012

Zhang, Zhiyong et al., 2018. Draft Genome of the Protandrous Chinese Black Porgy, Acanthopagrus schlegelii. GigaScience. Available at: http://dx.doi.org/10.1093/gigascience/giy012.

**Comment by only1chunts** [comment]
thats great, but doesn't Harvard style include the authors initials too? if you can find out how to include the initials that would be perfect, but as that is also fine. Thanks

**Comment by only1chunts** [comment]
I have seen this working correctly in @jessesiu version
