### ISSUE TITLE
Solve logging/monitoring difficulties with AWS deployed instances of GigaDB

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#740]
## User Story

>As a developer
>I want all errors and warning from Gigadb services to be logged out in a central dashboard
>So that I can easily trace and diagnostics problems

## Acceptance Criteria

>Given web site is throwing an error because of error in Composer dependencies
>When I go to the central dashboard
>Then I can see the error

>Given web site is throwing an error because of error in application
>When I go to the central dashboard
>Then I can see the error

>Given web site is throwing an error because of HTTP error
>When I go to the central dashboard
>Then I can see the error

## Additional info

* Ensure all developers can easily access from our dev environment the logs of services running on staging and live production environments
* Ensure errors thrown from Composer libraries are logged
* One instance of portainer in each environment (staging and live) served through a reverse proxy (nginx) using https

Make use of Portainer

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by pli888** [comment]
Portainer is now providing our logging needs for now.
