### ISSUE TITLE
[S781] Verify static content on staging is accurate

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#743]
Updated ticket with results of 20 Jan 2022 checks:

| Page name | old live location| staging location | Check Dec version | Check 20Jan version |
|-----|-----|-----|-----|-----|
| Home | [live](http://gigadb.org/) | [staging](https://staging.gigadb.org/) | [y]| [y]|
|  About - general | [live](http://gigadb.org/site/about) | [staging](https://staging.gigadb.org/site/about) | [y]| [y]|
| About - our team | [live](http://gigadb.org/site/team) | [staging](https://staging.gigadb.org/site/team)  | [n1] see #869|  [y]|
|  About - contacts | [live](http://gigadb.org/site/contact) | [staging](https://staging.gigadb.org/site/contact)  | [y]| [y]|
|  About - advisaroy board | [live](http://gigadb.org/site/advisory) | [staging](https://staging.gigadb.org/site/advisory) | [y]| [y]|
| Help - Gigadb search | [live](http://gigadb.org/site/help#search) | [staging](https://staging.gigadb.org/site/help#search) | [y]| [n] see #938 |
|  Help - controlled vocabulary | [live](http://gigadb.org/site/help#vocabulary) | [staging](https://staging.gigadb.org/site/help#vocabulary) | [n2] see #870 and #871 | [y] and page anchors now work|
|  Help - API  | [live](http://gigadb.org/site/help#interface) | [staging](https://staging.gigadb.org/site/help#interface) | [y]| [y]|
|  Help - submission guidelines | [live](http://gigadb.org/site/guide) | [staging](https://staging.gigadb.org/site/guide) | [n3] see #872 | [y]|
|  Help - genomic dataset checklist | [live](http://gigadb.org/site/guidegenomic) | [staging](http://gigadb.org/site/guidegenomic) | [y] see also n3| [y]|
|  Help - imageing checklist | [live](http://gigadb.org/site/guideimaging) | [staging](https://staging.gigadb.org/site/guideimaging) | [y] see n3| [y]|
|  Help - metabolomic dataset checklit | [live](http://gigadb.org/site/guidemetabolomic) | [staging](https://staging.gigadb.org/site/guidemetabolomic) | [y] see n3| [y]|
|  Help - epigenetics dataset checklist | [live](http://gigadb.org/site/guideepigenomic) | [staging](https://staging.gigadb.org/site/guideepigenomic) | [y] see n3| [y]|
|  Help - metagenmics dataset checklist | [live](http://gigadb.org/site/guidemetagenomic) | [staging](https://staging.gigadb.org/site/guidemetagenomic) | [y] see n3| [y]|
|  Help - software dataset checklist | [live](http://gigadb.org/site/guidesoftware) | [staging](https://staging.gigadb.org/site/guidesoftware) | [y] see n3| [y]|
|  FAQS | [live](http://gigadb.org/site/faq) | [staging](https://staging.gigadb.org/site/faq) | [y]| [y]|
|  Terms - Gigadb user policies | [live](http://gigadb.org/site/term) | [staging](https://staging.gigadb.org/site/term) | [y] but see n4 see #873| [y]| [y]|
|  Terms - hosting statement | [live](http://gigadb.org/site/term#statement) | [staging](https://staging.gigadb.org/site/term#hosting) | [n5] see #874 | [y]|
|  Terms - privacy | [live](http://gigadb.org/site/term#privacy) | [staging](https://staging.gigadb.org/site/term#privacy) | [y]| [y]|
|  Terms - correction of web traffic information | [live](http://gigadb.org/site/term#information) | [staging](https://staging.gigadb.org/site/term#information) | [y]| [y]|
|  Terms - personal data | [live](http://gigadb.org/site/term#personal) | [staging](https//staging.gigadb.org/site/term#personal) | [y]| [y]|
| MapBrowse | [live](http://gigadb.org/site/mapbrowse) | [staging](https://staging.gigadb.org/site/mapbrowse) | [y]| [n] see #939|
| Login Page | [live](http://gigadb.org/site/login) | [staging](https://staging.gigadb.org/site/login) | [n6] see #875 | [y]|
| Create account | [live](http://gigadb.org/user/create) | [staging](https://staging.gigadb.org/user/create) | [n7] see #859| [n] see #928 |
| Reset password | [live](http://gigadb.org/user/reset/username//style/float%3Aright) | [staging](https://staging.gigadb.org/user/reset/username//style/float%3Aright) |[n8] see #876 |
| Search | [live](http://gigadb.org/search/new?keyword=Genomic&type%5B%5D=dataset&dataset_type%5B%5D=2) | [staging](https://staging.gigadb.org/search/new?keyword=Genomic&type%5B%5D=dataset&dataset_type%5B%5D=2) | [y] slow, but works| [y]|
| Dataset page static content| e.g. [DOI:10.5524/100933](https://doi.org/10.5524/100933) | [staging-100933](https://staging.gigadb.org/dataset/100933) | [n9] see #877| [n] see #940 |

**Comment by only1chunts** [comment]
n1 - some text changes have been made on the public server; Chris Hunter job title, various other blurbs have odd spaces inserted in the middle of words? e.g. in Chris Armits text "and" has become "a nd"

**Comment by only1chunts** [comment]
n2 - [help-vocab page](http://staging.gigadb.org/site/help#vocabulary) the text here is very different to the current live website. only 5 dataset types are listed in the staging site instead of the full set asin the live site.

**Comment by only1chunts** [comment]
n3 - The content appears to be OK, but the dynamic sizing of the tables in the page is not working, i.e. on a narrow window (like I'm using for testing side by side) the current live site has a slider bar to scroll left/right in the tables, that is missing from the staging version
![guide-table-issue](https://user-images.githubusercontent.com/6037145/143900633-8771603f-68e2-452a-a3ff-e3306def9670.png)
.

**Comment by only1chunts** [comment]
n4 - In the tab heading "GigaDB User Policies" the word GigaDB appears to be in italics? That shouldn't be the case.

**Comment by only1chunts** [comment]
n5 - typo on https://staging.gigadb.org/site/term#hosting
"ll metadata collected by GigaDB is stored" should be "All metadata collected by GigaDB is stored"

**Comment by only1chunts** [comment]
n6 - The staging.gigadb.org/site/login page still includes all the affiliate login options, if they are fixed and working then thats fine, but my assumption was that these would not be fixed in this release, in which case they need to be removed from the login page for now.

**Comment by only1chunts** [comment]
n7 - staging.gigadb.org/user/create causes a CDbException error:
![Screenshot_40](https://user-images.githubusercontent.com/6037145/143907760-735dd1d5-0f6e-4e3b-9dad-e9ea9956cd00.png)

**Comment by only1chunts** [comment]
n8 - [reset password](https://staging.gigadb.org/user/reset/username//style/float%3Aright) page has a couple of tick boxes on it that shouldn't be present, see screensho
![reset-password-issue](https://user-images.githubusercontent.com/6037145/143908304-7863de9e-0d0b-4871-a751-c84994ce3005.png)
t

**Comment by only1chunts** [comment]
n9 - generally the static content of the dataset page is OK with 3 exceptions:
 -  The metrics icons appear to be pre-ceeded by a little hyphen, see red arrows in screenshot below:
![Screenshot_41](https://user-images.githubusercontent.com/6037145/144075287-4926b8a1-036c-477c-865e-bd94d511f5bd.png)

 - dataset thumbnail images are not available on the staging server, hence not showing on dataset pages.
 - similarly, the linked project images are missing from the staging server, so not showing on dataset pages.

**Comment by only1chunts** [comment]
I think the tasks in this ticket are all closed, so can we also close this ticket?

**Comment by only1chunts** [comment]
all related tickets closed, so closing this one too.
