### ISSUE TITLE
[S781] Run performance tests on new live

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#746]
* can use gtmetrix.com to create performance reports.
* compare the performance reports for current gigadb.org and new.gigadb.org
* performance test of connection to database server

**Comment by kencho51** [comment]
Compared staging and current live on gtmetrix, here is the [report](https://gtmetrix.com/compare/Hzg6iHF9/ogUutZir).

**Comment by rija** [comment]
We did this, and it helped us figured out the correct PHP-FPM  settings and the correct sizes AWS reources.
