### ISSUE TITLE
[S781] Smoke tests the new staging deployed web site

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#747]
Updated table with results of 20th Jan 2022 checks

| Thing to check | check Dec version | Check Jan20 version | comments |
| --- | --- | --- | --- |
| login via email | [y] | [y] | |
| login via affiliates | [n] | [n] | Now there is no option to use affiliate login (which is correct for now) |
| automatic emails being sent on registration | [n] | [?] | Unable to test as I am unable to delete any of my user accounts and I dont have any unused email addresses!, this is also a bug in the live version, create ticket |
| automatic emails being sent on dataset submission | [n] | [n] | Error message returned when attempting to submit a prepared spreadsheet submission, see ticket #862 |
| does the contact us form actually send us an email | [n] | [n] | website says thanks for contacting us, but nothing is received in database@ mailbox, Not sure if there is meant to be a confirmation sent to the sender as well or not, but I didn't receive one of those either see #863|
| admin login gives access to admin pages | [y] | [y] | |
| general user login does NOT give access to admin pages | [y] | [n] | unable to check as I dont have a user account and the create account doesn't work|
| logout works | [y] | [y] | |
| reset password works | [n] | [n] | CDbException same error as registration (n1) see #859  |
| change password works | [n] | [n] | CDbException same error as registration (n1) see #859 |
| Edit your personal details works as expected | [n] | [n] | same 2 issues as Dec version; 1 you cant update password - see reset password issue above, 2 you cant unsubscribe from the mailing list! NB the account I was using was already subscribed so I dont know if it would be possible to subscribe via the edit personal details page? see #865 |
| edit dataset link on Your datasets work  | [y] | [y] | the layout of the submission wizard is still a mess, see #933 |
| delete dataset link on your datasets work | [n] | [n] | bug still present, see #866 |
| search bar on homepage works | [n] | [y] | still slow, see #825|
| search bar in header works | [y] | [y] | but still slow see #825 |
| search results are returned by clicking dataset types or keywords or authors | [y] | [y] | still slow, see #825|
| do all admin pages allow appropriate updates to the database? | [n] | [y] | I think they are all working |
| Does Google analytics still works | [n] | [n] | see ticket #942 |
| When i add a news item with the current date does it display on the home page? | [y] | [y] | |
| do the external links in headers and footer all work (e.g. facebook, twitter etc) | [y] | [y] | |
| Are the numbers on the home page accurate? (number of datasets, samples, files and volume, as well as individual dataset types) | [n] | [n] | data volume - known bug see #531 |
| Is the number of datasets in the banner on homepage correct | [y] | [y] | |
| Is the RSS feed on home page working | [y] | [y] | it appears to be, but not sure how to check properly |
| able to download files from datasets | [y] | [y] | confirmed #858 is fixed |
| able to download the templates for sample and files within submission wizard | [n] | [n] | same Error 404. Unable to resolve the request "files/GigaDBUploadForm.xls". see #867 |
| does hypothes.is work | [n] | [y] | not sure if its related or not, but staging now seems slower than it was |
| do admin tables all work as expected? | [n] | [n] |see #943, #944, #934 |

**Comment by rija** [comment]
@only1chunts  probably will notice this to, but I've stumbled upon this issue now while working on #742, and it's not related to the issue that task is for, so putting it here:
it seems github links are not appearing. See http://staging.gigadb.org/dataset/100640

**Comment by only1chunts** [comment]
n1 - CDbException when trying to update user password or register an account
<html>
<body>
<h1 style="border: 0px; outline: 0px; font: 18pt Verdana; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 0.5em; padding: 0px; color: rgb(255, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbException</h1><p class="message" style="border: 0px; outline: 0px; font-size: 11pt; vertical-align: baseline; background: rgb(243, 243, 243); margin: 0px 0px 1em; padding: 1em; color: rgb(0, 0, 0); border-radius: 10px; line-height: 23.4667px; font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbCommand failed to execute the SQL statement: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(64). The SQL statement executed was: UPDATE "gigadb_user" SET "id"=:yp0, "email"=:yp1, "password"=:yp2, "first_name"=:yp3, "last_name"=:yp4, "affiliation"=:yp5, "role"=:yp6, "is_activated"=:yp7, "newsletter"=:yp8, "previous_newsletter_state"=:yp9, "facebook_id"=:yp10, "twitter_id"=:yp11, "linkedin_id"=:yp12, "google_id"=:yp13, "username"=:yp14, "orcid_id"=:yp15, "preferred_link"=:yp16 WHERE "gigadb_user"."id"=35. Bound with :yp0=35, :yp1='only1chunts@gmail.com', :yp2='$argon2id$v=19$m=65536,t=2,p=1$DrmhmKjMKz8k41rg9Wc9LA$E0rSktXtxL6msxt/VQeG6tqRSdXRxTTnDzZbLNCSnsk', :yp3='Chris', :yp4='Hunter', :yp5='GigaDB', :yp6='user', :yp7=true, :yp8=true, :yp9=false, :yp10=NULL, :yp11=NULL, :yp12=NULL, :yp13=NULL, :yp14='only1chunts@gmail.com', :yp15=NULL, :yp16='EBI'</p><div class="source" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 1em; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="file" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px 0px 1em; padding: 0px; font-weight: bold;">/var/www/vendor/yiisoft/yii/framework/db/CDbCommand.php(358)</p><div class="code" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;"><pre style="border: 1px solid rgb(238, 238, 238); outline: 0px; font: 11pt / 18.3333px Menlo, Consolas, &quot;Lucida Console&quot;, monospace; vertical-align: baseline; background: rgb(255, 255, 238); margin: 0.5em 0px; padding: 0.5em;"><span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">346</span>         {
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">347</span>             if($this-&gt;_connection-&gt;enableProfiling)
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">348</span>                 Yii::endProfile('system.db.CDbCommand.execute('.$this-&gt;getText().$par.')','system.db.CDbCommand.execute');
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">349</span> 
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">350</span>             $errorInfo=$e instanceof PDOException ? $e-&gt;errorInfo : null;
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">351</span>             $message=$e-&gt;getMessage();
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">352</span>             Yii::log(Yii::t('yii','CDbCommand::execute() failed: {error}. The SQL statement executed was: {sql}.',
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">353</span>                 array('{error}'=&gt;$message, '{sql}'=&gt;$this-&gt;getText().$par)),CLogger::LEVEL_ERROR,'system.db.CDbCommand');
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">354</span> 
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">355</span>             if(YII_DEBUG)
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">356</span>                 $message.='. The SQL statement executed was: '.$this-&gt;getText().$par;
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">357</span> 
<span class="error" style="border: 0px; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: rgb(252, 227, 227); margin: 0px; padding: 0px; display: block;"><span class="ln error-ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153); font-weight: bold;">358</span>             throw new CDbException(Yii::t('yii','CDbCommand failed to execute the SQL statement: {error}',
</span><span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">359</span>                 array('{error}'=&gt;$message)),(int)$e-&gt;getCode(),$errorInfo);
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">360</span>         }
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">361</span>     }
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">362</span> 
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">363</span>     /**
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">364</span>      * Executes the SQL statement and returns query result.
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">365</span>      * This method is for executing an SQL query that returns result set.
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">366</span>      * @param array $params input parameters (name=&gt;value) for the SQL execution. This is an alternative
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">367</span>      * to {@link bindParam} and {@link bindValue}. If you have multiple input parameters, passing
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">368</span>      * them in this way can improve the performance. Note that if you pass parameters in this way,
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">369</span>      * you cannot bind parameters or values using {@link bindParam} or {@link bindValue}, and vice versa.
<span class="ln" style="border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">370</span>      * Please also note that all values are treated as strings in this case, if you need them to be handled as
</pre></div></div><div class="traces" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 2em 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="border: 0px; outline: 0px; font: 14pt Verdana; vertical-align: baseline; background: transparent; margin: 0px 0px 0.5em; padding: 0px; color: rgb(128, 0, 0);">Stack Trace</h2>

#0 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1756): CDbCommand->execute()
-- | --
#1 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1130): CActiveRecord->updateByPk(35, array("id" => 35, "email" => "only1chunts@gmail.com", "password" => "$argon2id$v=19$m=65536,t=2,p=1$DrmhmKjMKz8k41rg9Wc9LA$E0rSktXtxL...", "first_name" => "Chris", ...))
#2 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(811): CActiveRecord->update(null)
#3 | –  /var/www/protected/models/ChangePasswordForm.php(46): CActiveRecord->save(false)41             $user->password = $this->password; 42             $user->password_repeat = $this->confirmPassword; 43             $user->newsletter = $this->newsletter; 44             $user->encryptPassword(); 45  46             if($user->save(false)) { 47                 return true; 48             } 49         } 50         return false; 51     }
#4 | –  /var/www/protected/controllers/UserController.php(406): ChangePasswordForm->changePass()401  402         if(isset($_POST['ChangePasswordForm'])) 403         { 404             $model->attributes=$_POST['ChangePasswordForm']; 405             $model->newsletter=$_POST['ChangePasswordForm']['newsletter']; 406             if($model->validate() && $model->changePass()) 407                 $this->redirect('/user/view_profile'); 408         } 409         $model->password = $model->confirmPassword = ''; 410         $this->render('changePassword',array('model'=>$model)); 411     }
#5 | +  /var/www/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(49): UserController->actionChangePassword()
#6 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(array())
#7 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(CInlineAction)
#8 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#9 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(1148): CFilter->filter(CFilterChain)
#10 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#11 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(CFilterChain)
#12 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()
#13 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#14 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run("changePassword")
#15 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController("user/changePassword")
#16 | +  /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#17 | –  /var/www/index.php(23): CApplication->run()18 require_once($composer); 19  20 # Run the Yii1.1 application 21 Yii::$enableIncludePath = false; 22 $config=dirname(__FILE__).'/protected/config/main.php'; 23 Yii::createWebApplication($config)->run();

</div><div class="version" style="border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(170, 170, 170); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 8pt; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 1em; padding: 1em 0px 0px; color: gray; font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2021-11-30 10:59:00 nginx/1.21.3<span> </span><a href="http://www.yiiframework.com/" style="border: 0px; outline: 0px; font-size: 10.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Yii Framework</a>/1.1.20-yii2-2.0.15.1-migration</div>
</body>
</html>

**Comment by rija** [comment]
Another problem I noticed, iframe in tabs that are not of type "Protocols.io","JBrowse","3D Models", "Code Ocean" won't load due to limitation of server side code. I discovered it as part of #742, but it's not related to CSP configuration so it won't be tackled in that issue.

**Comment by only1chunts** [comment]
n2 - Dataset Admin table sort not working. 
None of the admin-dataset page table headers actually sort when clicked. The URL changes, but the table order remains the same, e.g.
https://staging.gigadb.org/adminDataset/admin gives the same ordered table as all of these:
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/publication_date
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/identifier 
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/manuscript_id
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/title
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/publication_date
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/modification_date

**Comment by only1chunts** [comment]
n3 - On the tables in most of the Admin pages the text filters do not work in any columns. the space is there at the top of the column to type in, but nothing happens when you click enter.

![image](https://user-images.githubusercontent.com/6037145/144080065-4db2a6ba-fe2d-48ec-9d27-88059f0a2a52.png)

[Dataset_author](https://staging.gigadb.org/adminDatasetAuthor/admin) - sort works, filters do not
[Dataset_Files](https://staging.gigadb.org/adminFile/admin) - sort works, filters do not
[Dataset_Project](https://staging.gigadb.org/adminDatasetProject/admin) - sort work, filters do not
[Dataset_Links](https://staging.gigadb.org/adminLink/admin) - sort works (not DOI - but thats the same as the current live page!), filters do not
[Dataset_relations](https://staging.gigadb.org/adminRelation/admin) - sork works (not related_DOI - but thats the same as the current live page!), filters do not
[Dataset_Funders](https://staging.gigadb.org/datasetFunder/admin) - sort work, filters do not
[Dataset_manuscript](https://staging.gigadb.org/adminManuscript/admin) - sort works (not DOI - but thats the same as the current live page!), filters do not
[Authors](https://staging.gigadb.org/adminAuthor/admin) - sort work, filters do not
[Species](https://staging.gigadb.org/adminSpecies/admin) - sort work, filters do not
[Projects](https://staging.gigadb.org/adminProject/admin)  - sort work, filters do not
[External_links](https://staging.gigadb.org/adminExternalLink/admin) - sort work (as well as live), filters do not
[Link_prefixes](https://staging.gigadb.org/adminLinkPrefix/admin) - sort work, filters do not
[Funder](https://staging.gigadb.org/funder/admin) - sort work, filters do not
[Attribute](https://staging.gigadb.org/attribute/admin) - sort work, filters do not
[Dataset_types](https://staging.gigadb.org/adminDatasetType/admin) - sort work (as well as live), filters do not
[Data_types](https://staging.gigadb.org/adminFileType/admin) - sort work, filters do not
[File_formats](https://staging.gigadb.org/adminFileFormat/admin) - sort work, filters do not
[Users](https://staging.gigadb.org/user/admin) - sort work, filters do not
[News_items](https://staging.gigadb.org/news/admin) - sort work, filters do not
RSS_Messages - no data in table - probably do not even need this table in admin pages!
[Publishers](https://staging.gigadb.org/adminPublisher/admin) - sort work, filters do not
[Update_logs](https://staging.gigadb.org/datasetLog/admin) - sort work (as well as live), filters do not

**Comment by rija** [comment]
This has served its purpose
