### ISSUE TITLE
GigaDB search function not working

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#753]
**Describe the bug**
It appears the search function on the live GigaDB.org page has completely stopped working.

**To Reproduce**
1. Go to http://gigadb.org/search/new?keyword=hazelnut
2. See error :
![image](https://user-images.githubusercontent.com/6037145/128058072-d18ff4b9-3781-4001-9fc1-8826205b3c47.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser chrome
 - Version 92.0.4515.107

**Additional context**

**Comment by tuli** [comment]
It works for me. I even get the right hit! 
Supporting data for "A chromosome-level reference genome of the hazelnut, Corylus heterophylla Fisch."

Just tried with 'brain' and got 92 hits. 

OS: MacOS
Chrome 92.0.4515.107

**Comment by only1chunts** [comment]
it is now working for me too, but the search function still needs work (see #599) so this ticket may act as a reminder that its in need of attention.
