### ISSUE TITLE
Updating or viewing a dataset via Admin: Manage Datasets

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#754]
## User story

>As a curator  
>I want a page I've clicked on to open in a new browser tab
>So that I retain the Manage Datasets page in the original tab

## Acceptance criteria

>Given I have clicked on either the 'view' or 'update' button
>When I want to view or edit the Dataset page for a DOI
>Then I want that page to open in a new tab.

>Given conditions  
>When event  
>Then outcome

## Additional Info

1) http://gigadb.org/dataset/admin
2) query DOI e.g. 100913
3) Click on 'update' button, which takes you to http://gigadb.org/dataset/update/id/2323
I want this in a new tab. 

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by only1chunts** [comment]
not going to be done. If a user wants a separate tab there are already ways to do that in most browsers.
