### ISSUE TITLE
add open peer review section

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#78]
Due to certain reviewers not wanting publons accounts we need the ability to host landing pages for gigascience reviews.
We should create the domain gigadb.org/opr/ to host these.
There is a specific immediate need for this so I have created 2 basic HTML pages (emailed to @jessesiu) to be used as landing pages for the 2 reviews. You may need to tweek the headers to makes sure they display within the GigaDB framework?!

[gigadb.org/opr/s13742-016-0146-1_v0_r1.html](http://gigadb.org/opr/s13742-016-0146-1_v0_r1.html)
and
[gigadb.org/opr/s13742-016-0146-1_v1_r1.html](http://gigadb.org/opr/s13742-016-0146-1_v1_r1.html)

**Comment by pli888** [comment]
The above 2 links to the opr pages do not work.

**Comment by jessesiu** [comment]
The link will changed to 
gigadb.org/files/html/s13742-016-0146-1_v0_r1.html
gigadb.org/files/html/s13742-016-0146-1_v1_r1.html

**Comment by jessesiu** [comment]
@only1chunts It's in the develop branch

**Comment by only1chunts** [comment]
@pli888 This github issue appears to have been done in the past and is currently in the production website, e.g. DOI:10.5524/review.100497 points to  http://gigadb.org/files/html/s13742-016-0146-1_v0_r1.html and DOI:10.5524/review.100499 points to http://gigadb.org/files/html/s13742-016-0146-1_v1_r1.html which is correct...
BUT the link to the PDF downloadable review file on those html pages is out of date and needs to be updated.
Currently they point to CLIMB they need to be changed to point to PARROT server instead:
17 July 2016 | V0 should point to ftp://parrot.genomics.cn/pub/10.5524/reviews/s13742-016-0146-1/13742_2016_146_ReviewerReport_V0_R1.pdf
 and
17 July 2016 | V2 (should say V1) should point to ftp://parrot.genomics.cn/gigadb/pub/10.5524/reviews/s13742-016-0146-1/13742_2016_146_ReviewerReport_V1_R1.pdf
