### ISSUE TITLE
Addition of a Dataset Type "Peer Review"

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#782]
# Potential issue for discussion
This is kind of a solution to a technical challenge rather than a story as such, and maybe best suited to being a task instead of a story. 
Is the addition of another "Dataset_Type" the correct solution to the challenge of knowing how to determine which datasets are data vs peerReview? 
Pros:
Easy to implement quickly

Cons:
As there are multiple things that will need to be changed about the peerReview datasets compared to the data-datasets it may be too simplistic to use the dataset-type (which will have ~70 other terms in it from the SRAO slim #712) e.g.
-The mintDOI button will need to function differently between data and peerReview datasets (#777 )
-the actual admin pages (where one selects the dataset-type) for peerReview-datasets may need to be different (#779 )
-the URL for peerReview-datasets needs to be different to data-datasets (#768 )
-the end-user view of the pages may need to be different 

## User story

>As an editor
>I want to be able to assign a dataset-type of "Peer Review" specifically for peerReview-datasets
>So that we can easily identify datasets of type peer-review

## Acceptance criteria
>Given I am preparing a peer-review dataset for publication  
>When I am on the dataset admin page for that peer-review dataset
>Then I can select the dataset type "Peer Review" from the list of possible dataset types

## Additional Info
This is a task that anyone with an admin user account on GigaDB.org can do, it doesn't have to be a developer.

###Value
The addition of a specific dataset type will give the system a means to identify those entities that should be treated as peerReview-datasets instead of data-datasets

### Dependencies
none known

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by rija** [comment]
not relevant anymore, we made peer review top level objects
