### ISSUE TITLE
[S781] Enable access to staging on staging.gigadb.org

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#783]
* [x] Create Elastic IP for upstream staging environment with appropriate tag
* [x] Modify DNS records for gigasciencejournal.com to have an A record for `staging` to point to Elastic IP of staging environment in Upstream group.
* [x] Create new AWS IAM user for staging and live deployment

**Comment by pli888** [comment]
>Create Elastic IP for upstream staging environment with appropriate tag

Currently, we are using the HK ap-east-1 region for our development work. I would like to suggest that we use the Tokyo ap-northeast-1 region for deployment of GigaDB from `Upstream` group so we don't run into reached max elastic IP issues, etc.
