### ISSUE TITLE
remove anonymous FTP access to data server

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#796]
## User story

>As a site Administrator
>I want to tighten the security of the public FTP server
>So that only private user accounts have access

## Acceptance criteria

>Given there is a ftp server where to download dataset files  
>When I try to download a file
>Then I need to input credentials

>Given there is a ftp server where to download dataset files  
>When I try to download a file without credentials
>Then the connection is denied

## Additional Info
Since the public FTP server is no longer accessed directly from GigaDB.org there is no need for anonymous FTP access.

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by rija** [comment]
Not relevant since we are moving to Wasabi and files will be publicly availlable using HTTP URLS
