### ISSUE TITLE
change the author list display

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#80]
This issue will actually be fixed by completing #81 
This should also be considered whilst looking at issue #82 
At least 2 authors have said the format of the author list on the webpage is inconsistent with how they would expect to see names displayed, i.e. using comma's instead of periods between initials. check how GigaScience journal displays them and match it.

**Comment by only1chunts** [comment]
The citations are listed in GigaScience papers as <Surname><space><first-initial><second-initial><third-initial><comma>. e.g Hebsgaard MB, Gilbert MTP, Arneborg J

**Comment by rija** [comment]
closing as done and merged 6 years ago
