### ISSUE TITLE
Capture EM report on a regular basis E760

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#804]
## User story

>As an editor
>I want The EM report to be automatically captured periodically
>So that the regular reviews spreadsheet in the report is downloaded and can be further processed

## Acceptance criteria

>Given a EM report is uploaded daily to a sftp server
>When the file is on the sftp server
>Then the EM report spreadsheet is downloaded

## Additional Info
Regular interval: daily

a prototype of the sftp server is running at ``gigadb-sftp.rija.dev``

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

This Story is part of Epic #760

**Comment by rija** [comment]
Hi @only1chunts,

I have a question about the report you have set up: 
Is there specific reason that in your report  you are joining "Review Questions and Responses View" and "Reviewers and Submissions View" on PUBDNUMBER, instead of using PEOPLEID. It seems to me that what connect those two views are the reviewers (hence PEOPLEID), but I'm sure I'm missing something.

**Comment by only1chunts** [comment]
there is no good reason for anything! it was all done by trial and error as I had no schema to work from so had no clues as to what were common fields in different tables :-D 
However, I'm not sure the PEOPLEID would be appropriate as a single person can make multiple reviews of multiple different manuscripts, so perhaps the manuscript ID is the one to use to make sure you are getting the correct review from that reviewer?
