### ISSUE TITLE
[S781] Update service uptime monitoring to focus on live use facing service

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#836]
Monitor:

* live web site (gigadb.org)
* FTP server 
* Database server

Change email notification to go to all gigascience

**Comment by kencho51** [comment]
The uptime status page has been updated as [here](https://stats.uptimerobot.com/LGVQXSkN1y).
The alert messages of these servers will also be sent to gigateam@gigasciencejournal.com which needs to be activated first.
