### ISSUE TITLE
integrated genome explorer E613

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#84]
## User story

>As a website user
>I want to visualise and interact with an assembled genome
>So that I get better perspective on the genome

### Acceptance criteria

>Given
>When
>Then
## Additional info

Discussed this with Monica Munoz Torez, J-browse ([https://jbrowse.org/](https://jbrowse.org/)) is now the carrier for Appollo genome annotation tool.

We could include JBrowse as the basic viewer for any genome, and include Appollo capabilities for any that we think would be useful, or maybe even all! [http://gmod.org/wiki/WebApollo ](http://gmod.org/wiki/WebApollo )

Another options might be to look at Badger: https://github.com/elswob/Badger/blob/master/README.md#installation-requirements, either way, we need to ensure all assemblies are in the appropriate format for it. 

This Story is part of #613

**Comment by only1chunts** [comment]
@jessesiu , please can you list all the files that are required to be able to get a jbrowse working for a dataset?: 
1-Genome assembly file in Fasta format
2-???

**Comment by jessesiu** [comment]
In the test dataset http://dx.doi.org/10.5524/100240 
2- Gene structure annotation file in GFF format 

For BAM, BigWig, VCF formats etc can directly put in the JBrowse

**Comment by jessesiu** [comment]
1- genome assembly (fasta)
2- gene structure (gff3 or BigWig)
3- RNAseq aligned files (BAM or BigWig) -optional
4- SNPs/variants (VCF or BigWig) - optional
5- Any other tracks (BigWig) - optional

**Comment by ChrisArmit** [comment]
1. JBrowse
JBrowse is currently available as a tab in GigaDB. An example dataset is below:
http://dx.doi.org/10.5524/100644
JBrowse is displayed in an iFrame in GigaDB.

2. Integrative Genomics Viewer (IGV)
igv.js is an embeddable interactive genome visualisation component developed by the Integrative Genomics Viewer (IGV) team.
https://github.com/igvteam/igv.js#igvjs
This viewer is particularly suited for multi-locus visualisation (see following link).
http://software.broadinstitute.org/software/igv/multilocus_view
Consequently, it could be a superior alternative to JBrowse for comparative genomics (e.g. Fish10K, Ruili Botanical Garden dataset) where a user may wish to simultaneously view, for example, paralogous genes in multiple species.

**Comment by ChrisArmit** [comment]
BlobTools also includes IGV (Intergrative Genomics Viewer) which may be an alternative to JBrowse / Apollo.

An example, I've added BlobTools to a test GigaDB entry. It is displayed immediately below MultiQC on the 3D Viewer tab.
http://gigadb.org/dataset/view/id/200051/token/S7iZ8uzhes9NCHgF

--Click on the 3D Viewer tab to see BlobTools

**Comment by only1chunts** [comment]
There are apparently issues with including JBrowse code and data on our public FTP server now (Chinese security police flagged it with CNGB/BGI today). As a quick "fix" to comply with network police notice CNGB are removing the JBrowse related file from their current location parrot.genomics.cn/gigadb/JBrowse/ to somewhere else (I'm not sure where!) that is not public. This will break all URLs that we have currently displaying JBrowse data from our datasets (listed below):
100240, 100441, 100589, 100606, 100619, 100622.
**In order to not show broken links in the public version of the website we could remove the JBrowse links from the admin tables.**

Note - there are other datasets that appear to have been processed in the JBrowse directory that we are not displaying in GigaDB, I have no recollection as to why, so they need investigating, they are : rice_var, 100602 and 100503
