### ISSUE TITLE
Status "Private" datasets should not be visible on base URL

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#857]
**Describe the bug**
regardless of logged-in status I can view PRIVATE datasets without using the token URL.

**To Reproduce**
1. Go to 'https://staging.gigadb.org/dataset/200070'
2. See the Private dataset 200070!

**Expected behavior**
A private dataset (such as 200070) should not be visible on the base URL https://staging.gigadb.org/dataset/200070 or any derivative thereof (e.g. https://staging.gigadb.org/dataset/view/id/200070 or https://staging.gigadb.org/dataset/view/id/200070/File_page/1 etc...)
A private dataset (such as 200070) should only be visible via its token-URL, e.g. 
https://staging.gigadb.org/dataset/200070/token/ImP3Bbu7ytRSfYFh

## Additional information

* Maybe bug relating to status information in codebase

**Comment by rija** [comment]
Fixed in PR #906
