### ISSUE TITLE
Not all files in database are being displayed on dataset pages

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#858]
**Describe the bug**
The files table on public dataset pages has some issues! 
1 - there is no indication of how many files are in the dataset (see red box on screenshot of comparison of staging vs live)
2- Not all files are being displayed in the table, in the screenshot example you can see 7 files in the staging server display, yet 778 in the live production version.

I suspect issue 2 has something to do with sub-directories somehow, just not sure how/why.

**To Reproduce**
1. Go to 'https://staging.gigadb.org/dataset/100926'
2. Scroll down to the tables section
3. Click on "Files" tab
4. See only 7 of the 778 files within that dataset.

**Expected behavior**
All files listed in GigaDB database should be displayed in GigaDB website

**Screenshots**
left is staging.gigadb.org   right is the live CNGB gigadb.org for dataset 100926
![files-table](https://user-images.githubusercontent.com/6037145/144264645-cf51f957-c0b9-4cd7-bba5-9d18640d1d02.png)

## Additional Information

* Chris thinks the files in this dataset are in folders and staging server is not showing the files in these folders
* Maybe problem with pagination too

**Comment by rija** [comment]
Fixed in PR #912
