### ISSUE TITLE
Dataset Admin table is not sortable

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#860]
**Describe the bug**
The dataset admin table sort on column function is not working. 

**To Reproduce**
1. Go to https://staging.gigadb.org/adminDataset/admin
2. Click on any column heading, e.g. "ID"
3. See page reload with new URL (e.g. https://staging.gigadb.org/adminDataset/admin/Dataset_sort/id) but nothing happened to the table row order.

**Expected behavior**
When one clicks the header of a column the rows in the table should be sorted by that column in a-z, then if clicked again in z-a order.

**Additional context**
None of the admin-dataset page table headers actually sort when clicked. The URL changes, but the table order remains the same, e.g.
https://staging.gigadb.org/adminDataset/admin gives the same ordered table as all of these:
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/publication_date
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/identifier 
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/manuscript_id
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/title
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/publication_date
https://staging.gigadb.org/adminDataset/admin/Dataset_sort/modification_date

_Originally posted by @only1chunts in https://github.com/gigascience/gigadb-website/issues/747#issuecomment-982753844_

* Check differences in code between live server and develop branch

**Comment by rija** [comment]
This is fixed with PR #890
