### ISSUE TITLE
Error when attempting to submit dataset spreadsheet via webpage

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#862]
**Describe the bug**
Error message returned when attempting to submit a prepared spreadsheet submission "Upload failed. Please contact database@gigasciencejournal.com"

**To Reproduce**
1. Go to https://staging.gigadb.org/datasetSubmission/upload
2. Tick agree to terms and conditions
3. add a file to be uploaded
4. click "upload new dataset" button
5. see error message "Upload failed. Please contact database@gigasciencejournal.com"

**Expected behavior**
the website is suposed to send the spreadsheet to database@gigasciencejournal.com AND send a confirmation/thank you letter to the submitter.

** Additional information ** 
Ticket created from smoke testing question "are automatic emails being sent on dataset submission" in #747 

* Spreadsheet is sent as an attachment to database@gigasciencejournal.com
* Probably configuration problem

**Comment by rija** [comment]
reopen as still a problem on staging.
Maybe a problem with the email sending details

**Comment by pli888** [comment]
>reopen as still a problem on staging.

@only1chunts This is working on the staging server now with the spreadsheet sent as an attachment in the email. Note that the attachment does not have the original Excel filename though.

**Comment by only1chunts** [comment]
Yes it sends the attachment, but as you noted it does mess up the file name, including removing any file extension which means its difficult to open it. If there is an easy fix to this it would be great to have it now, but if its something that will take a while then we can go "live" with it for now and add it to the backlog for later.
NB- I also noticed a very Ugly breakage when I accidentally clicked the "Upload dataset" button before selecting a file, so that should be made more elegant in the future.

**Comment by pli888** [comment]
>NB- I also noticed a very Ugly breakage when I accidentally clicked the "Upload dataset" button before selecting a file, so that should be made more elegant in the future.

Clicking "Upload New Dataset" button before selecting a file is also a problem on the live server. It's because the file selector and `Upload New Dataset` button both become enabled in the front-end code after the `terms and conditions` checkbox is checked.
