### ISSUE TITLE
no email received from contact us form

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#863]
**Describe the bug**
When a website user tries to contact us via the website contact us form it should send the email to database@gigasciencejournal.com, but it does not appear to be working on staging.gigadb.org
It says thanks for contacting us, but nothing is received in database@ mailbox, Not sure if there is meant to be a confirmation sent to the sender as well or not, but I didn't receive one of those either.

**To Reproduce**
1. Go to https://staging.gigadb.org/site/contact
2. Fill out the form & verify code
3. click send
4. goto database@gigasciencejournal.com mailbox or the mailbox you entered as sender to await an email that never comes.

**Expected behavior**
When a website user tries to contact us via the website contact us form it should send the email to database@gigasciencejournal.com

**Additional context**
Ticket created from smoke testing question "does the contact us form actually send us an email" in #747

* Need to check configuration for mail server used in staging server
* There is a standard way now to send emails - need to make this functionality is using this standard way

**Comment by only1chunts** [comment]
still an issue on the Jan20 version

**Comment by rija** [comment]
This is still a problem on staging

**Comment by pli888** [comment]
>still an issue on the Jan20 version

This is working for me on the [staging server](https://staging.gigadb.org/site/contact) now. @only1chunts can you confirm please?

**Comment by only1chunts** [comment]
Confirmed. It is working for me also on the staging server thanks.
