### ISSUE TITLE
smoke test fail: hypothes.is not working

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#868]
**Describe the bug**
 does hypothes.is work? No. there is no sign that hypothes.is is active on the staging website. 

**To Reproduce**
1. Go to any GigaDB page, e.g. staging.gigadb.org
2. look to the right hand side 
3. see ... nothing!

**Expected behavior**
The hypothes.is side bar should be available on all gigadb.org pages, see screenshot below of comparison of home page on public live server vs staging server

**Screenshots**

![Screenshot_46](https://user-images.githubusercontent.com/6037145/144615100-1438299d-d6eb-4fdd-9b3b-36c77fcf35e8.png)

**Additional context**
This is a bug found during tests listed in #747

* This problem is related to the Content Security Policy issue - see #850

**Comment by rija** [comment]
This should be fixed by PR #850
