### ISSUE TITLE
static content test failed: "Terms - hosting statement"

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#874]
**Describe the bug**
typo on https://staging.gigadb.org/site/term#hosting
"ll metadata collected by GigaDB is stored" should be "All metadata collected by GigaDB is stored".

Note - also suffers from the lack of anchoring bug #871 

**To Reproduce**
1. Go to https://staging.gigadb.org/site/term#hosting
2. Click on "Hosting" tab
3. Scroll down to 'Metadata" section
4. See first letter 'A' missing from word All

**Additional context**
This is a bug found during tests listed in #743

**Comment by rija** [comment]
fixed 3 years ago, so closing
