### ISSUE TITLE
static content test failed: "login page"

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#875]
**Describe the bug**
The staging.gigadb.org/site/login page still includes all the affiliate login options, if they are fixed and working then thats fine, but my assumption was that these would not be fixed in this release, in which case they need to be removed from the login page for now.

**To Reproduce**
1. Go to https://staging.gigadb.org/site/login
2. See affiliate login options on right side of screen

**Expected behavior**
Until the single sign on functionality (#826 )has been completed we agreed to remove the ability of users to log on using affiliates as that code is currently broken.

**Additional context**
This is a bug found during tests listed in #743

**Comment by rija** [comment]
Fixed long time ago
