### ISSUE TITLE
static content test failed: "reset password"

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#876]
[reset password](https://staging.gigadb.org/user/reset/username//style/float%3Aright) page has a couple of tick boxes on it that shouldn't be present, see screenshot:
![reset-password-issue](https://user-images.githubusercontent.com/6037145/143908304-7863de9e-0d0b-4871-a751-c84994ce3005.png)
t

_Originally posted by @only1chunts in https://github.com/gigascience/gigadb-website/issues/743#issuecomment-981814583_

**Comment by rija** [comment]
Fixed long time ago
