### ISSUE TITLE
static content test failed: "dataset page"

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#877]
generally the static content of the dataset page is OK with 2 exceptions:
 -  The metrics icons appear to be pre-ceeded by a little hyphen, see red arrows in screenshot below:
![Screenshot_41](https://user-images.githubusercontent.com/6037145/144075287-4926b8a1-036c-477c-865e-bd94d511f5bd.png)

 - similarly, the linked project images are missing from the staging server, so not showing on dataset pages.

_Originally posted by @only1chunts in https://github.com/gigascience/gigadb-website/issues/743#issuecomment-982739373_

* Write acceptance test to check single dataset page contains an image

**Comment by rija** [comment]
Closing as fixed long time ago
