### ISSUE TITLE
Display dataset images from Cloud

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#878]
## User story

>As a website user
>I want to see the dataset images
>So that the dataset page looks more engaging

## Acceptance criteria

>Given there is a dataset with an image in Cloud storage
>When I navigate to the dataset page
>Then I can see the dataset image

>Given there is no image associated with a dataset
>When I navigate to the dataset page
>Then I can see generic image

## Additional Info

* Images from new datasets will be uploaded to cloud manually by curators using dataset admin form
* All images currently on CNGB server can be batch uploaded to cloud storage
* Batch upload will need to update URLs to images so they link to those on cloud storage
* Generic image - Chris H to supply generic image for converting to base 64
* Exclude generic images from batch upload into cloud
* Ensure code displays generic image if dataset has `null` for its image location

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not be compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (I.e. the increment has not broken anything)

--

Images on dataset pages are not being displayed on dataset pages:

 - dataset thumbnail images are not available on the staging server, hence not showing on dataset pages.

_Originally posted by @only1chunts in https://github.com/gigascience/gigadb-website/issues/743#issuecomment-982739373_

## Additional information

Images are in a directory on the current live server. Have dedicated online image server for storing image files?

Need to build a command line tool to do the following:

1. Install Rclone on current live server and use it to retrieve file from CNGB server and place in S3.
2. Then need to update the image links for dataset record in PostgreSQL database to refer to the same image in S3.

Blog describing an approach: https://dev.to/chattes/s3-as-docker-volumes-3bkd

**Comment by rija** [comment]
Hi all,

Based on @only1chunts's last comment on #922 about thumbnail,

we can say that he initial upload of an image is associated with the bulk upload of data for new datasets 
Which for now we'll let happen on CNGB deployment of GigaDB.

What we can do then, is to let dataset images on CNGB deployment for now until we are ready to release Submission Wizard and File Upload Wizard.

In the meantime, the AWS deployment of GigaDB will request the images from the CNGB deployment directly, so we don't have to transfer any image for now.

In other words, it is not necessary to transfer the dataset images in order to go live with AWS deployment.

To make that possible, the following needs to be done:

* There should be a DNS A-record ``images.gigadb.org.`` that points to the current IP address of the CNGB deployment
* The Nginx configuration file for CNGB deployment needs a change to add ``images.gigadb.org`` to the ``server`` directive
* The content security Policy configuration on AWS deployment need a new ``images.gigadb.org`` to the ``img-src:`` directive
* We need to create a database migration file similar to the one to be made on PR #896 so dataset pages can resolve the url to their thumbnail image

**Comment by rija** [comment]
Amendment to the approach to implementing this task:

1. Ensure ``images.gigadb.org`` point to CNGB live web server and Let's Encrypt configuration include that new domain
2. Make a migration script to update the image column to have full url starting with ``https://images.gigadb.org/``  (ok to use gigadb.org as this is temporary  and for accessing legacy images)
3. In AdminDatasetController.php: Update the dataset update form to allow image upload and saving to a S3 compatible cloud storage using [Flysystem](https://flysystem.thephpleague.com/v2/docs/)
4. When saving the corresponding dataset record, save the edge-cached url in the image column of the image table: use ``https://gigadbcdn.net`` (it's better to NOT use gigadb.org as it makes cookie-less access easier to static assets, which is important for performances): create that domain in Route53, but setup CloudFlare as its DNS server to enable edge caching

**Comment by only1chunts** [comment]
no-image.png file to be used for datasets that have no image uploaded
![no_image](https://user-images.githubusercontent.com/6037145/153566262-d4b06329-adbe-4597-baf9-bcb8e4964f42.png)

**Comment by rija** [comment]
the generic image is now on S3 at :
http://gigadb-cdn.net.s3-website.ap-east-1.amazonaws.com/assets/images/datasets/no_image.png

**Comment by rija** [comment]
Sprint 20 (where we switch over to AWS for real):

* cut database synchronisation from CNGB (by Friday 26th May)
* curators to manually upload images for recent datasets into the new system
* for the full image migration next sprint: scrape the image directly from old.gigadb.org, not from the filesystem

**Comment by rija** [comment]
Mechanism dataset images on AWS is already so closing. Will create another ticket  (#1295) for migration of existing dataset images
