### ISSUE TITLE
Link out to Nitime from GigaDB datasets

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#88]
Nicole suggested collaborating with [NITRC](https://www.nitrc.org):

> One of the ways we discussed a collaboration between the two repositories is having a link from GigaDB on relevant pages where a tool or data is also available in NITRC. For example, this is supporting data for one of the Brainhack reports using Nitime: http://gigadb.org/dataset/100225
We can add an external link to Nitime in NITRC: https://www.nitrc.org/projects/nitime

We can do this probably by adding the Nitime link as an entry in the `external_link` table in the GigaDB PostgreSQL database from the create dataset wizard webpage.

**Comment by only1chunts** [comment]
This is covered by various other tickets in Epic #597
