### ISSUE TITLE
CDbException when updating file metadata

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#886]
**Describe the bug**
This bug exists on current CNGB live production server too so its not something introduced in the code re-write, but it does need to be fixed.
When a file is updated via the admin pages it throws a CDbException error if the release date is not set.

**To Reproduce**
1. Go to any edit file page, e.g. https://staging.gigadb.org/adminFile/update/id/464662
2. delete the release date if present
3. Click on save

**Expected behavior**
There is a bigger issue that does need to be addressed (see ticket #887) but for initial release of the dev-staging codebase it will be sufficient to remove the requirement for the release date to be set when updating files via the admin page.

**Additional context**
<html>
<body>
<h1 style="border: 0px; outline: 0px; font: 18pt Verdana; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 0.5em; padding: 0px; color: rgb(255, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbException</h1><p class="message" style="border: 0px; outline: 0px; font-size: 11pt; vertical-align: baseline; background: rgb(243, 243, 243); margin: 0px 0px 1em; padding: 1em; color: rgb(0, 0, 0); border-radius: 10px; line-height: 23.4667px; font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbCommand failed to execute the SQL statement: SQLSTATE[22007]: Invalid datetime format: 7 ERROR: invalid input syntax for type date: "". The SQL statement executed was: UPDATE "file" SET "id"=:yp0, "dataset_id"=:yp1, "name"=:yp2, "location"=:yp3, "extension"=:yp4, "size"=:yp5, "description"=:yp6, "date_stamp"=:yp7, "format_id"=:yp8, "type_id"=:yp9, "code"=:yp10, "index4blast"=:yp11, "download_count"=:yp12, "alternative_location"=:yp13 WHERE "file"."id"=464662. Bound with :yp0=464662, :yp1=2342, :yp2='readme.txt', :yp3='ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100754/relative_abundance_correlation.csv', :yp4='pdf', :yp5='3043', :yp6='testing', :yp7='', :yp8=6, :yp9=128, :yp10='FILE_CODE', :yp11=NULL, :yp12=0, :yp13=NULL</p><div class="source" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 1em; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="file" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px 0px 1em; padding: 0px; font-weight: bold;">/var/www/vendor/yiisoft/yii/framework/db/CDbCommand.php(358)</p><div class="code" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;"><pre style="border: 1px solid rgb(238, 238, 238); outline: 0px; font: 11pt / 18.3333px Menlo, Consolas, &quot;Lucida Console&quot;, monospace; vertical-align: baseline; background: rgb(255, 255, 238); margin: 0.5em 0px; padding: 0.5em;"><span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">346</span>         {
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">347</span>             if($this-&gt;_connection-&gt;enableProfiling)
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">348</span>                 Yii::endProfile('system.db.CDbCommand.execute('.$this-&gt;getText().$par.')','system.db.CDbCommand.execute');
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">349</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">350</span>             $errorInfo=$e instanceof PDOException ? $e-&gt;errorInfo : null;
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">351</span>             $message=$e-&gt;getMessage();
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">352</span>             Yii::log(Yii::t('yii','CDbCommand::execute() failed: {error}. The SQL statement executed was: {sql}.',
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">353</span>                 array('{error}'=&gt;$message, '{sql}'=&gt;$this-&gt;getText().$par)),CLogger::LEVEL_ERROR,'system.db.CDbCommand');
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">354</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">355</span>             if(YII_DEBUG)
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">356</span>                 $message.='. The SQL statement executed was: '.$this-&gt;getText().$par;
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">357</span> 
<span class="error" style="box-sizing: border-box; border: 0px; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: rgb(252, 227, 227); margin: 0px; padding: 0px; display: block;"><span class="ln error-ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153); font-weight: bold;">358</span>             throw new CDbException(Yii::t('yii','CDbCommand failed to execute the SQL statement: {error}',
</span><span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">359</span>                 array('{error}'=&gt;$message)),(int)$e-&gt;getCode(),$errorInfo);
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">360</span>         }
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">361</span>     }
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">362</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">363</span>     /**
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">364</span>      * Executes the SQL statement and returns query result.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">365</span>      * This method is for executing an SQL query that returns result set.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">366</span>      * @param array $params input parameters (name=&gt;value) for the SQL execution. This is an alternative
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">367</span>      * to {@link bindParam} and {@link bindValue}. If you have multiple input parameters, passing
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">368</span>      * them in this way can improve the performance. Note that if you pass parameters in this way,
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">369</span>      * you cannot bind parameters or values using {@link bindParam} or {@link bindValue}, and vice versa.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">370</span>      * Please also note that all values are treated as strings in this case, if you need them to be handled as
</pre></div></div><div class="traces" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 2em 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="border: 0px; outline: 0px; font: 14pt Verdana; vertical-align: baseline; background: transparent; margin: 0px 0px 0.5em; padding: 0px; color: rgb(128, 0, 0);">Stack Trace</h2>

#0 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1756): CDbCommand->execute()
-- | --
#1 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1130): CActiveRecord->updateByPk(464662, array("id" => 464662, "dataset_id" => "2342", "name" => "readme.txt", "location" => "ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100754...", ...))
#2 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(811): CActiveRecord->update(null)
#3 | –  /var/www/protected/controllers/AdminFileController.php(413): CActiveRecord->save()408         } elseif (isset($_POST['File'])) { 409             $model->attributes = $_POST['File']; 410  411             $model->setSizeValue(); 412             if ($model->validate()) { 413                 $model->save(); 414  415                 if(isset($_POST['File']['sample_name']) && !empty($_POST['File']['sample_name'])) { 416                     $fs = $model->fileSamples; 417                     if(!isset($fs[0])) { 418                         $fs = new FileSample;
#4 | unknown(0): AdminFileController->actionUpdate("464662")
#5 | +  /var/www/vendor/yiisoft/yii/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(AdminFileController, array("464662"))
#6 | +  /var/www/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(AdminFileController, ReflectionMethod, array("id" => "464662"))
#7 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(array("id" => "464662"))
#8 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(CInlineAction)
#9 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#10 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(1148): CFilter->filter(CFilterChain)
#11 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#12 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(CFilterChain)
#13 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()
#14 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#15 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run("update")
#16 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController("adminFile/update/id/464662")
#17 | +  /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#18 | –  /var/www/index.php(23): CApplication->run()18 require_once($composer); 19  20 # Run the Yii1.1 application 21 Yii::$enableIncludePath = false; 22 $config=dirname(__FILE__).'/protected/config/main.php'; 23 Yii::createWebApplication($config)->run();

</div>
</body>
</html>

**Comment by rija** [comment]
Fixed in PR #909
