### ISSUE TITLE
protocols.io integration

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#89]
We have some instances of datasets that link out to protocols.io e.g.
They have now added iframes availability to all their protocols, so we should look at ways to integrate those into GigaDB pages. From Lenny "every public protocol already has it. Click on "MORE" and copy-paste the code. Nice example of the iframe protocols on another site: http://2015.igem.org/Team:Northeastern_Boston/notebook. "
Example: 
GigaDB dataset = http://dx.doi.org/10.5524/100248
protocols.io iframe widget code = 
<iframe src="https://www.protocols.io/widgets/protocol/megabase-dna-extraction-from-animal-blood-gagbsbw" style="width: 100%; height: 700px; border: 1px solid transparent;"></iframe>
AND
<iframe src="https://www.protocols.io/widgets/protocol/irys-nlrs-dna-labeling-and-data-collection-gahbsb6" style="width: 100%; height: 700px; border: 1px solid transparent;"></iframe>

We could now just stick them directly into the description section as that accepts HTML, and it works. but I would like to include them as a separate section that is collapsible (like the igem example given by Lenny above).
For an immediate results hack I have stuck the iframes code into the database in the external links field where we would usually put the DOI. This can be seen in the Pangolin dataset example http://dx.doi.org/10.5524/100248
Quickest fix would be to expand the width of the field for the external links section.
Ideally we should include the +/- expand button like the tables have. And include the protocols.io logo

**Comment by only1chunts** [comment]
@jessesiu is this ticket complete and inegrated into production code-base yet?

**Comment by jessesiu** [comment]
Yes it can close

发自我的 iPhone
