### ISSUE TITLE
Show sample ID in file tables in an efficient way

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#913]
There's a column in the file table (Sample ID) that show an expandable list  the sample attributes associated to each file of the table. 

That functionality is implemented by ``FormattedDatasetFiles::formatDatasetFilesSamples()`` 
which is extremely slow when the dataset has a lot of files and sample attributes, causing the page to take a very long time to load (and often fails to as a 504 gateway timeout HTTP error is triggered) .

So the call to that method in ``protected/views/dataset/view.php`` has been commented out for now, effectively disabling that functionality to users.

This task is to rewrite the functionality to be more efficient.

Stages:

* Repair code profilling tools (xdebug, xhprof, xhgui)
* profile the bad code
* Rewrite the method
* profile again

**Comment by only1chunts** [comment]
maybe its just the wording here, but why are there any SAMPLE ATTRIBUTES being shown in the FILE table? I'm hoping you are either talking about FILE ATTRIBUTES being shown in the FILE table, or else the SAMPLE IDs being shown in the FILE table.

**Comment by only1chunts** [comment]
The samples tables load quickly so i think this work has been completed, closing ticket
