### ISSUE TITLE
Check boxes on table settings for files are too small to be usable

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#917]
**Describe the bug**

**To Reproduce**
1. Go to https://staging.gigadb.org/dataset/101000
2. Click on "Files"
3. Click on "Table settings"

**Expected behavior**

Check boxes will be of normal size, so we can interact with them.

**Additional context**

* The problem occur on staging, but not on current CNGB live deployment.
* The problem happens only for  files  table settings, samples table settings are ok

**Comment by only1chunts** [comment]
this bug appears to have fallen off the list of things to be done, its still a bug and needs to be addressed before we go live (i.e. high impact) as its a feature that the general public will see and get annoyed at if its not fixed.
