### ISSUE TITLE
Tables not resize or provide scroll bar on dataset page

### ISSUE THREAD

**Issue by kencho51** [gigascience/gigadb-website#921]
**Describe the bug**
1. scroll bar is not available in all tables
2. when the screen size >= 150%, all tables are not resized.

Example:
1. ${staging gigadb website}/dataset/100921
![image](https://user-images.githubusercontent.com/64770635/149907205-1444b73e-4172-42c8-93df-3db0ed1c2986.png)

2. ${dev gigadb website}/dataset/100002
![image](https://user-images.githubusercontent.com/64770635/149907556-205915e4-9dfd-4d2d-8f6b-e92eb03eb48e.png)

**Comment by only1chunts** [comment]
this has been fixed in other tickets
