### ISSUE TITLE
Ensure new database entries from CNGB deployment of PostgreSQL are in AWS deployment of PostgreSQL

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#922]
## User story

>As a curator  
>I want new datasets and related data bulk imported by consultant into legacy database to be available on AWS database
>So that I can work with the new GigaDB website before Submission Wizard and File Upload Wizard are ready to be released

## Acceptance criteria

>Given new datasets related data have been uploaded to CNGB database earlier
>When I navigate to the Cloud-deployment of GigaDB website
>Then I can see them on that website

>Given stuff* is updated via bulk-upload method by consultant on CNGB database
>When I navigate to the Cloud-deployment of GigaDB website
>Then I need to see those changes reflected on that website

## Additional Info
*- "Stuff" includes rows in the following tables:
dataset
dataset_file
attribute
dataset_attributes
sample_attributes
file_attributes
samples
authors
users
dataset_authors
dataset_samples

There are several approaches to the situation:

1. Not launch the new GigaDB WebSite until Submission Wizard and File Upload Wizard have been integrated and tested
2. Update the custom tooling used by the consultant to upload dataset related to work with the AWS deployment of GigaDB
3. Launch the new GigaDB WebSite on AWS, let the consultant upload datasets to CNGB database but setup a export/import mechanism to feed AWS database with the new data added to CNGB database on a regular basis

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Item(s) in increment pass all Acceptance Criteria
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] Data security has not be compromised (with particular reference to the personal information we hold in GigaDB)
* [ ] No deviation from the team technology stack and software architecture has been introduced
* [ ] The product is in a releasable state (I.e. the increment has not broken anything)

**Comment by rija** [comment]
@only1chunts 

what about the thumbnail image for the dataset. Is it the consultant who normally upload them as part of the same job?

**Comment by only1chunts** [comment]
correct, for the curators convenience it is usually the consultant that uploads the thumbnail image as part of the initial dataset creation, they are not usually updated by the consultant as it's just 1 image per dataset so if it needs changing the curator does it via the admin page.

**Comment by only1chunts** [comment]
Just to note, in discussions we agreed that the curators are OK to upload all thumbnail images using the admin pages so there is no requirement for the consultant to do this, and therefore no requirement for the images to be copied from CNGB version to AWS version on new dataset uploads.

**Comment by rija** [comment]
This is done (CNGB data is synched every day to AWS deployment of beta website)
