### ISSUE TITLE
[S781] Verify static content 20-Jan: Create user account FAILED

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#928]
**Describe the bug**
When trying to create a new user account I filled in the form but when I clicked submit it returned a CDb exception error.

**To Reproduce**
1. Go to https://staging.gigadb.org/user/create
2. fill in details
3. click submit
4. see error message

**Expected behavior**
The page should thank you for registering and tell you to check your email for a confirmation.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: chrome
 - Version: 97.0.4692.71 (Official Build) (64-bit)

**Additional context **
Copy and paste entire Error message:
<html>
<body>
<h1 style="border: 0px; outline: 0px; font: 18pt Verdana; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 0.5em; padding: 0px; color: rgb(255, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbException</h1><p class="message" style="border: 0px; outline: 0px; font-size: 11pt; vertical-align: baseline; background: rgb(243, 243, 243); margin: 0px 0px 1em; padding: 1em; color: rgb(0, 0, 0); border-radius: 10px; line-height: 23.4667px; font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbCommand failed to execute the SQL statement: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(64). The SQL statement executed was: INSERT INTO "gigadb_user" ("role", "is_activated", "newsletter", "previous_newsletter_state", "preferred_link", "email", "first_name", "last_name", "password", "affiliation", "username") VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9, :yp10). Bound with :yp0='user', :yp1=false, :yp2=false, :yp3=true, :yp4='EBI', :yp5='chris@dingleberry.com', :yp6='ding', :yp7='dong', :yp8='$argon2id$v=19$m=65536,t=2,p=1$G4T9OnqLI1J1RbXV73+0ug$5poYo6PAgETAs90gnfbtleYw/aaZABpJshmVpOgvI0c', :yp9='High', :yp10='chris@dingleberry.com'</p><div class="source" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 1em; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="file" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px 0px 1em; padding: 0px; font-weight: bold;">/var/www/vendor/yiisoft/yii/framework/db/CDbCommand.php(358)</p><div class="code" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;"><pre style="border: 1px solid rgb(238, 238, 238); outline: 0px; font: 11pt / 18.3333px Menlo, Consolas, &quot;Lucida Console&quot;, monospace; vertical-align: baseline; background: rgb(255, 255, 238); margin: 0.5em 0px; padding: 0.5em;"><span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">346</span>         {
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">347</span>             if($this-&gt;_connection-&gt;enableProfiling)
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">348</span>                 Yii::endProfile('system.db.CDbCommand.execute('.$this-&gt;getText().$par.')','system.db.CDbCommand.execute');
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">349</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">350</span>             $errorInfo=$e instanceof PDOException ? $e-&gt;errorInfo : null;
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">351</span>             $message=$e-&gt;getMessage();
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">352</span>             Yii::log(Yii::t('yii','CDbCommand::execute() failed: {error}. The SQL statement executed was: {sql}.',
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">353</span>                 array('{error}'=&gt;$message, '{sql}'=&gt;$this-&gt;getText().$par)),CLogger::LEVEL_ERROR,'system.db.CDbCommand');
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">354</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">355</span>             if(YII_DEBUG)
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">356</span>                 $message.='. The SQL statement executed was: '.$this-&gt;getText().$par;
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">357</span> 
<span class="error" style="box-sizing: border-box; border: 0px; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: rgb(252, 227, 227); margin: 0px; padding: 0px; display: block;"><span class="ln error-ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153); font-weight: bold;">358</span>             throw new CDbException(Yii::t('yii','CDbCommand failed to execute the SQL statement: {error}',
</span><span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">359</span>                 array('{error}'=&gt;$message)),(int)$e-&gt;getCode(),$errorInfo);
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">360</span>         }
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">361</span>     }
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">362</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">363</span>     /**
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">364</span>      * Executes the SQL statement and returns query result.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">365</span>      * This method is for executing an SQL query that returns result set.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">366</span>      * @param array $params input parameters (name=&gt;value) for the SQL execution. This is an alternative
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">367</span>      * to {@link bindParam} and {@link bindValue}. If you have multiple input parameters, passing
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">368</span>      * them in this way can improve the performance. Note that if you pass parameters in this way,
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">369</span>      * you cannot bind parameters or values using {@link bindParam} or {@link bindValue}, and vice versa.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">370</span>      * Please also note that all values are treated as strings in this case, if you need them to be handled as
</pre></div></div><div class="traces" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 2em 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="border: 0px; outline: 0px; font: 14pt Verdana; vertical-align: baseline; background: transparent; margin: 0px 0px 0.5em; padding: 0px; color: rgb(128, 0, 0);">Stack Trace</h2>

#0 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1083): CDbCommand->execute()
-- | --
#1 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(811): CActiveRecord->insert(null)
#2 | –  /var/www/protected/controllers/UserController.php(97): CActiveRecord->save(false)092             } 093  094             if ($user->validate('insert')) { 095                 $user->encryptPassword(); 096  097                 if ($user->save(false)) { 098                     $this->sendActivationEmail($user); 099                     if($user->newsletter) 100                         Yii::app()->newsletter->addToMailing($user->email); 101  102                     $this->redirect(array('welcome', 'id'=>$user->id));
#3 | +  /var/www/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(49): UserController->actionCreate()
#4 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(array())
#5 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(CInlineAction)
#6 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#7 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(1148): CFilter->filter(CFilterChain)
#8 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#9 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(CFilterChain)
#10 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()
#11 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#12 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run("create")
#13 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController("user/create")
#14 | +  /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 | –  /var/www/index.php(23): CApplication->run()18 require_once($composer); 19  20 # Run the Yii1.1 application 21 Yii::$enableIncludePath = false; 22 $config=dirname(__FILE__).'/protected/config/main.php'; 23 Yii::createWebApplication($config)->run();

</div><div class="version" style="border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(170, 170, 170); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 8pt; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 1em; padding: 1em 0px 0px; color: gray; font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2022-01-20 13:48:16 nginx/1.21.3<span> </span><a href="http://www.yiiframework.com/" style="border: 0px; outline: 0px; font-size: 10.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Yii Framework</a>/1.1.20-yii2-2.0.15.1-migration</div>
</body>
</html>

**Comment by rija** [comment]
this is should have been fixed on staging by PR #899

**Comment by pli888** [comment]
@only1chunts I have checked that the create user account functionality is working now on the staging server.
