### ISSUE TITLE
To open a new tab when editing/updating an entity.

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#930]
**Is your feature request related to a problem? Please describe.**
I always find myself right mouse clicking "open link in new tab".

**Describe the solution you'd like**
The edit/update function to open a new tab.

**Describe alternatives you've considered**
Right mouse click - "open in new tab" is OK.

**Additional context**
Screen shot showing where I click.
![Screen Shot 2022-01-20 at 14 04 54](https://user-images.githubusercontent.com/1359170/150353908-46b9e738-ae19-4c13-bf96-daf8b9b9f647.png)

**Comment by rija** [comment]
WONTFIX
