### ISSUE TITLE
Page alignment looks terrible 

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#932]
**Describe the bug**
The format of the page is awful - too much white space which I think effects the alignment

**To Reproduce**
1. Go to http://staging.gigadb.org/adminDataset/update/id/1310
2. Look [grin]

**Expected behavior**
User-friendly interface.

**Screenshots**
Attached: current and staging view for same record.

**Desktop (please complete the following information):**
OS: iOS 10.12.6
Browser Chrome
Version 96.0.4664.110

**Additional context**
I think this is an issue across the board

![staging](https://user-images.githubusercontent.com/1359170/150356533-ec5ac0d8-85dc-4990-a685-b3b15bf523ec.png)
.![current](https://user-images.githubusercontent.com/1359170/150356538-80bd6f78-6492-4ba4-bbce-129d279fbd8a.png)

**Comment by rija** [comment]
Same issue as #926
