### ISSUE TITLE
Default Sample Attributes List box to be larger

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#935]
## User Story 

>As a curator
>I want the text field to be bigger
>So that I can the content with having to expand it

## Acceptance Criteria

>GivenI am logged in as an admin
>When I navigate to the sample update form
>Then I should see a large text box for attributes list

**Is your feature request related to a problem? Please describe.**
Not a problem, just an inconvenience. I always expand the box.

**Describe the solution you'd like**
I would like the default box to be larger.

**Describe alternatives you've considered**
None.

**Additional context**
screenshot - now = what it looks like now
screenshot - wish = what I would like it to look like (although I guess the box should stay within the limits of the background grey.
![wish](https://user-images.githubusercontent.com/1359170/150362545-0e2ffe12-3b8b-428e-a470-d778038a69a8.png)
busercontent.com/1359170/150362535-4343c04a-e07e-4c17-b79f-f449fc67a34e.png)
![now](https://user-images.githubusercontent.com/1359170/150362693-fec97378-44b6-4567-b0cc-4cc9f7a0930d.png)

**Comment by rija** [comment]
May be related and fixed by #54

**Comment by only1chunts** [comment]
closing ticket as the box is now (a bit) larger than it was, and there are other tickets #54 to adjust how we add sample attributes anyway so this problem will go away if those tickets are worked on.
