### ISSUE TITLE
Default File Location box to be larger

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#936]
## User story

>As a curator,
>I want the location field in the file creation/update form
>So that I can paste long url without the need to expand the box

## Acceptance Criteria

>Given I am logged in as an admin
>When I navigate to the file creation or update form
>Then the location field is big enough for URLS 
>and the content is wrapped
>and alignement with other fields are maintained

**Is your feature request related to a problem? Please describe.**
Not a problem, just an inconvenience. I always expand the box.

**Describe the solution you'd like**
Go to: http://staging.gigadb.org/adminFile/create

I would like the default Location box to be longer so that the whole path can be seen. 
e.g. https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100934/ISfinder_output.csv rather than 
https://ftp.cngb.org/pub/gigadb/pub/1

**Describe alternatives you've considered**
None

**Additional context**
The same issue as #935

**Comment by only1chunts** [comment]
luis has made a minor adjustment so it is a bit wider now, but i dont think this is an issue we need to worry about as the file-upload wizard will negate the need for it
