### ISSUE TITLE
Drop-down Funder list needs to be more easily navigable

### ISSUE THREAD

**Issue by tuli** [gigascience/gigadb-website#937]
## User Story

>As a curator
>I want to a lookup field for funders  in the dataset funder form
>So that I can quickly select the funder of my choice

## Acceptance Criteria

>Given I am logged in as an admin
>When I navigate to the dataset funder form
>Then I should a lookup field to search through funder names

## Additional information

**Is your feature request related to a problem? Please describe.**
The drop-down Funder list is so long it's very hard to work with. It is impossible to scroll through.

**Describe the solution you'd like**
I don't know.

**Describe alternatives you've considered**
I don't use it at the moment.

**Additional context**
Screenshot attached. 
![Screen Shot 2022-01-20 at 15 05 56](https://user-images.githubusercontent.com/1359170/150367527-fe12b1a1-b39f-46ff-bfb9-bd39706da690.png)

* [  ] Check how it's implemented in the Submission Wizard

**Comment by luistoptal** [comment]
I think the most reasonable solution here is to use a searchable dropdown where the user can type and filter the options, perhaps this https://select2.org/searching

**Comment by tuli** [comment]
That sounds good to me.

**Comment by rija** [comment]
Hi @luistoptal that library looks nice
