### ISSUE TITLE
[S781] Verify static content 20-Jan: dataset page fail

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#940]
**Describe the bug**
The keywords displayed on dataset pages should all be lower-case, some are showing up with Capital letters

**To Reproduce**
1. Go to https://staging.gigadb.org/dataset/view/id/100245
2. Scroll down to the Keywords section
3. See example of some keywords starting with Caps "Hong Kong Orchid"

**Expected behavior**
all keywords should be saved in db as lowercase and displayed as lowercase.

**Screenshots**
![Screenshot_50](https://user-images.githubusercontent.com/6037145/150393927-efc1c9f9-648b-480a-9308-550047ccf1a7.png)

**Additional context**
this was originally done to facilitate searching and may be something that can be revisited when we work on the search functionality.

**Comment by kencho51** [comment]
Just double checked in the production database table `dataset_attributes`, `Hong Kong Orchid` is in capital letter.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/64770635/154180149-a373b2b0-fb3b-4b4c-9d8c-3785cb9a32f8.png">

**Comment by kencho51** [comment]
Just for reference:
```
gigadb=> select * from dataset_attributes where id = 351;
 id  | dataset_id | attribute_id |      value       | units_id | image_id | until_date 
-----+------------+--------------+------------------+----------+----------+------------
 351 |        319 |          455 | Hong Kong Orchid |          |          | 
(1 row)
gigadb=> update dataset_attributes set value = 'hong kong orchid' where id = 351;
UPDATE 1
gigadb=> select value from dataset_attributes da, attribute a where da.attribute_id = a.id and a.attribute_name='keyword' and da.dataset_id=319;
       value        
--------------------
 crowd funding
 teaching resources
 community analysis
 hong kong orchid
(4 rows)
```
<img width="793" alt="image" src="https://user-images.githubusercontent.com/64770635/160086136-bb6d75eb-d519-4799-8159-706f569cee77.png">

Hi @only1chunts,  just to confirm that you want all keywords in db as lowercase and displayed as lowercase?  It is because  this query `select value from dataset_attributes da, attribute a where da.attribute_id = a.id and a.attribute_name='keyword';` returns quit a lot of values that are not lower case, see below: 
```
gigadb=> select value from dataset_attributes da, attribute a where da.attribute_id = a.id and a.attribute_name='keyword';
                                                                          value                                                                         
 
--------------------------------------------------------------------------------------------------------------------------------------------------------
-
 transcriptome
 midgut
 pink bollworm
 Pectinophora gossypiella
 Bacillus thuringiensis
 AGOUTI
 assembly
 Genome
 RNA-Seq
 Exome
 Nanopore sequencing
 Real-time analysis
 Pathogen identi cation
 Antibiotic resistance
 Malus domestica
 apple
 Illumina sequencing
--More--
```

A migration script could be used to make them all lower case.

**Comment by only1chunts** [comment]
Actually, if it makes things easier, I'm not so bothered about how they are stored in the db as long as they are presented to the user as lowercase on the dataset pages.
The only thing to bear in mind about storing in db as any case is does that affect searching at all? i.e. if the search is case-sensitive then it might be important to have them in the db as lowercase (but i hope the search will not be case sensitive anyway.)
