### ISSUE TITLE
Google analytics admin view not working

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#942]
**Describe the bug**
The admin pages for viewing dataset metrics recorded by google analytics is not working on live or staging

**To Reproduce**
1. Go to https://staging.gigadb.org/report/index
2. fill in start and end dates, and select "All DOIs" from dropdown
3. Click "View"
4. See error (nothing is displayed)

**Expected behavior**
The display should change to show the chart of the number of page views for the dataset DOIs selected over the dates selected

**Additional context**
this is related #832 which is part of Epic #137

**Comment by pli888** [comment]
May or may not be relevant, email from Google: 

Google Analytics 4 is our next-generation measurement solution, and is replacing Universal Analytics. On July 1, 2023, Universal Analytics properties will stop processing new hits. If you still rely on Universal Analytics, we recommend that you complete your move to Google Analytics 4. You can continue to use and collect new data in your Universal Analytics properties until July 1, 2023. After that, you will be able to access your previously processed data in Universal Analytics for a period of at least six months. We know your data is important to you and we strongly encourage you to export your historical reports during this time.

**Comment by rija** [comment]
We use Matomo now. 
This work is to embed reports from Matomo API into GigaDB admin area

**Comment by only1chunts** [comment]
closing this ticket as we're no longer using google analytics
