### ISSUE TITLE
sorting of Dataset_Samples Admin page by DOI causes CDb Exception

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#943]
**Describe the bug**
The sort Dataset_Sample table by DOI causes a CDb exception error (https://staging.gigadb.org/adminDatasetSample/admin/sort/doi_search)

**To Reproduce**
1. Go to Dataset_Samples Admin page https://staging.gigadb.org/adminDatasetSample/admin 
2. Click on DOI column header to sort the table by DOI
3. See error

**Expected behavior**

**Screenshots**

**Additional context**
related to #849 

the CDb exception I get is :

<html>
<body>
<h1 style="border: 0px; outline: 0px; font: 18pt Verdana; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 0.5em; padding: 0px; color: rgb(255, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbException</h1><p class="message" style="border: 0px; outline: 0px; font-size: 11pt; vertical-align: baseline; background: rgb(243, 243, 243); margin: 0px 0px 1em; padding: 1em; color: rgb(0, 0, 0); border-radius: 10px; line-height: 23.4667px; font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">CDbCommand failed to execute the SQL statement: SQLSTATE[21000]: Cardinality violation: 7 ERROR: more than one row returned by a subquery used as an expression. The SQL statement executed was: SELECT "t"."id" AS "t0_c0", "t"."dataset_id" AS "t0_c1", "t"."sample_id" AS "t0_c2", "sample"."id" AS "t1_c0", "sample"."species_id" AS "t1_c1", "sample"."name" AS "t1_c2", "sample"."consent_document" AS "t1_c3", "sample"."submitted_id" AS "t1_c4", "sample"."submission_date" AS "t1_c5", "sample"."contact_author_name" AS "t1_c6", "sample"."contact_author_email" AS "t1_c7", "sample"."sampling_protocol" AS "t1_c8", "dataset"."id" AS "t2_c0", "dataset"."submitter_id" AS "t2_c1", "dataset"."image_id" AS "t2_c2", "dataset"."identifier" AS "t2_c3", "dataset"."title" AS "t2_c4", "dataset"."description" AS "t2_c5", "dataset"."dataset_size" AS "t2_c6", "dataset"."ftp_site" AS "t2_c7", "dataset"."upload_status" AS "t2_c8", "dataset"."excelfile" AS "t2_c9", "dataset"."excelfile_md5" AS "t2_c10", "dataset"."publication_date" AS "t2_c11", "dataset"."modification_date" AS "t2_c12", "dataset"."publisher_id" AS "t2_c13", "dataset"."token" AS "t2_c14", "dataset"."fairnuse" AS "t2_c15", "dataset"."curator_id" AS "t2_c16", "dataset"."manuscript_id" AS "t2_c17", "dataset"."handing_editor" AS "t2_c18" FROM "dataset_sample" "t" LEFT OUTER JOIN "sample" "sample" ON ("t"."sample_id"="sample"."id") LEFT OUTER JOIN "dataset" "dataset" ON ("t"."dataset_id"="dataset"."id") ORDER BY (SELECT identifier from dataset d WHERE dataset.id = t.dataset_id) ASC LIMIT 10</p><div class="source" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 1em; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p class="file" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px 0px 1em; padding: 0px; font-weight: bold;">/var/www/vendor/yiisoft/yii/framework/db/CDbCommand.php(543)</p><div class="code" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;"><pre style="border: 1px solid rgb(238, 238, 238); outline: 0px; font: 11pt / 18.3333px Menlo, Consolas, &quot;Lucida Console&quot;, monospace; vertical-align: baseline; background: rgb(255, 255, 238); margin: 0.5em 0px; padding: 0.5em;"><span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">531</span>         {
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">532</span>             if($this-&gt;_connection-&gt;enableProfiling)
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">533</span>                 Yii::endProfile('system.db.CDbCommand.query('.$this-&gt;getText().$par.')','system.db.CDbCommand.query');
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">534</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">535</span>             $errorInfo=$e instanceof PDOException ? $e-&gt;errorInfo : null;
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">536</span>             $message=$e-&gt;getMessage();
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">537</span>             Yii::log(Yii::t('yii','CDbCommand::{method}() failed: {error}. The SQL statement executed was: {sql}.',
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">538</span>                 array('{method}'=&gt;$method, '{error}'=&gt;$message, '{sql}'=&gt;$this-&gt;getText().$par)),CLogger::LEVEL_ERROR,'system.db.CDbCommand');
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">539</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">540</span>             if(YII_DEBUG)
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">541</span>                 $message.='. The SQL statement executed was: '.$this-&gt;getText().$par;
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">542</span> 
<span class="error" style="box-sizing: border-box; border: 0px; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: rgb(252, 227, 227); margin: 0px; padding: 0px; display: block;"><span class="ln error-ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153); font-weight: bold;">543</span>             throw new CDbException(Yii::t('yii','CDbCommand failed to execute the SQL statement: {error}',
</span><span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">544</span>                 array('{error}'=&gt;$message)),(int)$e-&gt;getCode(),$errorInfo);
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">545</span>         }
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">546</span>     }
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">547</span> 
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">548</span>     /**
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">549</span>      * Builds a SQL SELECT statement from the given query specification.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">550</span>      * @param array $query the query specification in name-value pairs. The following
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">551</span>      * query options are supported: {@link select}, {@link distinct}, {@link from},
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">552</span>      * {@link where}, {@link join}, {@link group}, {@link having}, {@link order},
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">553</span>      * {@link limit}, {@link offset} and {@link union}.
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">554</span>      * @throws CDbException if "from" key is not present in given query parameter
<span class="ln" style="box-sizing: border-box; border-width: 0px 1px 0px 0px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: rgb(204, 204, 204); border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 14.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px 0.5em 0px 0px; color: rgb(153, 153, 153);">555</span>      * @return string the SQL statement
</pre></div></div><div class="traces" style="border: 0px; outline: 0px; font-size: 12px; vertical-align: baseline; background: rgb(255, 255, 255); margin: 2em 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="border: 0px; outline: 0px; font: 14pt Verdana; vertical-align: baseline; background: transparent; margin: 0px 0px 0.5em; padding: 0px; color: rgb(128, 0, 0);">Stack Trace</h2>

#0 | +  /var/www/vendor/yiisoft/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal("fetchAll", array(2), array())
-- | --
#1 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveFinder.php(810): CDbCommand->queryAll()
#2 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveFinder.php(441): CJoinElement->runQuery(CJoinQuery)
#3 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveFinder.php(68): CJoinElement->find(CDbCriteria)
#4 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1364): CActiveFinder->query(CDbCriteria, true)
#5 | +  /var/www/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1478): CActiveRecord->query(CDbCriteria, true)
#6 | +  /var/www/vendor/yiisoft/yii/framework/web/CActiveDataProvider.php(199): CActiveRecord->findAll(CDbCriteria)
#7 | +  /var/www/vendor/yiisoft/yii/framework/web/CDataProvider.php(168): CActiveDataProvider->fetchData()
#8 | +  /var/www/vendor/yiisoft/yii/framework/zii/widgets/CBaseListView.php(125): CDataProvider->getData()
#9 | +  /var/www/vendor/yiisoft/yii/framework/zii/widgets/grid/CGridView.php(339): CBaseListView->init()
#10 | +  /var/www/vendor/yiisoft/yii/framework/web/CBaseController.php(147): CGridView->init()
#11 | +  /var/www/vendor/yiisoft/yii/framework/web/CBaseController.php(181): CBaseController->createWidget("zii.widgets.grid.CGridView", array("id" => "dataset-sample-grid", "ajaxUpdate" => false, "dataProvider" => CActiveDataProvider, "itemsCssClass" => "table table-bordered", ...))
#12 | –  /var/www/protected/views/adminDatasetSample/admin.php(6): CBaseController->widget("zii.widgets.grid.CGridView", array("id" => "dataset-sample-grid", "ajaxUpdate" => false, "dataProvider" => CActiveDataProvider, "itemsCssClass" => "table table-bordered", ...))01 <h1>Manage Dataset - Samples</h1> 02  03 <a href="/adminDatasetSample/create" class="btn">Add a Sample to a Dataset</a> 04  05 <?php $this->widget('zii.widgets.grid.CGridView', array( 06     'id'=>'dataset-sample-grid', 07     'ajaxUpdate' => false, 08     'dataProvider'=>$model->search(), 09     'itemsCssClass'=>'table table-bordered', 10     'filter'=>$model, 11     'columns'=>array(
#13 | +  /var/www/vendor/yiisoft/yii/framework/web/CBaseController.php(126): require("/var/www/protected/views/adminDatasetSample/admin.php")
#14 | +  /var/www/vendor/yiisoft/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal("/var/www/protected/views/adminDatasetSample/admin.php", array("model" => DatasetSample), true)
#15 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(872): CBaseController->renderFile("/var/www/protected/views/adminDatasetSample/admin.php", array("model" => DatasetSample), true)
#16 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(785): CController->renderPartial("admin", array("model" => DatasetSample), true)
#17 | –  /var/www/protected/controllers/AdminDatasetSampleController.php(352): CController->render("admin", array("model" => DatasetSample))347         $model->unsetAttributes();  // clear any default values 348         if(isset($_GET['DatasetSample'])) 349             $model->setAttributes($_GET['DatasetSample']); 350  351         $this->render('admin',array( 352             'model'=>$model, 353         )); 354     } 355  356     /** 357      * Returns the data model based on the primary key given in the GET variable.
#18 | +  /var/www/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(49): AdminDatasetSampleController->actionAdmin()
#19 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(array("sort" => "doi_search"))
#20 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(CInlineAction)
#21 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()
#22 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(1148): CFilter->filter(CFilterChain)
#23 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(CFilterChain)
#24 | +  /var/www/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(CFilterChain)
#25 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()
#26 | +  /var/www/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(CInlineAction, array("accessControl"))
#27 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run("admin")
#28 | +  /var/www/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController("adminDatasetSample/admin/sort/doi_search")
#29 | +  /var/www/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#30 | –  /var/www/index.php(23): CApplication->run()18 require_once($composer); 19  20 # Run the Yii1.1 application 21 Yii::$enableIncludePath = false; 22 $config=dirname(__FILE__).'/protected/config/main.php'; 23 Yii::createWebApplication($config)->run();

</div><div class="version" style="border-width: 1px 0px 0px; border-top-style: solid; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-top-color: rgb(170, 170, 170); border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; outline: 0px; font-size: 8pt; vertical-align: baseline; background: rgb(255, 255, 255); margin: 0px 0px 1em; padding: 1em 0px 0px; color: gray; font-family: Verdana; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2022-01-21 09:39:42 nginx/1.21.3<span> </span><a href="http://www.yiiframework.com/" style="border: 0px; outline: 0px; font-size: 10.6667px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Yii Framework</a>/1.1.20-yii2-2.0.15.1-migration</div>
</body>
</html>

**Comment by rija** [comment]
Fixed in PR #948
