### ISSUE TITLE
sample attribute "comment" gets removed when updating a sample via admin page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#945]
**Describe the bug**
In dataset 100987 a sample needed a typo updated in one of the samples, when this was done in the admin page the comment attribute was removed by the commit action despite the comment having not been deleted by the admin person

**To Reproduce**
1. Go to http://gigadb.org/adminSample/update/id/148151
2. Click on 'Save'
3. See the confirmation of what is saved to the database and notice that the comment attribute is now missing

NB the full list of attributes are 
Description="MicroCT image data (volumetric TIFF stack) and surface-rendered 3D reconstructions (STL format) of skull and dentition of Timon lepidus",life_stage="Adult",age="not provided",sample_source="Department of Anatomy, Histology and Embryology at the Faculty of Veterinary Medicine, University of Veterinary Sciences Brno, Czech Republic",tissue_type="Head [UBERON:0000033]",collection_date="not provided",Exp_Scan method="MicroCT",Exp_Scanner="GE Phoenix v|tome|x L 240",Exp_Scan_parameters="Acceleration voltage of the X-ray tube 60 kV; Tube current 230 μA; Exposure time 500 ms; 2600 images",Exp_Scan_resolution="18 µm (isotropic)",comment="Specimens originated from private breeders. Deceased animals were part of the collection of the Department of Anatomy, Histology and Embryology at the Faculty of Veterinary Medicine, University of Veterinary Sciences Brno (Brno, Czech Republic)."

**Expected behavior**
all listed attributes with values should be added to the database as provided and the confirmation page should show those.
IF for any reason something is NOT added then a message should be presented to the admin user explaining what has been ignored and why.

**Screenshots**
![image](https://user-images.githubusercontent.com/6037145/150524450-0ec5c458-b3d5-479b-976d-80fa814765a9.png)

![image](https://user-images.githubusercontent.com/6037145/150524549-a05e725c-4cda-4634-9237-a780898ed517.png)

**Additional context**
My GUESS is that there is a char limit on the length of the comment attribute that has been exceeded in this case.

**Comment by rija** [comment]
This is a quick bug fix. The proper fix to the acward workflow will be done in #54

**Comment by only1chunts** [comment]
closing this ticket, #54 will fix this issue
