### ISSUE TITLE
Download resources and configurations for CNGB deployment of GigaDB

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#946]
On the CNGB live server, locate:

* nginx configuration files
* php configuration files
* application codebase

tar archive them togegther and upload to ``gigadb-sftp.rija.dev``

>Note: maybe we don't want in that archive  the content ``/var/www/hosts/localhost/htdocs/images/uploads/`` as it may be too big.

**Comment by kencho51** [comment]
Hi,

All files have been put into `gigadb-sftp.rija.dev` folder `editorialmanager` now.
