### ISSUE TITLE
Let admin upload dataset images to cloud storage

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#959]
## User story

>As a curator
>I want to associate an image to a dataset
>So that I can make the dataset page more engaging

## Acceptance criteria

>Given that I am on the admin page for dataset
>When I upload an image
>Then the image is saved on cloud storage
>And the image is associated with the dataset

>Given that I am on the admin page for dataset
>And there is already an image associated with the dataset
>When I upload a new image
>Then the new image is upload on cloud storage
>And the new image is associated with the dataset
>And the old image is disassociated from the dataset

## Additional Info

* Enable current admin controller for uploading images to write image to S3 using FlySystem
* Update image metadata with new link to image in Cloud
* Re-implement image management code and get rid of `ImageHaver` code

**Comment by rija** [comment]
This is done and deployed to beta.gigadb.org
