### ISSUE TITLE
Configure edge caching of image

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#962]
* [x] Create new domain name in Route53
* [x] Configure Route53 to use CloudFlare DNS
* [x] Enable caching in CloudFlare
* [x] Connect CloudFlare domain to S3
* [x] Verify that we can access image from cache

**Comment by rija** [comment]
@pli888, @kencho51 

There were two errors we made in our setup of edge caching. I'll explain on Thurday.
I've fixed the problem, and now we can access our images from the edge:

https://assets.gigadb-cdn.net/images/datasets/no_image.png
