### ISSUE TITLE
dataset thumbnail image is cached in mockup page

### ISSUE THREAD

**Issue by only1chunts** [gigascience/gigadb-website#963]
## User story

>As a curator
>I want thumbnail image updates to display imeadiatly
>So that I can see the newly provided image on the mockup page

## Acceptance criteria

>Given there is an unpublished dataset with a thumbnail image associated
>When I update that image via the dataset-admin page
>Then the mockup page displays the new image

## Additional Info
Currently the image is saved in the cache, so the mockup page shows the old image until the cache expires or is expunged. The caching on the mockup pages could be removed.

Implementation: On the mockup page:
* Use S3 link instead of CDN link to image:
  * store image path in ``location``
  * create yii migration to convert location column of existing images
  * In view action of DatasetController set up a url prefix variable  to be S3 or CDN url based on whether it's mockup or regular dataset page that we want to render
* Invalidate programmatically the CDN cache if it'ts the same name
* Ensure that S3 bucket has cache disabled

Docs to Cloudflare API:
* https://api.cloudflare.com/
* https://blog.cloudflare.com/introducing-a-powerful-way-to-purge-cache-on-cloudflare-purge-by-cache-tag/

## Product Backlog Item Ready Checklist

* [ ] Business value is clearly articulated
* [ ] Item is understood enough by the IT team so it can make an informed decision as to whether it can complete this item
* [ ] Dependencies are identified and no external dependencies would block this item from being completed
* [ ] At the time of the scheduled sprint, the IT team has the appropriate composition to complete this item
* [ ] This item is estimated and small enough to comfortably be completed in one sprint
* [ ] Acceptance criteria are clear and testable
* [ ] Performance criteria, if any, are defined and testable
* [ ] The Scrum team understands how to demonstrate this item at the sprint review

## Product Backlog Item Done Checklist

* [ ] Code is complete
* [ ] Automated tests related to the changes are implemented and passing
* [ ] All automated test suites are passing locally
* [ ] Code is refactored to best practices and coding standards
* [ ] Documentation is updated as needed
* [ ] A Pull Request has been created and review requested
* [ ] Pull Request is reviewed and approved
* [ ] The item has been merged to the develop branch
* [ ] All automated test suites are passing on continuous Integration pipeline and item is ready to release

**Comment by only1chunts** [comment]
@rija can this be closed? it seems to not be an issue anymore.

**Comment by rija** [comment]
@only1chunts, let's close it then. We'll create a new issue if it ever comes back
