### ISSUE TITLE
Ensure beta.gigadb.org is receiving real data

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#986]
- [x] On bastion server, manually update database with latest CNGB database backup
- [x] Automate above process - cron job / systemd
- [x] Deal with errors by looking at logs
- ~~[ ] Expose logs to uptime endpoint to get notifications when import fails~~

**Comment by rija** [comment]
I stroke of the 4th TODO item as I don't think this is the right time to do that.

We should think of monitoring/alerting holistically for the whole systems, not just this feature, as tooling is going to be shared and setting them up have us to have a difine list of  things to monitor
