### ISSUE TITLE
Get spreadsheet import tool into codebase

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#987]
- [x] Add sample spreadsheet for testing spreadsheet upload tool into gigadb/app/tools directory
- [x] Add README file to document how to use the tool into gigadb/app/tools directory
- [x] If required, add gitignore file so log files are not saved into main codebase, etc into gigadb/app/tools directory
- [x] Add dependencies of the tool
- [x] Run unit tests

**Comment by kencho51** [comment]
The tool [repo](https://github.com/jessesiu/gigadb-tools-dataupload).

**Comment by rija** [comment]
More tasks to do before this is considered complete:
* [ ] Ensure tool works on cloud deployment (see PR #1051)
* [ ] Ensure MD5 checksum are written to the file table
* [ ] Ensure file size are written to the file table

**Comment by rija** [comment]
closing as this technically done. There will be a separate issue (#1052) for using on cloud deployment
