### ISSUE TITLE
Test spreadsheet upload tool with sample spreadsheet on database

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#988]
- [x] Use tool with sample spreadsheet to generate SQL statements
- [x] Import SQL statements into database on local environment
- [ ] Ensure results of import is working on local environment by checking new dataset page exists using functional tests that test against the database specifically used for testing spreadsheet import tool  
- [x] Document errors and add test cases arising from using the tool

**Comment by only1chunts** [comment]
we're using it, so this ticket must be complete
