### ISSUE TITLE
terraform plan causes unsupported argument errors

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#995]
Executing `$ AWS_PROFILE=Gigadb terraform plan` to deploy an upstream live environment causes the errors below:
```
│ Error: Unsupported argument
│ 
│   on ../../modules/rds-instance/rds-instance.tf line 31, in module "db":
│   31:   name                   = var.gigadb_db_database
│ 
│ An argument named "name" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on ../../modules/rds-instance/rds-instance.tf line 54, in module "db":
│   54:   final_snapshot_identifier = "snapshot-final-${var.deployment_target}-${var.owner}-${local.tstamp}"
│ 
│ An argument named "final_snapshot_identifier" is not expected here.
```

Looks like this is caused by the use of `terraform-aws-modules/rds/aws` version 4.2.0 in my upstream live environment whereas we have been using version 3.5.0 which does not have this problem. The fix to the above problems are to use `db_name = var.gigadb_db_database` and `final_snapshot_identifier_prefix = "snapshot-final-${var.deployment_target}-${var.owner}-${local.tstamp}”` in `rds-instance.tf`.

**Comment by rija** [comment]
Fixed two years ago with PR #1001, so closing
